from pathlib import Path

p=Path('app/src/v7/java/com/mg/battleship/GameActivity.java')
s=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit('missing patch target: '+label)
    s=s.replace(old,new,1)

rep('private TextView status,rankText;\n    private BoardView board;\n    private Button rotate,randomize,ready;',
    'private TextView status,rankText,battleHud;\n    private BoardView board;\n    private Button rotate,randomize,ready;\n    private LinearLayout setupControls;','fields-ui')
rep('private int aiLevel=2,careerStage=0;',
    'private int aiLevel=2,careerStage=0;\n    private int matchShots=0,matchHits=0,enemySunkCount=0;','fields-stats')
rep('TextView footer=label("v7 • Sinematik savaş • Kariyer • Rütbe • Gelişmiş AI",11,Color.rgb(120,145,155));',
    'TextView footer=label("v8 • Kesintisiz savaş • Batış efektleri • Canlı HUD • Gelişmiş AI",11,Color.rgb(120,145,155));','footer')
rep('solo=soloMode;career=careerMode;aiLevel=difficulty;connected=false;localReady=remoteReady=myTurn=false;aiTargets.clear();',
    'solo=soloMode;career=careerMode;aiLevel=difficulty;connected=false;localReady=remoteReady=myTurn=false;aiTargets.clear();matchShots=matchHits=enemySunkCount=0;','battle-reset')
rep('status=label(solo?"Gemilerini yerleştir. Hazır olduğunda savaşı başlat.":"Bluetooth rakip aranıyor…",14,Color.rgb(65,205,240));root.addView(status);\n        board=new BoardView();',
    'status=label(solo?"Gemilerini yerleştir. Hazır olduğunda savaşı başlat.":"Bluetooth rakip aranıyor…",14,Color.rgb(65,205,240));root.addView(status);\n        battleHud=label("",12,Color.rgb(255,214,92));battleHud.setVisibility(View.GONE);battleHud.setBackgroundColor(Color.rgb(7,35,47));root.addView(battleHud,new LinearLayout.LayoutParams(-1,dp(34)));\n        board=new BoardView();','battle-hud')
rep('LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.HORIZONTAL);controls.setGravity(Gravity.CENTER);',
    'setupControls=new LinearLayout(this);setupControls.setOrientation(LinearLayout.HORIZONTAL);setupControls.setGravity(Gravity.CENTER);','controls-field')
rep('controls.addView(b,lp);}root.addView(controls);',
    'setupControls.addView(b,lp);}root.addView(setupControls);','controls-use')

old_ready='''private void setReady(){\n        if(!board.complete()){status.setText("Önce tüm filoyu yerleştir veya Rastgele\'ye bas.");return;}localReady=true;ready.setEnabled(false);rotate.setEnabled(false);randomize.setEnabled(false);\n        if(solo){board.playing=true;myTurn=true;status.setText("HEDEFLEME SERBEST — Sıra sende.");board.invalidate();return;}\n        if(!connected){localReady=false;ready.setEnabled(true);rotate.setEnabled(true);randomize.setEnabled(true);status.setText("Rakip henüz bağlanmadı.");return;}link.send("READY");if(remoteReady)beginBluetooth();else status.setText("Filo hazır. Rakip bekleniyor…");\n    }\n    private void beginBluetooth(){myTurn=localNonce>remoteNonce;board.playing=true;board.invalidate();status.setText(myTurn?"Sıra sende — hedef seç.":"Rakibin hamlesi bekleniyor…");}'''
new_ready='''private void setReady(){\n        if(!board.complete()){status.setText("Önce tüm filoyu yerleştir veya Rastgele'ye bas.");return;}\n        localReady=true;ready.setEnabled(false);rotate.setEnabled(false);randomize.setEnabled(false);\n        if(solo){board.playing=true;myTurn=true;enterCombat();status.setText("SIRA SENDE — vurulmamış bir hedef seç.");board.invalidate();return;}\n        if(!connected){localReady=false;ready.setEnabled(true);rotate.setEnabled(true);randomize.setEnabled(true);status.setText("Rakip henüz bağlanmadı.");return;}\n        link.send("READY");if(remoteReady)beginBluetooth();else status.setText("Filo hazır. Rakip bekleniyor…");\n    }\n    private void beginBluetooth(){myTurn=localNonce>remoteNonce;board.playing=true;enterCombat();board.invalidate();status.setText(myTurn?"SIRA SENDE — hedef seç.":"RAKİBİN SIRASI — hamle bekleniyor…");updateHud();}\n    private void enterCombat(){if(setupControls!=null)setupControls.setVisibility(View.GONE);if(battleHud!=null)battleHud.setVisibility(View.VISIBLE);updateHud();}\n    private void updateHud(){if(board==null||battleHud==null||!board.playing)return;int mine=board.aliveOwnShips();int enemy=solo?board.aliveAiShips():Math.max(0,5-enemySunkCount);float acc=matchShots==0?0f:(100f*matchHits/matchShots);String turn=board.gameOver?"MUHAREBE BİTTİ":(myTurn?"SIRA: SEN":(solo?"SIRA: "+DIFF[aiLevel]:"SIRA: RAKİP"));battleHud.setText(turn+"   •   GEMİ: "+mine+"   •   DÜŞMAN: "+enemy+"   •   İSABET %"+String.format(java.util.Locale.US,"%.0f",acc));}\n    private void restoreTurnPrompt(){if(board!=null&&board.playing&&!board.gameOver&&myTurn){status.setText("SIRA SENDE — vurulmamış bir hedef seç.");updateHud();}}'''
rep(old_ready,new_ready,'ready-combat')
rep('main.postDelayed(()->showDebrief(win),1100);','main.postDelayed(()->showDebrief(win),1750);','debrief-delay')

old_player='''private void playerShot(int r,int c){if(board.enemyMarks[r][c]!=0){status.setText("Bu koordinat zaten vuruldu.");return;}int res=board.receiveAiShot(r,c);board.enemyMarks[r][c]=res;recordShot(res==2);board.flash(r,c,false,res==2);if(board.allAiSunk()){board.gameOver=true;myTurn=false;finishMatch(true);return;}myTurn=false;status.setText(res==2?"VURUŞ! Yapay zekâ karşılık veriyor…":"ISKALANDI — Yapay zekâ karşılık veriyor…");main.postDelayed(this::aiShot,aiLevel>=3?420:650);}\n    private void aiShot(){if(!solo||board.gameOver)return;int[] q=pickAi();if(q==null)return;int res=board.receiveOwnShot(q[0],q[1]);if(res==2)addNeighbors(q[0],q[1]);board.flash(q[0],q[1],true,res==2);if(board.allOwnSunk()){board.gameOver=true;myTurn=false;finishMatch(false);}else{myTurn=true;status.setText(res==2?"Gemimiz VURULDU! Sıra sende.":"Rakip ıskaladı. Sıra sende.");}}'''
new_player='''private void playerShot(int r,int c){\n        if(board.enemyMarks[r][c]!=0){myTurn=true;status.setText("BU KOORDİNAT ZATEN VURULDU — sıran devam ediyor.");board.flash(r,c,false,false);updateHud();main.postDelayed(this::restoreTurnPrompt,700);return;}\n        myTurn=false;int shipId=board.aiFleet[r][c];int res=board.receiveAiShot(r,c);board.enemyMarks[r][c]=res;matchShots++;if(res==2)matchHits++;recordShot(res==2);board.flash(r,c,false,res==2);boolean sunk=res==2&&shipId>=0&&board.isAiShipSunk(shipId);\n        if(sunk){board.startSinking(shipId,false);main.postDelayed(()->BattleEffects.sunk(this),140);status.setText(AdvancedShipRenderer.name(shipId)+" BATIRILDI!  •  "+DIFF[aiLevel]+" karşılık veriyor…");}\n        if(board.allAiSunk()){board.gameOver=true;myTurn=false;updateHud();finishMatch(true);return;}\n        if(!sunk)status.setText(res==2?"VURUŞ!  •  "+DIFF[aiLevel]+" HEDEFLİYOR…":"ISKALANDI  •  "+DIFF[aiLevel]+" HEDEFLİYOR…");updateHud();\n        main.postDelayed(this::aiShot,sunk?1050:(aiLevel>=3?520:720));\n        main.postDelayed(()->{if(solo&&board!=null&&!board.gameOver&&!myTurn){status.setText("SIRA KURTARILIYOR…");aiShot();}},2600);\n    }\n    private void aiShot(){\n        if(!solo||board.gameOver||myTurn)return;int[] q=pickAi();if(q==null){myTurn=true;restoreTurnPrompt();return;}int shipId=board.own[q[0]][q[1]];int res=board.receiveOwnShot(q[0],q[1]);if(res==2)addNeighbors(q[0],q[1]);board.flash(q[0],q[1],true,res==2);boolean sunk=res==2&&shipId>=0&&board.isOwnShipSunk(shipId);\n        if(sunk){board.startSinking(shipId,true);main.postDelayed(()->BattleEffects.sunk(this),140);}\n        if(board.allOwnSunk()){board.gameOver=true;myTurn=false;updateHud();finishMatch(false);}\n        else{myTurn=true;status.setText(sunk?AdvancedShipRenderer.name(shipId)+" GEMİMİZ BATTI!  •  SIRA SENDE":(res==2?"GEMİMİZ VURULDU!  •  SIRA SENDE":"RAKİP ISKALADI  •  SIRA SENDE"));updateHud();}\n    }'''
rep(old_player,new_player,'solo-turn-flow')

# Enhance Bluetooth receiver with own-ship sinking animation.
old_bt='''case"SHOT":{int r=Integer.parseInt(a[1]),c=Integer.parseInt(a[2]),res=board.receiveOwnShot(r,c);link.send("RESULT|"+r+"|"+c+"|"+res);board.flash(r,c,true,res==2);if(board.allOwnSunk()){link.send("GAMEOVER");board.gameOver=true;finishMatch(false);}else{myTurn=true;status.setText("Sıra sende — hedef seç.");}break;}case"RESULT":{int r=Integer.parseInt(a[1]),c=Integer.parseInt(a[2]),res=Integer.parseInt(a[3]);board.enemyMarks[r][c]=res;recordShot(res==2);if(res==2)BattleEffects.hit(this);else BattleEffects.miss(this);board.flash(r,c,false,res==2);status.setText(res==2?"VURUŞ! Rakibin sırası…":"ISKALANDI — Rakibin sırası…");break;}'''
new_bt='''case"SHOT":{int r=Integer.parseInt(a[1]),c=Integer.parseInt(a[2]),shipId=board.own[r][c],res=board.receiveOwnShot(r,c);boolean sunk=res==2&&shipId>=0&&board.isOwnShipSunk(shipId);link.send("RESULT|"+r+"|"+c+"|"+res+"|"+shipId+"|"+(sunk?1:0));board.flash(r,c,true,res==2);if(sunk){board.startSinking(shipId,true);main.postDelayed(()->BattleEffects.sunk(this),140);}if(board.allOwnSunk()){link.send("GAMEOVER");board.gameOver=true;updateHud();finishMatch(false);}else{myTurn=true;status.setText(sunk?AdvancedShipRenderer.name(shipId)+" GEMİMİZ BATTI!  •  SIRA SENDE":"SIRA SENDE — hedef seç.");updateHud();}break;}case"RESULT":{int r=Integer.parseInt(a[1]),c=Integer.parseInt(a[2]),res=Integer.parseInt(a[3]);board.enemyMarks[r][c]=res;matchShots++;if(res==2)matchHits++;recordShot(res==2);if(res==2)BattleEffects.hit(this);else BattleEffects.miss(this);board.flash(r,c,false,res==2);boolean sunk=a.length>5&&"1".equals(a[5]);int shipId=a.length>4?Integer.parseInt(a[4]):-1;if(sunk){enemySunkCount++;main.postDelayed(()->BattleEffects.sunk(this),140);status.setText((shipId>=0?AdvancedShipRenderer.name(shipId):"DÜŞMAN GEMİSİ")+" BATIRILDI!  •  Rakibin sırası…");}else status.setText(res==2?"VURUŞ! Rakibin sırası…":"ISKALANDI — Rakibin sırası…");updateHud();break;}'''
rep(old_bt,new_bt,'bluetooth-sink')

# Board state and sinking helpers.
rep('int placed=0;boolean horizontal=true,playing=false,gameOver=false;int flashR=-1,flashC=-1;boolean flashMine=false,flashHit=false;long flashUntil=0;',
    'int placed=0;boolean horizontal=true,playing=false,gameOver=false;int flashR=-1,flashC=-1;boolean flashMine=false,flashHit=false;long flashUntil=0;int sinkShip=-1;boolean sinkMine=false;long sinkStart=0,sinkUntil=0;','sink-fields')
rep('boolean allOwnSunk(){for(int r=0;r<10;r++)for(int c=0;c<10;c++)if(own[r][c]>=0&&!hit[r][c])return false;return true;}boolean allAiSunk(){for(int r=0;r<10;r++)for(int c=0;c<10;c++)if(aiFleet[r][c]>=0&&!aiHit[r][c])return false;return true;}',
'''boolean isOwnShipSunk(int id){boolean found=false;for(int r=0;r<10;r++)for(int c=0;c<10;c++)if(own[r][c]==id){found=true;if(!hit[r][c])return false;}return found;}\n        boolean isAiShipSunk(int id){boolean found=false;for(int r=0;r<10;r++)for(int c=0;c<10;c++)if(aiFleet[r][c]==id){found=true;if(!aiHit[r][c])return false;}return found;}\n        int aliveOwnShips(){int n=0;for(int id=0;id<len.length;id++)if(!isOwnShipSunk(id))n++;return n;}\n        int aliveAiShips(){int n=0;for(int id=0;id<len.length;id++)if(!isAiShipSunk(id))n++;return n;}\n        boolean allOwnSunk(){return aliveOwnShips()==0;}boolean allAiSunk(){return aliveAiShips()==0;}\n        void startSinking(int id,boolean mine){sinkShip=id;sinkMine=mine;sinkStart=System.currentTimeMillis();sinkUntil=sinkStart+1550;animateSink();}\n        void animateSink(){invalidate();if(System.currentTimeMillis()<sinkUntil)main.postDelayed(this::animateSink,70);}''','sink-helpers')

old_draw='''if(mine)for(int id=0;id<len.length;id++)AdvancedShipRenderer.draw(c,p,left,top,cell,own,id);for(int r=0;r<10;r++)for(int col=0;col<10;col++){'''
new_draw='''if(mine){for(int id=0;id<len.length;id++)if(!isOwnShipSunk(id)&&!(sinkMine&&sinkShip==id&&System.currentTimeMillis()<sinkUntil))AdvancedShipRenderer.draw(c,p,left,top,cell,own,id);}else if(solo){for(int id=0;id<len.length;id++)if(isAiShipSunk(id)&&!(!sinkMine&&sinkShip==id&&System.currentTimeMillis()<sinkUntil))AdvancedShipRenderer.draw(c,p,left,top,cell,aiFleet,id);}for(int r=0;r<10;r++)for(int col=0;col<10;col++){'''
rep(old_draw,new_draw,'draw-sunk-ships')
rep('''if(System.currentTimeMillis()<flashUntil&&flashMine==mine){float cx=left+(flashC+.5f)*cell,cy=top+(flashR+.5f)*cell;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(cell*.10f);p.setColor(flashHit?Color.YELLOW:Color.WHITE);c.drawCircle(cx,cy,cell*.40f,p);p.setStyle(Paint.Style.FILL);}}''',
'''if(System.currentTimeMillis()<flashUntil&&flashMine==mine){float cx=left+(flashC+.5f)*cell,cy=top+(flashR+.5f)*cell;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(cell*.10f);p.setColor(flashHit?Color.YELLOW:Color.WHITE);c.drawCircle(cx,cy,cell*.40f,p);p.setStyle(Paint.Style.FILL);}if(sinkShip>=0&&sinkMine==mine&&System.currentTimeMillis()<sinkUntil)drawSinking(c,left,top,cell,mine);}\n        private void drawSinking(Canvas c,float left,float top,float cell,boolean mine){int[][] b=mine?own:aiFleet;int minR=99,maxR=-1,minC=99,maxC=-1;for(int r=0;r<10;r++)for(int col=0;col<10;col++)if(b[r][col]==sinkShip){minR=Math.min(minR,r);maxR=Math.max(maxR,r);minC=Math.min(minC,col);maxC=Math.max(maxC,col);}if(maxR<0)return;float progress=Math.min(1f,(System.currentTimeMillis()-sinkStart)/(float)Math.max(1,sinkUntil-sinkStart));float cx=left+(minC+maxC+1)*cell/2f,cy=top+(minR+maxR+1)*cell/2f;c.save();c.translate(0,progress*cell*.85f);AdvancedShipRenderer.draw(c,p,left,top,cell,b,sinkShip);c.restore();float fade=1f-progress;p.setStyle(Paint.Style.FILL);p.setColor(Color.argb((int)(210*fade),255,92,25));c.drawCircle(cx,cy-progress*cell*.15f,cell*(.34f+.16f*progress),p);p.setColor(Color.argb((int)(180*fade),45,45,45));c.drawCircle(cx-cell*.18f,cy-cell*(.34f+.30f*progress),cell*(.22f+.18f*progress),p);c.drawCircle(cx+cell*.16f,cy-cell*(.46f+.38f*progress),cell*(.17f+.20f*progress),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(cell*.06f);p.setColor(Color.argb((int)(220*fade),170,235,250));c.drawCircle(cx,cy+cell*.35f,cell*(.32f+.72f*progress),p);p.setStyle(Paint.Style.FILL);}''','sink-draw-fx')

old_touch='''@Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float[]g=geo();float cell=g[1],left=g[2],t1=g[3],t2=g[4];if(!playing&&!localReady){int c=(int)((e.getX()-left)/cell),r=(int)((e.getY()-t1)/cell);if(valid(r,c)&&placed<len.length&&can(own,r,c,len[placed],horizontal)){place(own,r,c,len[placed],horizontal,placed);placed++;invalidate();}return true;}if(playing&&myTurn&&!gameOver){int c=(int)((e.getX()-left)/cell),r=(int)((e.getY()-t2)/cell);if(valid(r,c)){myTurn=false;if(solo)playerShot(r,c);else if(connected){link.send("SHOT|"+r+"|"+c);status.setText("Atış gönderildi — sonuç bekleniyor…");}}}return true;}'''
new_touch='''@Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float[]g=geo();float cell=g[1],left=g[2],t1=g[3],t2=g[4];if(!playing&&!localReady){int c=(int)((e.getX()-left)/cell),r=(int)((e.getY()-t1)/cell);if(valid(r,c)&&placed<len.length&&can(own,r,c,len[placed],horizontal)){place(own,r,c,len[placed],horizontal,placed);placed++;invalidate();}return true;}if(playing&&myTurn&&!gameOver){int c=(int)((e.getX()-left)/cell),r=(int)((e.getY()-t2)/cell);if(valid(r,c)){if(enemyMarks[r][c]!=0){status.setText("BU KOORDİNAT ZATEN VURULDU — sıran devam ediyor.");flash(r,c,false,false);main.postDelayed(GameActivity.this::restoreTurnPrompt,700);return true;}if(solo)playerShot(r,c);else if(connected){myTurn=false;link.send("SHOT|"+r+"|"+c);status.setText("ATIŞ GÖNDERİLDİ — sonuç bekleniyor…");updateHud();main.postDelayed(()->{if(!solo&&board!=null&&board.playing&&!board.gameOver&&!myTurn&&connected)status.setText("SONUÇ BEKLENİYOR — Bluetooth bağlantısı aktif…");},2200);}}}return true;}'''
rep(old_touch,new_touch,'touch-turn-lock')

p.write_text(s,encoding='utf-8')
print('v8 patch applied:',p)
for token in ['battleHud','startSinking','BATIRILDI','SIRA KURTARILIYOR','BU KOORDİNAT ZATEN VURULDU']:
    assert token in s, token
