plugins { id 'com.android.application' }

android {
    namespace 'com.muhammetgecgil.modelviewer'
    compileSdk 36
    defaultConfig {
        applicationId 'com.muhammetgecgil.mg3dmodelviewer'
        minSdk 26
        targetSdk 36
        versionCode 14
        versionName '1.3.1'
    }
    signingConfigs {
        release {
            storeFile rootProject.file('mg3d-release.jks')
            storePassword 'mg3dviewer2026'
            keyAlias 'mg3d'
            keyPassword 'mg3dviewer2026'
        }
        debug {
            storeFile rootProject.file('mg3d-release.jks')
            storePassword 'mg3dviewer2026'
            keyAlias 'mg3d'
            keyPassword 'mg3dviewer2026'
        }
    }
    buildTypes {
        debug { signingConfig signingConfigs.debug }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
