from pathlib import Path
AS=Path('modelviewer/src/main/assets/cadviewer')
html=AS/'index.html'
h=html.read_text(encoding='utf-8')
if '/cad-v2560.js' not in h:
    h=h.replace('</body>','<script src="/cad-v2560.js"></script></body>',1)
html.write_text(h,encoding='utf-8')
js=r'''(function(){
'use strict';
function ready(f){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f,{once:true}):f()}
let thickOn=false, thickGeom=[],activeMethod=null,sceneAddOriginal=null;
const BLUE=0x42a5ff,GREEN=0x55d98a,ORANGE=0xff9f43;
function unit(v){const f=typeof unitFactor==='function'?unitFactor():1,u=document.getElementById('unit')?.value||'mm';return (v*f).toFixed(Math.abs(v*f)>=100?2:3)+' '+u}
function info(t){const e=document.getElementById('mgMeasureInfo2560');if(e)e.innerHTML=t}
function smartBtn(){return document.getElementById('mgSmartMeasure2550')}
function smartActive(){const b=smartBtn();return !!(b&&b.classList.contains('on'))}
function smartOff(){const b=smartBtn();if(b&&smartActive())b.click()}
function classicOff(){if(window.measureOn&&window.toggleMeasure)window.toggleMeasure()}
function clearThick(){thickGeom.forEach(o=>{scene.remove(o);if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()});thickGeom=[]}
function setActive(name){activeMethod=name||null;['mgRef2560','mgPoint2560','mgThick2560'].forEach(id=>{const b=document.getElementById(id);if(b)b.classList.remove('mgm-active')});const m={ref:'mgRef2560',point:'mgPoint2560',thick:'mgThick2560'}[name];if(m){const b=document.getElementById(m);if(b)b.classList.add('mgm-active')}}
function stopAll(){smartOff();classicOff();thickOn=false;clearThick();setActive(null)}
function hideLegacySmart(){const b=smartBtn();if(!b)return;let p=b.parentElement;while(p&&p.parentElement&&p.parentElement.id!=='tools')p=p.parentElement;if(p&&p.parentElement&&p.parentElement.id==='tools')p.style.display='none'}
function cleanupLegacyMeasurementUI(){
 const tools=document.getElementById('tools');if(!tools)return;
 const keep=new Set(['mgRef2560','mgPoint2560','mgThick2560','mgClear2560']);
 const oldTexts=new Set(['AKILLI ÖLÇ','ÖZELLİK ÖLÇ','AKILLI ÖLÇÜ','AKILLI ÖLÇÜM','KALINLIK']);
 [...tools.querySelectorAll('button')].forEach(b=>{if(keep.has(b.id)||b.id==='mgSmartMeasure2550'||b.id==='mgSmartMeasureRef2550')return;const t=(b.textContent||'').replace(/\s+/g,' ').trim().toLocaleUpperCase('tr-TR');if(oldTexts.has(t))b.style.display='none'});
 const mb=document.getElementById('mB');if(mb){const row=mb.closest('.row');if(row)row.style.display='none';let n=row&&row.nextElementSibling;if(n&&n.classList.contains('small'))n.style.display='none';let h=row&&row.previousElementSibling;if(h&&h.classList.contains('head')&&(h.textContent||'').trim().toLocaleUpperCase('tr-TR')==='ÖLÇÜM')h.style.display='none'}
 [...tools.querySelectorAll('.row')].forEach(r=>{const bs=[...r.querySelectorAll('button')];if(bs.length&&bs.every(b=>getComputedStyle(b).display==='none'))r.style.display='none'});
}
function hitAtXY(x,y){const r=canvas.getBoundingClientRect(),m=new THREE.Vector2(((x-r.left)/r.width)*2-1,-((y-r.top)/r.height)*2+1),rr=new THREE.Raycaster();rr.setFromCamera(m,camera);return rr.intersectObjects(group.children.filter(o=>o.visible),true)[0]||null}
function hitAt(ev){return hitAtXY(ev.clientX,ev.clientY)}
function centerHit(){const r=canvas.getBoundingClientRect();let h=hitAtXY(r.left+r.width/2,r.top+r.height/2);if(h)return h;const target=new THREE.Vector3();if(window.selected){new THREE.Box3().setFromObject(window.selected).getCenter(target)}else if(window.bbox){window.bbox.getCenter(target)}else{const vis=group.children.filter(o=>o.visible);if(!vis.length)return null;new THREE.Box3().setFromObject(vis[0]).getCenter(target)}const dir=target.clone().sub(camera.position).normalize(),rr=new THREE.Raycaster(camera.position.clone(),dir,0,1e9);return rr.intersectObjects(group.children.filter(o=>o.visible),true)[0]||null}
function opposite(hit){if(!hit||!hit.face)return null;const n=hit.face.normal.clone().transformDirection(hit.object.matrixWorld).normalize(),span=Math.max(baseDims.x||1,baseDims.y||1,baseDims.z||1,1),eps=span*1e-5;function shoot(dir){const rr=new THREE.Raycaster(hit.point.clone().addScaledVector(dir,eps*8),dir,eps*4,span*4);const hs=rr.intersectObjects(group.children.filter(o=>o.visible),true).filter(x=>x.distance>eps*4);return hs.length?hs[0]:null}const a=shoot(n.clone().negate()),b=shoot(n.clone());if(a&&b)return a.distance<=b.distance?a:b;return a||b}
function addLine(points,color,width){const g=new THREE.BufferGeometry().setFromPoints(points),m=new THREE.LineBasicMaterial({color:color,depthTest:false,linewidth:width||1}),o=new THREE.Line(g,m);o.renderOrder=999;scene.add(o);thickGeom.push(o);return o}
function drawCaliper(a,b,n){clearThick();const span=Math.max(baseDims.x||1,baseDims.y||1,baseDims.z||1,1),view=new THREE.Vector3();camera.getWorldDirection(view);let t=n.clone().cross(view);if(t.lengthSq()<1e-8)t=n.clone().cross(new THREE.Vector3(0,1,0));if(t.lengthSq()<1e-8)t=n.clone().cross(new THREE.Vector3(1,0,0));t.normalize();const jaw=span*.09,stem=span*.035;addLine([a.clone().addScaledVector(t,-jaw),a.clone().addScaledVector(t,jaw)],ORANGE,4);addLine([b.clone().addScaledVector(t,-jaw),b.clone().addScaledVector(t,jaw)],ORANGE,4);addLine([a,b],ORANGE,4);const d=b.clone().sub(a).normalize();addLine([a.clone().addScaledVector(t,jaw),a.clone().addScaledVector(t,jaw).addScaledVector(d,stem)],ORANGE,4);addLine([b.clone().addScaledVector(t,-jaw),b.clone().addScaledVector(t,-jaw).addScaledVector(d,-stem)],ORANGE,4)}
function measureThicknessFromHit(h){if(!h){info('<b>🟧 KALINLIK:</b> Görünür nesne bulunamadı. Nesneyi ekranda ortala.');return false}const o=opposite(h);if(!o){clearThick();info('<b>🟧 Karşı yüz bulunamadı.</b> Kapalı/katı geometriyi ekranda ortala veya ölçmek istediğin yüzeye dokun.');return false}const n=h.face.normal.clone().transformDirection(h.object.matrixWorld).normalize();drawCaliper(h.point.clone(),o.point.clone(),n);const d=h.point.distanceTo(o.point);info('<b>🟧 KALINLIK: '+unit(d)+'</b><br><small>Turuncu iki kumpas çenesi karşı yüzeyleri gösteriyor.</small>');if(navigator.vibrate)navigator.vibrate([20,35,20]);return true}
function installSceneColorHook(){if(sceneAddOriginal)return;sceneAddOriginal=scene.add.bind(scene);scene.add=function(){const objs=[...arguments];let col=activeMethod==='ref'?BLUE:activeMethod==='point'?GREEN:activeMethod==='thick'?ORANGE:null;if(col!==null){objs.forEach(o=>{if(!o||!o.material)return;const isMeasureLine=!!o.isLine,isMeasureMarker=!!(o.isMesh&&o.geometry&&o.geometry.type==='SphereGeometry');if(isMeasureLine||isMeasureMarker){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if(m.color)m.color.setHex(col)})}})}return sceneAddOriginal(...objs)}}
function install(){const tools=document.getElementById('tools');if(!tools||document.getElementById('mgMeasureModes2560'))return;hideLegacySmart();installSceneColorHook();const style=document.createElement('style');style.textContent=`#mgMeasureModes2560{margin-top:8px}.mgm-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mgm-btn{min-height:58px;font-size:15px;border-width:2px}.mgm-ref{border-color:#42a5ff;color:#bfe4ff}.mgm-point{border-color:#55d98a;color:#c9f7da}.mgm-thick{grid-column:1/-1;border-color:#ff9f43;color:#ffd4ad;font-size:16px}.mgm-active{outline:3px solid currentColor;box-shadow:0 0 0 2px rgba(255,255,255,.08) inset}.mgm-legend{display:flex;gap:8px;flex-wrap:wrap;font-size:11px;opacity:.86;margin:6px 0}.mgm-dot{font-weight:900}`;document.head.appendChild(style);const w=document.createElement('div');w.id='mgMeasureModes2560';w.innerHTML='<div class="sep"></div><div class="head">ÖLÇÜM MODLARI</div><div class="mgm-grid"><button id="mgRef2560" class="mgm-btn mgm-ref">🔷 REFERANSLI ÖLÇÜM</button><button id="mgPoint2560" class="mgm-btn mgm-point">🟢 NOKTA–NOKTA</button><button id="mgThick2560" class="mgm-btn mgm-thick">🟧 ┫━━━━┣ KUMPAS / KALINLIK</button></div><div class="mgm-legend"><span>🔷 Referanslı</span><span>🟢 Mesafe</span><span>🟧 Kalınlık</span><span>🟨 Otomatik ölçü</span></div><div class="row"><button id="mgClear2560">ÖLÇÜMÜ TEMİZLE</button></div><div class="small" id="mgMeasureInfo2560">Her ölçüm metodu ayrı renkte; aynı anda yalnızca biri aktif.</div>';tools.appendChild(w);cleanupLegacyMeasurementUI();const rb=document.getElementById('mgRef2560'),pb=document.getElementById('mgPoint2560'),tb=document.getElementById('mgThick2560');rb.onclick=e=>{e.preventDefault();classicOff();thickOn=false;clearThick();setActive('ref');if(!smartActive()){const b=smartBtn();if(b)b.click()}info('<b>🔷 REFERANSLI:</b> Referans kenar/yüzey → 1. nokta → 2. nokta. Ölçüm grafikleri mavi.')};pb.onclick=e=>{e.preventDefault();smartOff();thickOn=false;clearThick();setActive('point');if(!window.measureOn&&window.toggleMeasure)window.toggleMeasure();info('<b>🟢 NOKTA–NOKTA:</b> İlk noktayı, sonra ikinci noktayı seç. Ölçüm grafikleri yeşil.')};tb.onclick=e=>{e.preventDefault();smartOff();classicOff();clearThick();thickOn=true;setActive('thick');info('<b>🟧 KUMPAS:</b> Nesne otomatik ölçülüyor…');setTimeout(()=>measureThicknessFromHit(centerHit()),0)};document.getElementById('mgClear2560').onclick=e=>{e.preventDefault();stopAll();if(window.clearMeasure)window.clearMeasure();info('Ölçümler temizlendi. Bir ölçüm modu seç.')};canvas.addEventListener('click',ev=>{if(!thickOn||ev.clientY<58)return;const h=hitAt(ev);if(!h)return;ev.preventDefault();ev.stopImmediatePropagation();measureThicknessFromHit(h)},true)}
function init(){install();window.MG_CAD_V2560={version:'2.5.6',baseline:'2.5.5',referenceVersion:'2.5.5',exclusiveMeasurementModes:true,visualModeSeparation:true,instantCaliperOnButton:true,oneTapThickness:true,largeCaliperJaws:true,methodColors:{smart:'blue',point:'green',thickness:'orange',automatic:'yellow'},legacyDuplicateMeasurementUIRemoved:true}}
ready(init)
})();'''
(AS/'cad-v2560.js').write_text(js,encoding='utf-8')
print('v2.5.6 instant caliper + method colors + duplicate measurement UI cleanup')
