from pathlib import Path

AS=Path('modelviewer/src/main/assets/cadviewer')
AS.mkdir(parents=True, exist_ok=True)
js=r'''(function(){
'use strict';
let smartOn=false, smartPicks=[], thicknessOn=false, holeCandidates=[], markupOn=false, markupCtx=null, currentDensity=2.70, lastSmart='';
const tools=document.getElementById('tools');
function el(tag,attrs={},html=''){const x=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>x.setAttribute(k,v));x.innerHTML=html;return x}
function addSection(title,html){const sep=el('div',{class:'sep'});const h=el('div',{class:'head'},title);const box=el('div');box.innerHTML=html;tools.appendChild(sep);tools.appendChild(h);tools.appendChild(box);return box}
function U(v){return fmt(v)+' '+document.getElementById('unit').value}
function worldNormal(hit){let n=hit.face?hit.face.normal.clone():new THREE.Vector3(0,0,1);const nm=new THREE.Matrix3().getNormalMatrix(hit.object.matrixWorld);return n.applyMatrix3(nm).normalize()}
function hitNow(ev){const r=canvas.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);return ray.intersectObjects(group.children.filter(x=>x.visible),false)[0]||null}
function markerAt(p,color=0xffd34d){const g=new THREE.SphereGeometry(Math.max(Math.max(baseDims.x,baseDims.y,baseDims.z)*.006,.05),12,8);const m=new THREE.MeshBasicMaterial({color});const s=new THREE.Mesh(g,m);s.position.copy(p);scene.add(s);markers.push(s);return s}

const mode=addSection('MÜHENDİSLİK MODLARI',`<div class="row"><button id="smartB">AKILLI ÖLÇ</button><button id="thickB">KALINLIK</button></div><div class="row"><button id="holesB">DELİKLER</button><button id="probeB">PROB</button></div><div id="proResult" class="small">Yüzey/kenar incelemesi için bir araç seç.</div>`);
document.getElementById('smartB').onclick=()=>{smartOn=!smartOn;thicknessOn=false;document.getElementById('smartB').classList.toggle('on',smartOn);document.getElementById('thickB').classList.remove('on');controls.enableRotate=!smartOn;smartPicks=[];document.getElementById('proResult').textContent=smartOn?'Bir yüzey noktası seç; ikinci seçimde mesafe ve bileşenler hesaplanır.':'Akıllı ölç kapalı'};
document.getElementById('thickB').onclick=()=>{thicknessOn=!thicknessOn;smartOn=false;document.getElementById('thickB').classList.toggle('on',thicknessOn);document.getElementById('smartB').classList.remove('on');controls.enableRotate=!thicknessOn;document.getElementById('proResult').textContent=thicknessOn?'Kalınlık için bir yüzeye dokun.':'Kalınlık modu kapalı'};
document.getElementById('probeB').onclick=()=>{smartOn=true;thicknessOn=false;document.getElementById('smartB').classList.add('on');controls.enableRotate=false;smartPicks=[];document.getElementById('proResult').textContent='Koordinat probu: model üzerinde bir nokta seç.'};

canvas.addEventListener('click',ev=>{if(!smartOn&&!thicknessOn)return;ev.preventDefault();ev.stopImmediatePropagation();const h=hitNow(ev);if(!h)return;const p=h.point.clone(),n=worldNormal(h),u=document.getElementById('unit').value;markerAt(p, smartOn?0xffd34d:0x73ff9d);if(thicknessOn){const eps=Math.max(Math.max(baseDims.x,baseDims.y,baseDims.z)*1e-5,1e-4);const rr=new THREE.Raycaster(p.clone().add(n.clone().multiplyScalar(-eps*4)),n.clone().negate(),eps,Math.max(baseDims.x,baseDims.y,baseDims.z)*3);const hs=rr.intersectObject(h.object,false).filter(z=>z.distance>eps*3);if(hs.length){const d=hs[0].distance;lastSmart='Tahmini lokal et kalınlığı: '+U(d);document.getElementById('proResult').innerHTML='<b>KALINLIK ≈ '+U(d)+'</b><br>Seçili parça: '+esc(h.object.name)+'<br>Not: üçgenleştirilmiş CAD yüzeyinden hesaplanır.'}else document.getElementById('proResult').textContent='Karşı yüzey bulunamadı; açık geometri olabilir.';return}
smartPicks.push(p);const sx=fmt(p.x),sy=fmt(p.y),sz=fmt(p.z);if(smartPicks.length===1){lastSmart='Prob X='+sx+' '+u+', Y='+sy+' '+u+', Z='+sz+' '+u;document.getElementById('proResult').innerHTML='<b>KOORDİNAT PROBU</b><br>X '+sx+' '+u+' • Y '+sy+' '+u+' • Z '+sz+' '+u+'<br>Normal ≈ ['+n.x.toFixed(3)+', '+n.y.toFixed(3)+', '+n.z.toFixed(3)+']'}else{const a=smartPicks[smartPicks.length-2],b=smartPicks[smartPicks.length-1],d=a.distanceTo(b),dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z;lastSmart='Mesafe '+U(d)+' | ΔX '+U(dx)+' ΔY '+U(dy)+' ΔZ '+U(dz);document.getElementById('proResult').innerHTML='<b>MESAFE '+U(d)+'</b><br>ΔX '+U(dx)+' • ΔY '+U(dy)+' • ΔZ '+U(dz);if(smartPicks.length>=4)smartPicks=smartPicks.slice(-2)}} ,true);

function weldGeometry(g,tol){const p=g.attributes.position,ids=[],pts=[],map=new Map();for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),k=Math.round(x/tol)+','+Math.round(y/tol)+','+Math.round(z/tol);let id=map.get(k);if(id===undefined){id=pts.length;map.set(k,id);pts.push(new THREE.Vector3(x,y,z))}ids.push(id)}return{ids,pts}}
function fitCircle(comp,pts){let min=new THREE.Vector3(Infinity,Infinity,Infinity),max=new THREE.Vector3(-Infinity,-Infinity,-Infinity),c=new THREE.Vector3();comp.forEach(i=>{const p=pts[i];min.min(p);max.max(p);c.add(p)});c.multiplyScalar(1/comp.length);const s=max.clone().sub(min);let drop=s.x<=s.y&&s.x<=s.z?0:(s.y<=s.z?1:2),rs=[];for(const i of comp){const p=pts[i];const a=drop===0?p.y-c.y:p.x-c.x,b=drop===2?p.y-c.y:p.z-c.z;rs.push(Math.hypot(a,b))}const r=rs.reduce((a,b)=>a+b,0)/rs.length,sd=Math.sqrt(rs.reduce((a,b)=>a+(b-r)*(b-r),0)/rs.length);if(r<=0||sd/r>.055)return null;const dia=2*r;if(dia<Math.max(baseDims.x,baseDims.y,baseDims.z)*.002)return null;return{center:c,r,axis:drop===0?'X':drop===1?'Y':'Z',quality:1-sd/r}}
function detectHoles(){holeCandidates=[];const scale=Math.max(baseDims.x,baseDims.y,baseDims.z,1),tol=scale*1e-5;group.children.forEach(mesh=>{const g=mesh.geometry, p=g.attributes.position;if(!p)return;const w=weldGeometry(g,tol),idx=g.index,edges=new Map();const tc=idx?idx.count/3:p.count/3;function add(a,b){if(a>b){const t=a;a=b;b=t}const k=a+','+b;edges.set(k,(edges.get(k)||0)+1)}for(let t=0;t<tc;t++){const ia=w.ids[idx?idx.getX(t*3):t*3],ib=w.ids[idx?idx.getX(t*3+1):t*3+1],ic=w.ids[idx?idx.getX(t*3+2):t*3+2];add(ia,ib);add(ib,ic);add(ic,ia)}const adj=new Map();for(const [k,n] of edges)if(n===1){const [a,b]=k.split(',').map(Number);if(!adj.has(a))adj.set(a,[]);if(!adj.has(b))adj.set(b,[]);adj.get(a).push(b);adj.get(b).push(a)}const seen=new Set();for(const start of adj.keys()){if(seen.has(start))continue;const stack=[start],comp=[];while(stack.length){const v=stack.pop();if(seen.has(v))continue;seen.add(v);comp.push(v);(adj.get(v)||[]).forEach(n=>{if(!seen.has(n))stack.push(n)})}if(comp.length>=10){const f=fitCircle(comp,w.pts);if(f){f.mesh=mesh;holeCandidates.push(f)}}}});holeCandidates=holeCandidates.filter((h,i,a)=>!a.slice(0,i).some(k=>k.center.distanceTo(h.center)<Math.max(h.r,k.r)*.15&&Math.abs(k.r-h.r)<Math.max(h.r,k.r)*.08));renderHoleTable()}
function renderHoleTable(){let panel=document.getElementById('holePanel');if(!panel){panel=el('div',{id:'holePanel',class:'panel hide'});panel.style.cssText='left:8px;top:66px;max-width:360px;max-height:60%;overflow:auto';document.body.appendChild(panel)}let h='<div class="head">DELİK / DAİRESEL AÇIKLIK TABLOSU</div><div class="small">Mesh sınırlarından otomatik aday tespiti. CAD toleransına göre doğrula.</div>';if(!holeCandidates.length)h+='<p>Aday bulunamadı.</p>';else{h+='<div class="small">';holeCandidates.forEach((x,i)=>{h+=(i+1)+'. Ø'+U(2*x.r)+' • '+x.axis+' ekseni • X '+U(x.center.x)+' Y '+U(x.center.y)+' Z '+U(x.center.z)+'<br>'});h+='</div>'}h+='<div class="row"><button onclick="document.getElementById(\'holePanel\').classList.add(\'hide\')">KAPAT</button></div>';panel.innerHTML=h;panel.classList.remove('hide')}
document.getElementById('holesB').onclick=()=>{document.getElementById('proResult').textContent='Dairesel sınırlar analiz ediliyor…';setTimeout(()=>{detectHoles();document.getElementById('proResult').textContent=holeCandidates.length+' dairesel açıklık adayı bulundu.'},20)};

const manuf=addSection('İMALAT / KÜTLE',`<select id="matSel" style="width:100%"><option value="2.70">Alüminyum 6061/Genel (2.70)</option><option value="2.81">Alüminyum 7075 (2.81)</option><option value="7.85">Çelik (7.85)</option><option value="4.43">Titanyum Ti-6Al-4V (4.43)</option><option value="1.04">ABS (1.04)</option><option value="1.24">PLA (1.24)</option></select><div class="row"><button id="massB">KÜTLE / CG</button><button id="reportB">RAPOR</button></div><div id="massOut" class="small"></div>`);
document.getElementById('matSel').onchange=e=>currentDensity=parseFloat(e.target.value)||2.7;
function calcCG(){let sv=0,cg=new THREE.Vector3();group.children.forEach(m=>{const g=m.geometry,p=g.attributes.position,idx=g.index;if(!p)return;const A=new THREE.Vector3(),B=new THREE.Vector3(),C=new THREE.Vector3(),cr=new THREE.Vector3();const tc=idx?idx.count/3:p.count/3;for(let t=0;t<tc;t++){A.fromBufferAttribute(p,idx?idx.getX(t*3):t*3);B.fromBufferAttribute(p,idx?idx.getX(t*3+1):t*3+1);C.fromBufferAttribute(p,idx?idx.getX(t*3+2):t*3+2);const v=A.dot(cr.crossVectors(B,C))/6;sv+=v;cg.add(A.clone().add(B).add(C).multiplyScalar(v/4))}});if(Math.abs(sv)>1e-9)cg.multiplyScalar(1/sv);else if(bbox)bbox.getCenter(cg);return{v:Math.abs(sv),cg}}
document.getElementById('massB').onclick=()=>{const z=calcCG(),mass=z.v*currentDensity/1000;document.getElementById('massOut').innerHTML='<b>Tahmini kütle '+mass.toFixed(2)+' g</b><br>Hacim '+(z.v/1000).toFixed(3)+' cm³<br>CG X '+U(z.cg.x)+' • Y '+U(z.cg.y)+' • Z '+U(z.cg.z)+'<br><span style="color:#9db4c8">Kapalı ve doğru yönlü mesh varsayımıyla.</span>';lastSmart='Kütle '+mass.toFixed(2)+' g; CG '+U(z.cg.x)+', '+U(z.cg.y)+', '+U(z.cg.z)};

const mark=addSection('S-PEN / MARKUP',`<div class="row"><button id="markB">ÇİZ</button><button id="markClear">SİL</button></div><div class="small">Kalem veya parmakla kırmızı işaretleme. Çizim modeli değiştirmez.</div>`);
const mc=el('canvas',{id:'markupCanvas'});mc.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:12;pointer-events:none';document.body.appendChild(mc);function resizeMarkup(){mc.width=innerWidth*devicePixelRatio;mc.height=innerHeight*devicePixelRatio;mc.style.width=innerWidth+'px';mc.style.height=innerHeight+'px';markupCtx=mc.getContext('2d');markupCtx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);markupCtx.lineCap='round';markupCtx.lineJoin='round'}resizeMarkup();addEventListener('resize',resizeMarkup);let drawing=false;mc.addEventListener('pointerdown',e=>{if(!markupOn)return;drawing=true;mc.setPointerCapture(e.pointerId);markupCtx.beginPath();markupCtx.moveTo(e.clientX,e.clientY)});mc.addEventListener('pointermove',e=>{if(!drawing)return;markupCtx.strokeStyle=e.pointerType==='pen'?'#ff3b30':'#ff5a52';markupCtx.lineWidth=e.pointerType==='pen'?2.2:3.2;markupCtx.lineTo(e.clientX,e.clientY);markupCtx.stroke()});mc.addEventListener('pointerup',()=>drawing=false);document.getElementById('markB').onclick=()=>{markupOn=!markupOn;document.getElementById('markB').classList.toggle('on',markupOn);mc.style.pointerEvents=markupOn?'auto':'none'};document.getElementById('markClear').onclick=()=>markupCtx.clearRect(0,0,innerWidth,innerHeight);

function reportText(){const u=document.getElementById('unit').value,z=calcCG(),mass=z.v*currentDensity/1000;let r='MG CAD MANUFACTURING INSPECTION REPORT\n\nDosya: '+fileName+'\nFormat: '+fileType.toUpperCase()+'\nDış Ölçüler: X '+fmt(baseDims.x)+' '+u+'  Y '+fmt(baseDims.y)+' '+u+'  Z '+fmt(baseDims.z)+' '+u+'\nParça/Mesh: '+partCount+'\nÜçgen: '+triCount+'\nYüzey alanı (yaklaşık): '+(totalArea*unitFactor()*unitFactor()).toFixed(2)+' '+u+'²\nKapalı hacim (yaklaşık): '+fmt(Math.cbrt(Math.abs(totalVolume)))+'^3 ölçek karşılığı\nYoğunluk: '+currentDensity+' g/cm³\nTahmini kütle: '+mass.toFixed(2)+' g\nCG: X '+U(z.cg.x)+' Y '+U(z.cg.y)+' Z '+U(z.cg.z)+'\nDairesel açıklık adayı: '+holeCandidates.length+'\n';holeCandidates.forEach((h,i)=>r+='H'+(i+1)+': Ø'+U(2*h.r)+' '+h.axis+' ekseni @ X '+U(h.center.x)+' Y '+U(h.center.y)+' Z '+U(h.center.z)+'\n');if(lastSmart)r+='\nSon ölçüm: '+lastSmart+'\n';r+='\nNot: Delik/kalınlık/kütle değerleri üçgenleştirilmiş CAD geometrisinden hesaplanan inspeksiyon yardımcı sonuçlarıdır; üretim resmi/PMI yerine geçmez.';return r}
document.getElementById('reportB').onclick=()=>{const t=reportText();if(window.AndroidHost&&AndroidHost.savePdf)AndroidHost.savePdf(fileName.replace(/\.[^.]+$/,'')+'_MG_CAD_Report',t);else navigator.clipboard&&navigator.clipboard.writeText(t);document.getElementById('proResult').textContent='Rapor oluşturma komutu gönderildi.'};

const oldUpdate=updateInfo;updateInfo=function(){oldUpdate();if(holeCandidates.length){const u=document.getElementById('unit').value;document.getElementById('proResult').dataset.unit=u}};
})();'''
(AS/'pro160.js').write_text(js,encoding='utf-8')

idx=AS/'index.html'
s=idx.read_text(encoding='utf-8')
if '/pro160.js' not in s:
    s=s.replace('</script></body></html>','</script><script src="/pro160.js"></script></body></html>')
idx.write_text(s,encoding='utf-8')

jp=Path('modelviewer/src/main/java/com/muhammetgecgil/modelviewer/CadViewerActivity.java')
j=jp.read_text(encoding='utf-8')
if '@JavascriptInterface public void savePdf' not in j:
    j=j.replace('@JavascriptInterface public void closeViewer() { runOnUiThread(() -> finish()); }','@JavascriptInterface public void closeViewer() { runOnUiThread(() -> finish()); }\n            @JavascriptInterface public void savePdf(String title, String body) { runOnUiThread(() -> saveSimplePdf(title, body)); }')
    anchor='    private WebResourceResponse resp(String mime, InputStream in) {'
    method=r'''    private void saveSimplePdf(String title, String body) {
        android.graphics.pdf.PdfDocument doc = new android.graphics.pdf.PdfDocument();
        android.graphics.pdf.PdfDocument.PageInfo pi = new android.graphics.pdf.PdfDocument.PageInfo.Builder(595,842,1).create();
        android.graphics.pdf.PdfDocument.Page page = doc.startPage(pi);
        android.graphics.Canvas c = page.getCanvas(); android.graphics.Paint p = new android.graphics.Paint(1);
        p.setColor(android.graphics.Color.BLACK); p.setTextSize(12f); int x=36,y=45,max=88;
        String safe = body == null ? "" : body; for(String line:safe.split("\\n",-1)){ java.util.List<String> chunks=new java.util.ArrayList<>(); if(line.length()==0)chunks.add(""); else for(int i=0;i<line.length();i+=max)chunks.add(line.substring(i,Math.min(line.length(),i+max))); for(String q:chunks){ if(y>810) break; c.drawText(q,x,y,p); y+=16; } if(y>810) break; }
        doc.finishPage(page);
        String fn=(title==null||title.isBlank()?"MG_CAD_Report":title).replaceAll("[^a-zA-Z0-9._-]","_")+".pdf";
        try {
            if(android.os.Build.VERSION.SDK_INT>=29){ android.content.ContentValues v=new android.content.ContentValues(); v.put(android.provider.MediaStore.MediaColumns.DISPLAY_NAME,fn); v.put(android.provider.MediaStore.MediaColumns.MIME_TYPE,"application/pdf"); v.put(android.provider.MediaStore.MediaColumns.RELATIVE_PATH,android.os.Environment.DIRECTORY_DOWNLOADS+"/MG_CAD"); android.net.Uri u=getContentResolver().insert(android.provider.MediaStore.Downloads.EXTERNAL_CONTENT_URI,v); if(u==null)throw new java.io.IOException("MediaStore"); try(java.io.OutputStream o=getContentResolver().openOutputStream(u)){doc.writeTo(o);} }
            else { java.io.File f=new java.io.File(getExternalFilesDir(android.os.Environment.DIRECTORY_DOCUMENTS),fn); try(java.io.OutputStream o=new java.io.FileOutputStream(f)){doc.writeTo(o);} }
            android.widget.Toast.makeText(this,"PDF rapor kaydedildi: "+fn,android.widget.Toast.LENGTH_LONG).show();
        } catch(Exception e){ android.widget.Toast.makeText(this,"PDF kaydedilemedi: "+e.getMessage(),android.widget.Toast.LENGTH_LONG).show(); }
        finally { doc.close(); }
    }

'''
    if anchor not in j: raise SystemExit('CadViewerActivity anchor missing')
    j=j.replace(anchor,method+anchor,1)
jp.write_text(j,encoding='utf-8')
print('CAD Manufacturing Inspection v1.6 patch applied')
