from pathlib import Path
AS=Path('modelviewer/src/main/assets/cadviewer')
html=AS/'index.html'
h=html.read_text(encoding='utf-8')
if '/cad-v2580.js' not in h:
    h=h.replace('</body>','<script src="/cad-v2580.js"></script></body>',1)
html.write_text(h,encoding='utf-8')
js=r'''(function(){
'use strict';
function ready(f){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f,{once:true}):f()}
const BLUE=0x42a5ff,GREEN=0x55d98a;
let mode258='',stage='OFF',ref=null,p1=null,geom=[],faces=[];
const V=()=>new THREE.Vector3();
function span(){return Math.max(baseDims.x||1,baseDims.y||1,baseDims.z||1,1)}
function unit(v){const f=typeof unitFactor==='function'?unitFactor():1,u=document.getElementById('unit')?.value||'mm';return (v*f).toFixed(Math.abs(v*f)>=100?2:3)+' '+u}
function hitAt(ev){const r=canvas.getBoundingClientRect(),m=new THREE.Vector2(((ev.clientX-r.left)/r.width)*2-1,-((ev.clientY-r.top)/r.height)*2+1),rr=new THREE.Raycaster();rr.setFromCamera(m,camera);return rr.intersectObjects(group.children.filter(o=>o.visible),true)[0]||null}
function dispose(o){if(!o)return;scene.remove(o);if(o.geometry)o.geometry.dispose();if(o.material){const a=Array.isArray(o.material)?o.material:[o.material];a.forEach(m=>{if(m.map)m.map.dispose();m.dispose&&m.dispose()})}}
function clearGeom(){geom.forEach(dispose);geom=[];faces.forEach(dispose);faces=[]}
function add(o,a){o.renderOrder=1400;scene.add(o);a.push(o);return o}
function point(p,c){const r=span()*.014,o=new THREE.Mesh(new THREE.SphereGeometry(r,18,12),new THREE.MeshBasicMaterial({color:c,depthTest:false}));o.position.copy(p);return add(o,geom)}
function line(a,b,c){return add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color:c,depthTest:false})),geom)}
function faceVerts(h){if(!h.face||!h.object?.geometry?.attributes?.position)return null;const p=h.object.geometry.attributes.position,f=h.face;return [V().fromBufferAttribute(p,f.a).applyMatrix4(h.object.matrixWorld),V().fromBufferAttribute(p,f.b).applyMatrix4(h.object.matrixWorld),V().fromBufferAttribute(p,f.c).applyMatrix4(h.object.matrixWorld)]}
function faceHighlight(h,c){const a=faceVerts(h);if(!a)return;const g=new THREE.BufferGeometry().setFromPoints(a);g.setIndex([0,1,2]);const o=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.42,side:THREE.DoubleSide,depthTest:false,depthWrite:false}));add(o,faces)}
function closestEdge(h){const a=faceVerts(h);if(!a)return null;function ds(P,A,B){const d=B.clone().sub(A),l2=d.lengthSq();let t=l2?P.clone().sub(A).dot(d)/l2:0;t=Math.max(0,Math.min(1,t));const q=A.clone().addScaledVector(d,t);return{d:P.distanceTo(q),dir:d.normalize(),q,len:A.distanceTo(B)}}const es=[ds(h.point,a[0],a[1]),ds(h.point,a[1],a[2]),ds(h.point,a[2],a[0])].sort((x,y)=>x.d-y.d),e=es[0],mx=Math.max(...es.map(x=>x.len),1e-6);return e.d<mx*.12?e:null}
function makeRef(h){let z=h.face?h.face.normal.clone().transformDirection(h.object.matrixWorld).normalize():new THREE.Vector3(0,0,1),e=closestEdge(h),x=e?e.dir.clone():null;if(x){x.sub(z.clone().multiplyScalar(x.dot(z)));if(x.lengthSq()<1e-12)x=null}if(!x){let w=Math.abs(z.y)<.92?new THREE.Vector3(0,1,0):new THREE.Vector3(1,0,0);x=w.sub(z.clone().multiplyScalar(w.dot(z))).normalize()}x.normalize();let y=z.clone().cross(x).normalize();x=y.clone().cross(z).normalize();return{o:h.point.clone(),x,y,z,type:e?'KENAR':'YÜZEY',edge:e}}
function showRef(h,r){if(r.edge){const len=span()*.30,s=h.point.clone().addScaledVector(r.x,-len*.5),ar=new THREE.ArrowHelper(r.x,s,len,BLUE,len*.12,len*.06);ar.line.material.depthTest=false;ar.cone.material.depthTest=false;add(ar,geom);point(h.point,BLUE)}else{faceHighlight(h,BLUE);point(h.point,BLUE);const len=span()*.18,ar=new THREE.ArrowHelper(r.z,h.point.clone(),len,BLUE,len*.12,len*.06);ar.line.material.depthTest=false;ar.cone.material.depthTest=false;add(ar,geom)}}
function label(p,text,c){const cv=document.createElement('canvas');cv.width=1024;cv.height=256;const x=cv.getContext('2d');x.clearRect(0,0,cv.width,cv.height);x.fillStyle='rgba(3,10,20,.92)';x.roundRect?x.roundRect(12,22,1000,212,34):x.fillRect(12,22,1000,212);x.fill();x.strokeStyle=c===GREEN?'#55d98a':'#42a5ff';x.lineWidth=12;x.stroke();x.fillStyle='#ffffff';x.font='bold 68px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,512,128);const tex=new THREE.CanvasTexture(cv),m=new THREE.SpriteMaterial({map:tex,depthTest:false,transparent:true}),s=new THREE.Sprite(m);s.position.copy(p);const z=span()*.22;s.scale.set(z*2.8,z*.7,1);return add(s,geom)}
function guide(t,cls){const e=document.getElementById('mgOnModelGuide2570')||document.getElementById('mgMeasureInfo2560');if(e){e.className='mg-guide '+(cls||'');e.innerHTML=t}}
function stopLegacy(){const sb=document.getElementById('mgSmartMeasure2550');if(sb&&sb.classList.contains('on'))sb.click();if(window.measureOn&&window.toggleMeasure)window.toggleMeasure()}
function startPoint(){stopLegacy();clearGeom();mode258='point';stage='P1';ref=null;p1=null;document.getElementById('mgRef2560')?.classList.remove('mgm-active');document.getElementById('mgPoint2560')?.classList.add('mgm-active');document.getElementById('mgThick2560')?.classList.remove('mgm-active');guide('🟢 <b>1. NOKTAYI / YÜZEYİ SEÇ</b> — seçimin parça üzerinde yeşil gösterilecek.','green')}
function startRef(){stopLegacy();clearGeom();mode258='ref';stage='REF';ref=null;p1=null;document.getElementById('mgPoint2560')?.classList.remove('mgm-active');document.getElementById('mgRef2560')?.classList.add('mgm-active');document.getElementById('mgThick2560')?.classList.remove('mgm-active');guide('🔷 <b>REFERANS KENAR / EKSEN VEYA YÜZEY SEÇ</b> — ilk seçim yalnızca referanstır.','blue')}
function finishPoint(h){faceHighlight(h,GREEN);point(h.point,GREEN);line(p1,h.point,GREEN);const d=p1.distanceTo(h.point),mid=p1.clone().add(h.point).multiplyScalar(.5);label(mid,'MESAFE  '+unit(d),GREEN);guide('🟢 <b>MESAFE: '+unit(d)+'</b> — ölçü parça üzerinde yeşil gösteriliyor. Yeni ölçüm için NOKTA–NOKTA’ya tekrar bas.','green');stage='DONE';if(navigator.vibrate)navigator.vibrate([20,35,20])}
function finishRef(h){faceHighlight(h,BLUE);point(h.point,BLUE);line(p1,h.point,BLUE);const d=h.point.clone().sub(p1),d3=d.length(),dx=d.dot(ref.x),dy=d.dot(ref.y),dz=d.dot(ref.z),along=Math.abs(dx),perp=Math.sqrt(Math.max(0,d3*d3-dx*dx)),mid=p1.clone().add(h.point).multiplyScalar(.5);label(mid,'3D '+unit(d3)+'  |  REF '+unit(along),BLUE);guide('🔷 <b>3D '+unit(d3)+'</b> • Referans boyunca <b>'+unit(along)+'</b> • Dik <b>'+unit(perp)+'</b><br>ΔX '+unit(dx)+' • ΔY '+unit(dy)+' • ΔZ '+unit(dz),'blue');stage='DONE';if(navigator.vibrate)navigator.vibrate([20,35,20])}
function canvasClick(ev){if((mode258!=='point'&&mode258!=='ref')||stage==='OFF'||stage==='DONE'||ev.clientY<58)return;const h=hitAt(ev);if(!h)return;ev.preventDefault();ev.stopImmediatePropagation();if(mode258==='point'){if(stage==='P1'){clearGeom();faceHighlight(h,GREEN);point(h.point,GREEN);p1=h.point.clone();stage='P2';guide('🟢 <b>1. NOKTA SEÇİLDİ</b> — şimdi 2. noktayı / yüzeyi seç.','green')}else if(stage==='P2')finishPoint(h);return}if(stage==='REF'){clearGeom();ref=makeRef(h);showRef(h,ref);stage='P1';guide('🔷 <b>REFERANS '+ref.type+' SEÇİLDİ</b> — mavi gösterim aktif. Şimdi 1. noktayı seç.','blue')}else if(stage==='P1'){faceHighlight(h,BLUE);point(h.point,BLUE);p1=h.point.clone();stage='P2';guide('🔷 <b>1. NOKTA SEÇİLDİ</b> — şimdi 2. noktayı seç.','blue')}else if(stage==='P2')finishRef(h)}
function install(){const rb=document.getElementById('mgRef2560'),pb=document.getElementById('mgPoint2560'),tb=document.getElementById('mgThick2560'),cb=document.getElementById('mgClear2560');if(!rb||!pb)return;rb.onclick=e=>{e.preventDefault();e.stopPropagation();startRef()};pb.onclick=e=>{e.preventDefault();e.stopPropagation();startPoint()};if(tb)tb.addEventListener('click',()=>{mode258='';stage='OFF';clearGeom()},true);if(cb)cb.addEventListener('click',()=>{mode258='';stage='OFF';clearGeom()},true);canvas.addEventListener('click',canvasClick,true);window.MG_CAD_V2580={version:'2.5.8',baseline:'2.5.5',pointMeasurementOnModel:true,greenDimensionLabel:true,referenceThreeClickFlow:true,referenceFirstSelectionOnly:true,referenceAxisVisible:true,referenceFaceVisible:true}}
ready(install)
})();'''
(AS/'cad-v2580.js').write_text(js,encoding='utf-8')
print('v2.5.8 on-model point dimensions + fixed 3-step reference measurement')
