from pathlib import Path
AS=Path('modelviewer/src/main/assets/cadviewer')
html=AS/'index.html'
h=html.read_text(encoding='utf-8')
if '/cad-v2610.js' not in h:
    h=h.replace('</body>','<script src="/cad-v2610.js"></script></body>',1)
html.write_text(h,encoding='utf-8')
js=r'''(function(){
'use strict';
function ready(f){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f,{once:true}):f()}
const PURPLE=0xb56cff,YELLOW=0xffc928,ORANGE=0xff9f43;
let probeOn=false,holeGeom=[],probeGeom=[];
const V=()=>new THREE.Vector3();
function span(){return Math.max(baseDims.x||1,baseDims.y||1,baseDims.z||1,1)}
function uf(){return typeof unitFactor==='function'?unitFactor():1}
function uname(){return document.getElementById('unit')?.value||'mm'}
function unit(v){const q=v*uf();return q.toFixed(Math.abs(q)>=100?2:3)+' '+uname()}
function dispose(o){if(!o)return;scene.remove(o);if(o.geometry)o.geometry.dispose();if(o.material){(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{if(m&&m.map)m.map.dispose();if(m&&m.dispose)m.dispose()})}}
function clearList(a){a.splice(0).forEach(dispose)}
function add(o,a){o.renderOrder=2400;scene.add(o);a.push(o);return o}
function line(a,b,c,arr){return add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color:c,depthTest:false})),arr)}
function point(p,c,arr,r=.010){const s=new THREE.Mesh(new THREE.SphereGeometry(span()*r,16,10),new THREE.MeshBasicMaterial({color:c,depthTest:false}));s.position.copy(p);return add(s,arr)}
function label(p,text,c,arr,scale=.16){const cv=document.createElement('canvas');cv.width=1400;cv.height=280;const x=cv.getContext('2d');x.fillStyle='rgba(3,10,20,.96)';x.fillRect(16,24,1368,232);x.strokeStyle=c===PURPLE?'#b56cff':c===YELLOW?'#ffc928':'#ff9f43';x.lineWidth=12;x.strokeRect(16,24,1368,232);x.fillStyle='#fff';x.font='bold 70px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,700,140);const tex=new THREE.CanvasTexture(cv),m=new THREE.SpriteMaterial({map:tex,depthTest:false,transparent:true}),s=new THREE.Sprite(m);s.position.copy(p);const z=span()*scale;s.scale.set(z*4.2,z*.84,1);return add(s,arr)}
function result(html,cls){const e=document.getElementById('mgLiveResult2600')||document.getElementById('mgLiveResult2610');if(e){e.className='mg-live-result '+(cls||'');e.innerHTML=html}}
function hitAt(ev){const r=canvas.getBoundingClientRect(),m=new THREE.Vector2(((ev.clientX-r.left)/r.width)*2-1,-((ev.clientY-r.top)/r.height)*2+1),rr=new THREE.Raycaster();rr.setFromCamera(m,camera);return rr.intersectObjects(group.children.filter(o=>o.visible),true)[0]||null}
function worldFaceNormal(h){return h.face?h.face.normal.clone().transformDirection(h.object.matrixWorld).normalize():new THREE.Vector3(0,0,1)}
function probeMeasure(h){clearList(probeGeom);if(!h)return;const p=h.point.clone(),n=worldFaceNormal(h),L=span()*.16;point(p,PURPLE,probeGeom,.014);const ar=new THREE.ArrowHelper(n,p,L,PURPLE,L*.13,L*.07);ar.line.material.depthTest=false;ar.cone.material.depthTest=false;add(ar,probeGeom);label(p.clone().addScaledVector(n,L*.55),'PROB  X '+unit(p.x)+'  Y '+unit(p.y)+'  Z '+unit(p.z),PURPLE,probeGeom,.145);result('🟣 <b>PROB</b><br>X: <b>'+unit(p.x)+'</b> • Y: <b>'+unit(p.y)+'</b> • Z: <b>'+unit(p.z)+'</b><br><small>Yüzey normali parça üzerinde mor okla gösteriliyor.</small>','probe')}
function qkey(p,tol){return Math.round(p.x/tol)+','+Math.round(p.y/tol)+','+Math.round(p.z/tol)}
function collectFeatureEdges(){const tol=span()*1e-5,vm=new Map(),em=new Map();function vadd(p){const k=qkey(p,tol);if(!vm.has(k))vm.set(k,p.clone());return k}function eadd(A,B,n){const ka=vadd(A),kb=vadd(B);if(ka===kb)return;const k=ka<kb?ka+'|'+kb:kb+'|'+ka;if(!em.has(k))em.set(k,{a:ka,b:kb,ns:[]});em.get(k).ns.push(n.clone())}
 group.children.filter(o=>o.visible&&o.isMesh).forEach(o=>{const g=o.geometry,p=g?.attributes?.position;if(!p)return;const idx=g.index,tri=idx?idx.count/3:p.count/3,A=V(),B=V(),C=V(),n=V();for(let i=0;i<tri;i++){const ia=idx?idx.getX(i*3):i*3,ib=idx?idx.getX(i*3+1):i*3+1,ic=idx?idx.getX(i*3+2):i*3+2;A.fromBufferAttribute(p,ia).applyMatrix4(o.matrixWorld);B.fromBufferAttribute(p,ib).applyMatrix4(o.matrixWorld);C.fromBufferAttribute(p,ic).applyMatrix4(o.matrixWorld);n.crossVectors(B.clone().sub(A),C.clone().sub(A)).normalize();eadd(A,B,n);eadd(B,C,n);eadd(C,A,n)}});
 const edges=[];em.forEach(e=>{let feature=e.ns.length===1;if(e.ns.length>=2){let md=1;for(let i=0;i<e.ns.length;i++)for(let j=i+1;j<e.ns.length;j++)md=Math.min(md,e.ns[i].dot(e.ns[j]));feature=md<Math.cos(28*Math.PI/180)}if(feature)edges.push(e)});return{edges,vm}}
function closedLoops(){const {edges,vm}=collectFeatureEdges(),adj=new Map();function aa(a,b){if(!adj.has(a))adj.set(a,[]);adj.get(a).push(b)}edges.forEach(e=>{aa(e.a,e.b);aa(e.b,e.a)});const seenE=new Set(),loops=[];function ek(a,b){return a<b?a+'|'+b:b+'|'+a}adj.forEach((ns,start)=>{if(ns.length!==2)return;for(const first of ns){if(seenE.has(ek(start,first)))continue;const ks=[start];let prev=null,cur=start,next=first,guard=0,ok=true;while(guard++<5000){seenE.add(ek(cur,next));prev=cur;cur=next;if(cur===start)break;ks.push(cur);const an=adj.get(cur)||[];if(an.length!==2){ok=false;break}next=an[0]===prev?an[1]:an[0]}if(ok&&cur===start&&ks.length>=8)loops.push(ks.map(k=>vm.get(k).clone()))}});return loops}
function fitCircle(loop){const c=V();loop.forEach(p=>c.add(p));c.multiplyScalar(1/loop.length);let n=V();for(let i=0;i<loop.length;i++){const a=loop[i].clone().sub(c),b=loop[(i+1)%loop.length].clone().sub(c);n.add(a.cross(b))}if(n.lengthSq()<1e-10)return null;n.normalize();let rs=[],maxPlane=0;loop.forEach(p=>{const d=p.clone().sub(c),pl=Math.abs(d.dot(n));maxPlane=Math.max(maxPlane,pl);d.addScaledVector(n,-d.dot(n));rs.push(d.length())});const r=rs.reduce((a,b)=>a+b,0)/rs.length;if(r<span()*1e-4)return null;const sd=Math.sqrt(rs.reduce((s,x)=>s+(x-r)*(x-r),0)/rs.length);if(sd/r>.035||maxPlane/r>.025)return null;return{c,n,r,pts:loop}}
function dedupe(cs){const out=[];cs.sort((a,b)=>b.r-a.r);for(const c of cs){let dup=false;for(const o of out){const dr=Math.abs(c.r-o.r)/Math.max(c.r,o.r),d=c.c.clone().sub(o.c),ax=Math.abs(d.dot(o.n)),lat=Math.sqrt(Math.max(0,d.lengthSq()-ax*ax)),nd=Math.abs(c.n.dot(o.n));if(dr<.035&&lat<Math.max(c.r,o.r)*.15&&nd>.94){dup=true;break}}if(!dup)out.push(c)}return out}
function ring(circle){const pts=circle.pts.concat([circle.pts[0]]);const g=new THREE.BufferGeometry().setFromPoints(pts),o=new THREE.Line(g,new THREE.LineBasicMaterial({color:YELLOW,depthTest:false}));add(o,holeGeom);const view=new THREE.Vector3();camera.getWorldDirection(view);const q=circle.c.clone().add(circle.n.clone().multiplyScalar(span()*.006));label(q,'Ø'+unit(circle.r*2),YELLOW,holeGeom,.125)}
function scanHoles(){clearList(holeGeom);result('🟨 <b>DELİK TANIMA:</b> Model taranıyor…','holes');setTimeout(()=>{let cs=closedLoops().map(fitCircle).filter(Boolean);cs=dedupe(cs).filter(c=>c.r<span()*.35);cs.forEach(ring);const panel=document.getElementById('mgHoleList2610');if(panel){panel.innerHTML=cs.length?cs.map((c,i)=>'<div class="mgHoleRow"><b>D'+(i+1)+'</b><span>Ø '+unit(c.r*2)+'</span><small>X '+unit(c.c.x)+' • Y '+unit(c.c.y)+' • Z '+unit(c.c.z)+'</small></div>').join(''):'<div class="small">Dairesel delik sınırı bulunamadı.</div>'}result(cs.length?'🟨 <b>'+cs.length+' DELİK TANINDI</b><br>'+cs.map((c,i)=>'D'+(i+1)+' Ø'+unit(c.r*2)).join(' • '):'🟨 Dairesel delik bulunamadı.','holes')},20)}
function txt(b){return (b.textContent||'').replace(/\s+/g,' ').trim().toLocaleUpperCase('tr-TR')}
function findAll(re){return [...document.querySelectorAll('#tools button')].filter(b=>re.test(txt(b)))}
function reorganize(){const tools=document.getElementById('tools'),hub=document.getElementById('mgMeasureHub2570')||document.getElementById('mgMeasureModes2560')?.parentElement;if(!tools||!hub)return;findAll(/^AKILLI ÖLÇ$/).forEach(b=>{b.style.display='none';const r=b.closest('.row');if(r)r.style.display='none'});[...tools.querySelectorAll('.head')].forEach(h=>{if((h.textContent||'').trim().toLocaleUpperCase('tr-TR')==='MÜHENDİSLİK ARAÇLARI')h.style.display='none'});
 let quick=document.getElementById('mgQuickMeasure2600');if(!quick){quick=document.createElement('div');quick.id='mgQuickMeasure2600';hub.insertBefore(quick,hub.firstChild)}let row=quick.querySelector('.mgQuickRow');if(!row){row=document.createElement('div');row.className='mgQuickRow';quick.appendChild(row)}
 const probe=findAll(/^PROB$/)[0],hole=findAll(/DELİKLER\s*\/\s*ÇAP|DELİK.*ÇAP/)[0];if(probe)row.appendChild(probe);if(hole)row.appendChild(hole);[probe,hole].filter(Boolean).forEach(b=>b.style.display='');
 let scan=document.getElementById('mgHoleScan2610');if(!scan){scan=document.createElement('div');scan.id='mgHoleScan2610';scan.innerHTML='<button id="mgHoleDetect2610">🟨 DELİK TANIMA / TÜM DELİKLERİ TARA</button><div id="mgHoleList2610"></div>';const core=document.getElementById('mgMeasureModes2560');core?.parentNode?.insertBefore(scan,core.nextSibling)}
 const pbtn=probe,hbtn=hole;if(pbtn)pbtn.onclick=e=>{e.preventDefault();e.stopPropagation();probeOn=!probeOn;pbtn.classList.toggle('on',probeOn);result(probeOn?'🟣 <b>PROB:</b> Parça üzerinde ölçmek istediğin yüzeye dokun.':'PROB kapalı.','probe')};if(hbtn)hbtn.onclick=e=>{e.preventDefault();e.stopPropagation();scanHoles()};document.getElementById('mgHoleDetect2610').onclick=e=>{e.preventDefault();scanHoles()};
 const clear=document.getElementById('mgClear2560');if(clear)clear.addEventListener('click',()=>{probeOn=false;probe?.classList.remove('on');clearList(probeGeom);clearList(holeGeom);const l=document.getElementById('mgHoleList2610');if(l)l.innerHTML=''},true)}
function install(){const s=document.createElement('style');s.textContent=`#mgQuickMeasure2600 .mgQuickRow{display:grid!important;grid-template-columns:1fr 1fr!important;gap:7px!important}#mgQuickMeasure2600 .mgQuickRow button{grid-column:auto!important;min-height:48px}.mg-live-result.probe{border-color:#b56cff;color:#ead7ff}.mg-live-result.holes{border-color:#ffc928;color:#fff1a8}#mgHoleScan2610{margin:8px 0;padding-top:7px;border-top:1px solid #245582}#mgHoleDetect2610{width:100%;border:2px solid #ffc928;color:#fff1a8;min-height:48px}#mgHoleList2610{max-height:180px;overflow:auto;margin-top:6px}.mgHoleRow{display:grid;grid-template-columns:38px 1fr;gap:2px 7px;padding:6px;border-bottom:1px solid #24445e}.mgHoleRow b{color:#ffc928}.mgHoleRow small{grid-column:1/-1;opacity:.78}`;document.head.appendChild(s);reorganize();canvas.addEventListener('pointerup',ev=>{if(!probeOn||ev.clientY<58)return;const h=hitAt(ev);if(!h)return;ev.preventDefault();ev.stopPropagation();probeMeasure(h)},true);window.MG_CAD_V2610={version:'2.6.1',baseline:'2.5.5',probeBesideHoleDiameter:true,probeResultInSharedPanel:true,probeOnModel:true,smartHoleRecognition:true,allHoleDiameters:true,holeLabelsOnModel:true,featureEdgeCircleRecognition:true}}
ready(install)
})();'''
(AS/'cad-v2610.js').write_text(js,encoding='utf-8')
print('v2.6.1 probe + smart hole recognition + on-model hole diameters')
