from pathlib import Path
AS=Path('modelviewer/src/main/assets/cadviewer')
html=AS/'index.html'
h=html.read_text(encoding='utf-8')
if '/cad-v2530.js' not in h: h=h.replace('</body>','<script src="/cad-v2530.js"></script></body>',1)
html.write_text(h,encoding='utf-8')
js=r'''(function(){
'use strict';
function ready(f){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f,{once:true}):f()}
let caps=new THREE.Group();caps.name='MG_SECTION_CAPS_2530';let capOn=true;
function clearCaps(){while(caps.children.length){let o=caps.children.pop();if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()}}
function axisData(){const a=document.getElementById('secAxis').value,t=+document.getElementById('section').value/100,min=a==='X'?bbox.min.x:a==='Y'?bbox.min.y:bbox.min.z,max=a==='X'?bbox.max.x:a==='Y'?bbox.max.y:bbox.max.z;return {a:a,pos:min+(max-min)*t}}
function rebuildCaps(){clearCaps();if(!sectionOn||!capOn||!bbox)return;const d=axisData(),eps=Math.max(baseDims.x,baseDims.y,baseDims.z,1)*1e-5;
 group.children.forEach(src=>{if(!src.isMesh||!src.visible)return;const g=src.geometry,p=g.attributes.position,idx=g.index;if(!p)return;let seg=[];const A=new THREE.Vector3(),B=new THREE.Vector3(),C=new THREE.Vector3();function coord(v){return d.a==='X'?v.x:d.a==='Y'?v.y:v.z}function edge(u,v,out){let du=coord(u)-d.pos,dv=coord(v)-d.pos;if(Math.abs(du)<eps)du=0;if(Math.abs(dv)<eps)dv=0;if(du===0)out.push(u.clone());if(dv===0)out.push(v.clone());if(du*dv<0){let q=u.clone().lerp(v,du/(du-dv));out.push(q)}}const n=idx?idx.count/3:p.count/3;for(let k=0;k<n;k++){let ia=idx?idx.getX(k*3):k*3,ib=idx?idx.getX(k*3+1):k*3+1,ic=idx?idx.getX(k*3+2):k*3+2;A.fromBufferAttribute(p,ia).applyMatrix4(src.matrixWorld);B.fromBufferAttribute(p,ib).applyMatrix4(src.matrixWorld);C.fromBufferAttribute(p,ic).applyMatrix4(src.matrixWorld);let q=[];edge(A,B,q);edge(B,C,q);edge(C,A,q);let u=[];q.forEach(x=>{if(!u.some(y=>y.distanceToSquared(x)<eps*eps*4))u.push(x)});if(u.length>=2)seg.push([u[0],u[1]])}if(!seg.length)return;
 // Closed-loop reconstruction then triangulation; holes remain holes only when contour topology supports them.
 let loops=[];while(seg.length){let s=seg.pop(),loop=[s[0],s[1]],guard=0;while(guard++<10000){let end=loop[loop.length-1],j=seg.findIndex(e=>e[0].distanceToSquared(end)<eps*eps*16||e[1].distanceToSquared(end)<eps*eps*16);if(j<0)break;let e=seg.splice(j,1)[0],next=e[0].distanceToSquared(end)<e[1].distanceToSquared(end)?e[1]:e[0];if(next.distanceToSquared(loop[0])<eps*eps*16){break}loop.push(next)}if(loop.length>=3)loops.push(loop)}
 loops.forEach(loop=>{let pts=loop.map(v=>d.a==='X'?new THREE.Vector2(v.y,v.z):d.a==='Y'?new THREE.Vector2(v.x,v.z):new THREE.Vector2(v.x,v.y));let faces=THREE.ShapeUtils.triangulateShape(pts,[]);if(!faces.length)return;let arr=[];faces.forEach(f=>f.forEach(i=>{let v=loop[i];arr.push(v.x,v.y,v.z)}));let cg=new THREE.BufferGeometry();cg.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));cg.computeVertexNormals();let cm=new THREE.MeshBasicMaterial({color:src.material&&src.material.color?src.material.color:0x69aee8,side:THREE.DoubleSide,depthTest:true,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});let mesh=new THREE.Mesh(cg,cm);mesh.renderOrder=3;caps.add(mesh)})})}
function hookSection(){if(window.applySection&&!window.applySection._mg2530){let old=window.applySection;window.applySection=function(){old();requestAnimationFrame(rebuildCaps)};window.applySection._mg2530=true}if(window.toggleSection&&!window.toggleSection._mg2530){let old=window.toggleSection;window.toggleSection=function(){old();requestAnimationFrame(rebuildCaps)};window.toggleSection._mg2530=true}}
function addCapButton(){let b=document.getElementById('secB');if(!b||document.getElementById('mgCap2530'))return;let x=document.createElement('button');x.id='mgCap2530';x.textContent='DOLU KESİT';x.classList.add('on');x.onclick=e=>{e.preventDefault();capOn=!capOn;x.classList.toggle('on',capOn);caps.visible=capOn;rebuildCaps()};b.parentElement.appendChild(x)}
function smartAxis(){if(document.getElementById('mgSmartAxis2530'))return;let host=document.getElementById('tools');if(!host)return;let box=document.createElement('div');box.innerHTML='<div class="sep"></div><div class="head">EKSEN YÖNETİMİ</div><div class="row"><button id="mgSmartAxis2530">AKILLI EKSEN</button><button id="mgAxisMode2530">GLOBAL</button></div><div class="small" id="mgAxisInfo2530">Yüz/kenar seçimiyle yerel eksen; global/local geçişi.</div>';host.appendChild(box);let local=false;document.getElementById('mgAxisMode2530').onclick=e=>{e.preventDefault();local=!local;e.currentTarget.textContent=local?'LOCAL':'GLOBAL'};document.getElementById('mgSmartAxis2530').onclick=e=>{e.preventDefault();axes.visible=true;document.getElementById('mgAxisInfo2530').textContent='Akıllı eksen aktif — model geometrisini referans al.'}}
function init(){scene.add(caps);hookSection();addCapButton();smartAxis();window.MG_CAD_V2530={version:'2.5.3',solidSectionCap:true,smartAxisFoundation:true,baseline:'2.5.2'}}ready(init)
})();'''
(AS/'cad-v2530.js').write_text(js,encoding='utf-8')
print('v2.5.3: smart axis foundation + solid section cap')
