package com.muhammetgecgil.nesnesayarai;

import android.Manifest;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.camera.core.*;
import androidx.camera.lifecycle.ProcessCameraProvider;
import androidx.camera.view.PreviewView;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import com.google.android.gms.tasks.Tasks;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.objects.*;
import com.google.mlkit.vision.objects.defaults.ObjectDetectorOptions;
import java.nio.ByteBuffer;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;

public class MainActivityV8 extends AppCompatActivity {
 static final int REQ=10; PreviewView preview; Overlay overlay; TextView result,status; Button mode,pen;
 volatile Bitmap latest; volatile List<RectF> boxes=new ArrayList<>(); boolean same=false; RectF sample;
 final ExecutorService cam=Executors.newSingleThreadExecutor(), work=Executors.newSingleThreadExecutor(); final AtomicBoolean busy=new AtomicBoolean(false);
 final ObjectDetector detector=ObjectDetection.getClient(new ObjectDetectorOptions.Builder().setDetectorMode(ObjectDetectorOptions.SINGLE_IMAGE_MODE).enableMultipleObjects().build());
 @Override protected void onCreate(Bundle b){super.onCreate(b);ui();if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera();else ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.CAMERA},REQ);}
 void ui(){FrameLayout root=new FrameLayout(this);preview=new PreviewView(this);preview.setScaleType(PreviewView.ScaleType.FILL_CENTER);root.addView(preview,new FrameLayout.LayoutParams(-1,-1));overlay=new Overlay();root.addView(overlay,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(14),0,dp(14),0);top.setBackgroundColor(Color.argb(210,10,18,22));TextView title=new TextView(this);title.setText("Nesne Sayar AI");title.setTextColor(Color.WHITE);title.setTextSize(22);top.addView(title,new LinearLayout.LayoutParams(0,dp(58),1));status=new TextView(this);status.setText("V110 Fiziksel Görüş");status.setTextColor(Color.LTGRAY);status.setTextSize(12);status.setGravity(Gravity.CENTER);top.addView(status,new LinearLayout.LayoutParams(dp(190),dp(58)));result=new TextView(this);result.setText("0");result.setTextColor(Color.rgb(45,245,130));result.setTextSize(34);result.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);top.addView(result,new LinearLayout.LayoutParams(dp(58),dp(58)));FrameLayout.LayoutParams tlp=new FrameLayout.LayoutParams(-1,dp(58),Gravity.TOP);root.addView(top,tlp);
  pen=btn("✎");pen.setTextSize(24);FrameLayout.LayoutParams plp=new FrameLayout.LayoutParams(dp(58),dp(58),Gravity.TOP|Gravity.START);plp.leftMargin=dp(8);plp.topMargin=dp(68);root.addView(pen,plp);
  LinearLayout bot=new LinearLayout(this);Button src=btn("CANLI");mode=btn("FARKLI");Button count=btn("SAY"),clear=btn("SİL");count.setBackgroundColor(Color.rgb(0,145,78));for(Button x:new Button[]{src,mode,count,clear})bot.addView(x,new LinearLayout.LayoutParams(0,dp(60),1));FrameLayout.LayoutParams blp=new FrameLayout.LayoutParams(-1,dp(60),Gravity.BOTTOM);root.addView(bot,blp);
  ViewCompat.setOnApplyWindowInsetsListener(root,(v,i)->{Insets x=i.getInsets(WindowInsetsCompat.Type.systemBars());tlp.topMargin=x.top;plp.topMargin=x.top+dp(66);blp.bottomMargin=x.bottom+dp(10);top.setLayoutParams(tlp);pen.setLayoutParams(plp);bot.setLayoutParams(blp);return i;});setContentView(root);
  pen.setOnClickListener(v->{overlay.drawMode=!overlay.drawMode;pen.setBackgroundColor(overlay.drawMode?Color.rgb(0,145,78):Color.rgb(19,58,68));status.setText(overlay.drawMode?"Bölgeyi çiz":"ROI kilitli");});
  mode.setOnClickListener(v->{same=!same;mode.setText(same?"AYNI":"FARKLI");sample=null;overlay.sample=null;overlay.invalidate();refresh();});
  count.setOnClickListener(v->{Bitmap f=latest;if(f!=null)analyze(f.copy(Bitmap.Config.ARGB_8888,false));});clear.setOnClickListener(v->{boxes=new ArrayList<>();sample=null;overlay.boxes=Collections.emptyList();overlay.sample=null;overlay.clearRoi();overlay.invalidate();result.setText("0");status.setText("Temizlendi");}); }
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setBackgroundColor(Color.rgb(19,58,68));return b;}
 void camera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider p=f.get();Preview pr=new Preview.Builder().build();pr.setSurfaceProvider(preview.getSurfaceProvider());ImageAnalysis a=new ImageAnalysis.Builder().setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_RGBA_8888).build();a.setAnalyzer(cam,img->{try{Bitmap b=rgba(img);latest=rotate(b,img.getImageInfo().getRotationDegrees());}catch(Throwable ignored){}finally{img.close();}});p.unbindAll();p.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,pr,a);}catch(Throwable e){}},ContextCompat.getMainExecutor(this));}
 Bitmap rgba(ImageProxy im){ImageProxy.PlaneProxy p=im.getPlanes()[0];ByteBuffer bf=p.getBuffer();bf.rewind();int ps=Math.max(1,p.getPixelStride()),pw=p.getRowStride()/ps;Bitmap pad=Bitmap.createBitmap(pw,im.getHeight(),Bitmap.Config.ARGB_8888);pad.copyPixelsFromBuffer(bf);return pw==im.getWidth()?pad:Bitmap.createBitmap(pad,0,0,im.getWidth(),im.getHeight());}
 Bitmap rotate(Bitmap s,int d){if(d==0)return s;Matrix m=new Matrix();m.postRotate(d);return Bitmap.createBitmap(s,0,0,s.getWidth(),s.getHeight(),m,true);}
 void analyze(Bitmap src){if(!busy.compareAndSet(false,true))return;status.setText("Maske → kontur → nesne fill...");List<PointF> rv=overlay.copyRoi();int vw=overlay.getWidth(),vh=overlay.getHeight();work.execute(()->{try{List<RectF> raw=new ArrayList<>();detect(src,0,0,src.getWidth(),src.getHeight(),raw);int g=4,cw=src.getWidth()/g,ch=src.getHeight()/g,pad=Math.min(cw,ch)/7;for(int y=0;y<g;y++)for(int x=0;x<g;x++){int l=Math.max(0,x*cw-pad),t=Math.max(0,y*ch-pad),r=Math.min(src.getWidth(),(x+1)*cw+pad),b=Math.min(src.getHeight(),(y+1)*ch+pad);detect(src,l,t,r,b,raw);}List<RectF> out=hybrid(src,raw,rv,vw,vh);boxes=out;runOnUiThread(()->{overlay.boxes=new ArrayList<>(out);overlay.invalidate();refresh();status.setText("Fiziksel nesne: "+out.size()+" / AI aday: "+raw.size());});}catch(Throwable e){runOnUiThread(()->status.setText("Algılama hatası"));}finally{busy.set(false);}});}
 void detect(Bitmap s,int l,int t,int r,int b,List<RectF> out)throws Exception{if(r-l<32||b-t<32)return;Bitmap c=Bitmap.createBitmap(s,l,t,r-l,b-t);for(DetectedObject o:Tasks.await(detector.process(InputImage.fromBitmap(c,0)))){android.graphics.Rect q=o.getBoundingBox();RectF z=new RectF(q.left+l,q.top+t,q.right+l,q.bottom+t);if(z.width()>10&&z.height()>10)out.add(z);}}
 List<RectF> hybrid(Bitmap src,List<RectF> raw,List<PointF> rv,int vw,int vh){int W=src.getWidth(),H=src.getHeight();float sc=Math.min(1f,520f/Math.max(W,H));int w=Math.max(100,Math.round(W*sc)),h=Math.max(100,Math.round(H*sc));Bitmap sm=Bitmap.createScaledBitmap(src,w,h,true);int[] p=new int[w*h];sm.getPixels(p,0,w,0,0,w,h);boolean[] roi=new boolean[p.length];int rc=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++){boolean ok=rv.isEmpty()||pip(x/sc,y/sc,W,H,rv,vw,vh);roi[y*w+x]=ok;if(ok)rc++;}int[] bg=background(p,roi,w,h);boolean[] fg=new boolean[p.length];for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int i=y*w+x;if(!roi[i])continue;int c=p[i],r=Color.red(c),g=Color.green(c),b=Color.blue(c);double d=Math.sqrt(sq(r-bg[0])+sq(g-bg[1])+sq(b-bg[2]));int edge=diff(p[i-1],p[i+1])+diff(p[i-w],p[i+w]);fg[i]=d>30||edge>100;}
  fg=erode(dilate(fg,roi,w,h),roi,w,h);List<Comp> cs=components(fg,w,h);List<RectF> phys=new ArrayList<>();for(Comp c:cs){if(c.n<Math.max(18,rc/5000))continue;RectF r=new RectF(c.l/sc,c.t/sc,(c.r+1)/sc,(c.b+1)/sc);float af=area(r)/(W*(float)H);if(af>.82f||r.width()<8||r.height()<8)continue;if(!rv.isEmpty()&&!inside(r,W,H,rv,vw,vh))continue;phys.add(r);}
  phys=mergeFragments(phys,W,H);List<RectF> raw2=cleanRaw(raw,W,H,rv,vw,vh);for(RectF a:raw2){int contained=0;for(RectF q:phys)if(contain(q,a)>.72f&&area(q)<area(a)*.72f)contained++;if(contained>=2)continue;boolean covered=false;for(RectF q:phys)if(iou(a,q)>.22f||contain(a,q)>.82f||contain(q,a)>.82f){covered=true;break;}if(!covered)phys.add(a);}List<RectF> d=dedup(phys);List<RectF> out=new ArrayList<>();for(int i=0;i<d.size();i++){RectF a=d.get(i);int children=0;for(int j=0;j<d.size();j++)if(i!=j){RectF b=d.get(j);float rr=area(b)/area(a);if(rr>.03f&&rr<.60f&&contain(b,a)>.88f)children++;}if(children<2)out.add(a);}out.sort((a,b)->{int q=Float.compare(a.centerY(),b.centerY());return q!=0?q:Float.compare(a.centerX(),b.centerX());});return out;}
 List<RectF> mergeFragments(List<RectF> in,int W,int H){List<RectF> a=new ArrayList<>(in);boolean ch=true;for(int pass=0;pass<2&&ch;pass++){ch=false;outer:for(int i=0;i<a.size();i++)for(int j=i+1;j<a.size();j++){RectF x=a.get(i),y=a.get(j);float gx=Math.max(0,Math.max(x.left,y.left)-Math.min(x.right,y.right)),gy=Math.max(0,Math.max(x.top,y.top)-Math.min(x.bottom,y.bottom));float xo=Math.max(0,Math.min(x.right,y.right)-Math.max(x.left,y.left))/Math.max(1,Math.min(x.width(),y.width()));float yo=Math.max(0,Math.min(x.bottom,y.bottom)-Math.max(x.top,y.top))/Math.max(1,Math.min(x.height(),y.height()));boolean join=(xo>.70f&&gy<Math.min(x.height(),y.height())*.06f)||(yo>.70f&&gx<Math.min(x.width(),y.width())*.06f);if(join){a.set(i,new RectF(Math.min(x.left,y.left),Math.min(x.top,y.top),Math.max(x.right,y.right),Math.max(x.bottom,y.bottom)));a.remove(j);ch=true;break outer;}}}return a;}
 List<RectF> cleanRaw(List<RectF> raw,int W,int H,List<PointF> rv,int vw,int vh){List<RectF> a=new ArrayList<>();for(RectF r:raw){float af=area(r)/(W*(float)H);if(af<.00012f||af>.65f)continue;if(!rv.isEmpty()&&!inside(r,W,H,rv,vw,vh))continue;a.add(new RectF(r));}return dedup(a);}
 List<RectF> dedup(List<RectF> a){a.sort((x,y)->Float.compare(area(y),area(x)));List<RectF> k=new ArrayList<>();for(RectF c:a){boolean dup=false;for(RectF q:k){float rr=Math.min(area(c),area(q))/Math.max(area(c),area(q));if(iou(c,q)>.58f||(contain(c,q)>.94f&&rr>.70f)){dup=true;break;}}if(!dup)k.add(c);}return k;}
 int[] background(int[] p,boolean[] roi,int w,int h){ArrayList<Integer> rs=new ArrayList<>(),gs=new ArrayList<>(),bs=new ArrayList<>();for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int i=y*w+x;if(!roi[i])continue;boolean bd=!roi[i-1]||!roi[i+1]||!roi[i-w]||!roi[i+w];if(bd){rs.add(Color.red(p[i]));gs.add(Color.green(p[i]));bs.add(Color.blue(p[i]));}}if(rs.size()<20)for(int i=0;i<p.length;i+=Math.max(1,p.length/700))if(roi[i]){rs.add(Color.red(p[i]));gs.add(Color.green(p[i]));bs.add(Color.blue(p[i]));}Collections.sort(rs);Collections.sort(gs);Collections.sort(bs);int n=Math.max(1,rs.size());return new int[]{rs.get(n/2),gs.get(n/2),bs.get(n/2)};}
 boolean[] dilate(boolean[] a,boolean[] roi,int w,int h){boolean[] o=new boolean[a.length];for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int i=y*w+x;if(!roi[i])continue;for(int dy=-1;dy<=1&&!o[i];dy++)for(int dx=-1;dx<=1;dx++)if(a[i+dy*w+dx]){o[i]=true;break;}}return o;}
 boolean[] erode(boolean[] a,boolean[] roi,int w,int h){boolean[] o=new boolean[a.length];for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int i=y*w+x;if(!roi[i]||!a[i])continue;o[i]=true;for(int dy=-1;dy<=1&&o[i];dy++)for(int dx=-1;dx<=1;dx++)if(!roi[i+dy*w+dx]||!a[i+dy*w+dx]){o[i]=false;break;}}return o;}
 List<Comp> components(boolean[] f,int w,int h){int[] lab=new int[f.length],q=new int[f.length];List<Comp> out=new ArrayList<>();int id=0;for(int s=0;s<f.length;s++){if(!f[s]||lab[s]!=0)continue;id++;int qs=0,qe=0;q[qe++]=s;lab[s]=id;Comp c=new Comp();c.l=c.r=s%w;c.t=c.b=s/w;while(qs<qe){int z=q[qs++],x=z%w,y=z/w;c.n++;c.l=Math.min(c.l,x);c.r=Math.max(c.r,x);c.t=Math.min(c.t,y);c.b=Math.max(c.b,y);for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){if(dx==0&&dy==0)continue;int nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=w||ny>=h)continue;int ni=ny*w+nx;if(f[ni]&&lab[ni]==0){lab[ni]=id;q[qe++]=ni;}}}out.add(c);}return out;}
 static class Comp{int l,r,t,b,n;}
 boolean inside(RectF r,int W,int H,List<PointF> poly,int vw,int vh){PointF c=mapToView(r.centerX(),r.centerY(),W,H,vw,vh);return point(c.x,c.y,poly);} boolean pip(float x,float y,int W,int H,List<PointF> poly,int vw,int vh){PointF p=mapToView(x,y,W,H,vw,vh);return point(p.x,p.y,poly);} PointF mapToView(float x,float y,int W,int H,int vw,int vh){float sc=Math.max(vw/(float)W,vh/(float)H),dx=(vw-W*sc)/2f,dy=(vh-H*sc)/2f;return new PointF(x*sc+dx,y*sc+dy);} boolean point(float x,float y,List<PointF> p){boolean c=false;for(int i=0,j=p.size()-1;i<p.size();j=i++){PointF a=p.get(i),b=p.get(j);if(((a.y>y)!=(b.y>y))&&(x<(b.x-a.x)*(y-a.y)/(b.y-a.y+.00001f)+a.x))c=!c;}return c;}
 float area(RectF r){return Math.max(1,r.width()*r.height());} float inter(RectF a,RectF b){float l=Math.max(a.left,b.left),t=Math.max(a.top,b.top),r=Math.min(a.right,b.right),bb=Math.min(a.bottom,b.bottom);return r>l&&bb>t?(r-l)*(bb-t):0;} float iou(RectF a,RectF b){float i=inter(a,b);return i/(area(a)+area(b)-i);} float contain(RectF a,RectF b){return inter(a,b)/area(a);} double sq(double x){return x*x;} int diff(int a,int b){return Math.abs(Color.red(a)-Color.red(b))+Math.abs(Color.green(a)-Color.green(b))+Math.abs(Color.blue(a)-Color.blue(b));}
 void refresh(){if(!same||sample==null){result.setText(String.valueOf(boxes.size()));return;}int n=0;float sa=area(sample),asp=aspect(sample);for(RectF r:boxes){float sz=Math.min(area(r),sa)/Math.max(area(r),sa);if(sz>.42f&&Math.abs(aspect(r)-asp)<.55f)n++;}result.setText(String.valueOf(n));status.setText("AYNI: "+n);} float aspect(RectF r){float x=r.width()/Math.max(1,r.height());return Math.max(x,1/Math.max(.001f,x));} int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 @Override public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)camera();} @Override protected void onDestroy(){super.onDestroy();detector.close();cam.shutdownNow();work.shutdownNow();}
 class Overlay extends View{Paint box=new Paint(1),num=new Paint(1),txt=new Paint(1),rp=new Paint(1),sp=new Paint(1);List<RectF> boxes=new ArrayList<>();RectF sample;boolean drawMode=false;List<PointF> roi=new ArrayList<>();Path path=new Path();Overlay(){super(MainActivityV8.this);box.setColor(Color.rgb(45,245,130));box.setStyle(Paint.Style.STROKE);box.setStrokeWidth(dp(3));num.setColor(Color.rgb(0,165,88));txt.setColor(Color.WHITE);txt.setTextAlign(Paint.Align.CENTER);txt.setTextSize(dp(16));rp.setColor(Color.CYAN);rp.setStyle(Paint.Style.STROKE);rp.setStrokeWidth(dp(4));sp.setColor(Color.YELLOW);sp.setStyle(Paint.Style.STROKE);sp.setStrokeWidth(dp(4));setOnTouchListener((v,e)->{if(drawMode){if(e.getAction()==MotionEvent.ACTION_DOWN){roi.clear();path.reset();roi.add(new PointF(e.getX(),e.getY()));path.moveTo(e.getX(),e.getY());invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){roi.add(new PointF(e.getX(),e.getY()));path.lineTo(e.getX(),e.getY());invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP){roi.add(new PointF(e.getX(),e.getY()));path.close();drawMode=false;status.setText("ROI kilitli");invalidate();return true;}}else if(same&&e.getAction()==MotionEvent.ACTION_UP){for(RectF r:boxes)if(map(r).contains(e.getX(),e.getY())){MainActivityV8.this.sample=new RectF(r);sample=new RectF(r);refresh();invalidate();break;}}return true;});}
  List<PointF> copyRoi(){List<PointF> x=new ArrayList<>();for(PointF p:roi)x.add(new PointF(p.x,p.y));return x;} void clearRoi(){roi.clear();path.reset();drawMode=false;} @Override protected void onDraw(Canvas c){super.onDraw(c);if(!roi.isEmpty())c.drawPath(path,rp);for(int i=0;i<boxes.size();i++){RectF r=map(boxes.get(i));c.drawRoundRect(r,dp(7),dp(7),box);float cx=r.centerX(),cy=Math.max(dp(82),r.top+dp(3));c.drawCircle(cx,cy,dp(16),num);c.drawText(""+(i+1),cx,cy+dp(6),txt);}if(sample!=null)c.drawRoundRect(map(sample),dp(9),dp(9),sp);} RectF map(RectF s){Bitmap f=latest;if(f==null)return new RectF(s);float vw=getWidth(),vh=getHeight(),sw=f.getWidth(),sh=f.getHeight(),sc=Math.max(vw/sw,vh/sh),dx=(vw-sw*sc)/2f,dy=(vh-sh*sc)/2f;return new RectF(s.left*sc+dx,s.top*sc+dy,s.right*sc+dx,s.bottom*sc+dy);}}
}
