package com.muhammetgecgil.pcbzekapro;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.Bundle;
import android.util.Size;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.ScaleGestureDetector;
import android.view.View;
import android.widget.*;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.camera.core.*;
import androidx.camera.lifecycle.ProcessCameraProvider;
import androidx.camera.view.PreviewView;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.Text;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.io.File;
import java.io.FileOutputStream;

public class MainActivity extends AppCompatActivity {
    private enum Mode { OCR, BOARD, BANDS }
    private PreviewView preview; private ComponentOverlayView overlay; private TextView status,result,zoom,summary;
    private Camera camera; private ExecutorService executor; private ScaleGestureDetector scaler;
    private final TextRecognizer recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);
    private final AtomicBoolean requested=new AtomicBoolean(false),busy=new AtomicBoolean(false);
    private final List<ComponentDecoder.Item> bom=new ArrayList<>();
    private Mode mode=Mode.BOARD; private boolean torch; private String lastCode=""; private int scanNo=1;
    private int framesRemaining=0,frameWidth=1080,frameHeight=1920;
    private int panoramaCell=0; private boolean probeMode=false;
    private final StringBuilder multiText=new StringBuilder();
    private final ActivityResultLauncher<String> permission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),ok->{if(ok)startCamera();else status.setText("Kamera izni gerekli • Ayarlar > Uygulamalar > PCB Zekâ Pro > İzinler");});

    @Override protected void onCreate(Bundle b){super.onCreate(b);executor=Executors.newSingleThreadExecutor();buildUi();if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)startCamera();else permission.launch(Manifest.permission.CAMERA);}
    private void buildUi(){
        FrameLayout root=new FrameLayout(this);root.setBackgroundColor(0xFF071017);
        preview=new PreviewView(this);preview.setImplementationMode(PreviewView.ImplementationMode.PERFORMANCE);preview.setScaleType(PreviewView.ScaleType.FILL_CENTER);root.addView(preview,new FrameLayout.LayoutParams(-1,-1));overlay=new ComponentOverlayView(this);root.addView(overlay,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(dp(14),dp(10),dp(14),dp(8));top.setBackgroundColor(0xD9071017);
        top.addView(label("PCB ZEKÂ PRO v4 • PROFESYONEL SERVİS",17,Color.WHITE));status=label("Kamera hazırlanıyor…",12,0xFF65FFF5);top.addView(status);summary=label("BOM: 0 • SÜPER OCR hazır • R/C/L/D/Q/U",12,0xFFFFD166);top.addView(summary);root.addView(top,new FrameLayout.LayoutParams(-1,-2,Gravity.TOP));
        LinearLayout bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.VERTICAL);bottom.setPadding(dp(10),dp(8),dp(10),dp(18));bottom.setBackgroundColor(0xEB071017);
        zoom=label("Zoom 1.0× • dokunarak netleştir",12,Color.WHITE);bottom.addView(zoom);SeekBar zb=new SeekBar(this);zb.setMax(100);bottom.addView(zb,new LinearLayout.LayoutParams(-1,dp(34)));
        HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout buttons=new LinearLayout(this);
        Button board=button("8 KARE KART TARA"),pano=button("3×3 PANORAMA"),bands=button("DİRENÇ RENK"),ocr=button("SÜPER OCR"),flash=button("FLAŞ"),bomBtn=button("BOM"),areas=button("DEVRE BÖLGELERİ"),netlist=button("YOL/NETLİST"),data=button("IC DOĞRULA"),fault=button("ARIZA AĞACI"),meter=button("ÖLÇÜM KAYDI"),probe=button("AR PROB"),reference=button("REFERANS KART"),compare=button("GÖRSEL FARK"),teach=button("ÖĞRET"),hardware=button("USB/TERMAL"),archive=button("SERVİS ARŞİVİ"),pdf=button("PDF RAPOR"),share=button("CSV PAYLAŞ"),clear=button("TEMİZLE");
        for(Button x:new Button[]{board,pano,bands,ocr,flash,bomBtn,areas,netlist,data,fault,meter,probe,reference,compare,teach,hardware,archive,pdf,share,clear})buttons.addView(x,new LinearLayout.LayoutParams(dp(140),dp(48)));hs.addView(buttons);bottom.addView(hs);
        result=label("Kartı sabitleyin. Tüm kart için KARTI TARA; direnç için elemanı yatay ortalayıp DİRENÇ RENK seçin.",13,Color.WHITE);result.setMaxLines(7);result.setPadding(0,dp(6),0,0);bottom.addView(result);
        FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);bp.setMargins(dp(6),0,dp(6),dp(6));root.addView(bottom,bp);setContentView(root);
        board.setOnClickListener(v->requestMulti(Mode.BOARD,"8 kareli kart OCR + BOM"));pano.setOnClickListener(v->panoramaStep());bands.setOnClickListener(v->request(Mode.BANDS,"Renk/ışık kalibrasyonu ve bant analizi"));ocr.setOnClickListener(v->requestMulti(Mode.OCR,"8 kareli süper OCR"));
        flash.setOnClickListener(v->{if(camera!=null&&camera.getCameraInfo().hasFlashUnit()){torch=!torch;camera.getCameraControl().enableTorch(torch);flash.setText(torch?"FLAŞ AÇIK":"FLAŞ");}});
        bomBtn.setOnClickListener(v->showBom());areas.setOnClickListener(v->dialog("DEVRE FONKSİYON BÖLGELERİ",ServiceEngine.functionalAreas(bom)));netlist.setOnClickListener(v->dialog("PCB YOL / NETLİST",ServiceEngine.provisionalNetlist(bom)));data.setOnClickListener(v->datasheet());fault.setOnClickListener(v->chooseFault());meter.setOnClickListener(v->measurementLog());probe.setOnClickListener(v->{probeMode=!probeMode;overlay.showProbes(probeMode);Toast.makeText(this,probeMode?"AR prob işaretleri açık":"AR prob işaretleri kapalı",Toast.LENGTH_SHORT).show();});reference.setOnClickListener(v->saveReference());compare.setOnClickListener(v->compareReference());teach.setOnClickListener(v->teachComponent());hardware.setOnClickListener(v->dialog("USB MİKROSKOP / TERMAL / ÖLÇÜM CİHAZI",ServiceEngine.usbStatus(this)+"\n\nGörünür kamera gerçek sıcaklık ölçmez. Termal değer yalnız desteklenen harici cihazdan alınır."));archive.setOnClickListener(v->serviceArchive());pdf.setOnClickListener(v->createPdf());share.setOnClickListener(v->shareCsv());clear.setOnClickListener(v->{bom.clear();scanNo=1;lastCode="";multiText.setLength(0);panoramaCell=0;overlay.clear();refresh();result.setText("Sonuçlar temizlendi.");});
        zb.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean from){if(from)setZoom(p/100f);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});
        scaler=new ScaleGestureDetector(this,new ScaleGestureDetector.SimpleOnScaleGestureListener(){@Override public boolean onScale(ScaleGestureDetector d){if(camera==null)return false;float z=camera.getCameraInfo().getZoomState().getValue().getZoomRatio();camera.getCameraControl().setZoomRatio(z*d.getScaleFactor());updateZoom();return true;}});preview.setOnTouchListener(this::touch);
    }
    private void request(Mode m,String s){mode=m;requested.set(true);status.setText(s+" • net kare bekleniyor…");}
    private void requestMulti(Mode m,String s){mode=m;framesRemaining=8;multiText.setLength(0);requested.set(true);status.setText(s+" • 1/8");}
    private void panoramaStep(){if(panoramaCell>=9){panoramaCell=0;dialog("PANORAMA TAMAMLANDI","Dokuz bölge tarandı. BOM aynı referans/kodu ikinci kez eklemedi. Kartın ön ve arka yüzünü ayrı proje olarak kaydedin.");return;}String[] pos={"SOL ÜST","ORTA ÜST","SAĞ ÜST","SOL ORTA","MERKEZ","SAĞ ORTA","SOL ALT","ORTA ALT","SAĞ ALT"};String p=pos[panoramaCell++];requestMulti(Mode.BOARD,"Panorama "+panoramaCell+"/9 • "+p);result.setText("Kartın "+p+" bölgesini kadraja alın ve telefonu sabit tutun.");}
    private boolean touch(View v,MotionEvent e){scaler.onTouchEvent(e);if(e.getAction()==MotionEvent.ACTION_UP&&camera!=null&&!scaler.isInProgress()){MeteringPoint p=preview.getMeteringPointFactory().createPoint(e.getX(),e.getY());camera.getCameraControl().startFocusAndMetering(new FocusMeteringAction.Builder(p,FocusMeteringAction.FLAG_AF|FocusMeteringAction.FLAG_AE).setAutoCancelDuration(5,TimeUnit.SECONDS).build());status.setText("AF/AE hedefe kilitlendi");}return true;}
    private void startCamera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider provider=f.get();Preview pv=new Preview.Builder().setTargetResolution(new Size(1920,1080)).build();pv.setSurfaceProvider(preview.getSurfaceProvider());ImageAnalysis ia=new ImageAnalysis.Builder().setTargetResolution(new Size(1920,1080)).setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();ia.setAnalyzer(executor,this::analyze);provider.unbindAll();camera=provider.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,pv,ia);camera.getCameraControl().setLinearZoom(0);runOnUiThread(()->status.setText("Kamera açık • 1080p analiz • dokunarak netleştir"));}catch(Exception e){runOnUiThread(()->status.setText("Kamera açılamadı: "+e.getMessage()));}},ContextCompat.getMainExecutor(this));}
    private void analyze(@NonNull ImageProxy im){
        if(!requested.compareAndSet(true,false)||!busy.compareAndSet(false,true)){im.close();return;}frameWidth=im.getWidth();frameHeight=im.getHeight();
        if(mode==Mode.BANDS){ResistorBandAnalyzer.Result r=ResistorBandAnalyzer.analyze(im);runOnUiThread(()->{result.setText("RENK BANTLARI\n"+r.bands+"\nDeğer: "+r.value+" • Güven %"+r.confidence);bom.add(new ComponentDecoder.Item("R?"+(scanNo++),r.bands,"Direnç",r.value,r.confidence,"Kamera renk bandı"));refresh();status.setText("Direnç analizi tamamlandı");});busy.set(false);im.close();return;}
        if(im.getImage()==null){busy.set(false);im.close();return;}InputImage input=InputImage.fromMediaImage(im.getImage(),im.getImageInfo().getRotationDegrees());
        recognizer.process(input).addOnSuccessListener(this::textDone).addOnFailureListener(e->runOnUiThread(()->status.setText("OCR hatası: "+e.getMessage()))).addOnCompleteListener(t->{busy.set(false);im.close();if(framesRemaining>0)requested.set(true);});
    }
    private void textDone(Text text){overlay.update(text,frameWidth,frameHeight);String raw=text.getText().trim();if(framesRemaining>0){multiText.append(raw).append('\n');framesRemaining--;runOnUiThread(()->status.setText("SÜPER OCR • "+(8-framesRemaining)+"/8 kare"));if(framesRemaining>0)return;raw=multiText.toString();}final String decodedRaw=raw;List<ComponentDecoder.Item> decoded=ComponentDecoder.decodeText(decodedRaw),found=new ArrayList<>();for(ComponentDecoder.Item x:decoded){String taught=getSharedPreferences("teach",MODE_PRIVATE).getString(x.code,"");if(taught.isEmpty())found.add(x);else found.add(new ComponentDecoder.Item(x.ref,x.code,x.type,taught,99,"Kullanıcı tarafından öğretildi"));}if(!found.isEmpty()){for(ComponentDecoder.Item x:found)if(!contains(x.ref,x.code))bom.add(x);lastCode=found.get(0).code;}runOnUiThread(()->{StringBuilder s=new StringBuilder();for(ComponentDecoder.Item x:found)s.append(x.line()).append('\n');if(s.length()==0)s.append("Kod bulunamadı. Yaklaştırın, hedefe dokunup tekrar deneyin.");result.setText(s.toString().trim());status.setText("SÜPER OCR tamamlandı • "+found.size()+" aday • canlı kutular açık");refresh();saveProject();});}
    private boolean contains(String ref,String code){for(ComponentDecoder.Item x:bom)if(x.ref.equals(ref)&&x.code.equals(code))return true;return false;}
    private void refresh(){int r=0,c=0,l=0,d=0,q=0,u=0;for(ComponentDecoder.Item x:bom){if(x.ref.startsWith("R"))r++;else if(x.ref.startsWith("C"))c++;else if(x.ref.startsWith("L")||x.ref.startsWith("FB"))l++;else if(x.ref.startsWith("D"))d++;else if(x.ref.startsWith("Q"))q++;else if(x.ref.startsWith("U"))u++;}summary.setText("BOM: "+bom.size()+" • R"+r+" C"+c+" L/FB"+l+" D"+d+" Q"+q+" U"+u);}
    private void showBom(){StringBuilder s=new StringBuilder("REF • TÜR • KOD → DEĞER • GÜVEN\n\n");for(ComponentDecoder.Item x:bom)s.append(x.line()).append("\n");if(bom.isEmpty())s.append("Henüz eleman yok. KARTI TARA ile başlayın.");dialog("BOM / MALZEME LİSTESİ",s.toString());}
    private void datasheet(){String q=lastCode.isEmpty()?"electronic component marking datasheet":lastCode+" datasheet pdf pinout";startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+URLEncoder.encode(q,StandardCharsets.UTF_8))));}
    private void faultReport(){StringBuilder s=new StringBuilder("GÖRSEL KONTROL PLANI\n\n1. Yanık, çatlak, şişme, oksit ve lehim köprüsü için kartı farklı açılarda tarayın.\n2. Düşük güvenli değerleri multimetre/LCR ile doğrulayın.\n3. IC kodunu paket ve pin sayısıyla doğrulayın.\n4. İşaretsiz bobin/kondansatör kameradan ölçülemez.\n\n");for(ComponentDecoder.Item x:bom)if(x.confidence<80||x.value.contains("gerekli"))s.append("⚠ ").append(x.line()).append("\n");dialog("ARIZA / KONTROL ET",s.toString());}
    private void meterGuide(){String type=bom.isEmpty()?"":bom.get(bom.size()-1).type;String guide="ÖNCE ENERJİYİ KESİN VE KONDANSATÖRLERİ DEŞARJ EDİN.\n\n";if(type.contains("Direnç"))guide+="Kademe: Ω. Devre etkiliyorsa bir bacağı kaldırın. Probları iki uca bağlayın.";else if(type.contains("Bobin")||type.contains("Ferrit"))guide+="Kademe: süreklilik/Ω; gerçek endüktans için LCR. DC direnç düşük olabilir.";else if(type.contains("Diyot"))guide+="Kademe: diyot testi. İleri yönde tipik 0.2–0.8 V; ters yönde OL beklenir.";else if(type.contains("Kondansatör"))guide+="Kapasite/ESR ölçümü. Enerjisiz ve deşarj edilmiş olmalı; devre etkiliyorsa sökün.";else guide+="Önce GND noktasını belirleyin. Enerjisiz kartta süreklilik/diyot, enerjili kartta yalnız güvenli gerilim ölçümü yapın.";dialog("MULTİMETRE YÖNLENDİRMESİ",guide);}
    private void chooseFault(){String[] a={"Cihaz açılmıyor","Fazla akım/kısa devre","Haberleşmiyor","Aşırı ısınıyor","Diğer belirti"};new AlertDialog.Builder(this).setTitle("ARIZA BELİRTİSİ").setItems(a,(d,w)->dialog("AKILLI ARIZA AĞACI",ServiceEngine.faultTree(a[w]))).show();}
    private void measurementLog(){LinearLayout l=form();EditText point=input("Ölçüm noktası / eleman");EditText value=input("Ölçülen değer ve birim");l.addView(point);l.addView(value);new AlertDialog.Builder(this).setTitle("ÖLÇÜM KAYDI").setView(l).setPositiveButton("KAYDET",(d,w)->{String old=getSharedPreferences("pcb",MODE_PRIVATE).getString("measurements","");getSharedPreferences("pcb",MODE_PRIVATE).edit().putString("measurements",old+point.getText()+" = "+value.getText()+"\n").apply();Toast.makeText(this,"Ölçüm servis dosyasına eklendi",Toast.LENGTH_SHORT).show();}).setNegativeButton("İPTAL",null).show();}
    private void teachComponent(){LinearLayout l=form();EditText code=input("Okunan kod (örn. A7W)");code.setText(lastCode);EditText value=input("Doğru parça/değer");l.addView(code);l.addView(value);new AlertDialog.Builder(this).setTitle("KULLANICI ÖĞRETME MODU").setView(l).setPositiveButton("ÖĞRET",(d,w)->{String c=code.getText().toString().trim().toUpperCase();if(!c.isEmpty())getSharedPreferences("teach",MODE_PRIVATE).edit().putString(c,value.getText().toString().trim()).apply();Toast.makeText(this,"Kod eşlemesi kaydedildi",Toast.LENGTH_SHORT).show();}).setNegativeButton("İPTAL",null).show();}
    private void serviceArchive(){LinearLayout l=form();EditText customer=input("Müşteri / proje");EditText device=input("Cihaz ve kart modeli");EditText serial=input("Seri no / kart revizyonu");EditText symptom=input("Arıza belirtisi");l.addView(customer);l.addView(device);l.addView(serial);l.addView(symptom);new AlertDialog.Builder(this).setTitle("PROFESYONEL SERVİS DOSYASI").setView(l).setPositiveButton("KAYDET",(d,w)->{String meta="Müşteri: "+customer.getText()+"\nCihaz: "+device.getText()+"\nSeri/Rev: "+serial.getText()+"\nBelirti: "+symptom.getText();getSharedPreferences("pcb",MODE_PRIVATE).edit().putString("service_meta",meta).apply();Toast.makeText(this,"Servis dosyası kaydedildi",Toast.LENGTH_LONG).show();}).setNegativeButton("İPTAL",null).show();}
    private LinearLayout form(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(20),dp(8),dp(20),0);return l;}private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);return e;}
    private String snapshot(){StringBuilder s=new StringBuilder();for(ComponentDecoder.Item x:bom)s.append(x.ref).append('|').append(x.code).append('|').append(x.value).append('\n');return s.toString();}
    private void saveReference(){getSharedPreferences("pcb",MODE_PRIVATE).edit().putString("reference",snapshot()).apply();Toast.makeText(this,"Sağlam kart referansı kaydedildi",Toast.LENGTH_LONG).show();}
    private void compareReference(){String ref=getSharedPreferences("pcb",MODE_PRIVATE).getString("reference","");if(ref.isEmpty()){dialog("KARŞILAŞTIR","Önce sağlam kartı tarayıp REFERANS KART seçin.");return;}Set<String>a=new HashSet<>(Arrays.asList(ref.split("\n"))),b=new HashSet<>(Arrays.asList(snapshot().split("\n")));StringBuilder s=new StringBuilder("EKSİK/FARKLI\n");for(String x:a)if(!b.contains(x))s.append("− ").append(x).append('\n');s.append("\nYENİ/FAZLA\n");for(String x:b)if(!a.contains(x))s.append("+ ").append(x).append('\n');if(a.equals(b))s.append("Kart BOM'u referansla eşleşiyor.");dialog("SAĞLAM KART KARŞILAŞTIRMA",s.toString());}
    private void saveProject(){getSharedPreferences("pcb",MODE_PRIVATE).edit().putString("last_project",snapshot()).apply();}
    private void createPdf(){try{File dir=new File(getCacheDir(),"reports");dir.mkdirs();File f=new File(dir,"PCB_Zeka_Pro_Servis_Raporu.pdf");PdfDocument doc=new PdfDocument();Paint p=new Paint();p.setColor(Color.BLACK);p.setTextSize(13);int pageNo=1,index=0;String meta=getSharedPreferences("pcb",MODE_PRIVATE).getString("service_meta","Servis bilgisi girilmedi"),meas=getSharedPreferences("pcb",MODE_PRIVATE).getString("measurements","Ölçüm kaydı yok");while(index<Math.max(1,bom.size())){PdfDocument.Page page=doc.startPage(new PdfDocument.PageInfo.Builder(595,842,pageNo++).create());page.getCanvas().drawText("PCB ZEKÂ PRO v4 - PROFESYONEL SERVİS RAPORU",30,40,p);int y=65;for(String line:(meta+"\nBOM: "+bom.size()).split("\n")){page.getCanvas().drawText(line,30,y,p);y+=19;}y+=10;while(index<bom.size()&&y<620){page.getCanvas().drawText(bom.get(index++).line(),25,y,p);y+=20;}if(bom.isEmpty()){page.getCanvas().drawText("Henüz tarama sonucu yok.",30,y,p);index++;y+=20;}page.getCanvas().drawText("ÖLÇÜMLER",30,670,p);y=692;for(String line:meas.split("\n")){if(y>810)break;page.getCanvas().drawText(line,30,y,p);y+=18;}doc.finishPage(page);}try(FileOutputStream o=new FileOutputStream(f)){doc.writeTo(o);}doc.close();Uri u=FileProvider.getUriForFile(this,getPackageName()+".files",f);Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"PDF servis raporunu kaydet/paylaş"));}catch(Exception e){dialog("PDF HATASI",e.getMessage()==null?"Rapor oluşturulamadı":e.getMessage());}}
    private void shareCsv(){StringBuilder s=new StringBuilder("Ref,Tur,Kod,Deger,Guven,Not\n");for(ComponentDecoder.Item x:bom)s.append(x.csv()).append('\n');Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/csv");i.putExtra(Intent.EXTRA_SUBJECT,"PCB Zekâ Pro BOM");i.putExtra(Intent.EXTRA_TEXT,s.toString());startActivity(Intent.createChooser(i,"BOM kaydet veya paylaş"));}
    private void dialog(String title,String text){ScrollView sv=new ScrollView(this);TextView t=label(text,14,Color.WHITE);t.setPadding(dp(18),dp(10),dp(18),dp(10));sv.addView(t);new AlertDialog.Builder(this).setTitle(title).setView(sv).setPositiveButton("GERİ",null).show();}
    private void setZoom(float z){if(camera!=null){camera.getCameraControl().setLinearZoom(Math.max(0,Math.min(1,z)));preview.postDelayed(this::updateZoom,80);}}
    private void updateZoom(){if(camera!=null&&camera.getCameraInfo().getZoomState().getValue()!=null)zoom.setText(String.format(Locale.US,"Zoom %.1f× • dokunarak netleştir",camera.getCameraInfo().getZoomState().getValue().getZoomRatio()));}
    private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(Color.WHITE);return b;}private TextView label(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    @Override protected void onDestroy(){recognizer.close();executor.shutdown();super.onDestroy();}
}
