cmake_minimum_required(VERSION 3.22.1)
project(mgcad)
set(CMAKE_CXX_STANDARD 17)
set(OCCT_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/occt)
include_directories(${OCCT_ROOT}/include/opencascade)
add_library(mgcad SHARED cad_bridge.cpp)
set(OCCT_LIBS TKernel TKMath TKG2d TKG3d TKBRep TKGeomBase TKGeomAlgo TKTopAlgo TKPrim TKBO TKShHealing TKMesh TKDESTEP TKDEIGES TKXSBase TKDE)
foreach(L ${OCCT_LIBS})
  add_library(${L} SHARED IMPORTED)
  set_target_properties(${L} PROPERTIES IMPORTED_LOCATION ${OCCT_ROOT}/lib/lib${L}.so)
endforeach()
target_link_libraries(mgcad android log ${OCCT_LIBS})
