plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mg.veinassist'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mg.veinassist.stable29'
        minSdk 26
        targetSdk 35
        versionCode 29
        versionName '2.9-stable-skin-continuity'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
