plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mg.trainingassistant'
    compileSdk 36

    defaultConfig {
        applicationId 'com.mg.trainingassistant'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '1.2.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
