package com.muhammetgecgil.camera3d;

import android.Manifest;import android.app.Activity;import android.content.ContentValues;import android.content.pm.PackageManager;import android.graphics.*;import android.net.Uri;import android.opengl.*;import android.os.Bundle;import android.provider.MediaStore;import android.view.*;import android.widget.*;
import com.google.ar.core.*;import com.google.ar.core.exceptions.CameraNotAvailableException;
import java.io.OutputStream;import java.nio.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;

public class MainActivity extends Activity implements GLSurfaceView.Renderer{
 static final int REQ=71; GLSurfaceView gl; FaceView faces; Session session; BackgroundRenderer bg; volatile boolean scanning=false; ArrayList<float[]> pts=new ArrayList<>(); HashSet<Long> vox=new HashSet<>(); boolean[] done=new boolean[6]; int[] hits=new int[6]; int target=0; TextView status,count,guide; ProgressBar prog; Button scan,export; long lastUi;
 String[] names={"ÖN","SAĞ","ARKA","SOL","ÜST","ALT"};
 public void onCreate(Bundle b){super.onCreate(b);build();if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},REQ);else setup();}
 void build(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.HORIZONTAL);gl=new GLSurfaceView(this);gl.setEGLContextClientVersion(2);gl.setPreserveEGLContextOnPause(true);gl.setRenderer(this);faces=new FaceView();body.addView(gl,new LinearLayout.LayoutParams(0,-1,1.25f));body.addView(faces,new LinearLayout.LayoutParams(0,-1,.75f));root.addView(body,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(20,16,20,12);top.setBackgroundColor(0xdd101010);TextView title=new TextView(this);title.setText("CAMERA 3D • CAD SCAN 1.3");title.setTextColor(Color.WHITE);title.setTextSize(19);status=new TextView(this);status.setText("Kamera hazırlanıyor…");status.setTextColor(0xffdddddd);count=new TextView(this);count.setText("3D nokta: 0 • yüz: 0/6");count.setTextColor(0xff8ee8ff);count.setTextSize(15);prog=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);prog.setMax(100);guide=new TextView(this);guide.setText("Başlatınca uygulama hangi yüzü göstereceğini söyleyecek");guide.setTextColor(Color.WHITE);guide.setTextSize(14);top.addView(title);top.addView(status);top.addView(count);top.addView(prog);top.addView(guide);FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(-1,-2,Gravity.TOP);tp.setMargins(10,34,10,0);root.addView(top,tp);
  LinearLayout bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.VERTICAL);bottom.setPadding(14,10,14,18);bottom.setBackgroundColor(0xdd111111);LinearLayout row=new LinearLayout(this);scan=new Button(this);scan.setText("3D TARAMAYI BAŞLAT");scan.setOnClickListener(v->toggle());Button clear=new Button(this);clear.setText("TEMİZLE");clear.setOnClickListener(v->clear());row.addView(scan,new LinearLayout.LayoutParams(0,-2,2));row.addView(clear,new LinearLayout.LayoutParams(0,-2,1));bottom.addView(row);export=new Button(this);export.setText("CAD VERİSİ • PLY + OBJ");export.setEnabled(false);export.setOnClickListener(v->save());bottom.addView(export);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);bp.setMargins(10,0,10,28);root.addView(bottom,bp);setContentView(root);}
 void setup(){try{if(session!=null)return;if(ArCoreApk.getInstance().checkAvailability(this).isUnsupported()){status.setText("ARCore desteklenmiyor");return;}session=new Session(this);Config c=new Config(session);c.setUpdateMode(Config.UpdateMode.LATEST_CAMERA_IMAGE);session.configure(c);status.setText("Kamera hazır");}catch(Throwable t){status.setText("ARCore: "+t.getClass().getSimpleName());}}
 void toggle(){if(session==null){setup();if(session==null)return;}scanning=!scanning;scan.setText(scanning?"TARAMAYI BİTİR":"3D TARAMAYI BAŞLAT");if(scanning){target=firstMissing();guide.setText(command());}else guide.setText("Tarama durdu • sağdaki yüz kontrolünü incele");export.setEnabled(pts.size()>100);}
 synchronized void clear(){scanning=false;pts.clear();vox.clear();Arrays.fill(done,false);Arrays.fill(hits,0);target=0;scan.setText("3D TARAMAYI BAŞLAT");export.setEnabled(false);count.setText("3D nokta: 0 • yüz: 0/6");prog.setProgress(0);guide.setText("Ön → Sağ → Arka → Sol → Üst → Alt");faces.invalidate();}
 public void onSurfaceCreated(GL10 x,EGLConfig c){bg=new BackgroundRenderer();bg.create();GLES20.glClearColor(0,0,0,1);}public void onSurfaceChanged(GL10 x,int w,int h){GLES20.glViewport(0,0,w,h);if(session!=null)session.setDisplayGeometry(getWindowManager().getDefaultDisplay().getRotation(),w,h);}
 public void onDrawFrame(GL10 x){GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT);if(session==null||bg==null)return;try{session.setCameraTextureName(bg.textureId);Frame f=session.update();bg.draw(f);com.google.ar.core.Camera cam=f.getCamera();if(cam.getTrackingState()!=TrackingState.TRACKING){ui("Kamera açık • telefonu yavaş hareket ettir");return;}if(scanning){classify(cam.getPose());collect(f);}}catch(Throwable t){ui("Kamera/AR hatası: "+t.getClass().getSimpleName());}}
 void classify(Pose p){float[] z=p.getZAxis();float dx=-z[0],dy=-z[1],dz=-z[2];double el=Math.asin(Math.max(-1,Math.min(1,dy)));int face;if(el>.55)face=5;else if(el<-.55)face=4;else{double a=Math.atan2(dx,dz);if(a>=-.785&&a<.785)face=0;else if(a>=.785&&a<2.356)face=1;else if(a>=-2.356&&a<-.785)face=3;else face=2;}if(face==target){hits[face]++;if(hits[face]>=45){done[face]=true;target=firstMissing();runOnUiThread(()->{guide.setText(command());faces.invalidate();});}}}
 int firstMissing(){for(int i=0;i<6;i++)if(!done[i])return i;return -1;}String command(){if(target<0)return "TÜM YÜZLER TAMAM • taramayı bitirebilirsin";switch(target){case 0:return "1/6 • CİSMİN ÖN YÜZÜNÜ GÖSTER";case 1:return "2/6 • CİSMİN SAĞ YÜZÜNÜ GÖSTER";case 2:return "3/6 • CİSMİN ARKA YÜZÜNÜ GÖSTER";case 3:return "4/6 • CİSMİN SOL YÜZÜNÜ GÖSTER";case 4:return "5/6 • CİSMİN ÜST YÜZÜNÜ GÖSTER";default:return "6/6 • CİSMİN ALT YÜZÜNÜ GÖSTER";}}
 void collect(Frame f){try(PointCloud pc=f.acquirePointCloud()){FloatBuffer b=pc.getPoints();int n=b.remaining()/4,step=Math.max(1,n/900);synchronized(this){for(int i=0;i<n;i+=step){int q=i*4;float X=b.get(q),Y=b.get(q+1),Z=b.get(q+2),C=b.get(q+3);if(C<.25f||Math.abs(X)>6||Math.abs(Y)>6||Math.abs(Z)>6)continue;long k=key(X,Y,Z,.007f);if(vox.add(k))pts.add(new float[]{X,Y,Z,C});}update();}}catch(Throwable ignored){}}
 void update(){long now=System.currentTimeMillis();if(now-lastUi<350)return;lastUi=now;int d=0;for(boolean b:done)if(b)d++;int pc=(int)(100f*(d+(target>=0?Math.min(1f,hits[target]/45f):0))/6f);int n=pts.size(),dd=d;runOnUiThread(()->{count.setText("3D nokta: "+n+" • yüz: "+dd+"/6");prog.setProgress(pc);status.setText(target<0?"6 yüz tamamlandı":"Tarama aktif");guide.setText(command());faces.invalidate();export.setEnabled(n>100);});}
 long key(float x,float y,float z,float c){long a=(long)Math.floor(x/c)+1048576,b=(long)Math.floor(y/c)+1048576,d=(long)Math.floor(z/c)+1048576;return((a&0x1fffffL)<<42)|((b&0x1fffffL)<<21)|(d&0x1fffffL);}
 void ui(String s){long n=System.currentTimeMillis();if(n-lastUi>800){lastUi=n;runOnUiThread(()->status.setText(s));}}
 void save(){ArrayList<float[]> cp; synchronized(this){cp=new ArrayList<>(pts);}if(cp.size()<10)return;new Thread(()->{try{String st=new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date());write("CADScan_"+st+".ply","application/octet-stream",ply(cp));write("CADScan_"+st+".obj","text/plain",obj(cp));runOnUiThread(()->Toast.makeText(this,"PLY + OBJ kaydedildi",Toast.LENGTH_LONG).show());}catch(Throwable e){}}).start();}
 byte[] ply(ArrayList<float[]>p){StringBuilder s=new StringBuilder("ply\nformat ascii 1.0\nelement vertex "+p.size()+"\nproperty float x\nproperty float y\nproperty float z\nend_header\n");for(float[]v:p)s.append(v[0]).append(' ').append(v[1]).append(' ').append(v[2]).append('\n');return s.toString().getBytes(StandardCharsets.UTF_8);}byte[] obj(ArrayList<float[]>p){StringBuilder s=new StringBuilder("# CADScan\n");for(float[]v:p)s.append("v ").append(v[0]).append(' ').append(v[1]).append(' ').append(v[2]).append('\n');return s.toString().getBytes(StandardCharsets.UTF_8);}void write(String n,String m,byte[]d)throws Exception{ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,n);v.put(MediaStore.Downloads.MIME_TYPE,m);v.put(MediaStore.Downloads.RELATIVE_PATH,"Download/Camera3D");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(d);}}
 protected void onResume(){super.onResume();if(session==null&&checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)setup();if(session!=null)try{session.resume();}catch(CameraNotAvailableException e){status.setText("Kamera açılamadı");}if(gl!=null)gl.onResume();}protected void onPause(){if(gl!=null)gl.onPause();if(session!=null)session.pause();super.onPause();}protected void onDestroy(){if(session!=null)session.close();super.onDestroy();}public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){setup();try{session.resume();}catch(Throwable ignored){}}}
 class FaceView extends View{Paint p=new Paint(1);FaceView(){super(MainActivity.this);setBackgroundColor(0xff11151a);}protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth();p.setTextAlign(Paint.Align.CENTER);p.setTextSize(30);p.setColor(Color.WHITE);c.drawText("YÜZ KONTROLÜ",w/2,170,p);float y=230;for(int i=0;i<6;i++){p.setColor(done[i]?0xff28c76f:(i==target?0xffffb020:0xffd94b4b));c.drawRoundRect(25,y,w-25,y+62,14,14,p);p.setColor(Color.WHITE);p.setTextSize(25);c.drawText((done[i]?"✓ ":i==target?"→ ":"○ ")+names[i],w/2,y+41,p);y+=78;}p.setTextSize(18);p.setColor(0xffdddddd);c.drawText(target<0?"TAMAMLANDI":"SIRADAKİ: "+names[target],w/2,y+25,p);}}
 static class BackgroundRenderer{int textureId=-1,program,pos,tex,coord;FloatBuffer vb,tb;void create(){int[]t=new int[1];GLES20.glGenTextures(1,t,0);textureId=t[0];GLES20.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,textureId);GLES20.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,GLES20.GL_TEXTURE_MIN_FILTER,GLES20.GL_LINEAR);GLES20.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,GLES20.GL_TEXTURE_MAG_FILTER,GLES20.GL_LINEAR);float[]v={-1,-1,1,-1,-1,1,1,1},u={0,1,1,1,0,0,1,0};vb=buf(v);tb=buf(u);String vs="attribute vec2 a;attribute vec2 b;varying vec2 v;void main(){gl_Position=vec4(a,0.,1.);v=b;}";String fs="#extension GL_OES_EGL_image_external : require\nprecision mediump float;uniform samplerExternalOES s;varying vec2 v;void main(){gl_FragColor=texture2D(s,v);}";program=GLES20.glCreateProgram();int a=sh(GLES20.GL_VERTEX_SHADER,vs),b=sh(GLES20.GL_FRAGMENT_SHADER,fs);GLES20.glAttachShader(program,a);GLES20.glAttachShader(program,b);GLES20.glLinkProgram(program);pos=GLES20.glGetAttribLocation(program,"a");tex=GLES20.glGetAttribLocation(program,"b");coord=GLES20.glGetUniformLocation(program,"s");}void draw(Frame f){GLES20.glDisable(GLES20.GL_DEPTH_TEST);GLES20.glUseProgram(program);vb.position(0);tb.position(0);GLES20.glVertexAttribPointer(pos,2,GLES20.GL_FLOAT,false,0,vb);GLES20.glEnableVertexAttribArray(pos);GLES20.glVertexAttribPointer(tex,2,GLES20.GL_FLOAT,false,0,tb);GLES20.glEnableVertexAttribArray(tex);GLES20.glActiveTexture(GLES20.GL_TEXTURE0);GLES20.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,textureId);GLES20.glUniform1i(coord,0);GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP,0,4);}static FloatBuffer buf(float[]a){ByteBuffer b=ByteBuffer.allocateDirect(a.length*4).order(ByteOrder.nativeOrder());FloatBuffer f=b.asFloatBuffer();f.put(a).position(0);return f;}static int sh(int t,String s){int x=GLES20.glCreateShader(t);GLES20.glShaderSource(x,s);GLES20.glCompileShader(x);return x;}}
}