package com.muhammetgecgil.modelviewer;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.opengl.*;import android.provider.OpenableColumns;import android.database.Cursor;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.util.*;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;

public class MainActivity extends Activity {
 static final int OPEN_MODEL=1001; TextView status,info; ModelView view;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);buildUi();}
 TextView t(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.WHITE);v.setPadding(10,6,10,6);return v;}
 Button b(String s,View.OnClickListener l){Button v=new Button(this);v.setText(s);v.setTextSize(11);v.setOnClickListener(l);return v;}
 void buildUi(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);view=new ModelView(this);root.addView(view,new FrameLayout.LayoutParams(-1,-1));HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setBackgroundColor(0xdd07121c);TextView mg=t("MG CAD v1.3",15);mg.setTextColor(0xff38bdf8);top.addView(mg);top.addView(b("DOSYA AÇ",v->open()));top.addView(b("MERKEZ",v->view.reset()));top.addView(b("ÖN",v->view.preset(0)));top.addView(b("SAĞ",v->view.preset(1)));top.addView(b("ÜST",v->view.preset(2)));top.addView(b("İZO",v->view.preset(3)));top.addView(b("OTOMATİK ÖLÇÜ",v->autoDim()));hs.addView(top);root.addView(hs,new FrameLayout.LayoutParams(-1,-2,Gravity.TOP));LinearLayout bot=new LinearLayout(this);bot.setOrientation(LinearLayout.VERTICAL);bot.setBackgroundColor(0xdd05080b);status=t("STEP/STP • IGES/IGS • BREP",12);info=t("Model açılmadı",12);info.setTextColor(0xffffd166);bot.addView(status);bot.addView(info);root.addView(bot,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));setContentView(root);}
 void open(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,OPEN_MODEL);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r!=OPEN_MODEL||c!=RESULT_OK||data==null)return;Uri u=data.getData();if(u!=null)new Thread(()->load(u)).start();}
 void load(Uri u){try{String n=name(u);File f=new File(getCacheDir(),"cad_"+System.nanoTime()+"_"+n);try(InputStream in=getContentResolver().openInputStream(u);FileOutputStream out=new FileOutputStream(f)){byte[]buf=new byte[65536];int k;while((k=in.read(buf))>0)out.write(buf,0,k);}String l=n.toLowerCase(Locale.ROOT);if(!(l.endsWith(".step")||l.endsWith(".stp")||l.endsWith(".iges")||l.endsWith(".igs")||l.endsWith(".brep")))throw new Exception("Desteklenen CAD: STEP/STP, IGES/IGS, BREP");if(!CadNative.loadCad(f.getAbsolutePath()))throw new Exception("OCCT dosyayı okuyamadı");float[]tri=CadNative.getTriangles();if(tri==null||tri.length<9)throw new Exception("Yüzey üretilemedi");runOnUiThread(()->{view.setTriangles(tri);status.setText(n+" açıldı");info.setText(CadNative.getModelInfo());});}catch(Throwable e){runOnUiThread(()->status.setText("Açılamadı: "+e.getMessage()));}}
 void autoDim(){try{info.setText(CadNative.autoDimensions());}catch(Throwable e){info.setText("Ölçü hatası: "+e.getMessage());}}
 String name(Uri u){try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Throwable ignored){}return "model.step";}
 class ModelView extends GLSurfaceView implements GLSurfaceView.Renderer,View.OnTouchListener{FloatBuffer vb;int count,prog,aPos,uMvp;float rx=-20,ry=30,zoom=3.2f,lx,ly;ModelView(Context c){super(c);setEGLContextClientVersion(2);setRenderer(this);setRenderMode(RENDERMODE_CONTINUOUSLY);setOnTouchListener(this);}void setTriangles(float[]t){ByteBuffer bb=ByteBuffer.allocateDirect(t.length*4).order(ByteOrder.nativeOrder());vb=bb.asFloatBuffer();vb.put(t).position(0);count=t.length/3;reset();}void reset(){rx=-20;ry=30;zoom=3.2f;}void preset(int p){if(p==0){rx=0;ry=0;}else if(p==1){rx=0;ry=90;}else if(p==2){rx=-90;ry=0;}else{rx=-25;ry=35;}}@Override public void onSurfaceCreated(GL10 g,EGLConfig c){GLES20.glClearColor(.01f,.015f,.02f,1);GLES20.glEnable(GLES20.GL_DEPTH_TEST);String vs="uniform mat4 mvp;attribute vec3 p;void main(){gl_Position=mvp*vec4(p,1.0);}";String fs="precision mediump float;void main(){gl_FragColor=vec4(.25,.70,.95,1.0);}";prog=GLES20.glCreateProgram();GLES20.glAttachShader(prog,shader(GLES20.GL_VERTEX_SHADER,vs));GLES20.glAttachShader(prog,shader(GLES20.GL_FRAGMENT_SHADER,fs));GLES20.glLinkProgram(prog);aPos=GLES20.glGetAttribLocation(prog,"p");uMvp=GLES20.glGetUniformLocation(prog,"mvp");}int shader(int t,String s){int q=GLES20.glCreateShader(t);GLES20.glShaderSource(q,s);GLES20.glCompileShader(q);return q;}@Override public void onSurfaceChanged(GL10 g,int w,int h){GLES20.glViewport(0,0,w,h);}@Override public void onDrawFrame(GL10 g){GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);if(vb==null)return;float[]p=new float[16],v=new float[16],m=new float[16],tmp=new float[16],mvp=new float[16];Matrix.perspectiveM(p,0,45,(float)getWidth()/Math.max(1,getHeight()),.05f,50);Matrix.setLookAtM(v,0,0,0,zoom,0,0,0,0,1,0);Matrix.setIdentityM(m,0);Matrix.rotateM(m,0,rx,1,0,0);Matrix.rotateM(m,0,ry,0,1,0);Matrix.multiplyMM(tmp,0,v,0,m,0);Matrix.multiplyMM(mvp,0,p,0,tmp,0);GLES20.glUseProgram(prog);GLES20.glUniformMatrix4fv(uMvp,1,false,mvp,0);vb.position(0);GLES20.glVertexAttribPointer(aPos,3,GLES20.GL_FLOAT,false,0,vb);GLES20.glEnableVertexAttribArray(aPos);GLES20.glDrawArrays(GLES20.GL_TRIANGLES,0,count);}@Override public boolean onTouch(View v,MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){lx=e.getX();ly=e.getY();return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){ry+=(e.getX()-lx)*.35f;rx+=(e.getY()-ly)*.35f;lx=e.getX();ly=e.getY();return true;}return true;}}
}
