package com.mg.battleship;

import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.LinearGradient;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.graphics.Shader;

final class AdvancedShipRenderer {
    static final String[] NAMES={"UÇAK GEMİSİ","SAVAŞ GEMİSİ","KRUVAZÖR","DESTROYER","DENİZALTI"};
    private AdvancedShipRenderer(){}
    static String name(int id){return id>=0&&id<NAMES.length?NAMES[id]:"GEMİ";}
    static void draw(Canvas c,Paint p,float left,float top,float cell,int[][] own,int id){int minR=99,maxR=-1,minC=99,maxC=-1;for(int r=0;r<10;r++)for(int col=0;col<10;col++)if(own[r][col]==id){minR=Math.min(minR,r);maxR=Math.max(maxR,r);minC=Math.min(minC,col);maxC=Math.max(maxC,col);}if(maxR<0)return;boolean h=minR==maxR;float x0=left+minC*cell,y0=top+minR*cell,x1=left+(maxC+1)*cell,y1=top+(maxR+1)*cell,cx=(x0+x1)/2f,cy=(y0+y1)/2f;c.save();if(!h)c.rotate(90,cx,cy);float L=h?(x1-x0):(y1-y0),H=cell*.90f,sx=cx-L/2f,ex=cx+L/2f,w=cy+H*.26f;shadow(c,p,sx,ex,w,H);if(id==0)carrier(c,p,sx,ex,w,H,L);else if(id==1)battleship(c,p,sx,ex,w,H,L);else if(id==2)cruiser(c,p,sx,ex,w,H,L);else if(id==3)destroyer(c,p,sx,ex,w,H,L);else submarine(c,p,sx,ex,w,H,L);c.restore();}
    private static void shadow(Canvas c,Paint p,float sx,float ex,float w,float H){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(85,0,0,0));c.drawOval(new RectF(sx+H*.1f,w-H*.03f,ex-H*.05f,w+H*.18f),p);}
    private static void hull(Canvas c,Paint p,float sx,float ex,float w,float H,float bow,float stern){Path h=new Path();h.moveTo(sx+stern,w-H*.22f);h.lineTo(ex-bow,w-H*.22f);h.lineTo(ex,w-H*.06f);h.lineTo(ex-bow*.55f,w+H*.17f);h.lineTo(sx+stern*.7f,w+H*.18f);h.lineTo(sx,w-H*.02f);h.close();p.setStyle(Paint.Style.FILL);p.setShader(new LinearGradient(0,w-H*.3f,0,w+H*.2f,Color.rgb(137,151,157),Color.rgb(43,53,59),Shader.TileMode.CLAMP));c.drawPath(h,p);p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(H*.03f);p.setColor(Color.rgb(220,228,231));c.drawPath(h,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(48,59,65));c.drawRect(sx+stern*.7f,w-H*.27f,ex-bow*.65f,w-H*.20f,p);}
    private static void turret(Canvas c,Paint p,float x,float y,float s,float barrel){p.setColor(Color.rgb(77,88,94));c.drawRoundRect(new RectF(x-s*.28f,y-s*.18f,x+s*.28f,y+s*.18f),s*.08f,s*.08f,p);p.setColor(Color.rgb(31,39,43));p.setStrokeWidth(s*.08f);p.setStyle(Paint.Style.STROKE);c.drawLine(x+s*.18f,y,x+barrel,y,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(180,190,193));c.drawCircle(x,y,s*.09f,p);}
    private static void mast(Canvas c,Paint p,float x,float base,float H){p.setColor(Color.rgb(185,195,198));p.setStrokeWidth(H*.03f);p.setStyle(Paint.Style.STROKE);c.drawLine(x,base,x,base-H*.42f,p);c.drawLine(x-H*.13f,base-H*.29f,x+H*.14f,base-H*.29f,p);c.drawLine(x-H*.08f,base-H*.18f,x+H*.11f,base-H*.18f,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(74,196,220));c.drawCircle(x,base-H*.42f,H*.042f,p);}
    private static void carrier(Canvas c,Paint p,float sx,float ex,float w,float H,float L){hull(c,p,sx,ex,w,H,H*.34f,H*.15f);p.setColor(Color.rgb(70,79,84));c.drawRoundRect(new RectF(sx+L*.05f,w-H*.51f,ex-L*.02f,w-H*.25f),H*.05f,H*.05f,p);p.setColor(Color.WHITE);p.setStrokeWidth(H*.02f);p.setStyle(Paint.Style.STROKE);c.drawLine(sx+L*.12f,w-H*.38f,ex-L*.10f,w-H*.38f,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(158,168,171));c.drawRect(sx+L*.66f,w-H*.70f,sx+L*.79f,w-H*.50f,p);mast(c,p,sx+L*.72f,w-H*.69f,H*.72f);p.setColor(Color.rgb(28,33,36));for(int i=0;i<3;i++){float ax=sx+L*(.20f+i*.14f);Path a=new Path();a.moveTo(ax,w-H*.45f);a.lineTo(ax+H*.18f,w-H*.38f);a.lineTo(ax,w-H*.31f);a.lineTo(ax+H*.05f,w-H*.38f);a.close();c.drawPath(a,p);}}
    private static void battleship(Canvas c,Paint p,float sx,float ex,float w,float H,float L){hull(c,p,sx,ex,w,H,H*.38f,H*.18f);p.setColor(Color.rgb(111,123,128));c.drawRect(sx+L*.36f,w-H*.49f,sx+L*.68f,w-H*.22f,p);p.setColor(Color.rgb(155,166,170));c.drawRect(sx+L*.45f,w-H*.65f,sx+L*.59f,w-H*.48f,p);mast(c,p,sx+L*.53f,w-H*.64f,H*.8f);turret(c,p,sx+L*.17f,w-H*.31f,H*.58f,H*.46f);turret(c,p,sx+L*.29f,w-H*.30f,H*.54f,H*.42f);turret(c,p,sx+L*.80f,w-H*.29f,H*.52f,H*.40f);}
    private static void cruiser(Canvas c,Paint p,float sx,float ex,float w,float H,float L){hull(c,p,sx,ex,w,H,H*.32f,H*.14f);p.setColor(Color.rgb(133,145,150));c.drawRect(sx+L*.39f,w-H*.48f,sx+L*.64f,w-H*.22f,p);mast(c,p,sx+L*.52f,w-H*.48f,H*.72f);turret(c,p,sx+L*.20f,w-H*.30f,H*.43f,H*.34f);turret(c,p,sx+L*.78f,w-H*.29f,H*.40f,H*.31f);}
    private static void destroyer(Canvas c,Paint p,float sx,float ex,float w,float H,float L){hull(c,p,sx,ex,w,H,H*.27f,H*.10f);p.setColor(Color.rgb(135,148,153));c.drawRect(sx+L*.34f,w-H*.43f,sx+L*.57f,w-H*.22f,p);mast(c,p,sx+L*.45f,w-H*.43f,H*.64f);turret(c,p,sx+L*.16f,w-H*.29f,H*.34f,H*.29f);p.setColor(Color.rgb(48,54,58));for(int i=0;i<4;i++){float x=sx+L*(.61f+i*.035f);c.drawRoundRect(new RectF(x,w-H*.37f,x+H*.07f,w-H*.24f),H*.02f,H*.02f,p);}}
    private static void submarine(Canvas c,Paint p,float sx,float ex,float w,float H,float L){float cy=w-H*.10f;Path b=new Path();b.moveTo(sx+H*.16f,cy-H*.16f);b.quadTo(sx,cy,sx+H*.16f,cy+H*.16f);b.lineTo(ex-H*.18f,cy+H*.16f);b.quadTo(ex,cy,ex-H*.18f,cy-H*.16f);b.close();p.setShader(new LinearGradient(0,cy-H*.17f,0,cy+H*.17f,Color.rgb(65,76,81),Color.rgb(16,22,26),Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);c.drawPath(b,p);p.setShader(null);p.setColor(Color.rgb(91,102,106));c.drawRoundRect(new RectF(sx+L*.45f,cy-H*.38f,sx+L*.61f,cy-H*.10f),H*.05f,H*.05f,p);p.setColor(Color.rgb(183,193,196));p.setStrokeWidth(H*.03f);p.setStyle(Paint.Style.STROKE);float px=sx+L*.53f;c.drawLine(px,cy-H*.38f,px,cy-H*.65f,p);c.drawLine(px,cy-H*.65f,px+H*.11f,cy-H*.65f,p);p.setStyle(Paint.Style.FILL);}
}
