plugins { id 'com.android.application' }

android {
    namespace 'com.muhammetgecgil.sesgoruntuharitasi'
    compileSdk 36

    defaultConfig {
        applicationId 'com.muhammetgecgil.probefusionv8'
        minSdk 26
        targetSdk 36
        versionCode 80
        versionName '8.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
