plugins { id 'com.android.application' }

android {
    namespace 'com.muhammetgecgil.sesgoruntuharitasi'
    compileSdk 36
    defaultConfig {
        applicationId 'com.muhammetgecgil.probefusionv86'
        minSdk 26
        targetSdk 36
        versionCode 860
        versionName '8.6'
    }
    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' }
    }
}
