package com.muhammetgecgil.wifiradar;

import android.app.Activity;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.InputType;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.net.HttpURLConnection;
import java.net.InetAddress;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class CsiActivity extends Activity {
    private final Handler main=new Handler(Looper.getMainLooper());private final ExecutorService io=Executors.newFixedThreadPool(4);private final List<Node>nodes=new ArrayList<>(),fieldsNodes=new ArrayList<>();private final List<EditText>fields=new ArrayList<>();private final List<TextView>rows=new ArrayList<>();private boolean running;
    private TextView headline,state,metrics,centroid;private HeatMapView heat;private final Hmm hmm=new Hmm();
    private final Runnable loop=new Runnable(){@Override public void run(){if(!running)return;for(Node n:nodes)poll(n);main.postDelayed(()->{if(running)update();},350);main.postDelayed(this,1000);}};

    @Override protected void onCreate(Bundle b){super.onCreate(b);nodes.add(new Node("N1",.08,.08));nodes.add(new Node("N2",.92,.08));nodes.add(new Node("N3",.92,.92));nodes.add(new Node("N4",.08,.92));build();}
    private void build(){LinearLayout root=Ui.shell(this,"ESP32 CSI Füzyon Laboratuvarı");ScrollView sv=Ui.scroll(this);LinearLayout col=Ui.column(this);sv.addView(col);col.addView(Ui.button(this,"‹ Ana ekran",Ui.PANEL2,v->finish()),new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,Ui.dp(this,44)));headline=Ui.text(this,"Düğümler bekleniyor",21,Ui.WHITE,true);headline.setGravity(android.view.Gravity.CENTER);headline.setPadding(Ui.dp(this,10),Ui.dp(this,13),Ui.dp(this,10),Ui.dp(this,13));headline.setBackground(Ui.round(this,Ui.PANEL,Ui.GREEN,16));col.addView(headline);heat=new HeatMapView(this);heat.setBackground(Ui.round(this,Ui.PANEL,0,16));col.addView(heat,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,Ui.dp(this,330)));
        for(int i=0;i<nodes.size();i++){Node n=nodes.get(i);LinearLayout r=Ui.row(this);TextView id=Ui.text(this,n.id,13,Ui.GREEN,true);id.setGravity(android.view.Gravity.CENTER);EditText ip=new EditText(this);ip.setSingleLine(true);ip.setTextSize(14);ip.setTextColor(Ui.WHITE);ip.setHintTextColor(Ui.MUTED);ip.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);ip.setHint("192.168.1.x");ip.setText(getPreferences(MODE_PRIVATE).getString("ip"+i,""));ip.setBackground(Ui.round(this,Ui.PANEL2,0,10));ip.setPadding(Ui.dp(this,10),0,Ui.dp(this,10),0);TextView st=Ui.text(this,"kapalı",11,Ui.MUTED,false);st.setGravity(android.view.Gravity.CENTER_VERTICAL);r.addView(id,new LinearLayout.LayoutParams(Ui.dp(this,38),Ui.dp(this,46)));r.addView(ip,new LinearLayout.LayoutParams(0,Ui.dp(this,46),1));r.addView(st,new LinearLayout.LayoutParams(Ui.dp(this,145),Ui.dp(this,46)));fields.add(ip);rows.add(st);col.addView(r);}
        LinearLayout ctrl=Ui.row(this);ctrl.addView(Ui.button(this,"Füzyon Başlat",Ui.GREEN,v->toggle()),Ui.weight(this));ctrl.addView(Ui.button(this,"Kalibre Et",Ui.YELLOW,v->calibrate()),Ui.weight(this));col.addView(ctrl);state=Ui.metric(this);metrics=Ui.metric(this);centroid=Ui.metric(this);col.addView(state);col.addView(metrics);col.addView(centroid);col.addView(Ui.note(this,"ESP32 endpoint: GET http://<yerel-ip>/api/status • kalibrasyon: POST /calibrate. Uygulama kamu IP adreslerine bağlanmayı reddeder."));root.addView(sv,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));setContentView(root);update();}

    private void toggle(){if(running){stop();return;}saveIps();int valid=0;for(int i=0;i<nodes.size();i++){nodes.get(i).ip=fields.get(i).getText().toString().trim();if(privateIp(nodes.get(i).ip))valid++;}if(valid==0){Toast.makeText(this,"En az bir yerel ESP32 IP adresi gir.",Toast.LENGTH_LONG).show();return;}running=true;main.post(loop);}
    private void stop(){running=false;main.removeCallbacks(loop);for(Node n:nodes)n.online=false;update();}
    private void saveIps(){android.content.SharedPreferences.Editor e=getPreferences(MODE_PRIVATE).edit();for(int i=0;i<fields.size();i++)e.putString("ip"+i,fields.get(i).getText().toString().trim());e.apply();}
    private void poll(Node n){if(!privateIp(n.ip)){n.online=false;return;}io.submit(()->{HttpURLConnection c=null;long t=System.currentTimeMillis();try{c=(HttpURLConnection)new URL("http://"+n.ip+"/api/status").openConnection();c.setConnectTimeout(700);c.setReadTimeout(850);c.setRequestProperty("Accept","application/json");int code=c.getResponseCode();if(code<200||code>=300)throw new Exception("HTTP "+code);BufferedInputStream in=new BufferedInputStream(c.getInputStream());ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]buf=new byte[2048];int k;while((k=in.read(buf))>0&&out.size()<32768)out.write(buf,0,k);JSONObject j=new JSONObject(out.toString(StandardCharsets.UTF_8.name()));n.e=clamp(j.optDouble("presence_evidence",j.optBoolean("presence",false)?.72:.22));n.i=clamp(j.optDouble("intensity",0));n.q=clamp(j.optDouble("quality",0));n.stability=clamp(j.optDouble("stability",.5));n.drift=clamp(j.optDouble("baseline_drift",0));n.ready=j.optBoolean("fusion_ready",true);n.rssi=j.optInt("rssi",-100);n.latency=System.currentTimeMillis()-t;n.lastRx=System.currentTimeMillis();n.online=true;}catch(Exception ex){if(System.currentTimeMillis()-n.lastRx>2800)n.online=false;}finally{if(c!=null)c.disconnect();}});}
    private void calibrate(){saveIps();int sent=0;for(int x=0;x<nodes.size();x++){Node n=nodes.get(x);n.ip=fields.get(x).getText().toString().trim();if(!privateIp(n.ip))continue;sent++;io.submit(()->{HttpURLConnection c=null;try{c=(HttpURLConnection)new URL("http://"+n.ip+"/calibrate").openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(700);c.setReadTimeout(800);c.getOutputStream().write(new byte[0]);c.getResponseCode();}catch(Exception ignored){}finally{if(c!=null)c.disconnect();}});}Toast.makeText(this,sent+" düğüme kalibrasyon gönderildi. Odayı 20 sn boş ve sabit tut.",Toast.LENGTH_LONG).show();}

    private void update(){Fusion f=fuse(System.currentTimeMillis());heat.setData(nodes,f);heat.invalidate();if(f.online==0){headline.setText("CSI düğümü bağlı değil");headline.setTextColor(Ui.MUTED);}else if(f.conf<.18){headline.setText("BELİRSİZ • DÜŞÜK GÜVEN");headline.setTextColor(Ui.YELLOW);}else if(f.p>.64){headline.setText("VARLIK KANITI YÜKSEK");headline.setTextColor(Ui.GREEN);}else if(f.p<.36){headline.setText("ODA BOŞA YAKIN");headline.setTextColor(Ui.CYAN);}else{headline.setText("BELİRSİZ RF BÖLGESİ");headline.setTextColor(Ui.YELLOW);}state.setText("Aktivite: "+hmm.update(f.p,f.intensity,f.conf));metrics.setText(String.format(Locale.US,"Varlık %d • yoğunluk %d • güven %d • uyum %d • kalite %d • online %d/4",(int)(100*f.p),(int)(100*f.intensity),(int)(100*f.conf),(int)(100*f.agree),(int)(100*f.meanQ),f.online));centroid.setText(f.centroid?String.format(Locale.US,"RF kanıt ağırlık merkezi x=%.2f y=%.2f • fiziksel kişi koordinatı değildir",f.cx,f.cy):"RF kanıt ağırlık merkezi: yetersiz kanıt");for(int i=0;i<nodes.size();i++){Node n=nodes.get(i);TextView v=rows.get(i);if(n.online){v.setText(String.format(Locale.US,"Q%d P%d I%d • %dms",(int)(100*n.q),(int)(100*n.e),(int)(100*n.i),n.latency));v.setTextColor(Ui.GREEN);}else{v.setText(n.ip.isEmpty()?"IP yok":"bağlantı yok");v.setTextColor(Ui.MUTED);}}}
    private Fusion fuse(long now){Fusion f=new Fusion();double log=Math.log(.25/.75),ws=0,is=0,qs=0,fr=0,mx=0,my=0,ms=0;ArrayList<Double>ps=new ArrayList<>(),ww=new ArrayList<>();for(Node n:nodes){double fresh=n.online?clamp(1-(now-n.lastRx)/3000.0):0;if(fresh<=0)continue;f.online++;double w=Math.max(.03,n.q)*fresh*(.65+.35*n.stability)*(1-.45*n.drift)*(n.ready?1:.55);double p=Math.max(.05,Math.min(.95,.05+.90*n.e));log+=w*Math.log(p/(1-p));ws+=w;is+=w*n.i;qs+=w*n.q;fr+=w*fresh;ps.add(p);ww.add(w);double sp=w*n.e*Math.max(.08,n.i);mx+=sp*n.x;my+=sp*n.y;ms+=sp;}f.p=1/(1+Math.exp(-log));f.intensity=ws>0?is/ws:0;f.meanQ=ws>0?qs/ws:0;f.fresh=ws>0?fr/ws:0;double mean=0,sw=0;for(int i=0;i<ps.size();i++){mean+=ps.get(i)*ww.get(i);sw+=ww.get(i);}mean=sw>0?mean/sw:.5;double var=0;for(int i=0;i<ps.size();i++)var+=ww.get(i)*(ps.get(i)-mean)*(ps.get(i)-mean);var=sw>0?var/sw:1;f.agree=clamp(1-Math.sqrt(var)/.45);f.conf=clamp(clamp(f.online/3.0)*f.meanQ*f.fresh*(.45+.55*f.agree));if(ms>.04){f.cx=mx/ms;f.cy=my/ms;f.centroid=true;}return f;}
    private boolean privateIp(String ip){if(ip==null||ip.isEmpty())return false;try{InetAddress a=InetAddress.getByName(ip);return a.isSiteLocalAddress()||a.isLinkLocalAddress()||a.isLoopbackAddress();}catch(Exception e){return false;}}
    @Override protected void onDestroy(){running=false;main.removeCallbacksAndMessages(null);io.shutdownNow();super.onDestroy();}
    private static double clamp(double x){return Math.max(0,Math.min(1,x));}
    private static final class Node{final String id;final double x,y;String ip="";volatile boolean online,ready=true;volatile double e,i,q,stability=.5,drift;volatile int rssi=-100;volatile long lastRx,latency;Node(String id,double x,double y){this.id=id;this.x=x;this.y=y;}}
    private static final class Fusion{double p,intensity,conf,agree,meanQ,fresh,cx=.5,cy=.5;int online;boolean centroid;}
    private static final class Hmm{private final String[]labels={"BOŞ","DURGUN VARLIK","HAFİF HAREKET","YÜRÜME BENZERİ","GÜÇLÜ HAREKET"};private double[]post={.7,.12,.08,.06,.04};private final double[][]T={{.92,.05,.02,.01,0},{.08,.82,.07,.025,.005},{.03,.08,.78,.09,.02},{.01,.03,.10,.79,.07},{.01,.01,.03,.10,.85}};String update(double p,double i,double c){if(c<.12)return"BELİRSİZ / DÜŞÜK KALİTE";double[]pred=new double[5];for(int b=0;b<5;b++)for(int a=0;a<5;a++)pred[b]+=post[a]*T[a][b];double[][]mu={{.12,.04},{.78,.08},{.80,.28},{.86,.56},{.90,.84}},sd={{.18,.10},{.22,.13},{.22,.16},{.20,.18},{.18,.16}};double sum=0;for(int k=0;k<5;k++){double zp=(p-mu[k][0])/sd[k][0],zi=(i-mu[k][1])/sd[k][1],e=Math.exp(-.5*(zp*zp+zi*zi));e=Math.pow(Math.max(1e-6,e),Math.max(.2,c));post[k]=pred[k]*e+1e-9;sum+=post[k];}int best=0;double bp=0;for(int k=0;k<5;k++){post[k]/=sum;if(post[k]>bp){bp=post[k];best=k;}}return bp<.43?"BELİRSİZ / SINIFLAR ÇAKIŞIYOR":labels[best]+String.format(Locale.US," • HMM %.0f%%",100*bp);}}
    private static final class HeatMapView extends View{private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private List<Node>n=new ArrayList<>();private Fusion f=new Fusion();HeatMapView(Context c){super(c);}void setData(List<Node>x,Fusion y){n=new ArrayList<>(x);f=y;}@Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),pad=36;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.rgb(28,70,82));for(int k=1;k<5;k++){float x=pad+(w-2*pad)*k/5f;c.drawLine(x,pad,x,h-pad,p);float y=pad+(h-2*pad)*k/5f;c.drawLine(pad,y,w-pad,y,p);}p.setStyle(Paint.Style.FILL);int gx=28,gy=20;float cw=(w-2*pad)/gx,ch=(h-2*pad)/gy;for(int yy=0;yy<gy;yy++)for(int xx=0;xx<gx;xx++){double nx=(xx+.5)/gx,ny=(yy+.5)/gy,s=0,norm=0;for(Node z:n){if(!z.online)continue;double d2=(nx-z.x)*(nx-z.x)+(ny-z.y)*(ny-z.y),g=Math.exp(-d2/.11),wt=Math.max(.04,z.q)*g;s+=wt*z.e*Math.max(.1,z.i);norm+=wt;}double v=norm>0?s/norm:0;int a=(int)(20+160*clamp(v)),r=(int)(32+220*clamp(v)),gg=(int)(210-130*clamp(v)),b=(int)(170-115*clamp(v));p.setColor(Color.argb(a,r,gg,b));c.drawRect(pad+xx*cw,pad+yy*ch,pad+(xx+1)*cw+1,pad+(yy+1)*ch+1,p);}for(Node z:n){float x=(float)(pad+z.x*(w-2*pad)),y=(float)(pad+z.y*(h-2*pad));p.setColor(z.online?Ui.GREEN:Color.GRAY);c.drawCircle(x,y,10,p);p.setColor(Ui.WHITE);p.setTextSize(21);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText(z.id,x+13,y+6,p);}if(f.centroid){float x=(float)(pad+f.cx*(w-2*pad)),y=(float)(pad+f.cy*(h-2*pad));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(Ui.YELLOW);c.drawCircle(x,y,17,p);c.drawCircle(x,y,28,p);p.setStyle(Paint.Style.FILL);}p.setColor(Ui.WHITE);p.setTextSize(23);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("RF KANIT HARİTASI",pad,28,p);}}
}
