package com.mg.structuralai;

import java.util.*;

/** Production loads/BC mapping: connected regions, per-patch directional supports, force/pressure/moment and acceleration body force. */
public final class AdvancedFemLoads {
    public static final class SupportPatch {
        public final MeshModel.V3 pick; public final boolean fixX,fixY,fixZ;
        public SupportPatch(MeshModel.V3 pick,boolean fixX,boolean fixY,boolean fixZ){if(pick==null)throw new IllegalArgumentException("Support patch pick missing");if(!fixX&&!fixY&&!fixZ)throw new IllegalArgumentException("Support patch needs at least one constrained DOF");this.pick=pick;this.fixX=fixX;this.fixY=fixY;this.fixZ=fixZ;}
        public String summary(){return "Ux="+(fixX?"0":"free")+" Uy="+(fixY?"0":"free")+" Uz="+(fixZ?"0":"free");}
    }
    public static final class Result {
        public int fixedNodes,fixedDofs,loadedNodes,pressureTriangles,supportRegions,loadRegions,rejectedOverlapNodes;
        public double patchRadiusM,resultantFx,resultantFy,resultantFz,resultantMx,resultantMy,resultantMz,gravityMassKg,selectedPressureAreaM2,accelX,accelY,accelZ;
        public int supportPatches; public String supportSummary="";
    }
    private AdvancedFemLoads(){}

    public static Result apply(StaticFemSolver solver,TetMeshData mesh,MeshModel surface,List<MeshModel.V3> supports,List<MeshModel.V3> loads,double unitScale,double fx,double fy,double fz,double pressurePa,boolean gravity,double densityKgM3){return apply(solver,mesh,surface,uniformPatches(supports,true,true,true),loads,unitScale,PhysicalLoadDefinition.legacy(fx,fy,fz,pressurePa,gravity),densityKgM3);}
    public static Result apply(StaticFemSolver solver,TetMeshData mesh,MeshModel surface,List<MeshModel.V3> supports,List<MeshModel.V3> loads,double unitScale,double fx,double fy,double fz,double pressurePa,boolean gravity,double densityKgM3,boolean fixX,boolean fixY,boolean fixZ){return apply(solver,mesh,surface,uniformPatches(supports,fixX,fixY,fixZ),loads,unitScale,PhysicalLoadDefinition.legacy(fx,fy,fz,pressurePa,gravity),densityKgM3);}
    public static Result apply(StaticFemSolver solver,TetMeshData mesh,MeshModel surface,Collection<SupportPatch> supportPatches,List<MeshModel.V3> loads,double unitScale,double fx,double fy,double fz,double pressurePa,boolean gravity,double densityKgM3){return apply(solver,mesh,surface,supportPatches,loads,unitScale,PhysicalLoadDefinition.legacy(fx,fy,fz,pressurePa,gravity),densityKgM3);}

    public static Result apply(StaticFemSolver solver,TetMeshData mesh,MeshModel surface,Collection<SupportPatch> supportPatches,List<MeshModel.V3> loads,double unitScale,PhysicalLoadDefinition load,double densityKgM3){
        if(supportPatches==null||supportPatches.isEmpty())throw new IllegalArgumentException("En az bir mesnet patch'i seçilmeli");if(load==null||!load.finite())throw new IllegalArgumentException("Geçerli fiziksel yük tanımı gerekli");
        Result r=new Result();double diag=diag(mesh);r.patchRadiusM=Math.max(diag*0.035,1e-9);r.supportPatches=supportPatches.size();Set<Integer> fixed=new LinkedHashSet<>();StringBuilder ss=new StringBuilder();int pi=0;
        for(SupportPatch patch:supportPatches){SurfaceRegionExtractor.Region reg=SurfaceRegionExtractor.fromPick(surface,patch.pick,38.0);r.supportRegions++;Set<Integer> nodes=mapRegionsToVolumeNodes(mesh,surface,Collections.singletonList(reg),unitScale,r.patchRadiusM);if(nodes.isEmpty())throw new IllegalStateException("Mesnet patch volumetrik düğümlere eşlenemedi: "+(pi+1));for(int n:nodes){if(patch.fixX){solver.fixDof(3*n);r.fixedDofs++;}if(patch.fixY){solver.fixDof(3*n+1);r.fixedDofs++;}if(patch.fixZ){solver.fixDof(3*n+2);r.fixedDofs++;}fixed.add(n);}if(pi>0)ss.append(" | ");ss.append("P").append(pi+1).append("[").append(patch.summary()).append("] nodes=").append(nodes.size());pi++;}
        if(fixed.size()<3)throw new IllegalStateException("Mesnet patch'leri yeterli volumetrik düğüme eşlenemedi");r.fixedNodes=fixed.size();r.supportSummary=ss.toString();
        List<SurfaceRegionExtractor.Region> loadRegs=(loads==null)?Collections.emptyList():regions(surface,loads,38.0);r.loadRegions=loadRegs.size();Set<Integer> loaded=mapRegionsToVolumeNodes(mesh,surface,loadRegs,unitScale,r.patchRadiusM);int before=loaded.size();loaded.removeAll(fixed);r.rejectedOverlapNodes=before-loaded.size();
        if(load.hasForce()){if(loaded.isEmpty())throw new IllegalStateException("Kuvvet bölgesi mesnetlerle çakıştı veya volumetrik düğümlere eşlenemedi");double inv=1.0/loaded.size();for(int n:loaded)solver.addNodalForce(n,load.fx*inv,load.fy*inv,load.fz*inv);r.resultantFx+=load.fx;r.resultantFy+=load.fy;r.resultantFz+=load.fz;}
        if(load.hasPressure()){if(loadRegs.isEmpty())throw new IllegalArgumentException("Basınç için bağlı yüzey seçilmeli");applyPressure(solver,mesh,surface,loadRegs,unitScale,r.patchRadiusM,load.pressurePa,loaded,fixed,r);}
        if(load.hasMoment()){if(loaded.size()<3)throw new IllegalStateException("Moment için en az 3 serbest yük düğümü gerekli");applyMoment(solver,mesh,loaded,load.mx,load.my,load.mz,r);}
        r.loadedNodes=loaded.size();if(load.hasAcceleration())applyAcceleration(solver,mesh,densityKgM3,load.ax,load.ay,load.az,r);return r;
    }

    private static List<SupportPatch> uniformPatches(List<MeshModel.V3> supports,boolean x,boolean y,boolean z){List<SupportPatch> out=new ArrayList<>();if(supports!=null)for(MeshModel.V3 p:supports)out.add(new SupportPatch(p,x,y,z));return out;}
    private static List<SurfaceRegionExtractor.Region> regions(MeshModel s,List<MeshModel.V3> picks,double angle){List<SurfaceRegionExtractor.Region> out=new ArrayList<>();Set<Integer> covered=new HashSet<>();for(MeshModel.V3 p:picks){SurfaceRegionExtractor.Region rr=SurfaceRegionExtractor.fromPick(s,p,angle);boolean duplicate=false;for(int ti:rr.triangles)if(covered.contains(ti)){duplicate=true;break;}if(!duplicate){out.add(rr);covered.addAll(rr.triangles);}}return out;}
    private static Set<Integer> mapRegionsToVolumeNodes(TetMeshData mesh,MeshModel s,List<SurfaceRegionExtractor.Region> regs,double scale,double tol){Set<Integer> out=new LinkedHashSet<>();if(regs==null)return out;for(SurfaceRegionExtractor.Region rr:regs){for(int vi:rr.vertices){MeshModel.V3 p=si(s.vertices.get(vi),scale);out.addAll(nearOrNearest(mesh,p,tol,2));}if(!rr.vertices.isEmpty()){double x=0,y=0,z=0;for(int vi:rr.vertices){MeshModel.V3 q=s.vertices.get(vi);x+=q.x;y+=q.y;z+=q.z;}double n=rr.vertices.size();out.addAll(nearOrNearest(mesh,si(new MeshModel.V3(x/n,y/n,z/n),scale),tol,3));}}return out;}
    private static void applyPressure(StaticFemSolver solver,TetMeshData mesh,MeshModel s,List<SurfaceRegionExtractor.Region> regs,double scale,double tol,double pressurePa,Set<Integer> loaded,Set<Integer> fixed,Result out){Set<Integer> tris=new LinkedHashSet<>();for(SurfaceRegionExtractor.Region rr:regs)tris.addAll(rr.triangles);for(int ti:tris){int[] t=s.triangles.get(ti);if(t.length<3)continue;MeshModel.V3 a=s.vertices.get(t[0]),b=s.vertices.get(t[1]),c=s.vertices.get(t[2]);double ux=b.x-a.x,uy=b.y-a.y,uz=b.z-a.z,vx=c.x-a.x,vy=c.y-a.y,vz=c.z-a.z;double nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,mag=Math.sqrt(nx*nx+ny*ny+nz*nz);if(mag<=1e-20)continue;double areaM2=0.5*mag*scale*scale;out.selectedPressureAreaM2+=areaM2;double f=-pressurePa*areaM2,fx=f*nx/mag,fy=f*ny/mag,fz=f*nz/mag;MeshModel.V3 cent=si(new MeshModel.V3((a.x+b.x+c.x)/3,(a.y+b.y+c.y)/3,(a.z+b.z+c.z)/3),scale);List<Integer> ns=nearOrNearest(mesh,cent,tol,3);ns.removeIf(fixed::contains);if(ns.isEmpty())continue;double inv=1.0/ns.size();for(int n:ns){solver.addNodalForce(n,fx*inv,fy*inv,fz*inv);loaded.add(n);}out.resultantFx+=fx;out.resultantFy+=fy;out.resultantFz+=fz;out.pressureTriangles++;}if(out.pressureTriangles==0)throw new IllegalStateException("Seçilen bağlı yüzeyde basınç uygulanabilir üçgen bulunamadı veya yük düğümleri mesnetlerle çakıştı");}

    /** Equivalent nodal force couple: f_i = q × r_i, with J q = M and sum(r_i)=0. This gives zero resultant force and requested resultant moment. */
    private static void applyMoment(StaticFemSolver solver,TetMeshData mesh,Set<Integer> nodes,double mx,double my,double mz,Result out){double cx=0,cy=0,cz=0;for(int n:nodes){MeshModel.V3 p=mesh.nodes.get(n);cx+=p.x;cy+=p.y;cz+=p.z;}double inv=1.0/nodes.size();cx*=inv;cy*=inv;cz*=inv;double jxx=0,jyy=0,jzz=0,jxy=0,jxz=0,jyz=0;for(int n:nodes){MeshModel.V3 p=mesh.nodes.get(n);double x=p.x-cx,y=p.y-cy,z=p.z-cz;jxx+=y*y+z*z;jyy+=x*x+z*z;jzz+=x*x+y*y;jxy-=x*y;jxz-=x*z;jyz-=y*z;}double[] q=solve3(jxx,jxy,jxz,jxy,jyy,jyz,jxz,jyz,jzz,mx,my,mz);double sfx=0,sfy=0,sfz=0,smx=0,smy=0,smz=0;for(int n:nodes){MeshModel.V3 p=mesh.nodes.get(n);double x=p.x-cx,y=p.y-cy,z=p.z-cz;double fx=q[1]*z-q[2]*y,fy=q[2]*x-q[0]*z,fz=q[0]*y-q[1]*x;solver.addNodalForce(n,fx,fy,fz);sfx+=fx;sfy+=fy;sfz+=fz;smx+=y*fz-z*fy;smy+=z*fx-x*fz;smz+=x*fy-y*fx;}double fLeak=Math.sqrt(sfx*sfx+sfy*sfy+sfz*sfz),mMag=Math.max(Math.sqrt(mx*mx+my*my+mz*mz),1e-30);double mErr=Math.sqrt(sq(smx-mx)+sq(smy-my)+sq(smz-mz))/mMag;if(fLeak>Math.max(1e-8,mMag*1e-8)||mErr>1e-8)throw new IllegalStateException("Moment eşdeğer kuvvet dağılımı toleransı aşildi: forceLeak="+fLeak+" momentRelErr="+mErr);out.resultantMx+=smx;out.resultantMy+=smy;out.resultantMz+=smz;}

    private static double[] solve3(double a00,double a01,double a02,double a10,double a11,double a12,double a20,double a21,double a22,double b0,double b1,double b2){double det=a00*(a11*a22-a12*a21)-a01*(a10*a22-a12*a20)+a02*(a10*a21-a11*a20);double scale=Math.max(Math.max(Math.abs(a00),Math.abs(a11)),Math.abs(a22));if(!Double.isFinite(det)||Math.abs(det)<=Math.max(1e-30,scale*scale*scale*1e-12))throw new IllegalStateException("Moment yük bölgesi geometrik olarak tekil; daha geniş/2B yüzey seç");double d0=b0*(a11*a22-a12*a21)-a01*(b1*a22-a12*b2)+a02*(b1*a21-a11*b2);double d1=a00*(b1*a22-a12*b2)-b0*(a10*a22-a12*a20)+a02*(a10*b2-b1*a20);double d2=a00*(a11*b2-b1*a21)-a01*(a10*b2-b1*a20)+b0*(a10*a21-a11*a20);return new double[]{d0/det,d1/det,d2/det};}

    private static void applyAcceleration(StaticFemSolver solver,TetMeshData mesh,double rho,double ax,double ay,double az,Result out){if(!(rho>0&&Double.isFinite(rho)))throw new IllegalArgumentException("İvme/gravity için pozitif yoğunluk gerekli");double total=0;for(int[] t:mesh.tets){MeshModel.V3 a=mesh.nodes.get(t[0]),b=mesh.nodes.get(t[1]),c=mesh.nodes.get(t[2]),d=mesh.nodes.get(t[3]);double v=Math.abs(volume6(a,b,c,d))/6.0,m=rho*v,share=m/4.0;for(int n:t)solver.addNodalForce(n,share*ax,share*ay,share*az);total+=m;}out.gravityMassKg=total;out.accelX=ax;out.accelY=ay;out.accelZ=az;out.resultantFx+=total*ax;out.resultantFy+=total*ay;out.resultantFz+=total*az;}
    private static double volume6(MeshModel.V3 a,MeshModel.V3 b,MeshModel.V3 c,MeshModel.V3 d){return (b.x-a.x)*((c.y-a.y)*(d.z-a.z)-(c.z-a.z)*(d.y-a.y))-(b.y-a.y)*((c.x-a.x)*(d.z-a.z)-(c.z-a.z)*(d.x-a.x))+(b.z-a.z)*((c.x-a.x)*(d.y-a.y)-(c.y-a.y)*(d.x-a.x));}
    private static MeshModel.V3 si(MeshModel.V3 p,double s){return new MeshModel.V3(p.x*s,p.y*s,p.z*s);}
    private static double diag(TetMeshData m){double x0=1e99,y0=1e99,z0=1e99,x1=-1e99,y1=-1e99,z1=-1e99;for(MeshModel.V3 n:m.nodes){x0=Math.min(x0,n.x);x1=Math.max(x1,n.x);y0=Math.min(y0,n.y);y1=Math.max(y1,n.y);z0=Math.min(z0,n.z);z1=Math.max(z1,n.z);}return Math.sqrt(sq(x1-x0)+sq(y1-y0)+sq(z1-z0));}
    private static List<Integer> nearOrNearest(TetMeshData m,MeshModel.V3 p,double r,int fallback){List<Integer> o=new ArrayList<>();double r2=r*r;for(int i=0;i<m.nodes.size();i++){MeshModel.V3 n=m.nodes.get(i);if(sq(n.x-p.x)+sq(n.y-p.y)+sq(n.z-p.z)<=r2)o.add(i);}if(!o.isEmpty())return o;boolean[] used=new boolean[m.nodes.size()];for(int k=0;k<Math.min(fallback,m.nodes.size());k++){int bi=-1;double bd=1e300;for(int i=0;i<m.nodes.size();i++)if(!used[i]){MeshModel.V3 n=m.nodes.get(i);double d=sq(n.x-p.x)+sq(n.y-p.y)+sq(n.z-p.z);if(d<bd){bd=d;bi=i;}}if(bi>=0){used[bi]=true;o.add(bi);}}return o;}
    private static double sq(double x){return x*x;}
}
