package com.mg.structuralai;

import android.app.Activity;
import android.content.Intent;
import android.database.Cursor;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.provider.OpenableColumns;
import android.view.Gravity;
import android.widget.*;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** v1.0 candidate: connected surface BC/load + 3-level mesh convergence + real static FEM. */
public class MainActivity extends Activity {
    private static final int PICK_MODEL=1001;
    private final ExecutorService executor=Executors.newSingleThreadExecutor();
    private TextView status,report,modeBadge; private Spinner unitSpinner,axisSpinner,loadTypeSpinner;
    private EditText loadInput,pressureInput,eInput,nuInput,yieldInput,densityInput; private CheckBox gravityBox;
    private InteractiveModelView viewport; private MeshModel currentModel; private VoxelTetMesher.Result currentMesh; private String currentName="model";
    private final List<MeshModel.V3> supports=new ArrayList<>(),loads=new ArrayList<>();

    @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18);root.setBackgroundColor(Color.rgb(10,22,38));
        TextView title=new TextView(this);title.setText("STRUCTURAL AI STATIC");title.setTextColor(Color.WHITE);title.setTextSize(23);title.setGravity(Gravity.CENTER_HORIZONTAL);root.addView(title);
        TextView sub=new TextView(this);sub.setText("v1.0 RC • CONNECTED SURFACES • 3-LEVEL CONVERGENCE • REAL FEM");sub.setTextColor(Color.LTGRAY);sub.setTextSize(12);sub.setGravity(Gravity.CENTER_HORIZONTAL);root.addView(sub);
        modeBadge=new TextView(this);modeBadge.setText("MOD: HAZIR");modeBadge.setTextColor(Color.WHITE);modeBadge.setGravity(Gravity.CENTER);modeBadge.setBackgroundColor(Color.rgb(70,70,78));modeBadge.setPadding(10,7,10,7);root.addView(modeBadge,new LinearLayout.LayoutParams(-1,-2));

        viewport=new InteractiveModelView(this);viewport.setPickListener((p,idx)->{if(viewport.getPickMode()==InteractiveModelView.PickMode.SUPPORT){supports.add(p);viewport.addSupportPoint(p);status.setText("Mesnet yüzeyi eklendi • toplam "+supports.size());}else if(viewport.getPickMode()==InteractiveModelView.PickMode.LOAD){loads.add(p);viewport.addLoadPoint(p);status.setText("Yük/basınç yüzeyi eklendi • toplam "+loads.size());}});root.addView(viewport,new LinearLayout.LayoutParams(-1,390));

        LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);Button s=new Button(this);s.setText("+ MESNET");s.setOnClickListener(v->{viewport.setPickMode(InteractiveModelView.PickMode.SUPPORT);status.setText("Bağlı mesnet yüzeyine dokun");});Button l=new Button(this);l.setText("+ YÜK");l.setOnClickListener(v->{viewport.setPickMode(InteractiveModelView.PickMode.LOAD);status.setText("Bağlı yük/basınç yüzeyine dokun");});Button clear=new Button(this);clear.setText("TEMİZLE");clear.setOnClickListener(v->{supports.clear();loads.clear();viewport.clearSupportPoints();viewport.clearLoadPoints();viewport.setPickMode(InteractiveModelView.PickMode.NONE);status.setText("Seçimler temizlendi");});a.addView(s,new LinearLayout.LayoutParams(0,-2,1));a.addView(l,new LinearLayout.LayoutParams(0,-2,1));a.addView(clear,new LinearLayout.LayoutParams(0,-2,1));root.addView(a);

        LinearLayout cfg=new LinearLayout(this);cfg.setOrientation(LinearLayout.HORIZONTAL);unitSpinner=spin(new String[]{"mm","m","cm","in"});axisSpinner=spin(new String[]{"-Z","+Z","-Y","+Y","-X","+X"});loadTypeSpinner=spin(new String[]{"FORCE","PRESSURE","FORCE + PRESSURE"});cfg.addView(box("Birim",unitSpinner),new LinearLayout.LayoutParams(0,-2,1));cfg.addView(box("Kuvvet yönü",axisSpinner),new LinearLayout.LayoutParams(0,-2,1));cfg.addView(box("Yük tipi",loadTypeSpinner),new LinearLayout.LayoutParams(0,-2,1));root.addView(cfg);
        LinearLayout r1=new LinearLayout(this);r1.setOrientation(LinearLayout.HORIZONTAL);loadInput=field("1000");pressureInput=field("0");densityInput=field("7850");r1.addView(box("Kuvvet [N]",loadInput),new LinearLayout.LayoutParams(0,-2,1));r1.addView(box("Basınç [MPa]",pressureInput),new LinearLayout.LayoutParams(0,-2,1));r1.addView(box("ρ [kg/m³]",densityInput),new LinearLayout.LayoutParams(0,-2,1));root.addView(r1);
        LinearLayout r2=new LinearLayout(this);r2.setOrientation(LinearLayout.HORIZONTAL);eInput=field("210");nuInput=field("0.30");yieldInput=field("355");r2.addView(box("E [GPa]",eInput),new LinearLayout.LayoutParams(0,-2,1));r2.addView(box("ν",nuInput),new LinearLayout.LayoutParams(0,-2,1));r2.addView(box("Akma [MPa]",yieldInput),new LinearLayout.LayoutParams(0,-2,1));root.addView(r2);
        gravityBox=new CheckBox(this);gravityBox.setText("Gravity -Z 9.80665 m/s²");gravityBox.setTextColor(Color.WHITE);root.addView(gravityBox);

        Button loadModel=new Button(this);loadModel.setText("MODEL YÜKLE + MESH QA");loadModel.setOnClickListener(v->pickModel());root.addView(loadModel);
        Button solve=new Button(this);solve.setText("GERÇEK FEM + MESH CONVERGENCE ÇALIŞTIR");solve.setOnClickListener(v->solvePicked());root.addView(solve);
        status=new TextView(this);status.setText("Hazır — OBJ / ASCII STL / Binary STL");status.setTextColor(Color.rgb(120,220,190));status.setPadding(0,6,0,4);root.addView(status);
        ScrollView scroll=new ScrollView(this);report=new TextView(this);report.setTextColor(Color.WHITE);report.setTextSize(12);report.setTextIsSelectable(true);report.setText("v1.0 RC ANALİZ KAPISI\n\n1) Closed/manifold geometry\n2) Connected surface BC/load extraction\n3) TET4 mesh QA\n4) 8/12/16 h-refinement study\n5) Sparse PCG + residual\n6) Force equilibrium\n7) Von Mises + displacement + FoS\n8) Mesh convergence: ΔU ≤ %5, Δσvm ≤ %10\n\nYakınsama geçmezse genel ANALYSIS READY verilmez.");scroll.addView(report);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private Spinner spin(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
    private TextView label(String x){TextView v=new TextView(this);v.setText(x);v.setTextColor(Color.LTGRAY);v.setTextSize(10);return v;}
    private EditText field(String x){EditText e=new EditText(this);e.setText(x);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);return e;}
    private LinearLayout box(String t,android.view.View v){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(3,0,3,0);b.addView(label(t));b.addView(v);return b;}
    private double parse(EditText e,String n){try{return Double.parseDouble(e.getText().toString().trim());}catch(Exception x){throw new IllegalArgumentException(n+" sayısal olmalı");}}
    private void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"model/obj","application/sla","application/octet-stream","text/plain"});startActivityForResult(i,PICK_MODEL);}

    @Override protected void onActivityResult(int rq,int rc,Intent data){super.onActivityResult(rq,rc,data);if(rq!=PICK_MODEL||rc!=RESULT_OK||data==null)return;Uri uri=data.getData();if(uri==null)return;currentName=getName(uri);supports.clear();loads.clear();final double scale=AutoFemSetup.unitScaleToMetres((String)unitSpinner.getSelectedItem());status.setText("Model → topology → mesh QA: "+currentName);modeBadge.setText("MOD: MESH QA");
        executor.submit(()->{try(InputStream in=getContentResolver().openInputStream(uri)){MeshModel m=MeshParser.parse(currentName,in);SurfaceTopologyReport topo=SurfaceTopologyReport.evaluate(m);if(!topo.closedManifold)throw new IllegalStateException("Kapalı/manifold değil: "+topo.summary());VoxelTetMesher.Result mr=VoxelTetMesher.generate(m,12,scale);if(!mr.quality.pass)throw new IllegalStateException("Mesh QA: "+mr.quality.summary());currentModel=m;currentMesh=mr;runOnUiThread(()->{viewport.setModel(m);status.setText("Model hazır — bağlı mesnet ve yük yüzeylerini seç");modeBadge.setText("MOD: READY • PICK CONNECTED SURFACES");modeBadge.setBackgroundColor(Color.rgb(20,115,105));report.setText("MODEL READY\n\n"+currentName+"\n"+topo.summary()+"\nPreview nodes: "+mr.mesh.nodes.size()+"\nPreview TET4: "+mr.mesh.tets.size()+"\n"+mr.quality.summary()+"\n\nBir yüzeye dokunulduğunda paylaşılan kenarlar ve normal sürekliliği ile bağlı yüzey bölgesi çıkarılır.");});}catch(Exception e){runOnUiThread(()->{status.setText("Model/mesh bloke edildi");modeBadge.setText("MOD: QA BLOCKED");modeBadge.setBackgroundColor(Color.rgb(150,45,45));report.setText("Hata: "+e.getMessage());});}});}

    private void solvePicked(){if(currentModel==null||currentMesh==null){status.setText("Önce model yükle");return;}if(supports.isEmpty()){status.setText("En az bir mesnet yüzeyi seç");return;}final double force,pressureMPa,eGPa,nu,yieldMPa,rho;try{force=parse(loadInput,"Kuvvet");pressureMPa=parse(pressureInput,"Basınç");eGPa=parse(eInput,"E");nu=parse(nuInput,"Poisson");yieldMPa=parse(yieldInput,"Akma");rho=parse(densityInput,"Yoğunluk");}catch(Exception e){status.setText(e.getMessage());return;}String type=(String)loadTypeSpinner.getSelectedItem();boolean useForce=type.contains("FORCE"),usePressure=type.contains("PRESSURE");if((useForce||usePressure)&&loads.isEmpty()){status.setText("Yük/basınç için en az bir yüzey seç");return;}final String axis=(String)axisSpinner.getSelectedItem();final double scale=AutoFemSetup.unitScaleToMetres((String)unitSpinner.getSelectedItem());modeBadge.setText("MOD: 3-LEVEL FEM SOLVING");status.setText("8/12/16 mesh seviyeleri çözülüyor…");
        executor.submit(()->{try{LinearElasticMaterial mat=new LinearElasticMaterial("User isotropic",eGPa*1e9,nu,rho,yieldMPa*1e6);double fx=0,fy=0,fz=0;if(useForce){if(axis.equals("-Z"))fz=-force;else if(axis.equals("+Z"))fz=force;else if(axis.equals("-Y"))fy=-force;else if(axis.equals("+Y"))fy=force;else if(axis.equals("-X"))fx=-force;else fx=force;}double pPa=usePressure?pressureMPa*1e6:0;
            MeshConvergenceStudy.Result cv=MeshConvergenceStudy.run(currentModel,scale,mat,supports,loads,fx,fy,fz,pPa,gravityBox.isChecked(),rho);MeshConvergenceStudy.Level f=cv.fine;double fos=f.fem.maxVonMisesPa>0?mat.yieldPa/f.fem.maxVonMisesPa:Double.POSITIVE_INFINITY;boolean numerical=f.fem.linearSolve.converged&&f.fem.forceEquilibriumRelativeError<1e-5&&Double.isFinite(f.fem.maxVonMisesPa)&&Double.isFinite(f.fem.maxDisplacementM);boolean ready=numerical&&cv.converged;
            String txt=String.format(Locale.US,"REAL STATIC FEM • CONVERGENCE GATED\n\nModel: %s\nConnected support regions: %d • fixed nodes: %d\nConnected load regions: %d • loaded nodes: %d\nPressure area: %.6g m² • pressure triangles: %d\nGravity mass: %.6g kg\nResultant load: [%.5g, %.5g, %.5g] N\n\nMESH CONVERGENCE\n8 cells:  nodes %d • TET4 %d • Umax %.6g mm • σvm %.6g MPa\n12 cells: nodes %d • TET4 %d • Umax %.6g mm • σvm %.6g MPa\n16 cells: nodes %d • TET4 %d • Umax %.6g mm • σvm %.6g MPa\nΔU(12→16): %.2f %%\nΔσvm(12→16): %.2f %%\nConverged: %s\n\nFINE SOLVER\nPCG: %s • iter %d\nResidual: %.3e\nForce equilibrium error: %.3e\n\nMax displacement: %.6g mm\nMax Von Mises: %.6g MPa\nYield FoS: %.4f\n\nANALYSIS READY GATE: %s\n\nNot: Bu gate numerik ilk analiz yeterliliğini gösterir; malzeme, gerçek fikstür/yük büyüklüğü ve fiziksel sınır şartlarının mühendislik doğrulaması yine gereklidir.",currentName,f.setup.supportRegions,f.setup.fixedNodes,f.setup.loadRegions,f.setup.loadedNodes,f.setup.selectedPressureAreaM2,f.setup.pressureTriangles,f.setup.gravityMassKg,f.setup.resultantFx,f.setup.resultantFy,f.setup.resultantFz,cv.coarse.nodes,cv.coarse.tets,cv.coarse.fem.maxDisplacementM*1000,cv.coarse.fem.maxVonMisesPa/1e6,cv.medium.nodes,cv.medium.tets,cv.medium.fem.maxDisplacementM*1000,cv.medium.fem.maxVonMisesPa/1e6,cv.fine.nodes,cv.fine.tets,cv.fine.fem.maxDisplacementM*1000,cv.fine.fem.maxVonMisesPa/1e6,cv.displacementChange*100,cv.stressChange*100,cv.converged,f.fem.linearSolve.converged,f.fem.linearSolve.iterations,f.fem.linearSolve.relativeResidual,f.fem.forceEquilibriumRelativeError,f.fem.maxDisplacementM*1000,f.fem.maxVonMisesPa/1e6,fos,ready?"PASS":"BLOCKED");
            runOnUiThread(()->{viewport.setResult(f.mesh,f.fem);status.setText(ready?"İlk analiz kapısı GEÇTİ • converged FEM":"Analiz kapısı bloke • convergence/QA incele");modeBadge.setText(ready?"MOD: ANALYSIS READY • CONVERGED":"MOD: ANALYSIS QA BLOCKED");modeBadge.setBackgroundColor(ready?Color.rgb(20,125,70):Color.rgb(150,45,45));report.setText(txt);});
        }catch(Exception e){runOnUiThread(()->{status.setText("FEM/convergence çözülemedi");modeBadge.setText("MOD: ANALYSIS ERROR");modeBadge.setBackgroundColor(Color.rgb(150,45,45));report.setText("Hata: "+e.getMessage());});}});}

    private String getName(Uri uri){String n="model";Cursor c=getContentResolver().query(uri,null,null,null,null);if(c!=null){try{int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0)n=c.getString(i);}finally{c.close();}}return n;}
    @Override protected void onDestroy(){super.onDestroy();executor.shutdownNow();}
}
