package com.mg.structuralai;

import android.app.Activity;
import android.content.Intent;
import android.database.Cursor;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.provider.OpenableColumns;
import android.view.Gravity;
import android.widget.*;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** v0.9: multi-patch BC/load, force or pressure, gravity and deformed FEM contour. */
public class MainActivity extends Activity {
    private static final int PICK_MODEL=1001;
    private final ExecutorService executor=Executors.newSingleThreadExecutor();
    private TextView status,report,modeBadge; private Spinner unitSpinner,axisSpinner,loadTypeSpinner;
    private EditText loadInput,pressureInput,eInput,nuInput,yieldInput,densityInput; private CheckBox gravityBox;
    private InteractiveModelView viewport; private MeshModel currentModel; private VoxelTetMesher.Result currentMesh; private String currentName="model";
    private final List<MeshModel.V3> supports=new ArrayList<>(),loads=new ArrayList<>();

    @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18);root.setBackgroundColor(Color.rgb(10,22,38));
        TextView title=new TextView(this);title.setText("STRUCTURAL AI STATIC");title.setTextColor(Color.WHITE);title.setTextSize(23);title.setGravity(Gravity.CENTER_HORIZONTAL);root.addView(title);
        TextView sub=new TextView(this);sub.setText("v0.9 • MULTI-SURFACE BC/LOAD • PRESSURE • GRAVITY • DEFORMED FEM");sub.setTextColor(Color.LTGRAY);sub.setTextSize(12);sub.setGravity(Gravity.CENTER_HORIZONTAL);root.addView(sub);
        modeBadge=new TextView(this);modeBadge.setText("MOD: HAZIR");modeBadge.setTextColor(Color.WHITE);modeBadge.setGravity(Gravity.CENTER);modeBadge.setBackgroundColor(Color.rgb(70,70,78));modeBadge.setPadding(10,7,10,7);root.addView(modeBadge,new LinearLayout.LayoutParams(-1,-2));

        viewport=new InteractiveModelView(this);viewport.setPickListener((p,idx)->{if(viewport.getPickMode()==InteractiveModelView.PickMode.SUPPORT){supports.add(p);viewport.addSupportPoint(p);status.setText("Mesnet patch eklendi • toplam "+supports.size());}else if(viewport.getPickMode()==InteractiveModelView.PickMode.LOAD){loads.add(p);viewport.addLoadPoint(p);status.setText("Yük/basınç patch eklendi • toplam "+loads.size());}});root.addView(viewport,new LinearLayout.LayoutParams(-1,390));

        LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);Button s=new Button(this);s.setText("+ MESNET");s.setOnClickListener(v->{viewport.setPickMode(InteractiveModelView.PickMode.SUPPORT);status.setText("Mesnet yüzeyine dokun; tekrar dokunarak patch ekleyebilirsin");});Button l=new Button(this);l.setText("+ YÜK");l.setOnClickListener(v->{viewport.setPickMode(InteractiveModelView.PickMode.LOAD);status.setText("Yük/basınç yüzeyine dokun; çoklu patch eklenebilir");});Button clear=new Button(this);clear.setText("TEMİZLE");clear.setOnClickListener(v->{supports.clear();loads.clear();viewport.clearSupportPoints();viewport.clearLoadPoints();viewport.setPickMode(InteractiveModelView.PickMode.NONE);status.setText("Seçimler temizlendi");});a.addView(s,new LinearLayout.LayoutParams(0,-2,1));a.addView(l,new LinearLayout.LayoutParams(0,-2,1));a.addView(clear,new LinearLayout.LayoutParams(0,-2,1));root.addView(a);

        LinearLayout cfg=new LinearLayout(this);cfg.setOrientation(LinearLayout.HORIZONTAL);unitSpinner=spin(new String[]{"mm","m","cm","in"});axisSpinner=spin(new String[]{"-Z","+Z","-Y","+Y","-X","+X"});loadTypeSpinner=spin(new String[]{"FORCE","PRESSURE","FORCE + PRESSURE"});cfg.addView(box("Birim",unitSpinner),new LinearLayout.LayoutParams(0,-2,1));cfg.addView(box("Kuvvet yönü",axisSpinner),new LinearLayout.LayoutParams(0,-2,1));cfg.addView(box("Yük tipi",loadTypeSpinner),new LinearLayout.LayoutParams(0,-2,1));root.addView(cfg);
        LinearLayout r1=new LinearLayout(this);r1.setOrientation(LinearLayout.HORIZONTAL);loadInput=field("1000");pressureInput=field("0");densityInput=field("7850");r1.addView(box("Kuvvet [N]",loadInput),new LinearLayout.LayoutParams(0,-2,1));r1.addView(box("Basınç [MPa]",pressureInput),new LinearLayout.LayoutParams(0,-2,1));r1.addView(box("ρ [kg/m³]",densityInput),new LinearLayout.LayoutParams(0,-2,1));root.addView(r1);
        LinearLayout r2=new LinearLayout(this);r2.setOrientation(LinearLayout.HORIZONTAL);eInput=field("210");nuInput=field("0.30");yieldInput=field("355");r2.addView(box("E [GPa]",eInput),new LinearLayout.LayoutParams(0,-2,1));r2.addView(box("ν",nuInput),new LinearLayout.LayoutParams(0,-2,1));r2.addView(box("Akma [MPa]",yieldInput),new LinearLayout.LayoutParams(0,-2,1));root.addView(r2);
        gravityBox=new CheckBox(this);gravityBox.setText("Gravity -Z 9.80665 m/s²");gravityBox.setTextColor(Color.WHITE);root.addView(gravityBox);

        Button loadModel=new Button(this);loadModel.setText("MODEL YÜKLE + MESH HAZIRLA");loadModel.setOnClickListener(v->pickModel());root.addView(loadModel);
        Button solve=new Button(this);solve.setText("SEÇİMLERLE GERÇEK FEM ÇÖZ");solve.setOnClickListener(v->solvePicked());root.addView(solve);
        status=new TextView(this);status.setText("Hazır — OBJ / ASCII STL / Binary STL");status.setTextColor(Color.rgb(120,220,190));status.setPadding(0,6,0,4);root.addView(status);
        ScrollView scroll=new ScrollView(this);report=new TextView(this);report.setTextColor(Color.WHITE);report.setTextSize(12);report.setTextIsSelectable(true);report.setText("v0.9 AKIŞ\n\nModel → closed/manifold QA → TET4 mesh QA → çoklu mesnet patch → çoklu kuvvet/basınç patch → gravity opsiyonu → sparse PCG → Von Mises/deplasman/FoS/denge → deforme kontur.\n\nBasınç, seçilen kaynak yüzey üçgenlerinin alan ve normalinden eşdeğer düğüm yüküne dönüştürülür. STL yüzey normal yönü hatalıysa basınç yönü de hatalı olabilir; sonuç raporunda bu varsayım izlenir.");scroll.addView(report);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private Spinner spin(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
    private TextView label(String x){TextView v=new TextView(this);v.setText(x);v.setTextColor(Color.LTGRAY);v.setTextSize(10);return v;}
    private EditText field(String x){EditText e=new EditText(this);e.setText(x);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);return e;}
    private LinearLayout box(String t,android.view.View v){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(3,0,3,0);b.addView(label(t));b.addView(v);return b;}
    private double parse(EditText e,String n){try{return Double.parseDouble(e.getText().toString().trim());}catch(Exception x){throw new IllegalArgumentException(n+" sayısal olmalı");}}
    private void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"model/obj","application/sla","application/octet-stream","text/plain"});startActivityForResult(i,PICK_MODEL);}

    @Override protected void onActivityResult(int rq,int rc,Intent data){super.onActivityResult(rq,rc,data);if(rq!=PICK_MODEL||rc!=RESULT_OK||data==null)return;Uri uri=data.getData();if(uri==null)return;currentName=getName(uri);supports.clear();loads.clear();final double scale=AutoFemSetup.unitScaleToMetres((String)unitSpinner.getSelectedItem());status.setText("Model → topology → mesh: "+currentName);modeBadge.setText("MOD: MESH QA");
        executor.submit(()->{try(InputStream in=getContentResolver().openInputStream(uri)){MeshModel m=MeshParser.parse(currentName,in);SurfaceTopologyReport topo=SurfaceTopologyReport.evaluate(m);if(!topo.closedManifold)throw new IllegalStateException("Kapalı/manifold değil: "+topo.summary());VoxelTetMesher.Result mr=VoxelTetMesher.generate(m,12,scale);if(!mr.quality.pass)throw new IllegalStateException("Mesh QA: "+mr.quality.summary());currentModel=m;currentMesh=mr;runOnUiThread(()->{viewport.setModel(m);status.setText("Model hazır — mesnet ve yük patch'lerini seç");modeBadge.setText("MOD: READY • PICK SURFACES");modeBadge.setBackgroundColor(Color.rgb(20,115,105));report.setText("MODEL READY\n\n"+currentName+"\n"+topo.summary()+"\nNodes: "+mr.mesh.nodes.size()+"\nTET4: "+mr.mesh.tets.size()+"\n"+mr.quality.summary()+"\n\n+ MESNET ve + YÜK ile bir veya daha fazla patch seç.");});}catch(Exception e){runOnUiThread(()->{status.setText("Model/mesh bloke edildi");modeBadge.setText("MOD: QA BLOCKED");modeBadge.setBackgroundColor(Color.rgb(150,45,45));report.setText("Hata: "+e.getMessage());});}});}

    private void solvePicked(){if(currentModel==null||currentMesh==null){status.setText("Önce model yükle");return;}if(supports.isEmpty()){status.setText("En az bir mesnet patch seç");return;}final double force,pressureMPa,eGPa,nu,yieldMPa,rho;try{force=parse(loadInput,"Kuvvet");pressureMPa=parse(pressureInput,"Basınç");eGPa=parse(eInput,"E");nu=parse(nuInput,"Poisson");yieldMPa=parse(yieldInput,"Akma");rho=parse(densityInput,"Yoğunluk");}catch(Exception e){status.setText(e.getMessage());return;}String type=(String)loadTypeSpinner.getSelectedItem();boolean useForce=type.contains("FORCE"),usePressure=type.contains("PRESSURE");if((useForce||usePressure)&&loads.isEmpty()){status.setText("Yük/basınç için en az bir patch seç");return;}final String axis=(String)axisSpinner.getSelectedItem();final double scale=AutoFemSetup.unitScaleToMetres((String)unitSpinner.getSelectedItem());modeBadge.setText("MOD: REAL FEM SOLVING");status.setText("Çoklu patch + gerçek FEM çözülüyor…");
        executor.submit(()->{try{LinearElasticMaterial mat=new LinearElasticMaterial("User isotropic",eGPa*1e9,nu,rho,yieldMPa*1e6);StaticFemSolver solver=new StaticFemSolver(currentMesh.mesh,mat);double fx=0,fy=0,fz=0;if(useForce){if(axis.equals("-Z"))fz=-force;else if(axis.equals("+Z"))fz=force;else if(axis.equals("-Y"))fy=-force;else if(axis.equals("+Y"))fy=force;else if(axis.equals("-X"))fx=-force;else fx=force;}double pPa=usePressure?pressureMPa*1e6:0;AdvancedFemLoads.Result setup=AdvancedFemLoads.apply(solver,currentMesh.mesh,currentModel,supports,loads,scale,fx,fy,fz,pPa,gravityBox.isChecked(),rho);StaticFemSolver.Result fem=solver.solve();double fos=fem.maxVonMisesPa>0?mat.yieldPa/fem.maxVonMisesPa:Double.POSITIVE_INFINITY;boolean qa=fem.linearSolve.converged&&fem.forceEquilibriumRelativeError<1e-5&&Double.isFinite(fem.maxVonMisesPa)&&Double.isFinite(fem.maxDisplacementM);String txt=String.format(Locale.US,"REAL FEM v0.9\n\nModel: %s\nSupport picks: %d • fixed nodes: %d\nLoad picks: %d • loaded nodes: %d\nPatch radius: %.6g m\nPressure triangles: %d\nGravity mass: %.6g kg\nResultant load: [%.5g, %.5g, %.5g] N\n\nPCG: %s • iter %d\nResidual: %.3e\nForce equilibrium error: %.3e\n\nMax displacement: %.6g mm\nMax Von Mises: %.6g MPa\nYield FoS: %.4f\nNUMERICAL QA: %s\n\n3B kontur deforme geometri üzerinde otomatik büyütme ile çizilir. Basınç yönü kaynak yüzey üçgen normaline bağlıdır; yüzey normal kalitesi nihai mühendislik doğrulamasında kontrol edilmelidir.",currentName,supports.size(),setup.fixedNodes,loads.size(),setup.loadedNodes,setup.patchRadiusM,setup.pressureTriangles,setup.gravityMassKg,setup.resultantFx,setup.resultantFy,setup.resultantFz,fem.linearSolve.converged,fem.linearSolve.iterations,fem.linearSolve.relativeResidual,fem.forceEquilibriumRelativeError,fem.maxDisplacementM*1000,fem.maxVonMisesPa/1e6,fos,qa?"PASS":"BLOCKED");runOnUiThread(()->{viewport.setResult(currentMesh.mesh,fem);status.setText(qa?"Gerçek FEM tamamlandı • deforme kontur hazır":"FEM QA bloke edildi");modeBadge.setText(qa?"MOD: REAL FEM • DEFORMED CONTOUR":"MOD: FEM • QA BLOCKED");modeBadge.setBackgroundColor(qa?Color.rgb(20,125,70):Color.rgb(150,45,45));report.setText(txt);});}catch(Exception e){runOnUiThread(()->{status.setText("FEM çözülemedi");modeBadge.setText("MOD: FEM ERROR");modeBadge.setBackgroundColor(Color.rgb(150,45,45));report.setText("Hata: "+e.getMessage());});}});}

    private String getName(Uri uri){String n="model";Cursor c=getContentResolver().query(uri,null,null,null,null);if(c!=null){try{int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0)n=c.getString(i);}finally{c.close();}}return n;}
    @Override protected void onDestroy(){super.onDestroy();executor.shutdownNow();}
}
