package com.mg.structuralai;

import android.app.Activity;
import android.content.Intent;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.provider.OpenableColumns;
import android.view.Gravity;
import android.widget.*;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** Professional manual static setup: exact CAD, directional BCs, evidence-gated materials, convergence and PDF report. */
public class MainActivity extends Activity {
    private static final int PICK_MODEL=1001,SAVE_PDF=1002;
    private final ExecutorService executor=Executors.newSingleThreadExecutor();
    private TextView status,report,modeBadge;private Spinner unitSpinner,axisSpinner,loadTypeSpinner;
    private EditText loadInput,pressureInput,eInput,nuInput,yieldInput,ultimateInput,densityInput,materialSourceInput;
    private CheckBox gravityBox,fixXBox,fixYBox,fixZBox,materialCertifiedBox;
    private InteractiveModelView viewport;private MeshModel currentModel;private SmartTetMesher.Result currentMesh;private CadImportGateway.ImportedModel currentImport;private String currentName="model",lastReport="";
    private final List<MeshModel.V3> supports=new ArrayList<>(),loads=new ArrayList<>();

    @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18);root.setBackgroundColor(Color.rgb(10,22,38));
        TextView title=new TextView(this);title.setText("STRUCTURAL AI STATIC • MANUAL ENGINEERING");title.setTextColor(Color.WHITE);title.setTextSize(21);title.setGravity(Gravity.CENTER_HORIZONTAL);root.addView(title);
        TextView sub=new TextView(this);sub.setText("v"+BuildConfig.VERSION_NAME+" • EXACT CAD • TET4 • CONVERGENCE • EVIDENCE GATES");sub.setTextColor(Color.LTGRAY);sub.setTextSize(11);sub.setGravity(Gravity.CENTER_HORIZONTAL);root.addView(sub);
        modeBadge=new TextView(this);modeBadge.setText("MOD: HAZIR");modeBadge.setTextColor(Color.WHITE);modeBadge.setGravity(Gravity.CENTER);modeBadge.setBackgroundColor(Color.rgb(70,70,78));modeBadge.setPadding(10,7,10,7);root.addView(modeBadge,new LinearLayout.LayoutParams(-1,-2));

        viewport=new InteractiveModelView(this);viewport.setPickListener((p,idx)->{if(viewport.getPickMode()==InteractiveModelView.PickMode.SUPPORT){supports.add(p);viewport.addSupportPoint(p);status.setText("Mesnet yüzeyi eklendi • "+supports.size());}else if(viewport.getPickMode()==InteractiveModelView.PickMode.LOAD){loads.add(p);viewport.addLoadPoint(p);status.setText("Yük/basınç yüzeyi eklendi • "+loads.size());}});root.addView(viewport,new LinearLayout.LayoutParams(-1,390));

        LinearLayout pickRow=new LinearLayout(this);pickRow.setOrientation(LinearLayout.HORIZONTAL);Button sp=new Button(this);sp.setText("+ MESNET");sp.setOnClickListener(v->{viewport.setPickMode(InteractiveModelView.PickMode.SUPPORT);status.setText("Mesnet yüzeyine dokun");});Button lp=new Button(this);lp.setText("+ YÜK");lp.setOnClickListener(v->{viewport.setPickMode(InteractiveModelView.PickMode.LOAD);status.setText("Yük/basınç yüzeyine dokun");});Button clear=new Button(this);clear.setText("TEMİZLE");clear.setOnClickListener(v->{supports.clear();loads.clear();viewport.clearSupportPoints();viewport.clearLoadPoints();viewport.setPickMode(InteractiveModelView.PickMode.NONE);status.setText("Seçimler temizlendi");});pickRow.addView(sp,new LinearLayout.LayoutParams(0,-2,1));pickRow.addView(lp,new LinearLayout.LayoutParams(0,-2,1));pickRow.addView(clear,new LinearLayout.LayoutParams(0,-2,1));root.addView(pickRow);

        LinearLayout cfg=new LinearLayout(this);cfg.setOrientation(LinearLayout.HORIZONTAL);unitSpinner=spin(new String[]{"mm","m","cm","in"});axisSpinner=spin(new String[]{"-Z","+Z","-Y","+Y","-X","+X"});loadTypeSpinner=spin(new String[]{"FORCE","PRESSURE","FORCE + PRESSURE"});cfg.addView(box("Fallback birim",unitSpinner),new LinearLayout.LayoutParams(0,-2,1));cfg.addView(box("Kuvvet yönü",axisSpinner),new LinearLayout.LayoutParams(0,-2,1));cfg.addView(box("Yük tipi",loadTypeSpinner),new LinearLayout.LayoutParams(0,-2,1));root.addView(cfg);

        LinearLayout bc=new LinearLayout(this);bc.setOrientation(LinearLayout.HORIZONTAL);fixXBox=check("Ux=0",true);fixYBox=check("Uy=0",true);fixZBox=check("Uz=0",true);bc.addView(label("Mesnet DOF:"));bc.addView(fixXBox);bc.addView(fixYBox);bc.addView(fixZBox);root.addView(bc);
        LinearLayout r1=new LinearLayout(this);r1.setOrientation(LinearLayout.HORIZONTAL);loadInput=field("1000");pressureInput=field("0");densityInput=field("7850");r1.addView(box("Kuvvet [N]",loadInput),new LinearLayout.LayoutParams(0,-2,1));r1.addView(box("Basınç [MPa]",pressureInput),new LinearLayout.LayoutParams(0,-2,1));r1.addView(box("ρ [kg/m³]",densityInput),new LinearLayout.LayoutParams(0,-2,1));root.addView(r1);
        LinearLayout r2=new LinearLayout(this);r2.setOrientation(LinearLayout.HORIZONTAL);eInput=field("210");nuInput=field("0.30");yieldInput=field("355");ultimateInput=field("510");r2.addView(box("E [GPa]",eInput),new LinearLayout.LayoutParams(0,-2,1));r2.addView(box("ν",nuInput),new LinearLayout.LayoutParams(0,-2,1));r2.addView(box("Akma [MPa]",yieldInput),new LinearLayout.LayoutParams(0,-2,1));r2.addView(box("UTS [MPa]",ultimateInput),new LinearLayout.LayoutParams(0,-2,1));root.addView(r2);
        materialCertifiedBox=check("Malzeme standardı/sertifikası doğrulandı",false);root.addView(materialCertifiedBox);materialSourceInput=fieldText("örn. EN 10025 / lot sertifikası / kurum malzeme kartı");root.addView(box("Malzeme provenance / kaynak",materialSourceInput));
        gravityBox=check("Gravity -Z 9.80665 m/s²",false);root.addView(gravityBox);

        LinearLayout action=new LinearLayout(this);action.setOrientation(LinearLayout.HORIZONTAL);Button loadModel=new Button(this);loadModel.setText("MODEL + MESH QA");loadModel.setOnClickListener(v->pickModel());Button solve=new Button(this);solve.setText("FEM ÇALIŞTIR");solve.setOnClickListener(v->solvePicked());action.addView(loadModel,new LinearLayout.LayoutParams(0,-2,1));action.addView(solve,new LinearLayout.LayoutParams(0,-2,1));root.addView(action);
        Button pdf=new Button(this);pdf.setText("PDF MÜHENDİSLİK RAPORU");pdf.setOnClickListener(v->savePdf());root.addView(pdf);
        status=new TextView(this);status.setText("Hazır — STEP/STP/IGES/IGS/BREP/STL/OBJ");status.setTextColor(Color.rgb(120,220,190));status.setPadding(0,6,0,4);root.addView(status);
        ScrollView scroll=new ScrollView(this);report=new TextView(this);report.setTextColor(Color.WHITE);report.setTextSize(12);report.setTextIsSelectable(true);lastReport="MANUAL ENGINEERING GATE\n\nExact CAD/mesh import → topology → Smart TET4 → connected-surface BC/load → 8/12/16 convergence → sparse PCG → equilibrium → professional results.\nSafety factor is released only with explicit material evidence.";report.setText(lastReport);scroll.addView(report);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private Spinner spin(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
    private TextView label(String x){TextView v=new TextView(this);v.setText(x);v.setTextColor(Color.LTGRAY);v.setTextSize(10);return v;}
    private EditText field(String x){EditText e=new EditText(this);e.setText(x);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);return e;}
    private EditText fieldText(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.GRAY);e.setTextColor(Color.WHITE);e.setSingleLine(true);return e;}
    private CheckBox check(String text,boolean checked){CheckBox c=new CheckBox(this);c.setText(text);c.setTextColor(Color.WHITE);c.setChecked(checked);return c;}
    private LinearLayout box(String t,android.view.View v){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(3,0,3,0);b.addView(label(t));b.addView(v);return b;}
    private double parse(EditText e,String n){try{return Double.parseDouble(e.getText().toString().trim());}catch(Exception x){throw new IllegalArgumentException(n+" sayısal olmalı");}}
    private void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK_MODEL);}
    private double currentScale(){return currentModel!=null&&currentModel.authoritativeUnit&&Double.isFinite(currentModel.sourceUnitScaleM)&&currentModel.sourceUnitScaleM>0?currentModel.sourceUnitScaleM:AutoFemSetup.unitScaleToMetres((String)unitSpinner.getSelectedItem());}

    @Override protected void onActivityResult(int rq,int rc,Intent data){super.onActivityResult(rq,rc,data);if(rc!=RESULT_OK||data==null)return;Uri uri=data.getData();if(uri==null)return;if(rq==SAVE_PDF){exportPdf(uri);return;}if(rq!=PICK_MODEL)return;try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}currentName=getName(uri);supports.clear();loads.clear();status.setText("CAD/mesh → topology → Smart TET4 QA: "+currentName);modeBadge.setText("MOD: IMPORT + MESH QA");
        executor.submit(()->{try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IllegalStateException("Model stream açılamadı");CadImportGateway.ImportedModel im=CadImportGateway.read(currentName,in,getCacheDir());MeshModel m=im.mesh;SurfaceTopologyReport topo=SurfaceTopologyReport.evaluate(m);if(!topo.closedManifold)throw new IllegalStateException("Kapalı/manifold değil: "+topo.summary());double scale=m.authoritativeUnit?m.sourceUnitScaleM:AutoFemSetup.unitScaleToMetres((String)unitSpinner.getSelectedItem());SmartTetMesher.Result mr=SmartTetMesher.generate(m,12,scale);if(!mr.quality.pass)throw new IllegalStateException("Mesh QA: "+mr.quality.summary());currentModel=m;currentMesh=mr;currentImport=im;String unit=m.authoritativeUnit?("AUTHORITATIVE scale="+m.sourceUnitScaleM+" m/unit"):"USER FALLBACK unit="+unitSpinner.getSelectedItem();runOnUiThread(()->{viewport.setModel(m);status.setText("Model hazır — mesnet ve yük yüzeylerini seç");modeBadge.setText("MOD: READY • PICK SURFACES");modeBadge.setBackgroundColor(Color.rgb(20,115,105));lastReport="MODEL READY\n\n"+currentName+"\n"+topo.summary()+"\nImport: "+im.format+" • exact CAD="+im.exactCadSource+"\nUnit: "+unit+"\nPreview nodes: "+mr.mesh.nodes.size()+"\nPreview TET4: "+mr.mesh.tets.size()+"\n"+mr.quality.summary();report.setText(lastReport);});}catch(Exception e){runOnUiThread(()->{status.setText("Model/mesh bloke edildi");modeBadge.setText("MOD: QA BLOCKED");modeBadge.setBackgroundColor(Color.rgb(150,45,45));lastReport="IMPORT / MESH BLOCKED\n"+e.getMessage();report.setText(lastReport);});}});}

    private void solvePicked(){if(currentModel==null||currentMesh==null){status.setText("Önce model yükle");return;}if(supports.isEmpty()){status.setText("En az bir mesnet yüzeyi seç");return;}if(!fixXBox.isChecked()&&!fixYBox.isChecked()&&!fixZBox.isChecked()){status.setText("En az bir mesnet DOF'u seç");return;}final double force,pressureMPa,eGPa,nu,yieldMPa,ultimateMPa,rho;try{force=parse(loadInput,"Kuvvet");pressureMPa=parse(pressureInput,"Basınç");eGPa=parse(eInput,"E");nu=parse(nuInput,"Poisson");yieldMPa=parse(yieldInput,"Akma");ultimateMPa=parse(ultimateInput,"UTS");rho=parse(densityInput,"Yoğunluk");}catch(Exception e){status.setText(e.getMessage());return;}String type=(String)loadTypeSpinner.getSelectedItem();boolean useForce=type.contains("FORCE"),usePressure=type.contains("PRESSURE");if((useForce||usePressure)&&loads.isEmpty()){status.setText("Yük/basınç için en az bir yüzey seç");return;}final boolean certified=materialCertifiedBox.isChecked();final String source=materialSourceInput.getText().toString().trim();if(certified&&source.isEmpty()){status.setText("Doğrulanmış malzeme için provenance/kaynak gir");return;}final String axis=(String)axisSpinner.getSelectedItem();final double scale=currentScale();final boolean fixX=fixXBox.isChecked(),fixY=fixYBox.isChecked(),fixZ=fixZBox.isChecked();modeBadge.setText("MOD: 3-LEVEL FEM SOLVING");status.setText("8/12/16 Smart TET4 seviyeleri çözülüyor…");
        executor.submit(()->{try{LinearElasticMaterial.EvidenceLevel ev=certified?LinearElasticMaterial.EvidenceLevel.USER_CERTIFIED:LinearElasticMaterial.EvidenceLevel.REFERENCE;String prov=certified?source:"UNVERIFIED USER INPUT — screening only";LinearElasticMaterial mat=new LinearElasticMaterial("User isotropic",eGPa*1e9,nu,rho,yieldMPa*1e6,ultimateMPa*1e6,prov,ev);double fx=0,fy=0,fz=0;if(useForce){if(axis.equals("-Z"))fz=-force;else if(axis.equals("+Z"))fz=force;else if(axis.equals("-Y"))fy=-force;else if(axis.equals("+Y"))fy=force;else if(axis.equals("-X"))fx=-force;else fx=force;}double pPa=usePressure?pressureMPa*1e6:0;
            MeshConvergenceStudy.Result cv=MeshConvergenceStudy.run(currentModel,scale,mat,supports,loads,fx,fy,fz,pPa,gravityBox.isChecked(),rho,fixX,fixY,fixZ);MeshConvergenceStudy.Level f=cv.fine;boolean fosReady=mat.designReleaseEligible()&&f.fem.maxVonMisesPa>0;double fos=fosReady?mat.yieldPa/f.fem.maxVonMisesPa:Double.NaN;boolean numerical=f.fem.linearSolve.converged&&f.fem.forceEquilibriumRelativeError<1e-5&&Double.isFinite(f.fem.maxVonMisesPa)&&Double.isFinite(f.fem.maxDisplacementM);boolean ready=numerical&&cv.converged;String fosText=fosReady?String.format(Locale.US,"%.4f",fos):"BLOCKED — material evidence not release-eligible";
            String txt=String.format(Locale.US,"STRUCTURAL AI MANUAL ENGINEERING REPORT\nVersion: %s\n\nMODEL\n%s\nFormat: %s • exact CAD=%s\nUnit scale: %.9g m/model-unit • authoritative=%s\n\nBOUNDARY CONDITIONS\nConnected support regions: %d • support nodes: %d • fixed DOFs: %d\nDirectional constraints: Ux=%s Uy=%s Uz=%s\nConnected load regions: %d • loaded nodes: %d\nPressure area: %.6g m² • pressure triangles: %d\nGravity mass: %.6g kg\nResultant load: [%.5g, %.5g, %.5g] N\n\nMATERIAL EVIDENCE\nE=%.6g GPa • nu=%.6g • rho=%.6g kg/m³\nYield=%.6g MPa • UTS=%.6g MPa\nEvidence level: %s\nProvenance: %s\nDesign release eligible: %s\n\nMESH CONVERGENCE\n8 cells: nodes %d • TET4 %d • Umax %.6g mm • VM %.6g MPa\n12 cells: nodes %d • TET4 %d • Umax %.6g mm • VM %.6g MPa\n16 cells: nodes %d • TET4 %d • Umax %.6g mm • VM %.6g MPa\nDelta U(12→16): %.2f %%\nDelta VM(12→16): %.2f %%\nConverged: %s\n\nFINE SOLVER\nPCG: %s • iter %d\nResidual: %.3e\nForce equilibrium error: %.3e\nMax displacement: %.6g mm\nMax Von Mises: %.6g MPa\nYield FoS: %s\n\nNUMERICAL ANALYSIS GATE: %s\nDESIGN RELEASE GATE: %s\n\nPrincipal stress/strain, reaction, mesh quality and probe fields are available in the viewport. Numerical convergence does not certify the physical load case; design release requires traceable material, units, fixtures, loads and contacts.",BuildConfig.VERSION_NAME,currentName,currentImport==null?"unknown":currentImport.format.toString(),currentImport!=null&&currentImport.exactCadSource,scale,currentModel.authoritativeUnit,f.setup.supportRegions,f.setup.fixedNodes,f.setup.fixedDofs,fixX,fixY,fixZ,f.setup.loadRegions,f.setup.loadedNodes,f.setup.selectedPressureAreaM2,f.setup.pressureTriangles,f.setup.gravityMassKg,f.setup.resultantFx,f.setup.resultantFy,f.setup.resultantFz,eGPa,nu,rho,yieldMPa,ultimateMPa,mat.evidenceLevel,mat.provenance,mat.designReleaseEligible(),cv.coarse.nodes,cv.coarse.tets,cv.coarse.fem.maxDisplacementM*1000,cv.coarse.fem.maxVonMisesPa/1e6,cv.medium.nodes,cv.medium.tets,cv.medium.fem.maxDisplacementM*1000,cv.medium.fem.maxVonMisesPa/1e6,cv.fine.nodes,cv.fine.tets,cv.fine.fem.maxDisplacementM*1000,cv.fine.fem.maxVonMisesPa/1e6,cv.displacementChange*100,cv.stressChange*100,cv.converged,f.fem.linearSolve.converged,f.fem.linearSolve.iterations,f.fem.linearSolve.relativeResidual,f.fem.forceEquilibriumRelativeError,f.fem.maxDisplacementM*1000,f.fem.maxVonMisesPa/1e6,fosText,ready?"PASS":"BLOCKED",ready&&mat.designReleaseEligible()?"EVIDENCE READY — physical case still engineer-approved":"BLOCKED");
            runOnUiThread(()->{viewport.setResult(f.mesh,f.fem);status.setText(ready?"Numerik analiz PASS • sonuç/mesh alanlarına dokun":"Analiz gate bloke • convergence/QA incele");modeBadge.setText(ready?"MOD: NUMERICAL PASS":"MOD: ANALYSIS QA BLOCKED");modeBadge.setBackgroundColor(ready?Color.rgb(20,125,70):Color.rgb(150,45,45));lastReport=txt;report.setText(txt);});
        }catch(Exception e){runOnUiThread(()->{status.setText("FEM/convergence çözülemedi");modeBadge.setText("MOD: ANALYSIS ERROR");modeBadge.setBackgroundColor(Color.rgb(150,45,45));lastReport="ANALYSIS ERROR\n"+e.getMessage();report.setText(lastReport);});}});}

    private void savePdf(){if(lastReport==null||lastReport.trim().isEmpty()){status.setText("Önce rapor/analiz oluştur");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,"Structural_AI_"+currentName.replaceAll("[^A-Za-z0-9._-]","_")+"_"+BuildConfig.VERSION_NAME+".pdf");startActivityForResult(i,SAVE_PDF);}
    private void exportPdf(Uri uri){Bitmap bmp=null;try{if(viewport.getWidth()>0&&viewport.getHeight()>0){bmp=Bitmap.createBitmap(viewport.getWidth(),viewport.getHeight(),Bitmap.Config.ARGB_8888);viewport.draw(new Canvas(bmp));}EngineeringPdfExporter.write(getContentResolver(),uri,"STRUCTURAL AI ENGINEERING REPORT",lastReport,bmp);status.setText("PDF rapor kaydedildi");}catch(Exception e){status.setText("PDF kaydedilemedi: "+e.getMessage());}finally{if(bmp!=null)bmp.recycle();}}
    private String getName(Uri uri){String n="model";Cursor c=getContentResolver().query(uri,null,null,null,null);if(c!=null){try{int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0)n=c.getString(i);}finally{c.close();}}return n;}
    @Override protected void onDestroy(){super.onDestroy();executor.shutdownNow();}
}
