package com.mg.fixturecockpitsim;

import android.Manifest;import android.app.Activity;import android.bluetooth.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;
import com.mg.fixturecockpitsim.sim.*;
import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public final class Display3DActivity extends Activity {
 private static final UUID SIM_UUID=UUID.fromString("6d9b6c72-4d47-4d8e-9b58-b5e7465b4a22");private static final int REQ_BT=61;
 private final ExecutorService io=Executors.newSingleThreadExecutor();private final Handler simHandler=new Handler(Looper.getMainLooper());private final FlightDynamicsEngine dynamics=new FlightDynamicsEngine();private final FlightState simState=new FlightState();private final FlightControls simControls=new FlightControls();private final AutonomousFlightMission mission=new AutonomousFlightMission();private final FlightSoundEngine sound=new FlightSoundEngine();
 private volatile boolean running=true,connected,remoteDemo;private volatile float roll,pitch,yaw,throttle=.62f,linkHz;private volatile int lastSeq,drops;private volatile long previousRxMs;private volatile double remotePitch,remoteRoll,remoteYaw,remoteThrottle=.72;
 private BluetoothAdapter bt;private BluetoothServerSocket server;private BluetoothSocket socket;private BufferedWriter writer;private Jet3DView jetView;private RunwayHudView runwayView;private TextView missionHud;private LinearLayout waitingPanel,manualPanel;private Button modeButton,invertButton;private long lastSimNs;private boolean demoMode,manualDemo,invertedHold;private int demoCameraMode=Jet3DView.CAMERA_CHASE;private double manualPitch,manualRoll,manualYaw,manualThrottle=.72;private boolean manualGearDown;

 private final Runnable simTick=new Runnable(){@Override public void run(){if(!running)return;long now=System.nanoTime();double dt=lastSimNs==0?.02:Math.min(.05,Math.max(.005,(now-lastSimNs)/1e9));lastSimNs=now;if(demoMode){mission.update(simState,simControls,dt);AutonomousFlightMission.Phase ph=mission.getPhase();boolean pilotPhase=ph==AutonomousFlightMission.Phase.RUNWAY_HOLD||ph==AutonomousFlightMission.Phase.TAKEOFF_ROLL||ph==AutonomousFlightMission.Phase.ROTATE_CLIMB||ph==AutonomousFlightMission.Phase.ORBIT||ph==AutonomousFlightMission.Phase.APPROACH||ph==AutonomousFlightMission.Phase.FLARE;
   if(remoteDemo&&connected&&pilotPhase){simControls.pitch=remotePitch;simControls.roll=remoteRoll;simControls.yaw=remoteYaw;simControls.throttle=remoteThrottle;simControls.brake=0;simControls.gearDown=ph==AutonomousFlightMission.Phase.RUNWAY_HOLD||ph==AutonomousFlightMission.Phase.TAKEOFF_ROLL||simState.altitudeM<45;simControls.clamp();}
   else if(manualDemo&&pilotPhase){simControls.pitch=manualPitch;simControls.roll=invertedHold?1.0:manualRoll;simControls.yaw=manualYaw;simControls.throttle=manualThrottle;simControls.gearDown=manualGearDown;simControls.brake=0;simControls.clamp();}
   else if(manualDemo&&!pilotPhase){manualDemo=false;invertedHold=false;syncManualUi();}
   dynamics.step(simState,simControls,dt);roll=(float)simState.rollDeg;pitch=(float)simState.pitchDeg;yaw=(float)simState.headingDeg;throttle=(float)simState.throttle;jetView.setTelemetry(roll,pitch,yaw,throttle,50,0,true);jetView.setSimulationState((float)simState.gearPosition,(float)simState.mainStrutCompression01,(float)simState.noseStrutCompression01,(float)simState.brake01,simState.onGround);jetView.setFlightMotion((float)simState.trueAirspeedMps,(float)simState.verticalSpeedMps,simState.onGround);jetView.setWheelSpeed((float)(simState.onGround?simState.trueAirspeedMps:0));runwayView.setFlightState(simState.altitudeM,simState.trueAirspeedMps,simState.onGround,ph.name());runwayView.setDemoProgress(mission.getOrbitTimeSec());runwayView.setGroundProgress(mission.getPhaseProgress01(),simState.headingDeg);sound.update(simState.throttle,simState.trueAirspeedMps,simState.gearPosition,simState.brake01,simState.onGround);if(!manualDemo&&!remoteDemo)updateDemoCameraDirector();updateMissionHud();}simHandler.postDelayed(this,20);}};

 @Override protected void onCreate(Bundle b){super.onCreate(b);demoMode=getIntent()!=null&&getIntent().getBooleanExtra(LauncherActivity.EXTRA_DEMO_MODE,false);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);bt=BluetoothAdapter.getDefaultAdapter();mission.reset(simState);simControls.gearDown=true;runwayView=new RunwayHudView(this);runwayView.setDemoMode(demoMode);jetView=new Jet3DView(this);
  FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.rgb(3,9,13));root.addView(runwayView,new FrameLayout.LayoutParams(-1,-1));root.addView(jetView,new FrameLayout.LayoutParams(-1,-1));missionHud=new TextView(this);missionHud.setTextColor(Color.WHITE);missionHud.setTextSize(14);missionHud.setPadding(dp(12),dp(8),dp(12),dp(8));missionHud.setBackgroundColor(0x66000000);FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.LEFT);hp.setMargins(dp(10),dp(10),0,0);root.addView(missionHud,hp);
  waitingPanel=new LinearLayout(this);waitingPanel.setOrientation(LinearLayout.VERTICAL);waitingPanel.setGravity(Gravity.CENTER);waitingPanel.setPadding(dp(36),dp(28),dp(36),dp(28));waitingPanel.setBackgroundColor(Color.rgb(3,9,13));TextView wt=new TextView(this);wt.setText("UÇAK EKRANI");wt.setTextColor(Color.rgb(160,255,190));wt.setTextSize(28);wt.setGravity(Gravity.CENTER);TextView wx=new TextView(this);wx.setText("Pilot telefonu bağlantısı bekleniyor\n\nPilot telefonunda kokpiti aç ve bu telefona bağlan.");wx.setTextColor(Color.LTGRAY);wx.setTextSize(16);wx.setGravity(Gravity.CENTER);wx.setPadding(0,dp(18),0,0);waitingPanel.addView(wt);waitingPanel.addView(wx);root.addView(waitingPanel,new FrameLayout.LayoutParams(-1,-1));
  Button back=button("GERİ");FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(dp(84),dp(46),Gravity.TOP|Gravity.RIGHT);bp.setMargins(0,10,10,0);root.addView(back,bp);back.setOnClickListener(v->finish());buildManualPanel(root);setContentView(root);jetView.setSimulationState((float)simState.gearPosition,0,0,0,true);jetView.setFlightMotion(0,0,true);jetView.setWheelSpeed(0);jetView.setCameraMode(Jet3DView.CAMERA_CHASE);runwayView.setFlightState(0,0,true,mission.getPhase().name());runwayView.setGroundProgress(0,simState.headingDeg);
  if(demoMode){showFlightScene();sound.start();updateMissionHud();simHandler.post(simTick);requestBtThenStart();Toast.makeText(this,"DEMO: hangar/taksi otomatik. Pist başından itibaren MANUEL veya Bluetooth pilot telefonu kontrolü kullanılabilir.",Toast.LENGTH_LONG).show();}else{showWaitingScreen();requestBtThenStart();}}

 private void buildManualPanel(FrameLayout root){manualPanel=new LinearLayout(this);manualPanel.setOrientation(LinearLayout.HORIZONTAL);manualPanel.setGravity(Gravity.CENTER);manualPanel.setPadding(dp(3),dp(3),dp(3),dp(3));manualPanel.setBackgroundColor(0xB8000000);modeButton=button("MANUEL");Button left=button("◀");Button right=button("▶");Button up=button("BURUN↑");Button down=button("BURUN↓");Button level=button("DÜZLE");invertButton=button("TERS");Button tm=button("THR−");Button tp=button("THR+");Button gear=button("GEAR");Button cam=button("KAMERA");manualPanel.addView(modeButton);manualPanel.addView(left);manualPanel.addView(right);manualPanel.addView(up);manualPanel.addView(down);manualPanel.addView(level);manualPanel.addView(invertButton);manualPanel.addView(tm);manualPanel.addView(tp);manualPanel.addView(gear);manualPanel.addView(cam);FrameLayout.LayoutParams mp=new FrameLayout.LayoutParams(-1,dp(58),Gravity.BOTTOM);root.addView(manualPanel,mp);
  modeButton.setOnClickListener(v->{AutonomousFlightMission.Phase ph=mission.getPhase();boolean ok=ph==AutonomousFlightMission.Phase.RUNWAY_HOLD||ph==AutonomousFlightMission.Phase.TAKEOFF_ROLL||ph==AutonomousFlightMission.Phase.ROTATE_CLIMB||ph==AutonomousFlightMission.Phase.ORBIT||ph==AutonomousFlightMission.Phase.APPROACH||ph==AutonomousFlightMission.Phase.FLARE;if(!ok){Toast.makeText(this,"Manuel kontrol pist başında açılır",Toast.LENGTH_SHORT).show();return;}remoteDemo=false;manualDemo=!manualDemo;if(manualDemo){manualPitch=manualRoll=manualYaw=0;manualThrottle=Math.max(.10,simState.throttle);manualGearDown=simState.gearPosition>.5;invertedHold=false;jetView.setCameraMode(Jet3DView.CAMERA_CHASE);demoCameraMode=Jet3DView.CAMERA_CHASE;}else invertedHold=false;syncManualUi();});
  holdAxis(left,()->manualRoll=-1.0,()->manualRoll=0);holdAxis(right,()->manualRoll=1.0,()->manualRoll=0);holdAxis(up,()->manualPitch=.62,()->manualPitch=0);holdAxis(down,()->manualPitch=-.42,()->manualPitch=0);
  level.setOnClickListener(v->{manualPitch=manualRoll=manualYaw=0;invertedHold=false;syncManualUi();});invertButton.setOnClickListener(v->{if(!manualDemo)return;invertedHold=!invertedHold;manualRoll=0;syncManualUi();});tm.setOnClickListener(v->{if(manualDemo)manualThrottle=Math.max(0,manualThrottle-.05);});tp.setOnClickListener(v->{if(manualDemo)manualThrottle=Math.min(1,manualThrottle+.05);});gear.setOnClickListener(v->{if(manualDemo)manualGearDown=!manualGearDown;});cam.setOnClickListener(v->{if(!manualDemo&&!remoteDemo)return;demoCameraMode=(demoCameraMode+1)%4;jetView.setCameraMode(demoCameraMode);});}
 private void holdAxis(Button b,Runnable press,Runnable release){b.setOnTouchListener((v,e)->{if(!manualDemo)return false;if(e.getAction()==MotionEvent.ACTION_DOWN){invertedHold=false;press.run();syncManualUi();v.setPressed(true);return true;}if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL){release.run();v.setPressed(false);return true;}return true;});}
 private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(9);b.setMinWidth(0);b.setPadding(dp(2),0,dp(2),0);return b;}private void syncManualUi(){if(modeButton!=null)modeButton.setText(manualDemo?"OTOMATİK":"MANUEL");if(invertButton!=null)invertButton.setText(invertedHold?"TERS ✓":"TERS");}
 private void showWaitingScreen(){waitingPanel.setVisibility(View.VISIBLE);runwayView.setVisibility(View.GONE);jetView.setVisibility(View.GONE);missionHud.setVisibility(View.GONE);manualPanel.setVisibility(View.GONE);}private void showFlightScene(){waitingPanel.setVisibility(View.GONE);runwayView.setVisibility(View.VISIBLE);jetView.setVisibility(View.VISIBLE);missionHud.setVisibility(View.VISIBLE);manualPanel.setVisibility(demoMode?View.VISIBLE:View.GONE);}
 private void updateDemoCameraDirector(){int w=Jet3DView.CAMERA_CHASE;if(w!=demoCameraMode){demoCameraMode=w;jetView.setCameraMode(w);}}
 private String cameraName(){int c=demoMode?demoCameraMode:jetView.getCameraMode();switch(c){case 1:return"REAR";case 2:return"RIGHT 3/4";case 3:return"LEFT 3/4";default:return"CHASE";}}
 private void updateMissionHud(){if(!demoMode&&!connected)return;String ph=mission.getPhase().name().replace('_',' '),extra=mission.getPhase()==AutonomousFlightMission.Phase.ORBIT?String.format(Locale.US,"  UÇUŞ %.0f/300 s",mission.getOrbitTimeSec()):"",mode=demoMode?(remoteDemo&&connected?"BT PILOT":manualDemo?(invertedHold?"MANUEL TERS":"MANUEL"):"DEMO AUTO"):"UÇAK EKRANI / PILOT BAĞLI";missionHud.setText(String.format(Locale.US,"%s  %s%s   CAM %s\nALT %.0f m   VS %.1f m/s   SPD %.0f m/s   HDG %03.0f   ROLL %.0f°\nTHR %.0f%%  GEAR %.0f%%   BRK %.0f%%   %s",mode,ph,extra,cameraName(),simState.altitudeM,simState.verticalSpeedMps,simState.trueAirspeedMps,simState.headingDeg,simState.rollDeg,simState.throttle*100,simState.gearPosition*100,simState.brake01*100,simState.onGround?"GROUND":"AIR"));}
 private void requestBtThenStart(){if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_SCAN},REQ_BT);else startServer();}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_BT&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startServer();}
 private void startServer(){if(bt==null)return;if(!bt.isEnabled()){if(!demoMode)Toast.makeText(this,"Bluetooth kapalı",Toast.LENGTH_LONG).show();return;}io.execute(()->{while(running){try{server=bt.listenUsingRfcommWithServiceRecord("AircraftSimulator3D",SIM_UUID);socket=server.accept();connected=true;if(demoMode){remoteDemo=true;manualDemo=false;runOnUiThread(()->{syncManualUi();Toast.makeText(this,"Bluetooth pilot telefonu DEMO kontrolüne bağlandı",Toast.LENGTH_SHORT).show();});}else runOnUiThread(()->{showFlightScene();sound.start();missionHud.setText("UÇAK EKRANI — PILOT BAĞLANDI");});writer=new BufferedWriter(new OutputStreamWriter(socket.getOutputStream(),StandardCharsets.UTF_8));BufferedReader r=new BufferedReader(new InputStreamReader(socket.getInputStream(),StandardCharsets.UTF_8));String line;while(running&&(line=r.readLine())!=null){String[] a=line.split(",");if(a.length<7||!"V2".equals(a[0]))continue;try{int seq=Integer.parseInt(a[1]);float nr=Float.parseFloat(a[3]),np=Float.parseFloat(a[4]),ny=Float.parseFloat(a[5]),nt=Float.parseFloat(a[6]);long now=System.currentTimeMillis();if(lastSeq>0&&seq>lastSeq+1)drops+=seq-lastSeq-1;lastSeq=seq;if(previousRxMs>0){float d=Math.max(1,now-previousRxMs);linkHz+=(1000f/d-linkHz)*.15f;}previousRxMs=now;
    if(demoMode){remoteRoll=clamp(nr/55f,-1,1);remotePitch=clamp(np/24f,-1,1);remoteYaw=clamp(angleDelta((float)simState.headingDeg,ny)/32f,-1,1);remoteThrottle=clamp(nt,0,1);}else{roll=approach(roll,nr,7.5f);pitch=approach(pitch,np,5);yaw=angleLerp(yaw,ny,.24f);throttle+=(nt-throttle)*.20f;jetView.setTelemetry(roll,pitch,yaw,throttle,linkHz,drops,true);jetView.setFlightMotion(45+throttle*210,0,false);sound.update(throttle,45+throttle*210,0,0,false);}synchronized(this){writer.write("A,"+seq+"\n");writer.flush();}}catch(Exception ignored){}}}catch(Exception ignored){connected=false;}finally{remoteDemo=false;closeLink();if(!demoMode)sound.stop();if(running&&!demoMode)runOnUiThread(this::showWaitingScreen);}}});}
 private static float approach(float c,float t,float s){float d=t-c;if(d>s)d=s;if(d<-s)d=-s;return c+d;}private static float angleLerp(float a,float b,float k){float d=angleDelta(a,b);return a+d*k;}private static float angleDelta(float a,float b){float d=b-a;while(d>180)d-=360;while(d<-180)d+=360;return d;}private static double clamp(double v,double lo,double hi){return Math.max(lo,Math.min(hi,v));}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void closeLink(){try{if(socket!=null)socket.close();}catch(Exception ignored){}try{if(server!=null)server.close();}catch(Exception ignored){}socket=null;server=null;writer=null;connected=false;}
 @Override protected void onPause(){super.onPause();jetView.onPause();sound.stop();}@Override protected void onResume(){super.onResume();jetView.onResume();lastSimNs=0;if(demoMode&&running)sound.start();}@Override protected void onDestroy(){running=false;simHandler.removeCallbacks(simTick);sound.stop();closeLink();io.shutdownNow();super.onDestroy();}
}
