package com.mg.fixturecockpitsim;

import android.content.Context;
import android.graphics.PixelFormat;
import android.opengl.GLES20;
import android.opengl.GLSurfaceView;
import android.opengl.Matrix;
import android.view.MotionEvent;
import com.mg.fixturecockpitsim.visual.ProceduralFighterMesh;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.FloatBuffer;
import javax.microedition.khronos.egl.EGLConfig;
import javax.microedition.khronos.opengles.GL10;

/** v20 transition renderer until the production GLB replaces it. */
public final class Jet3DView extends GLSurfaceView {
    public static final int CAMERA_CHASE=0;
    public static final int CAMERA_REAR=1;
    public static final int CAMERA_RIGHT_QUARTER=2;
    public static final int CAMERA_LEFT_QUARTER=3;
    private final JetRenderer renderer;
    public Jet3DView(Context context){super(context);setEGLContextClientVersion(2);setEGLConfigChooser(8,8,8,8,16,0);getHolder().setFormat(PixelFormat.TRANSLUCENT);setZOrderOnTop(true);renderer=new JetRenderer();setRenderer(renderer);setRenderMode(RENDERMODE_CONTINUOUSLY);setPreserveEGLContextOnPause(true);}
    public void setTelemetry(float roll,float pitch,float yaw,float throttle,float linkHz,int drops,boolean live){renderer.setTelemetry(roll,pitch,yaw,throttle,live);}
    public void setSimulationState(float gear,float mainCompression,float noseCompression,float brake,boolean onGround){renderer.setSimulationState(gear,mainCompression,noseCompression,brake,onGround);}
    public void setCameraMode(int mode){renderer.setCameraMode(mode);} public int getCameraMode(){return renderer.getCameraMode();}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_UP)renderer.nextCamera();return true;}

    private static final class JetRenderer implements GLSurfaceView.Renderer{
        private final float[] projection=new float[16],view=new float[16],model=new float[16],vp=new float[16],mvp=new float[16];
        private volatile float targetRoll,targetPitch,targetYaw,throttle=.62f,targetGear=1f,targetMainComp,targetNoseComp,targetBrake;private volatile boolean live,onGround;
        private float roll,pitch,yaw,gear=1f,mainComp,noseComp,brake;private volatile int cameraMode;
        private int program,aPos,aNormal,aPart,uMvp,uModel,uColor,uLightDir,uThrottle,uSurfPitch,uSurfRoll,uSurfYaw,uGear,uMainComp,uNoseComp;
        private FloatBuffer vertices;private int vertexCount;private long lastNs;
        void setTelemetry(float r,float p,float y,float t,boolean l){targetRoll=r;targetPitch=p;targetYaw=y;throttle=Math.max(0f,Math.min(1f,t));live=l;}
        void setSimulationState(float g,float mc,float nc,float b,boolean ground){targetGear=clamp(g,0f,1f);targetMainComp=clamp(mc,0f,1f);targetNoseComp=clamp(nc,0f,1f);targetBrake=clamp(b,0f,1f);onGround=ground;}
        void setCameraMode(int mode){cameraMode=Math.max(0,Math.min(3,mode));} int getCameraMode(){return cameraMode;} void nextCamera(){cameraMode=(cameraMode+1)%4;}
        @Override public void onSurfaceCreated(GL10 gl,EGLConfig config){
            GLES20.glClearColor(0f,0f,0f,0f);GLES20.glEnable(GLES20.GL_DEPTH_TEST);GLES20.glDepthMask(true);GLES20.glEnable(GLES20.GL_CULL_FACE);GLES20.glCullFace(GLES20.GL_BACK);GLES20.glEnable(GLES20.GL_BLEND);GLES20.glBlendFunc(GLES20.GL_SRC_ALPHA,GLES20.GL_ONE_MINUS_SRC_ALPHA);
            program=buildProgram(VS,FS);aPos=GLES20.glGetAttribLocation(program,"aPos");aNormal=GLES20.glGetAttribLocation(program,"aNormal");aPart=GLES20.glGetAttribLocation(program,"aPart");uMvp=GLES20.glGetUniformLocation(program,"uMvp");uModel=GLES20.glGetUniformLocation(program,"uModel");uColor=GLES20.glGetUniformLocation(program,"uColor");uLightDir=GLES20.glGetUniformLocation(program,"uLightDir");uThrottle=GLES20.glGetUniformLocation(program,"uThrottle");uSurfPitch=GLES20.glGetUniformLocation(program,"uSurfPitch");uSurfRoll=GLES20.glGetUniformLocation(program,"uSurfRoll");uSurfYaw=GLES20.glGetUniformLocation(program,"uSurfYaw");uGear=GLES20.glGetUniformLocation(program,"uGear");uMainComp=GLES20.glGetUniformLocation(program,"uMainComp");uNoseComp=GLES20.glGetUniformLocation(program,"uNoseComp");
            ProceduralFighterMesh.Mesh mesh=ProceduralFighterMesh.build();ByteBuffer bb=ByteBuffer.allocateDirect(mesh.data.length*4).order(ByteOrder.nativeOrder());vertices=bb.asFloatBuffer();vertices.put(mesh.data).position(0);vertexCount=mesh.vertexCount();lastNs=System.nanoTime();
        }
        @Override public void onSurfaceChanged(GL10 gl,int width,int height){GLES20.glViewport(0,0,width,height);float aspect=Math.max(.1f,(float)width/Math.max(1,height));Matrix.perspectiveM(projection,0,34f,aspect,.1f,150f);}
        @Override public void onDrawFrame(GL10 gl){
            long now=System.nanoTime();float dt=Math.min(.05f,Math.max(.001f,(now-lastNs)/1_000_000_000f));lastNs=now;float k=1f-(float)Math.exp(-dt*8f);roll+=shortest(targetRoll-roll)*k;pitch+=(targetPitch-pitch)*k;yaw+=shortest(targetYaw-yaw)*k*.65f;float kg=1f-(float)Math.exp(-dt*4f);gear+=(targetGear-gear)*kg;mainComp+=(targetMainComp-mainComp)*kg;noseComp+=(targetNoseComp-noseComp)*kg;brake+=(targetBrake-brake)*kg;
            GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);setCamera();Matrix.multiplyMM(vp,0,projection,0,view,0);Matrix.setIdentityM(model,0);Matrix.rotateM(model,0,-yaw*.30f,0,1,0);Matrix.rotateM(model,0,pitch,1,0,0);Matrix.rotateM(model,0,-roll,0,0,1);Matrix.multiplyMM(mvp,0,vp,0,model,0);
            GLES20.glUseProgram(program);GLES20.glUniformMatrix4fv(uMvp,1,false,mvp,0);GLES20.glUniformMatrix4fv(uModel,1,false,model,0);float boost=live?throttle:0f;GLES20.glUniform4f(uColor,.31f+.045f*boost,.34f+.045f*boost,.37f+.05f*boost,1f);GLES20.glUniform3f(uLightDir,-.35f,.82f,-.45f);GLES20.glUniform1f(uThrottle,boost);GLES20.glUniform1f(uGear,gear);GLES20.glUniform1f(uMainComp,mainComp);GLES20.glUniform1f(uNoseComp,noseComp);GLES20.glUniform1f(uSurfPitch,clamp(targetPitch/25f,-1f,1f));GLES20.glUniform1f(uSurfRoll,clamp(targetRoll/45f,-1f,1f));GLES20.glUniform1f(uSurfYaw,clamp(targetYaw/45f,-1f,1f));
            final int stride=28;vertices.position(0);GLES20.glEnableVertexAttribArray(aPos);GLES20.glVertexAttribPointer(aPos,3,GLES20.GL_FLOAT,false,stride,vertices);vertices.position(3);GLES20.glEnableVertexAttribArray(aNormal);GLES20.glVertexAttribPointer(aNormal,3,GLES20.GL_FLOAT,false,stride,vertices);vertices.position(6);GLES20.glEnableVertexAttribArray(aPart);GLES20.glVertexAttribPointer(aPart,1,GLES20.GL_FLOAT,false,stride,vertices);GLES20.glDrawArrays(GLES20.GL_TRIANGLES,0,vertexCount);GLES20.glDisableVertexAttribArray(aPos);GLES20.glDisableVertexAttribArray(aNormal);GLES20.glDisableVertexAttribArray(aPart);
        }
        private void setCamera(){switch(cameraMode){case 1:Matrix.setLookAtM(view,0,0,2.4f,12.8f,0,0,.5f,0,1,0);break;case 2:Matrix.setLookAtM(view,0,10.5f,7f,13.8f,0,0,.2f,0,1,0);break;case 3:Matrix.setLookAtM(view,0,-13.5f,4.5f,5.5f,0,0,.8f,0,1,0);break;default:Matrix.setLookAtM(view,0,0,4.8f,18.2f,0,0,-.6f,0,1,0);}}
        private static float shortest(float d){while(d>180f)d-=360f;while(d<-180f)d+=360f;return d;}private static float clamp(float v,float a,float b){return Math.max(a,Math.min(b,v));}
        private static int buildProgram(String vs,String fs){int v=compile(GLES20.GL_VERTEX_SHADER,vs),f=compile(GLES20.GL_FRAGMENT_SHADER,fs),p=GLES20.glCreateProgram();GLES20.glAttachShader(p,v);GLES20.glAttachShader(p,f);GLES20.glLinkProgram(p);int[]ok=new int[1];GLES20.glGetProgramiv(p,GLES20.GL_LINK_STATUS,ok,0);if(ok[0]==0)throw new RuntimeException(GLES20.glGetProgramInfoLog(p));return p;}
        private static int compile(int type,String src){int s=GLES20.glCreateShader(type);GLES20.glShaderSource(s,src);GLES20.glCompileShader(s);int[]ok=new int[1];GLES20.glGetShaderiv(s,GLES20.GL_COMPILE_STATUS,ok,0);if(ok[0]==0)throw new RuntimeException(GLES20.glGetShaderInfoLog(s));return s;}
        private static final String VS="uniform mat4 uMvp;uniform mat4 uModel;uniform float uSurfPitch;uniform float uSurfRoll;uniform float uSurfYaw;uniform float uThrottle;uniform float uGear;uniform float uMainComp;uniform float uNoseComp;attribute vec3 aPos;attribute vec3 aNormal;attribute float aPart;varying vec3 vN;varying float vPart;varying float vThr;varying float vGear;mat2 r(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}void main(){vec3 p=aPos;vec3 n=aNormal;float deg=.0174532925;if(aPart>1.5&&aPart<2.5){float cx=p.x<0.0?-.70:.70;float t=clamp((p.z-3.06)/.58,0.0,1.0);float s=mix(1.0,.91+.17*uThrottle,t);p.x=cx+(p.x-cx)*s;p.y=-.10+(p.y+.10)*s;}else if(aPart>20.5&&aPart<21.5){float cx=p.x<0.0?-.70:.70;float t=clamp((p.z-3.30)/.42,0.0,1.0);float s=mix(1.0,.90+.19*uThrottle,t);p.x=cx+(p.x-cx)*s;p.y=-.10+(p.y+.10)*s;}else if(aPart>3.5&&aPart<5.5){float side=aPart<4.5?-1.0:1.0;float a=(-uSurfPitch*18.0+side*uSurfRoll*10.0)*deg;p.yz=r(a)*(p.yz-vec2(.18,2.15))+vec2(.18,2.15);n.yz=r(a)*n.yz;}else if(aPart>5.5&&aPart<7.5){float a=uSurfYaw*16.0*deg;p.xz=r(a)*(p.xz-vec2(0.0,2.15))+vec2(0.0,2.15);n.xz=r(a)*n.xz;}else if(aPart>8.5&&aPart<10.5){float side=aPart<9.5?-1.0:1.0;float a=(-uSurfPitch*8.0+side*uSurfRoll*20.0)*deg;p.yz=r(a)*(p.yz-vec2(.16,.88))+vec2(.16,.88);n.yz=r(a)*n.yz;}else if(aPart>7.5&&aPart<8.5){p.z=3.84+(p.z-3.84)*(0.05+1.20*uThrottle);p.x=(p.x<0.0?-.70:.70)+(p.x-(p.x<0.0?-.70:.70))*(.78+.24*uThrottle);}else if(aPart>21.5&&aPart<22.5){p.z=3.88+(p.z-3.88)*(0.03+1.00*uThrottle);}else if(aPart>12.5&&aPart<14.5){float nose=p.z< -2.0?1.0:0.0;float comp=mix(uMainComp,uNoseComp,nose);p.y+=comp*.34;float retract=1.0-uGear;p.y+=1.48*retract;p.z+=(p.z< -2.0?.72:-.42)*retract;p.x*=mix(1.0,.68,retract);}else if(aPart>14.5&&aPart<15.5){float retract=1.0-uGear;float side=p.x<0.0?-1.0:1.0;float doorOpen=sin(uGear*3.14159265);p.x+=side*doorOpen*.34;p.y-=doorOpen*.16;p.y+=retract*.52;}vN=normalize(mat3(uModel)*n);vPart=aPart;vThr=uThrottle;vGear=uGear;gl_Position=uMvp*vec4(p,1.0);}";
        private static final String FS="precision mediump float;uniform vec4 uColor;uniform vec3 uLightDir;varying vec3 vN;varying float vPart;varying float vThr;varying float vGear;void main(){float nd=max(dot(normalize(vN),normalize(uLightDir)),0.0);float rim=pow(1.0-max(abs(vN.z),0.0),2.0);float light=.22+.70*nd+.10*rim;vec3 c=uColor.rgb;float emissive=0.0;float alpha=1.0;if(vPart>.5&&vPart<1.5){float glass=.10+.34*rim;c=mix(vec3(.008,.015,.022),vec3(.055,.095,.115),glass+.12*nd);alpha=.975;}else if(vPart>1.5&&vPart<2.5)c=mix(vec3(.08,.075,.07),vec3(.42,.32,.20),.24+.50*nd)+vec3(.12,.03,0.0)*vThr;else if(vPart>2.5&&vPart<3.5)c=vec3(.055,.065,.07);else if(vPart>7.5&&vPart<8.5){c=mix(vec3(.10,.30,1.0),vec3(1.0,.24,.015),smoothstep(.35,1.0,vThr));emissive=.25+1.75*vThr;alpha=smoothstep(.08,.42,vThr)*.82;}else if(vPart>10.5&&vPart<11.5)c=vec3(.020,.026,.030);else if(vPart>11.5&&vPart<12.5)c=mix(vec3(.014,.014,.016),vec3(.12,.07,.035),.25+.55*vThr);else if(vPart>12.5&&vPart<13.5)c=vec3(.32,.34,.36);else if(vPart>13.5&&vPart<14.5)c=vec3(.025,.027,.029);else if(vPart>14.5&&vPart<15.5)c=vec3(.24,.27,.29);else if(vPart>15.5&&vPart<16.5)c=vec3(.020,.024,.027);else if(vPart>16.5&&vPart<17.5)c=vec3(.055,.060,.064);else if(vPart>17.5&&vPart<18.5)c=vec3(.018,.022,.024);else if(vPart>18.5&&vPart<19.5)c=vec3(.008,.012,.015);else if(vPart>19.5&&vPart<20.5)c=mix(vec3(.025,.030,.032),vec3(.20,.22,.23),.20+.62*nd);else if(vPart>20.5&&vPart<21.5)c=mix(vec3(.11,.105,.095),vec3(.38,.32,.25),.22+.58*nd)+vec3(.10,.025,0.0)*vThr;else if(vPart>21.5&&vPart<22.5){c=mix(vec3(.55,.72,1.0),vec3(1.0,.88,.62),vThr);emissive=.70+2.10*vThr;alpha=smoothstep(.18,.48,vThr)*.92;}gl_FragColor=vec4(c*(emissive>0.0?emissive:light),alpha);}";
    }
}
