package com.mg.fixturecockpitsim;

import android.content.Context;
import android.graphics.PixelFormat;
import android.opengl.GLES20;
import android.opengl.GLSurfaceView;
import android.opengl.Matrix;
import android.view.MotionEvent;
import java.nio.*;
import java.util.*;
import javax.microedition.khronos.egl.EGLConfig;
import javax.microedition.khronos.opengles.GL10;

/** V13 game/simulation renderer. Uses public F-22 dimensional/silhouette references.
 *  Twin vertical tails are closed 3D prisms and back-face culling is intentionally
 *  disabled so neither tail can disappear at steep bank/camera angles.
 */
public final class Jet3DViewV13 extends GLSurfaceView {
    private final R r;
    public Jet3DViewV13(Context c){super(c);setEGLContextClientVersion(2);getHolder().setFormat(PixelFormat.TRANSLUCENT);setZOrderOnTop(false);r=new R();setRenderer(r);setRenderMode(RENDERMODE_CONTINUOUSLY);setPreserveEGLContextOnPause(true);}
    public void setTelemetry(float roll,float pitch,float yaw,float thr,float hz,int drops,boolean live){r.set(roll,pitch,yaw,thr,live);}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_UP)r.nextCamera();return true;}

    private static final class R implements Renderer{
        final float[] proj=new float[16],view=new float[16],model=new float[16],mv=new float[16],mvp=new float[16];
        float tr,tp,ty,thr=.72f,roll,pitch,yaw,vr,vp,vy;boolean live;long last;int cam,program,aP,aN,aC,uMvp,uModel,uLight,uEm,uGloss;float camBlend=1f;Mesh airframe,glass,nozzles,flame;
        void set(float a,float b,float c,float t,boolean l){tr=a;tp=b;ty=c;thr=t;live=l;}void nextCamera(){cam=(cam+1)%5;camBlend=0f;}
        @Override public void onSurfaceCreated(GL10 gl,EGLConfig cfg){GLES20.glClearColor(0,0,0,0);GLES20.glEnable(GLES20.GL_DEPTH_TEST);GLES20.glDisable(GLES20.GL_CULL_FACE);GLES20.glEnable(GLES20.GL_BLEND);GLES20.glBlendFunc(GLES20.GL_SRC_ALPHA,GLES20.GL_ONE_MINUS_SRC_ALPHA);program=prog(VS,FS);aP=GLES20.glGetAttribLocation(program,"aPos");aN=GLES20.glGetAttribLocation(program,"aNormal");aC=GLES20.glGetAttribLocation(program,"aColor");uMvp=GLES20.glGetUniformLocation(program,"uMvp");uModel=GLES20.glGetUniformLocation(program,"uModel");uLight=GLES20.glGetUniformLocation(program,"uLight");uEm=GLES20.glGetUniformLocation(program,"uEmissive");uGloss=GLES20.glGetUniformLocation(program,"uGloss");airframe=buildAirframe();glass=buildGlass();nozzles=buildNozzles();flame=buildFlame();last=System.nanoTime();}
        @Override public void onSurfaceChanged(GL10 gl,int w,int h){GLES20.glViewport(0,0,w,h);Matrix.perspectiveM(proj,0,36f,(float)w/Math.max(1,h),.08f,160f);}
        @Override public void onDrawFrame(GL10 gl){long n=System.nanoTime();float dt=Math.min(.035f,Math.max(.001f,(n-last)/1e9f));last=n;float kr=20,kp=19,ky=11,dam=2f*(float)Math.sqrt(kr);vr+=(shortest(tr-roll)*kr-vr*dam)*dt;roll+=vr*dt;dam=2f*(float)Math.sqrt(kp);vp+=((tp-pitch)*kp-vp*dam)*dt;pitch+=vp*dt;dam=2f*(float)Math.sqrt(ky);vy+=(shortest(ty-yaw)*ky-vy*dam)*dt;yaw+=vy*dt;camBlend=Math.min(1f,camBlend+dt*1.7f);GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);camera();Matrix.setIdentityM(model,0);Matrix.rotateM(model,0,-yaw*.12f,0,1,0);Matrix.rotateM(model,0,pitch,1,0,0);Matrix.rotateM(model,0,-roll,0,0,1);Matrix.multiplyMM(mv,0,view,0,model,0);Matrix.multiplyMM(mvp,0,proj,0,mv,0);GLES20.glUseProgram(program);GLES20.glUniformMatrix4fv(uMvp,1,false,mvp,0);GLES20.glUniformMatrix4fv(uModel,1,false,model,0);GLES20.glUniform3f(uLight,-.42f,.82f,.56f);draw(airframe,.62f,0);draw(nozzles,.28f,0);draw(glass,.96f,0);if(live&&thr>.44f)draw(flame,0,.78f+.18f*(float)Math.sin(n/42_000_000.0));}
        void draw(Mesh m,float gloss,float em){GLES20.glUniform1f(uGloss,gloss);GLES20.glUniform1f(uEm,em);m.draw(aP,aN,aC);}
        void camera(){float[][] e={{0,2.55f,10.2f},{0,1.65f,7.15f},{5.3f,3.45f,6.7f},{-6.0f,2.4f,4.8f},{0,5.9f,5.7f}};float[]q=e[cam];float s=camBlend*camBlend*(3-2*camBlend);Matrix.setLookAtM(view,0,q[0]*s,2.55f+(q[1]-2.55f)*s,10.2f+(q[2]-10.2f)*s,0,.03f,-.18f,0,1,0);}static float shortest(float d){while(d>180)d-=360;while(d<-180)d+=360;return d;}

        Mesh buildAirframe(){B b=new B();float[] top={.56f,.58f,.60f,1},top2={.50f,.52f,.55f,1},side={.42f,.45f,.48f,1},under={.36f,.39f,.42f,1};
            // F-22-like slender nose, blended chines, wide centerbody and twin-engine rear deck.
            float[] z={-4.72f,-4.48f,-4.12f,-3.70f,-3.18f,-2.58f,-1.92f,-1.20f,-.45f,.30f,1.02f,1.68f,2.22f,2.66f,2.96f};
            float[] wx={.01f,.06f,.14f,.27f,.43f,.60f,.76f,.88f,.96f,1.02f,1.04f,1.00f,.91f,.78f,.62f};
            float[] hy={.01f,.035f,.08f,.14f,.22f,.31f,.39f,.46f,.50f,.51f,.49f,.45f,.39f,.31f,.22f};
            b.smoothLoft(z,wx,hy,32,top,side,under,0);
            chine(b,-1,top2,side);chine(b,1,top2,side);wing(b,-1,top,top2,side,under);wing(b,1,top,top2,side,under);htail(b,-1,top,side);htail(b,1,top,side);vtail(b,-.77f,-1,top2,side);vtail(b,.77f,1,top2,side);
            b.roundBox(-.48f,-.08f,1.42f,.72f,.50f,2.28f,14,top2,side);b.roundBox(.48f,-.08f,1.42f,.72f,.50f,2.28f,14,top2,side);
            float[] intake={.16f,.18f,.20f,1};b.q(p(-1.03f,-.12f,-1.24f),p(-.58f,-.18f,-.46f),p(-.53f,.18f,-.40f),p(-.91f,.20f,-1.18f),intake);b.q(p(.58f,-.18f,-.46f),p(1.03f,-.12f,-1.24f),p(.91f,.20f,-1.18f),p(.53f,.18f,-.40f),intake);
            return b.mesh();}
        Mesh buildGlass(){B b=new B();float[] g={.018f,.085f,.12f,.96f};b.smoothLoft(new float[]{-2.65f,-2.30f,-1.92f,-1.52f,-1.18f},new float[]{.03f,.17f,.28f,.30f,.11f},new float[]{.02f,.13f,.23f,.25f,.08f},28,g,g,g,.48f);return b.mesh();}
        Mesh buildNozzles(){B b=new B();float[] n={.08f,.085f,.09f,1},rim={.20f,.21f,.22f,1};b.tube(-.49f,-.12f,3.03f,.30f,.38f,36,n);b.tube(.49f,-.12f,3.03f,.30f,.38f,36,n);b.tube(-.49f,-.12f,3.24f,.33f,.08f,36,rim);b.tube(.49f,-.12f,3.24f,.33f,.08f,36,rim);return b.mesh();}
        Mesh buildFlame(){B b=new B();float[] o={1,.18f,.015f,.72f},i={1,.72f,.08f,.94f};b.cone(-.49f,-.12f,3.28f,.24f,1.42f,32,o);b.cone(.49f,-.12f,3.28f,.24f,1.42f,32,o);b.cone(-.49f,-.12f,3.30f,.11f,.86f,24,i);b.cone(.49f,-.12f,3.30f,.11f,.86f,24,i);return b.mesh();}
        static void chine(B b,float s,float[]t,float[]d){b.q(p(s*.36f,.20f,-3.12f),p(s*.90f,.18f,-2.02f),p(s*1.28f,.11f,-.72f),p(s*.64f,.24f,-1.06f),t);b.q(p(s*.64f,.24f,-1.06f),p(s*1.28f,.11f,-.72f),p(s*.98f,.10f,.70f),p(s*.58f,.20f,.25f),d);}
        static void wing(B b,float s,float[]top,float[]root,float[]side,float[]bot){float yt=.10f,yb=-.075f;float[] a=p(s*.62f,yt,-1.92f),m=p(s*1.45f,yt,-1.16f),c=p(s*3.34f,yt,-.18f),d=p(s*2.62f,yt,1.28f),e=p(s*.78f,yt,1.18f);float[]a2=p(a[0],yb,a[2]),m2=p(m[0],yb,m[2]),c2=p(c[0],yb,c[2]),d2=p(d[0],yb,d[2]),e2=p(e[0],yb,e[2]);b.q(a,m,c,e,root);b.t(c,d,e,top);b.q(e2,d2,c2,a2,bot);b.t(a2,c2,m2,bot);b.q(a,a2,m2,m,side);b.q(m,m2,c2,c,side);b.q(c,c2,d2,d,side);b.q(d,d2,e2,e,side);}
        static void htail(B b,float s,float[]t,float[]d){float y=.045f;b.q(p(s*.60f,y,1.33f),p(s*2.05f,y,1.82f),p(s*1.66f,y,2.72f),p(s*.65f,y,2.28f),t);b.q(p(s*.65f,y-.035f,2.28f),p(s*1.66f,y-.035f,2.72f),p(s*2.05f,y-.035f,1.82f),p(s*.60f,y-.035f,1.33f),d);}
        static void vtail(B b,float x,float s,float[]t,float[]d){float th=.035f;float[]a=p(x-th,.22f,1.02f),bb=p(x+s*.43f-th,1.73f,1.46f),c=p(x+s*.49f-th,1.37f,2.70f),e=p(x-th,.24f,2.36f);float[]a2=p(x+th,.22f,1.02f),b2=p(x+s*.43f+th,1.73f,1.46f),c2=p(x+s*.49f+th,1.37f,2.70f),e2=p(x+th,.24f,2.36f);b.q(a,bb,c,e,t);b.q(a2,e2,c2,b2,t);b.q(a,a2,b2,bb,d);b.q(bb,b2,c2,c,d);b.q(c,c2,e2,e,d);b.q(e,e2,a2,a,d);}
        static int prog(String v,String f){int a=sh(GLES20.GL_VERTEX_SHADER,v),b=sh(GLES20.GL_FRAGMENT_SHADER,f),p=GLES20.glCreateProgram();GLES20.glAttachShader(p,a);GLES20.glAttachShader(p,b);GLES20.glLinkProgram(p);return p;}static int sh(int t,String s){int a=GLES20.glCreateShader(t);GLES20.glShaderSource(a,s);GLES20.glCompileShader(a);return a;}
        static final String VS="uniform mat4 uMvp;uniform mat4 uModel;attribute vec3 aPos;attribute vec3 aNormal;attribute vec4 aColor;varying vec3 n;varying vec4 c;void main(){n=normalize(mat3(uModel)*aNormal);c=aColor;gl_Position=uMvp*vec4(aPos,1.0);}";
        static final String FS="precision mediump float;uniform vec3 uLight;uniform float uEmissive;uniform float uGloss;varying vec3 n;varying vec4 c;void main(){vec3 N=normalize(n);vec3 L=normalize(uLight);float diff=max(0.0,dot(N,L));float fres=pow(1.0-abs(N.z),2.3);float spec=pow(max(0.0,dot(reflect(-L,N),vec3(0.0,0.22,0.98))),34.0)*uGloss;float l=.30+.62*diff+.18*fres+spec+uEmissive;gl_FragColor=vec4(c.rgb*l,c.a);}";
    }
    static final class Mesh{final FloatBuffer p,n,c;final int count;Mesh(float[]a,float[]b,float[]d){p=buf(a);n=buf(b);c=buf(d);count=a.length/3;}void draw(int ap,int an,int ac){GLES20.glEnableVertexAttribArray(ap);GLES20.glVertexAttribPointer(ap,3,GLES20.GL_FLOAT,false,0,p);GLES20.glEnableVertexAttribArray(an);GLES20.glVertexAttribPointer(an,3,GLES20.GL_FLOAT,false,0,n);GLES20.glEnableVertexAttribArray(ac);GLES20.glVertexAttribPointer(ac,4,GLES20.GL_FLOAT,false,0,c);GLES20.glDrawArrays(GLES20.GL_TRIANGLES,0,count);}static FloatBuffer buf(float[]a){FloatBuffer b=ByteBuffer.allocateDirect(a.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();b.put(a).position(0);return b;}}
    static final class B{final ArrayList<Float>P=new ArrayList<>(),N=new ArrayList<>(),C=new ArrayList<>();void add(float[]v,float[]n,float[]co){for(float x:v)P.add(x);for(float x:n)N.add(x);for(float x:co)C.add(x);}void t(float[]a,float[]b,float[]c,float[]co){float[]n=norm(a,b,c);add(a,n,co);add(b,n,co);add(c,n,co);}void q(float[]a,float[]b,float[]c,float[]d,float[]co){t(a,b,c,co);t(a,c,d,co);}void smoothLoft(float[]z,float[]wx,float[]hy,int seg,float[]top,float[]side,float[]bottom,float yOff){for(int k=0;k<z.length-1;k++)for(int i=0;i<seg;i++){double a=2*Math.PI*i/seg,bb=2*Math.PI*(i+1)/seg;float[]p0=p((float)Math.cos(a)*wx[k],yOff+(float)Math.sin(a)*hy[k],z[k]),p1=p((float)Math.cos(bb)*wx[k],yOff+(float)Math.sin(bb)*hy[k],z[k]),p2=p((float)Math.cos(bb)*wx[k+1],yOff+(float)Math.sin(bb)*hy[k+1],z[k+1]),p3=p((float)Math.cos(a)*wx[k+1],yOff+(float)Math.sin(a)*hy[k+1],z[k+1]);float[]n0=loftN(a,wx[k],hy[k]),n1=loftN(bb,wx[k],hy[k]),n2=loftN(bb,wx[k+1],hy[k+1]),n3=loftN(a,wx[k+1],hy[k+1]);float mid=(float)Math.sin((a+bb)/2),coo=mid>.18?1:(mid<-.35?-1:0);float[]co=coo>0?top:(coo<0?bottom:side);add(p0,n0,co);add(p1,n1,co);add(p2,n2,co);add(p0,n0,co);add(p2,n2,co);add(p3,n3,co);}}static float[]loftN(double a,float wx,float hy){float nx=(float)Math.cos(a)/Math.max(.01f,wx),ny=(float)Math.sin(a)/Math.max(.01f,hy),l=(float)Math.sqrt(nx*nx+ny*ny);return new float[]{nx/l,ny/l,0};}void roundBox(float cx,float cy,float cz,float sx,float sy,float sz,int seg,float[]top,float[]side){float[]z={cz-sz/2,cz+sz/2},wx={sx/2,sx/2},hy={sy/2,sy/2};smoothLoft(z,wx,hy,seg,top,side,side,cy);}void tube(float cx,float cy,float z,float r,float len,int seg,float[]co){for(int i=0;i<seg;i++){double a=2*Math.PI*i/seg,bb=2*Math.PI*(i+1)/seg;float[]p0=p(cx+(float)Math.cos(a)*r,cy+(float)Math.sin(a)*r,z-len/2),p1=p(cx+(float)Math.cos(bb)*r,cy+(float)Math.sin(bb)*r,z-len/2),p2=p(cx+(float)Math.cos(bb)*r,cy+(float)Math.sin(bb)*r,z+len/2),p3=p(cx+(float)Math.cos(a)*r,cy+(float)Math.sin(a)*r,z+len/2);q(p0,p1,p2,p3,co);}}void cone(float cx,float cy,float z,float r,float len,int seg,float[]co){float[]tip=p(cx,cy,z+len);for(int i=0;i<seg;i++){double a=2*Math.PI*i/seg,bb=2*Math.PI*(i+1)/seg;t(p(cx+(float)Math.cos(a)*r,cy+(float)Math.sin(a)*r,z),p(cx+(float)Math.cos(bb)*r,cy+(float)Math.sin(bb)*r,z),tip,co);}}Mesh mesh(){return new Mesh(arr(P),arr(N),arr(C));}static float[]arr(ArrayList<Float>a){float[]r=new float[a.size()];for(int i=0;i<r.length;i++)r[i]=a.get(i);return r;}static float[]norm(float[]a,float[]b,float[]c){float ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=(float)Math.sqrt(nx*nx+ny*ny+nz*nz);if(l<1e-6)l=1;return new float[]{nx/l,ny/l,nz/l};}}
    static float[]p(float x,float y,float z){return new float[]{x,y,z};}
}
