package com.mg.fixturecockpitsim;
import android.content.Context;import android.graphics.PixelFormat;import android.opengl.*;import android.view.MotionEvent;import com.mg.fixturecockpitsim.visual.ProceduralFighterMesh;import java.nio.*;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;
/** AVM-8.8 renderer: landing gear is positively contained in lower bays and never crosses the upper skin. */
public final class Jet3DView extends GLSurfaceView{
 public static final int CAMERA_CHASE=0,CAMERA_REAR=1,CAMERA_RIGHT_QUARTER=2,CAMERA_LEFT_QUARTER=3;private final R r;private final FlightSoundEngine sound=new FlightSoundEngine();private float sndThrottle=.6f,sndGear=1f,sndBrake;private boolean sndGround=true;
 public Jet3DView(Context c){super(c);setEGLContextClientVersion(2);setEGLConfigChooser(8,8,8,8,16,0);getHolder().setFormat(PixelFormat.TRANSLUCENT);setZOrderOnTop(true);r=new R();setRenderer(r);setRenderMode(RENDERMODE_CONTINUOUSLY);setPreserveEGLContextOnPause(true);}public void setTelemetry(float a,float b,float c,float d,float e,int x,boolean live){r.tele(a,b,c,d,live);sndThrottle=Math.max(0,Math.min(1,d));sound.update(sndThrottle,Math.max(0,sndThrottle*230f),sndGear,sndBrake,sndGround);}public void setSimulationState(float g,float mc,float nc,float b,boolean ground){r.sim(g,mc,nc);sndGear=g;sndBrake=b;sndGround=ground;sound.update(sndThrottle,Math.max(0,sndThrottle*230f),sndGear,sndBrake,sndGround);}public void setCameraMode(int m){r.cam=Math.max(0,Math.min(3,m));}public int getCameraMode(){return r.cam;}public boolean onTouchEvent(MotionEvent e){if(e.getAction()==1)r.cam=(r.cam+1)%4;return true;}@Override public void onResume(){super.onResume();sound.start();}@Override public void onPause(){sound.stop();super.onPause();}
 private static final class R implements Renderer{float[] pr=new float[16],vw=new float[16],md=new float[16],vp=new float[16],mvp=new float[16];volatile float tr,tp,ty,thr=.6f,tg=1,tm,tn;float roll,pitch,yaw,gear=1,mc,nc;volatile boolean live;volatile int cam;int pg,ap,an,apart,umvp,umodel,uc,ul,ut,usp,usr,usy,ug,um,un;FloatBuffer vb;int count;long last;
  void tele(float a,float b,float c,float d,boolean x){tr=a;tp=b;ty=c;thr=cl(d,0,1);live=x;}void sim(float g,float m,float n){tg=cl(g,0,1);tm=cl(m,0,1);tn=cl(n,0,1);}
  public void onSurfaceCreated(GL10 g,EGLConfig e){GLES20.glClearColor(0,0,0,0);GLES20.glEnable(GLES20.GL_DEPTH_TEST);GLES20.glEnable(GLES20.GL_CULL_FACE);GLES20.glEnable(GLES20.GL_BLEND);GLES20.glBlendFunc(GLES20.GL_SRC_ALPHA,GLES20.GL_ONE_MINUS_SRC_ALPHA);pg=prog(VS,FS);ap=GLES20.glGetAttribLocation(pg,"aPos");an=GLES20.glGetAttribLocation(pg,"aNormal");apart=GLES20.glGetAttribLocation(pg,"aPart");umvp=GLES20.glGetUniformLocation(pg,"uMvp");umodel=GLES20.glGetUniformLocation(pg,"uModel");uc=GLES20.glGetUniformLocation(pg,"uColor");ul=GLES20.glGetUniformLocation(pg,"uLightDir");ut=GLES20.glGetUniformLocation(pg,"uThrottle");usp=GLES20.glGetUniformLocation(pg,"uSurfPitch");usr=GLES20.glGetUniformLocation(pg,"uSurfRoll");usy=GLES20.glGetUniformLocation(pg,"uSurfYaw");ug=GLES20.glGetUniformLocation(pg,"uGear");um=GLES20.glGetUniformLocation(pg,"uMainComp");un=GLES20.glGetUniformLocation(pg,"uNoseComp");ProceduralFighterMesh.Mesh m=ProceduralFighterMesh.build();vb=ByteBuffer.allocateDirect(m.data.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();vb.put(m.data).position(0);count=m.vertexCount();last=System.nanoTime();}
  public void onSurfaceChanged(GL10 g,int w,int h){GLES20.glViewport(0,0,w,h);Matrix.perspectiveM(pr,0,34,(float)w/Math.max(1,h),.1f,150);}
  public void onDrawFrame(GL10 g){long n=System.nanoTime();float dt=Math.min(.05f,Math.max(.001f,(n-last)/1e9f));last=n;float k=1-(float)Math.exp(-dt*8),kg=1-(float)Math.exp(-dt*2.35);roll+=shortest(tr-roll)*k;pitch+=(tp-pitch)*k;yaw+=shortest(ty-yaw)*k*.65f;gear+=(tg-gear)*kg;mc+=(tm-mc)*kg;nc+=(tn-nc)*kg;GLES20.glClear(16640);camera();Matrix.multiplyMM(vp,0,pr,0,vw,0);Matrix.setIdentityM(md,0);Matrix.rotateM(md,0,-yaw*.3f,0,1,0);Matrix.rotateM(md,0,pitch,1,0,0);Matrix.rotateM(md,0,-roll,0,0,1);Matrix.multiplyMM(mvp,0,vp,0,md,0);GLES20.glUseProgram(pg);GLES20.glUniformMatrix4fv(umvp,1,false,mvp,0);GLES20.glUniformMatrix4fv(umodel,1,false,md,0);float boost=live?thr:0;GLES20.glUniform4f(uc,.31f,.34f,.37f,1);GLES20.glUniform3f(ul,-.34f,.84f,-.42f);GLES20.glUniform1f(ut,boost);GLES20.glUniform1f(ug,gear);GLES20.glUniform1f(um,mc);GLES20.glUniform1f(un,nc);GLES20.glUniform1f(usp,cl(tp/25,-1,1));GLES20.glUniform1f(usr,cl(tr/45,-1,1));GLES20.glUniform1f(usy,cl(ty/45,-1,1));vb.position(0);GLES20.glEnableVertexAttribArray(ap);GLES20.glVertexAttribPointer(ap,3,5126,false,28,vb);vb.position(3);GLES20.glEnableVertexAttribArray(an);GLES20.glVertexAttribPointer(an,3,5126,false,28,vb);vb.position(6);GLES20.glEnableVertexAttribArray(apart);GLES20.glVertexAttribPointer(apart,1,5126,false,28,vb);GLES20.glDrawArrays(4,0,count);}
  void camera(){if(cam==1)Matrix.setLookAtM(vw,0,0,1.55f,10.7f,0,-.02f,2.45f,0,1,0);else if(cam==2)Matrix.setLookAtM(vw,0,10.5f,7,13.8f,0,0,.2f,0,1,0);else if(cam==3)Matrix.setLookAtM(vw,0,-13.5f,4.5f,5.5f,0,0,.8f,0,1,0);else Matrix.setLookAtM(vw,0,0,4.8f,18.2f,0,0,-.6f,0,1,0);}
  static float shortest(float d){while(d>180)d-=360;while(d<-180)d+=360;return d;}static float cl(float v,float a,float b){return Math.max(a,Math.min(b,v));}static int sh(int t,String s){int x=GLES20.glCreateShader(t);GLES20.glShaderSource(x,s);GLES20.glCompileShader(x);int[] ok=new int[1];GLES20.glGetShaderiv(x,GLES20.GL_COMPILE_STATUS,ok,0);if(ok[0]==0)throw new IllegalStateException("GLSL compile: "+GLES20.glGetShaderInfoLog(x));return x;}static int prog(String v,String f){int p=GLES20.glCreateProgram();GLES20.glAttachShader(p,sh(35633,v));GLES20.glAttachShader(p,sh(35632,f));GLES20.glLinkProgram(p);int[] ok=new int[1];GLES20.glGetProgramiv(p,GLES20.GL_LINK_STATUS,ok,0);if(ok[0]==0)throw new IllegalStateException("GLSL link: "+GLES20.glGetProgramInfoLog(p));return p;}
  static final String VS="uniform mat4 uMvp;uniform mat4 uModel;uniform float uSurfPitch,uSurfRoll,uSurfYaw,uThrottle,uGear,uMainComp,uNoseComp;attribute vec3 aPos,aNormal;attribute float aPart;varying vec3 vN;varying float vPart,vThr,vGear,vZ,vX,vRetract;mat2 rr(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}void main(){vec3 p=aPos,n=aNormal;float d=.0174532925;vRetract=0.;if(aPart>3.5&&aPart<5.5){float s=aPart<4.5?-1.:1.,a=(-uSurfPitch*18.+s*uSurfRoll*10.)*d;p.yz=rr(a)*(p.yz-vec2(.18,2.15))+vec2(.18,2.15);}else if(aPart>8.5&&aPart<10.5){float s=aPart<9.5?-1.:1.,a=(-uSurfPitch*8.+s*uSurfRoll*20.)*d;p.yz=rr(a)*(p.yz-vec2(.16,.88))+vec2(.16,.88);}else if(aPart>7.5&&aPart<8.5){p.z=3.84+(p.z-3.84)*(.05+1.2*uThrottle);}else if(aPart>12.5&&aPart<14.5){float nose=step(p.z,-2.0),r=1.-uGear,fold=smoothstep(.02,.88,r),seat=smoothstep(.62,.96,r),comp=mix(uMainComp,uNoseComp,nose);vRetract=r;p.y+=comp*.20*uGear;if(nose>.5){float qz=p.z+3.72,qy=p.y+1.66;p.x=mix(p.x,p.x*.35,fold);p.z=mix(p.z,-3.58+qz*.18,fold);p.y=mix(p.y,-.74+qy*.055,fold);}else{float side=p.x<0.?-1.:1.,ax=abs(p.x);p.x=side*mix(ax,.69+(ax-1.70)*.10,fold);p.z=mix(p.z,.83+(p.z-.84)*.12,fold);p.y=mix(p.y,-.76+(p.y+1.72)*.05,fold);}p.y=min(p.y,-.60+.18*uGear);p.y-=.06*seat;}else if(aPart>14.5&&aPart<15.5){float r=1.-uGear,opening=smoothstep(.02,.24,r)*(1.-smoothstep(.68,.96,r)),side=p.x<0.?-1.:1.;p.x+=side*.27*opening;p.y-=.10*opening;p.y=min(p.y,-.50);vRetract=r;}vN=normalize(mat3(uModel)*n);vPart=aPart;vThr=uThrottle;vGear=uGear;vZ=p.z;vX=p.x;gl_Position=uMvp*vec4(p,1.);}";
  static final String FS="precision mediump float;uniform vec4 uColor;uniform vec3 uLightDir;varying vec3 vN;varying float vPart,vThr,vGear,vZ,vX,vRetract;void main(){vec3 n=normalize(vN),c=uColor.rgb;float li=.22+.72*max(dot(n,normalize(uLightDir)),0.);float a=1.;if(vPart>.5&&vPart<1.5){c=vec3(.02,.06,.08);a=.96;}else if(vPart>7.5&&vPart<8.5){c=mix(vec3(.1,.3,1.),vec3(1.,.24,.02),vThr);li=.5+1.5*vThr;a=smoothstep(.08,.4,vThr)*.82;}else if(vPart>12.5&&vPart<13.5)c=vec3(.32,.34,.36);else if(vPart>13.5&&vPart<14.5)c=vec3(.025);else if(vPart>14.5&&vPart<15.5)c=vec3(.24,.27,.29);else if(vPart>18.5&&vPart<20.5)c=vec3(.02,.025,.028);else if(vPart>20.5&&vPart<22.5){c=vec3(.32,.18,.08);li=.5+vThr;}if(vPart>12.5&&vPart<14.5)a*=1.-smoothstep(.72,.90,vRetract);gl_FragColor=vec4(c*li,a);}";
 }
}
