package com.mg.fixturecockpitsim;
import android.content.Context;import android.graphics.*;import android.view.View;import java.util.Locale;
/** AVM-10.6 world: rebuilt hangar, apron/taxi departure, RWY27 and cinematic coast/sea transition. */
public final class RunwayHudView extends View{
 private final Paint f=new Paint(3),l=new Paint(3);private final Path p=new Path();private volatile float altitudeM,speedMps,route,groundProgress,headingDeg;private volatile boolean onGround,demoMode;private volatile String phase="";private float scroll,runwayMeters;private long last;
 public RunwayHudView(Context c){super(c);setWillNotDraw(false);f.setStyle(Paint.Style.FILL);l.setStyle(Paint.Style.STROKE);l.setStrokeCap(Paint.Cap.ROUND);}
 public void setDemoMode(boolean e){demoMode=e;postInvalidateOnAnimation();} public void setDemoProgress(double s){route=(float)Math.max(0,s);postInvalidateOnAnimation();} public void setGroundProgress(double q,double hdg){groundProgress=(float)Math.max(0,Math.min(1,q));headingDeg=(float)hdg;postInvalidateOnAnimation();} public void setFlightState(double a,double s,boolean g,String ph){altitudeM=(float)Math.max(0,a);speedMps=(float)Math.max(0,s);onGround=g;phase=ph==null?"":ph;postInvalidateOnAnimation();}
 @Override protected void onDraw(Canvas c){super.onDraw(c);long n=System.nanoTime();float dt=last==0?.016f:Math.min(.05f,(n-last)/1e9f);last=n;scroll=(scroll+speedMps*dt*.040f)%1f;if(phase.contains("TAKEOFF")||phase.contains("ROLLOUT"))runwayMeters+=speedMps*dt;if(phase.contains("HANGAR_START")||phase.contains("RUNWAY_HOLD"))runwayMeters=0;int w=getWidth(),h=getHeight();float hz=h*(.46f+.075f*Math.min(1,altitudeM/1300));sky(c,w,h,hz);if(phase.contains("HANGAR")){hangar(c,w,h,hz);return;}airport(c,w,h,hz);if(phase.contains("TAXI")){taxi(c,w,h,hz);requestMotionFrame();return;}if(demoMode&&phase.contains("ORBIT")){scenery(c,w,h,hz);requestMotionFrame();return;}if(onGround||phase.contains("RUNWAY")||phase.contains("TAKEOFF")||phase.contains("ROTATE")||phase.contains("APPROACH")||phase.contains("FLARE")||phase.contains("ROLLOUT"))runway(c,w,h,hz);requestMotionFrame();}
 private void requestMotionFrame(){if(speedMps>1)postInvalidateOnAnimation();}
 private void sky(Canvas c,int w,int h,float hz){f.setShader(new LinearGradient(0,0,0,hz,new int[]{0xff06131f,0xff356d8f,0xffa8d0e3},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,hz,f);f.setShader(null);f.setShader(new LinearGradient(0,hz*.68f,0,hz,0x00ffffff,0x46e8eef0,Shader.TileMode.CLAMP));c.drawRect(0,hz*.66f,w,hz,f);f.setShader(null);for(int i=0;i<5;i++){float drift=(route*.6f+scroll*w*.08f)%w,x=(w*(.08f+i*.22f)+drift)%w,y=hz*(.12f+(i%3)*.06f),ww=w*(.13f+(i%2)*.04f);f.setColor(0x1effffff);c.drawOval(x,y,x+ww,y+hz*.035f,f);c.drawOval(x+ww*.18f,y-hz*.016f,x+ww*.66f,y+hz*.025f,f);}f.setColor(0x20fff2c7);c.drawCircle(w*.83f,hz*.18f,w*.045f,f);}
 private void hangar(Canvas c,int w,int h,float hz){float q=phase.contains("PARK")?1-groundProgress:groundProgress,cx=w*.5f,open=clamp(.28f+q*.72f,0,1);f.setShader(new LinearGradient(0,0,0,h,new int[]{0xff0c1115,0xff151c21,0xff30373a},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,f);f.setShader(null);float doorTop=h*.18f,doorBottom=h*.79f,doorHalf=w*(.18f+.18f*open);outside(c,cx-doorHalf,doorTop,cx+doorHalf,doorBottom,w,h);
  quad(c,cx-doorHalf,doorBottom,cx+doorHalf,doorBottom,w,h,0,h,0xff303537);l.setColor(0xff525a5e);l.setStrokeWidth(2);for(int i=-8;i<=8;i++){float x=w*.5f+i*w*.072f;c.drawLine(x,h,cx+(x-cx)*.30f,doorBottom,l);}for(int i=0;i<7;i++){float z=(i+1)/7f,y=lerp(doorBottom,h,z*z);c.drawLine(0,y,w,y,l);}l.setColor(0xffdfbd2c);l.setStrokeWidth(5);c.drawLine(cx,doorBottom,cx,h,l);
  l.setColor(0xff58636a);for(int i=0;i<6;i++){float t=i/5f,y=lerp(h*.08f,doorBottom,t),half=lerp(w*.47f,doorHalf,t);l.setStrokeWidth(7-3*t);c.drawLine(cx-half,y,cx-half,doorBottom,l);c.drawLine(cx+half,y,cx+half,doorBottom,l);c.drawLine(cx-half,y,cx+half,y,l);c.drawLine(cx-half,y,cx,y-h*.06f,l);c.drawLine(cx+half,y,cx,y-h*.06f,l);}l.setStrokeWidth(3);for(int i=0;i<12;i++){float x=w*i/11f;c.drawLine(x,0,cx+(x-cx)*.34f,doorTop,l);}
  for(int i=0;i<9;i++){float x=w*(.10f+i*.10f);f.setColor(0x55fff1bf);c.drawRoundRect(x,h*.075f,x+w*.06f,h*.094f,5,5,f);f.setColor(0xffffe9a7);c.drawRoundRect(x+w*.008f,h*.080f,x+w*.052f,h*.090f,4,4,f);}
  for(int s=-1;s<=1;s+=2){float base=s<0?w*.025f:w*.865f;f.setColor(0xff3f484d);c.drawRect(base,h*.50f,base+w*.11f,h*.78f,f);f.setColor(0xff20272a);for(int k=0;k<4;k++)c.drawRect(base+w*.012f,h*(.53f+k*.055f),base+w*.098f,h*(.548f+k*.055f),f);f.setColor(0xffc52e2e);c.drawRect(base+w*.012f,h*.70f,base+w*.035f,h*.765f,f);f.setColor(0xffd8a531);c.drawCircle(base+w*.074f,h*.63f,w*.014f,f);}f.setColor(0xff70797e);c.drawRect(w*.16f,h*.62f,w*.26f,h*.67f,f);c.drawRect(w*.74f,h*.62f,w*.84f,h*.67f,f);
  f.setColor(0xff4d575d);c.drawRect(cx-doorHalf-w*.008f,doorTop,cx-doorHalf,doorBottom,f);c.drawRect(cx+doorHalf,doorTop,cx+doorHalf+w*.008f,doorBottom,f);f.setColor(0xffffd96a);c.drawRect(cx-doorHalf-w*.010f,doorBottom,cx+doorHalf+w*.010f,doorBottom+h*.008f,f);f.setColor(0xdfffffff);f.setTextSize(Math.max(16,w*.017f));c.drawText("HANGAR 01  •  TAXI CENTERLINE  •  RWY 27",w*.035f,h*.93f,f);}
 private void outside(Canvas c,float x0,float y0,float x1,float y1,int w,int h){f.setShader(new LinearGradient(0,y0,0,y1,new int[]{0xff8cc2dd,0xff83aeb8,0xff40583a},null,Shader.TileMode.CLAMP));c.drawRect(x0,y0,x1,y1,f);f.setShader(null);float cx=(x0+x1)/2;f.setColor(0xff6a6d6d);quad(c,cx-(x1-x0)*.055f,y0+(y1-y0)*.14f,cx+(x1-x0)*.055f,y0+(y1-y0)*.14f,x1,y1,x0,y1,0xff525759);l.setColor(0xffe6c52a);l.setStrokeWidth(4);c.drawLine(cx,y0+(y1-y0)*.14f,cx,y1,l);f.setColor(0xff465f42);c.drawRect(x0,y0+(y1-y0)*.38f,x1,y0+(y1-y0)*.49f,f);for(int i=0;i<5;i++){float bx=x0+(x1-x0)*(.06f+i*.19f),bw=(x1-x0)*.12f,bh=(y1-y0)*(.08f+(i%2)*.03f);f.setColor(0xff6a7377);c.drawRect(bx,y0+(y1-y0)*.38f-bh,bx+bw,y0+(y1-y0)*.38f,f);} }
 private void taxi(Canvas c,int w,int h,float hz){f.setColor(0xff3a523d);c.drawRect(0,hz,w,h,f);airportBuildings(c,w,h,hz);float cx=w*.5f,far=w*.038f,near=w*.28f;quad(c,cx-far,hz+h*.015f,cx+far,hz+h*.015f,cx+near,h,cx-near,h,0xff484d4f);quad(c,cx-far*.78f,hz+h*.015f,cx+far*.78f,hz+h*.015f,cx+near*.78f,h,cx-near*.78f,h,0xff393e40);l.setColor(0xffefc91f);l.setStrokeWidth(5);c.drawLine(cx,hz+h*.015f,cx,h,l);
  for(int i=0;i<24;i++){float q=(i/24f+scroll*.56f)%1f,z=q*q,y=lerp(hz+h*.025f,h,z),hh=lerp(far,near,z);f.setColor(0xff3793ff);float r=1.2f+4*z;c.drawCircle(cx-hh*.94f,y,r,f);c.drawCircle(cx+hh*.94f,y,r,f);if(i%3==0){l.setColor(0x335f6465);l.setStrokeWidth(1+2*z);c.drawLine(cx-hh*.72f,y,cx+hh*.72f,y,l);}}
  if(groundProgress>.56f){float y=h*.66f,hh=w*.13f;l.setColor(0xffffd33d);l.setStrokeWidth(5);c.drawLine(cx-hh,y,cx+hh,y,l);l.setStrokeWidth(2);for(int i=0;i<8;i++){float x=cx-hh+i*(2*hh/7f);c.drawLine(x,y+7,x+10,y+17,l);}f.setColor(0xddffffff);f.setTextSize(Math.max(15,w*.016f));c.drawText("RWY 27 HOLD SHORT",w*.69f,h*.72f,f);}f.setColor(0xddffffff);f.setTextSize(Math.max(14,w*.015f));c.drawText("HDG "+String.format(Locale.US,"%03.0f",norm(headingDeg))+"  •  TAXI",w*.04f,h*.92f,f);}
 private void runway(Canvas c,int w,int h,float hz){float near=1-Math.min(1,altitudeM/1050f),err=angleError(headingDeg,270f);float cx=w*.5f+clamp(err/28f,-1,1)*w*.12f,fh=w*(.017f+.012f*near),nh=w*(onGround?.45f:(.12f+.30f*near)),fy=hz+h*.014f,ny=h*(onGround?.999f:(.72f+.26f*near));terrain(c,w,h,hz);quad(c,cx-fh*1.28f,fy,cx+fh*1.28f,fy,cx+nh*1.10f,ny,cx-nh*1.10f,ny,0xff6a6d6b);quad(c,cx-fh,fy,cx+fh,fy,cx+nh,ny,cx-nh,ny,0xff25292b);for(int i=-8;i<=8;i++){float a=i/8f;l.setColor(i%3==0?0x33484a4b:0x1d0e0f10);l.setStrokeWidth(1+Math.abs(a)*1.2f);c.drawLine(cx+fh*a*.82f,fy,cx+nh*a*.82f,ny,l);}l.setColor(0xfff4f3ed);l.setStrokeWidth(Math.max(2,w*.0025f));c.drawLine(cx-fh,fy,cx-nh,ny,l);c.drawLine(cx+fh,fy,cx+nh,ny,l);for(int i=0;i<34;i++){float q=(i/34f+scroll)%1f,z=q*q,y=lerp(fy,ny,z),y2=Math.min(ny,y+4+44*z);l.setColor(0xfff5f5f0);l.setStrokeWidth(2+12*z);c.drawLine(cx,y,cx,y2,l);}for(int i=0;i<30;i++){float q=(i/30f+scroll*.62f)%1f,z=q*q,y=lerp(fy,ny,z),hh=lerp(fh,nh,z);f.setColor(i>25?0xffffd56b:0xfff3f0d8);float r=1+4*z;c.drawCircle(cx-hh,y,r,f);c.drawCircle(cx+hh,y,r,f);}for(int set=0;set<3;set++){float base=(.31f+set*.17f+scroll*.16f)%1f,z=base*base,y=lerp(fy,ny,z),hh=lerp(fh,nh,z),bw=hh*.10f,bh=5+20*z;f.setColor(0xffeeeeea);for(int s=-1;s<=1;s+=2){c.drawRect(cx+s*hh*.43f-bw,y,cx+s*hh*.43f+bw,y+bh,f);c.drawRect(cx+s*hh*.66f-bw*.72f,y,cx+s*hh*.66f+bw*.72f,y+bh,f);}}float ap=(.46f+scroll*.11f)%1f,az=ap*ap,ay=lerp(fy,ny,az),ah=lerp(fh,nh,az);f.setColor(0xfff4f4ef);c.drawRect(cx-ah*.62f,ay,cx-ah*.38f,ay+12+32*az,f);c.drawRect(cx+ah*.38f,ay,cx+ah*.62f,ay+12+32*az,f);float takeDist=phase.contains("TAKEOFF")?runwayMeters:0,nz=.49f+takeDist/300f;if(nz<=1.04f){float z=clamp(nz,0,1),y=lerp(fy,ny,z*z),hh=lerp(fh,nh,z);f.setColor(0xfffafaf5);for(int i=-5;i<=5;i++){if(i==0)continue;float x=cx+i*hh*.095f;c.drawRect(x-hh*.030f,y,x+hh*.030f,y+13+38*z,f);}f.setTextAlign(Paint.Align.CENTER);f.setTextSize(Math.max(27,w*(.033f+.030f*z)));c.drawText("27",cx,y+58+42*z,f);f.setTextAlign(Paint.Align.LEFT);}if(!onGround||phase.contains("APPROACH")||phase.contains("FLARE")){float py=lerp(fy,ny,.36f),ph=lerp(fh,nh,.36f);for(int i=0;i<4;i++){f.setColor(i<2?0xffffffff:0xffff3b30);c.drawCircle(cx-ph*1.28f+i*6,py,3.2f,f);}}if(onGround){for(int i=0;i<5;i++){float q=(i/5f+scroll*.28f)%1f,z=q*q,y=lerp(fy,ny,z),hh=lerp(fh,nh,z);f.setColor(0xff111513);c.drawRect(cx+hh*1.06f,y-5,cx+hh*1.06f+12+8*z,y+8+7*z,f);f.setColor(0xffffffff);f.setTextSize(7+8*z);c.drawText(String.valueOf(5-i),cx+hh*1.07f,y+6,f);}}if(phase.contains("APPROACH")||phase.contains("FLARE")){f.setColor(Math.abs(err)<2.5?0xff7fe889:0xffffd35a);f.setTextSize(Math.max(14,w*.015f));c.drawText(Math.abs(err)<2.5?"RWY 27 • CENTERLINE CAPTURED":"RWY 27 • ALIGNING",w*.68f,h*.92f,f);}}
 private void terrain(Canvas c,int w,int h,float hz){f.setColor(0xff314b35);c.drawRect(0,hz,w,h,f);mountains(c,w,h,hz,.22f,false);airportBuildings(c,w,h,hz);}
 private void airport(Canvas c,int w,int h,float hz){f.setColor(0xff38503a);c.drawRect(0,hz,w,hz+h*.12f,f);airportBuildings(c,w,h,hz);}
 private void airportBuildings(Canvas c,int w,int h,float hz){for(int i=0;i<7;i++){float x=w*(.02f+i*.065f),bw=w*(.042f+(i%2)*.016f),bh=h*(.028f+(i%3)*.018f);f.setColor(i%3==0?0xff6f797d:0xff565f63);c.drawRect(x,hz-bh,x+bw,hz,f);f.setColor(0x557dc2de);for(int k=0;k<3;k++)c.drawRect(x+bw*.13f+k*bw*.26f,hz-bh*.74f,x+bw*.24f+k*bw*.26f,hz-bh*.54f,f);}float tx=w*.82f;f.setColor(0xff565f63);c.drawRect(tx-5,hz-h*.105f,tx+5,hz,f);c.drawRect(tx-19,hz-h*.118f,tx+19,hz-h*.097f,f);f.setColor(0xff233039);c.drawRect(tx-14,hz-h*.115f,tx+14,hz-h*.101f,f);}
 private void scenery(Canvas c,int w,int h,float hz){float t=Math.min(300,route);if(t<45){departureCoast(c,w,h,hz,t/45f);label(c,w,h,"KIYIYA TIRMANIŞ");}else if(t<95){mountains(c,w,h,hz,.58f,false);label(c,w,h,"DAĞLARA YAKLAŞMA");}else if(t<150){mountains(c,w,h,hz,.82f,true);label(c,w,h,"VADİ İÇİ UÇUŞ");}else if(t<210){mountains(c,w,h,hz,.96f,true);road(c,w,h,hz);label(c,w,h,"DAĞ YOLU TAKİBİ");}else if(t<255){lake(c,w,h,hz);label(c,w,h,"GÖL / KIYI GEÇİŞİ");}else if(t<280){mountains(c,w,h,hz,.75f,false);label(c,w,h,"YÜKSEK ARAZİ");}else{mountains(c,w,h,hz,.34f,false);airport(c,w,h,hz);label(c,w,h,"RWY 27 İÇİN HİZALANMA");}}
 private void departureCoast(Canvas c,int w,int h,float hz,float t){float shore=hz+h*(.055f+.045f*t);mountains(c,w,h,hz,.20f+.13f*t,false);f.setColor(0xff3c573b);p.reset();p.moveTo(0,shore);for(int i=0;i<=12;i++){float x=w*i/12f,y=shore+h*.025f*(float)Math.sin(i*.9+route*.03);p.lineTo(x,y);}p.lineTo(w,h);p.lineTo(0,h);p.close();c.drawPath(p,f);float seaTop=shore+h*.065f;water(c,w,h,seaTop);f.setColor(0x66e8dfc0);p.reset();p.moveTo(0,seaTop);for(int i=0;i<=16;i++){float x=w*i/16f,y=seaTop+5*(float)Math.sin(i*.8+route*.05);p.lineTo(x,y);}l.setColor(0x88e9e1c6);l.setStrokeWidth(3);c.drawPath(p,l);}
 private void water(Canvas c,int w,int h,float top){f.setShader(new LinearGradient(0,top,0,h,new int[]{0xff4d9fba,0xff16607d,0xff072c45},null,Shader.TileMode.CLAMP));c.drawRect(0,top,w,h,f);f.setShader(null);float motion=route*11f+scroll*w*.9f;for(int i=0;i<52;i++){float z=((i*37)%100)/100f,y=top+(h-top)*(.05f+.90f*z),x=(i*113+motion*(.25f+z))%Math.max(1,w);float ww=12+w*.025f*z,hh=1.2f+2.8f*z;f.setColor(i%5==0?0x55ffffff:0x277bd0e4);c.drawOval(x,y,x+ww,y+hh,f);}for(int band=0;band<6;band++){float y=top+(h-top)*(.14f+band*.13f),amp=2+band*.8f;l.setColor(0x1fffffff);l.setStrokeWidth(1.2f);p.reset();for(int x=0;x<=w;x+=24){float yy=y+(float)Math.sin(x*.018+route*.13+band)*amp;if(x==0)p.moveTo(x,yy);else p.lineTo(x,yy);}c.drawPath(p,l);}f.setShader(new LinearGradient(w*.25f,top,w*.75f,h,0x00ffffff,0x24ffffff,Shader.TileMode.CLAMP));c.drawRect(w*.25f,top,w*.75f,h,f);f.setShader(null);}
 private void mountains(Canvas c,int w,int h,float hz,float scale,boolean valley){mountainLayer(c,w,h,hz,scale*.55f,0xff71868a,1.12f,valley);mountainLayer(c,w,h,hz,scale*.76f,0xff526a63,1.38f,valley);mountainLayer(c,w,h,hz,scale,0xff30483d,1.67f,valley);}
 private void mountainLayer(Canvas c,int w,int h,float hz,float scale,int col,float freq,boolean valley){p.reset();p.moveTo(0,h);for(int i=0;i<=22;i++){float x=w*i/22f,y=hz-h*scale*(.035f+.13f*(float)Math.abs(Math.sin(i*freq+route*.010)));if(valley&&i>9&&i<13)y+=h*.12f;p.lineTo(x,y);}p.lineTo(w,h);p.close();f.setColor(col);c.drawPath(p,f);}
 private void lake(Canvas c,int w,int h,float hz){mountains(c,w,h,hz,.56f,true);water(c,w,h,hz+h*.12f);} private void road(Canvas c,int w,int h,float hz){l.setColor(0xff6f7472);l.setStrokeWidth(Math.max(12,w*.018f));p.reset();p.moveTo(w*.10f,h);p.cubicTo(w*.38f,h*.72f,w*.32f,h*.60f,w*.61f,hz+h*.06f);c.drawPath(p,l);l.setColor(0xffe8d15a);l.setStrokeWidth(2);c.drawPath(p,l);} private void label(Canvas c,int w,int h,String s){f.setColor(0xe8ffffff);f.setTextSize(Math.max(19,w*.020f));c.drawText(s,w*.04f,h*.89f,f);}
 private void quad(Canvas c,float x1,float y1,float x2,float y2,float x3,float y3,float x4,float y4,int col){p.reset();p.moveTo(x1,y1);p.lineTo(x2,y2);p.lineTo(x3,y3);p.lineTo(x4,y4);p.close();f.setColor(col);c.drawPath(p,f);} private static float norm(float a){a%=360;if(a<0)a+=360;return a;} private static float angleError(float h,float t){float d=t-h;while(d>180)d-=360;while(d<-180)d+=360;return d;} private static float clamp(float v,float lo,float hi){return Math.max(lo,Math.min(hi,v));} private static float lerp(float a,float b,float t){return a+(b-a)*t;}
}
