package com.mg.fixturecockpitsim;
import android.content.Context;import android.graphics.*;import android.view.View;import java.util.Locale;
/** AVM-9.4 continuous airport/scenery scene with stronger forward motion and layered terrain. */
public final class RunwayHudView extends View{
 private final Paint f=new Paint(3),l=new Paint(3);private final Path p=new Path();private volatile float altitudeM,speedMps,route,groundProgress,headingDeg;private volatile boolean onGround,demoMode;private volatile String phase="";private float scroll;private long last;
 public RunwayHudView(Context c){super(c);setWillNotDraw(false);f.setStyle(Paint.Style.FILL);l.setStyle(Paint.Style.STROKE);l.setStrokeCap(Paint.Cap.ROUND);}
 public void setDemoMode(boolean e){demoMode=e;postInvalidateOnAnimation();}public void setDemoProgress(double s){route=(float)Math.max(0,s);postInvalidateOnAnimation();}public void setGroundProgress(double q,double hdg){groundProgress=(float)Math.max(0,Math.min(1,q));headingDeg=(float)hdg;postInvalidateOnAnimation();}public void setFlightState(double a,double s,boolean g,String ph){altitudeM=(float)Math.max(0,a);speedMps=(float)Math.max(0,s);onGround=g;phase=ph==null?"":ph;postInvalidateOnAnimation();}
 protected void onDraw(Canvas c){super.onDraw(c);long n=System.nanoTime();float dt=last==0?.016f:Math.min(.05f,(n-last)/1e9f);last=n;scroll=(scroll+speedMps*dt*.038f)%1f;int w=getWidth(),h=getHeight();float hz=h*(.47f+.07f*Math.min(1,altitudeM/1200));sky(c,w,h,hz);
  if(phase.contains("HANGAR")){hangarInterior(c,w,h,hz);return;}airport(c,w,h,hz);
  if(phase.contains("TAXI")){taxiway(c,w,h,hz);if(groundProgress<.28f)hangarExitOverlay(c,w,h,groundProgress/.28f);if(speedMps>1)postInvalidateOnAnimation();return;}
  if(demoMode&&phase.contains("ORBIT")){scenery(c,w,h,hz);if(speedMps>1)postInvalidateOnAnimation();return;}
  boolean rw=onGround||phase.contains("RUNWAY")||phase.contains("TAKEOFF")||phase.contains("ROTATE")||phase.contains("APPROACH")||phase.contains("FLARE")||phase.contains("ROLLOUT")||phase.contains("COMPLETE");if(rw)runway(c,w,h,hz);if(speedMps>1)postInvalidateOnAnimation();}
 private void sky(Canvas c,int w,int h,float hz){f.setShader(new LinearGradient(0,0,0,hz,0xff091a2c,0xff5c8fac,Shader.TileMode.CLAMP));c.drawRect(0,0,w,hz,f);f.setShader(null);f.setColor(0x24ffffff);for(int i=0;i<7;i++)c.drawOval(w*(.05f+i*.15f),hz*.18f+(i%2)*18,w*(.18f+i*.15f),hz*.22f+(i%2)*18,f);}
 private void hangarInterior(Canvas c,int w,int h,float hz){float q=groundProgress,cx=w*.5f;f.setColor(0xff15191c);c.drawRect(0,0,w,h,f);float doorTop=h*.19f,doorBot=h*.87f,doorHalf=w*(.19f+.12f*q);f.setShader(new LinearGradient(0,doorTop,0,doorBot,0xff80a9c1,0xff304a31,Shader.TileMode.CLAMP));c.drawRect(cx-doorHalf,doorTop,cx+doorHalf,doorBot,f);f.setShader(null);l.setColor(0xffd8c640);l.setStrokeWidth(5);c.drawLine(cx,doorBot,cx,h,l);
  f.setColor(0xff292f33);p.reset();p.moveTo(0,0);p.lineTo(cx-doorHalf,doorTop);p.lineTo(cx-doorHalf,doorBot);p.lineTo(0,h);p.close();c.drawPath(p,f);p.reset();p.moveTo(w,0);p.lineTo(cx+doorHalf,doorTop);p.lineTo(cx+doorHalf,doorBot);p.lineTo(w,h);p.close();c.drawPath(p,f);p.reset();p.moveTo(0,0);p.lineTo(w,0);p.lineTo(cx+doorHalf,doorTop);p.lineTo(cx-doorHalf,doorTop);p.close();f.setColor(0xff20262a);c.drawPath(p,f);
  l.setColor(0xff58646b);l.setStrokeWidth(3);for(int i=1;i<8;i++){float x=w*i/8f;c.drawLine(x,0,lerp(cx-doorHalf,cx+doorHalf,i/8f),doorTop,l);}for(int i=0;i<6;i++){float y=h*(.18f+i*.12f);c.drawLine(0,y,cx-doorHalf,lerp(doorTop,doorBot,i/5f),l);c.drawLine(w,y,cx+doorHalf,lerp(doorTop,doorBot,i/5f),l);}f.setColor(0xffffd76b);for(int i=0;i<9;i++)c.drawCircle(w*(.10f+i*.10f),h*.105f,3.2f,f);f.setColor(0xe8ffffff);f.setTextSize(Math.max(20,w*.022f));c.drawText(q<.45f?"HANGAR 01 • MOTOR START":"HANGAR 01 • KAPI AÇIK • TAXI",w*.04f,h*.91f,f);}
 private void hangarExitOverlay(Canvas c,int w,int h,float q){int a=(int)(220*(1-q));f.setColor((a<<24)|0x20262a);float edge=w*(.17f*(1-q));c.drawRect(0,0,edge,h,f);c.drawRect(w-edge,0,w,h,f);float top=h*(.17f*(1-q));c.drawRect(0,0,w,top,f);}
 private void taxiway(Canvas c,int w,int h,float hz){float q=groundProgress;f.setColor(0xff2d422f);c.drawRect(0,hz,w,h,f);float cx=w*.5f,farW=w*.055f,nearW=w*.24f;p.reset();p.moveTo(cx-farW,hz+h*.03f);p.lineTo(cx+farW,hz+h*.03f);p.lineTo(cx+nearW,h);p.lineTo(cx-nearW,h);p.close();f.setColor(0xff4b5052);c.drawPath(p,f);l.setColor(0xffe4c62e);l.setStrokeWidth(4);c.drawLine(cx,hz+h*.03f,cx,h,l);for(int i=0;i<15;i++){float z=(i/14f+scroll*.35f)%1f,y=lerp(hz+h*.04f,h,z*z),half=lerp(farW,nearW,z);f.setColor(0xff3c8fff);c.drawCircle(cx-half,y,2+3*z,f);c.drawCircle(cx+half,y,2+3*z,f);}if(q>.58f){float a=(q-.58f)/.42f;float split=lerp(h*.77f,h*.58f,a);f.setColor(0xff303335);p.reset();p.moveTo(cx-w*.06f,hz+h*.04f);p.lineTo(cx+w*.06f,hz+h*.04f);p.lineTo(w*.95f,h);p.lineTo(w*.05f,h);p.close();c.drawPath(p,f);l.setColor(0xffffffff);l.setStrokeWidth(3);c.drawLine(cx,split,cx,h,l);f.setColor(0xccffffff);f.setTextSize(Math.max(18,w*.02f));c.drawText("RWY 27 • LINE UP",w*.67f,hz+h*.18f,f);}f.setColor(0xe8ffffff);f.setTextSize(Math.max(15,w*.017f));c.drawText("HDG "+String.format(Locale.US,"%03.0f",(headingDeg%360+360)%360),w*.04f,h*.90f,f);}
 private void runway(Canvas c,int w,int h,float hz){float near=1-Math.min(1,altitudeM/950),fh=w*(.022f+.01f*near),nh=w*(onGround?.45f:(.14f+.28f*near)),fy=hz+h*(.012f+.018f*near),ny=h*(onGround?.998f:(.70f+.28f*near)),cx=w*.5f;f.setColor(0xff29402a);c.drawRect(0,hz,w,h,f);p.reset();p.moveTo(cx-fh*1.4f,fy);p.lineTo(cx+fh*1.4f,fy);p.lineTo(cx+nh*1.14f,ny);p.lineTo(cx-nh*1.14f,ny);p.close();f.setColor(0xff676a69);c.drawPath(p,f);p.reset();p.moveTo(cx-fh,fy);p.lineTo(cx+fh,fy);p.lineTo(cx+nh,ny);p.lineTo(cx-nh,ny);p.close();f.setColor(0xff2d3032);c.drawPath(p,f);
  // Longitudinal asphalt streaks make the direction of travel unmistakable.
  for(int i=-7;i<=7;i++){float xx=cx+i*nh*.12f;l.setColor((i%2==0)?0x24202020:0x153f3f3f);l.setStrokeWidth(2+Math.abs(i)%3);c.drawLine(cx+i*fh*.12f,fy,xx,ny,l);}l.setColor(0xfff3f2ed);l.setStrokeWidth(Math.max(2,w*.0024f));c.drawLine(cx-fh,fy,cx-nh,ny,l);c.drawLine(cx+fh,fy,cx+nh,ny,l);
  for(int i=0;i<24;i++){float q=(i/24f+scroll)%1f,z=q*q,y=lerp(fy,ny,z);l.setStrokeWidth(2+15*z);l.setColor(0xffffffff);c.drawLine(cx,y,cx,y+6+42*z,l);}for(int i=0;i<25;i++){float q=(i/24f+scroll*.18f)%1f,z=q*q,y=lerp(fy,ny,z),half=lerp(fh,nh,z),r=1+4*z;f.setColor(0xfff5f1dc);c.drawCircle(cx-half,y,r,f);c.drawCircle(cx+half,y,r,f);}
  // Threshold/27 is carried rapidly toward and underneath the viewer on takeoff.
  float take=phase.contains("TAKEOFF")?groundProgress:0f;float nz=.68f+take*.55f;float z=Math.min(1.20f,nz),y=lerp(fy,ny,z*z),half=lerp(fh,nh,Math.min(1,z));if(y<h*1.10f){f.setColor(0xffffffff);for(int i=-4;i<=4;i++)if(i!=0)c.drawRect(cx+i*half*.105f-half*.035f,y,cx+i*half*.105f+half*.035f,y+24+44*near,f);f.setTextAlign(Paint.Align.CENTER);f.setTextSize(Math.max(30,w*(.038f+.025f*take)));c.drawText("27",cx,y+78+45*take,f);f.setTextAlign(Paint.Align.LEFT);}if(phase.contains("TAKEOFF")&&speedMps>10){f.setColor(0x99ffffff);f.setTextSize(Math.max(13,w*.015f));c.drawText("→ İLERİ HAREKET  "+Math.round(speedMps)+" m/s",w*.72f,h*.93f,f);}float py=lerp(fy,ny,.58f),ph=lerp(fh,nh,.58f);for(int i=0;i<4;i++){f.setColor(i<2?0xffff3b30:0xffffffff);c.drawCircle(cx-ph*1.2f+i*10,py,4,f);}}
 private void airport(Canvas c,int w,int h,float hz){f.setColor(0xff344236);c.drawRect(0,hz,w,hz+h*.12f,f);f.setColor(0xff4b5151);for(int i=0;i<7;i++){float x=w*(.025f+i*.055f),bh=h*(.018f+(i%3)*.008f);c.drawRect(x,hz-bh,x+w*.04f,hz,f);}float x=w*.80f;f.setColor(0xff4b5154);c.drawRect(x-5,hz-h*.075f,x+5,hz,f);c.drawRect(x-16,hz-h*.086f,x+16,hz-h*.068f,f);}
 private void scenery(Canvas c,int w,int h,float hz){float t=Math.min(300,route);String label;if(t<45){label="SAHİL ÜZERİ TIRMANIŞ";coast(c,w,h,hz,.25f);}else if(t<90){label="DAĞLARA YAKLAŞMA";mountains(c,w,h,hz,.50f,false);}else if(t<145){label="VADİ İÇİ UÇUŞ";mountains(c,w,h,hz,.76f,true);}else if(t<205){label="DAĞ YOLU TAKİBİ";mountains(c,w,h,hz,.96f,true);road(c,w,h,hz);}else if(t<250){label="GÖL / KIYI GEÇİŞİ";lake(c,w,h,hz);}else if(t<280){label="YÜKSEK ARAZİ / DÖNÜŞ";mountains(c,w,h,hz,.72f,false);}else{label="HAVALİMANINA DÖNÜŞ";mountains(c,w,h,hz,.38f,false);airport(c,w,h,hz);}f.setColor(0xe8ffffff);f.setTextSize(Math.max(20,w*.022f));c.drawText(label,w*.04f,h*.88f,f);}
 private void mountains(Canvas c,int w,int h,float hz,float scale,boolean valley){mountainLayer(c,w,h,hz,scale*.62f,0xff6e7f7c,.006f,1.18f,valley);mountainLayer(c,w,h,hz,scale*.82f,0xff4c635b,.010f,1.37f,valley);mountainLayer(c,w,h,hz,scale,0xff2f463b,.014f,1.63f,valley); // snow caps / highlights
  l.setStrokeWidth(Math.max(2,w*.0015f));l.setColor(0x99d9e2df);Path cap=new Path();for(int i=0;i<=10;i++){float x=w*i/10f,y=hz-h*scale*(.055f+.13f*(float)Math.abs(Math.sin(i*1.63+route*.014)));if(i==0)cap.moveTo(x,y);else cap.lineTo(x,y);}c.drawPath(cap,l);f.setColor(0xff1f352c);for(int i=0;i<38;i++){float x=(i*83+route*4)%Math.max(1,w),base=hz+h*(.02f+(i%5)*.012f),s=3+(i%4);p.reset();p.moveTo(x,base-s*4);p.lineTo(x-s,base);p.lineTo(x+s,base);p.close();c.drawPath(p,f);}}
 private void mountainLayer(Canvas c,int w,int h,float hz,float scale,int color,float drift,float freq,boolean valley){p.reset();p.moveTo(0,h);for(int i=0;i<=18;i++){float x=w*i/18f,y=hz-h*scale*(.035f+.13f*(float)Math.abs(Math.sin(i*freq+route*drift)));if(valley&&i>7&&i<11)y+=h*.11f;p.lineTo(x,y);}p.lineTo(w,h);p.close();f.setColor(color);c.drawPath(p,f);}
 private void coast(Canvas c,int w,int h,float hz,float q){mountains(c,w,h,hz,q,false);water(c,w,h,hz+h*.08f);}private void lake(Canvas c,int w,int h,float hz){mountains(c,w,h,hz,.58f,true);water(c,w,h,hz+h*.13f);}
 private void water(Canvas c,int w,int h,float top){f.setShader(new LinearGradient(0,top,0,h,0xff397b96,0xff0b2b42,Shader.TileMode.CLAMP));c.drawRect(0,top,w,h,f);f.setShader(null);for(int row=0;row<24;row++){float y=top+(h-top)*(row+.5f)/24f,amp=1.2f+row*.18f,span=30+row*4;Path wp=new Path();wp.moveTo(0,y);for(int x=0;x<=w;x+=10){float yy=y+(float)Math.sin(x/span+route*.10f+row*.71f)*amp;wp.lineTo(x,yy);}l.setColor(row%4==0?0x58d8f3ff:0x229bc5d7);l.setStrokeWidth(.8f+row*.025f);c.drawPath(wp,l);}for(int i=0;i<34;i++){float x=(i*97+route*10)%Math.max(1,w),y=top+(h-top)*(.12f+((i*37)%78)/100f);f.setColor(0x48ffffff);c.drawOval(x,y,x+8+i%21,y+1.5f,f);}}
 private void road(Canvas c,int w,int h,float hz){l.setColor(0xff727775);l.setStrokeWidth(Math.max(12,w*.020f));p.reset();p.moveTo(w*.13f,h);p.cubicTo(w*.42f,h*.72f,w*.34f,h*.57f,w*.59f,hz+h*.07f);c.drawPath(p,l);l.setColor(0xffe5cf55);l.setStrokeWidth(2);c.drawPath(p,l);}
 private static float lerp(float a,float b,float t){return a+(b-a)*t;}
}
