package com.mg.fixturecockpitsim;

import android.content.Context;
import android.graphics.*;
import android.view.View;
import java.util.Locale;

/** AVM-12.1 military-airbase renderer: RWY27, tower/radar infrastructure, mountains, coast and sea. */
public final class RunwayHudView extends View {
    private final Paint fill=new Paint(3), stroke=new Paint(3);
    private final Path path=new Path();
    private volatile float altitudeM,speedMps,route,groundProgress,headingDeg;
    private volatile boolean onGround,demoMode;
    private volatile String phase="";
    private float scroll,runwayMeters;
    private long lastNs;

    public RunwayHudView(Context c){super(c);fill.setStyle(Paint.Style.FILL);stroke.setStyle(Paint.Style.STROKE);stroke.setStrokeCap(Paint.Cap.ROUND);}
    public void setDemoMode(boolean e){demoMode=e;postInvalidateOnAnimation();}
    public void setDemoProgress(double s){route=(float)Math.max(0,s);postInvalidateOnAnimation();}
    public void setGroundProgress(double q,double hdg){groundProgress=clamp((float)q,0,1);headingDeg=(float)hdg;postInvalidateOnAnimation();}
    public void setFlightState(double a,double s,boolean g,String ph){altitudeM=(float)Math.max(0,a);speedMps=(float)Math.max(0,s);onGround=g;phase=ph==null?"":ph;postInvalidateOnAnimation();}

    @Override protected void onDraw(Canvas c){super.onDraw(c);long now=System.nanoTime();float dt=lastNs==0?.016f:Math.min(.05f,(now-lastNs)/1e9f);lastNs=now;scroll=(scroll+speedMps*dt*.043f)%1f;if(phase.contains("TAKEOFF")||phase.contains("ROLLOUT"))runwayMeters+=speedMps*dt;if(phase.contains("HANGAR_START")||phase.contains("RUNWAY_HOLD"))runwayMeters=0;int w=getWidth(),h=getHeight();float hz=h*(.455f+.075f*Math.min(1,altitudeM/1300f));drawSky(c,w,h,hz);if(phase.contains("HANGAR")){drawHangar(c,w,h,hz);scheduleFrame();return;}if(phase.contains("TAXI")){drawTaxi(c,w,h,hz);scheduleFrame();return;}if(demoMode&&phase.contains("ORBIT")){drawScenery(c,w,h,hz);scheduleFrame();return;}drawRunway(c,w,h,hz);scheduleFrame();}
    private void scheduleFrame(){if(speedMps>1||demoMode)postInvalidateOnAnimation();}

    private void drawSky(Canvas c,int w,int h,float hz){fill.setShader(new LinearGradient(0,0,0,hz,new int[]{0xff06111e,0xff397b9f,0xffbfdce8},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,hz,fill);fill.setShader(null);fill.setShader(new LinearGradient(0,hz*.68f,0,hz,0x00ffffff,0x4ff4f0df,Shader.TileMode.CLAMP));c.drawRect(0,hz*.68f,w,hz,fill);fill.setShader(null);for(int i=0;i<7;i++){float x=(w*(.05f+i*.16f)+(route*1.5f)%w)%w,y=hz*(.09f+(i%3)*.055f),ww=w*(.10f+(i%2)*.05f);fill.setColor(0x22ffffff);c.drawOval(x,y,x+ww,y+hz*.025f,fill);c.drawOval(x+ww*.20f,y-hz*.016f,x+ww*.68f,y+hz*.018f,fill);}}

    private void drawHangar(Canvas c,int w,int h,float hz){float q=phase.contains("PARK")?1-groundProgress:groundProgress,cx=w*.5f;float doorHalf=w*(.22f+.16f*q),top=h*.16f,bottom=h*.78f;fill.setShader(new LinearGradient(0,0,0,h,new int[]{0xff0b1014,0xff182126,0xff353d41},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,fill);fill.setShader(null);drawOutside(c,cx-doorHalf,top,cx+doorHalf,bottom,w,h);quad(c,cx-doorHalf,bottom,cx+doorHalf,bottom,w,h,0,h,0xff363c3f);stroke.setColor(0xff646e74);stroke.setStrokeWidth(2);for(int i=-9;i<=9;i++){float x=cx+i*w*.064f;c.drawLine(x,h,cx+(x-cx)*.29f,bottom,stroke);}for(int i=1;i<8;i++){float t=i/8f,y=lerp(bottom,h,t*t);c.drawLine(0,y,w,y,stroke);}stroke.setColor(0xffe6c52e);stroke.setStrokeWidth(5);c.drawLine(cx,bottom,cx,h,stroke);stroke.setColor(0xff5e6970);for(int i=0;i<7;i++){float t=i/6f,y=lerp(h*.06f,bottom,t),half=lerp(w*.48f,doorHalf,t);stroke.setStrokeWidth(7-3*t);c.drawLine(cx-half,y,cx-half,bottom,stroke);c.drawLine(cx+half,y,cx+half,bottom,stroke);c.drawLine(cx-half,y,cx+half,y,stroke);c.drawLine(cx-half,y,cx,y-h*.055f,stroke);c.drawLine(cx+half,y,cx,y-h*.055f,stroke);}for(int i=0;i<9;i++){float x=w*(.07f+i*.105f);fill.setColor(0x55fff0ba);c.drawRoundRect(x,h*.072f,x+w*.060f,h*.092f,5,5,fill);fill.setColor(0xffffe7a4);c.drawRoundRect(x+w*.008f,h*.078f,x+w*.052f,h*.087f,4,4,fill);}for(int side=-1;side<=1;side+=2){float bx=side<0?w*.02f:w*.86f;fill.setColor(0xff444d52);c.drawRect(bx,h*.49f,bx+w*.115f,h*.775f,fill);fill.setColor(0xff20272b);for(int k=0;k<4;k++)c.drawRect(bx+w*.012f,h*(.525f+k*.055f),bx+w*.102f,h*(.544f+k*.055f),fill);fill.setColor(0xffc93631);c.drawRect(bx+w*.014f,h*.70f,bx+w*.038f,h*.765f,fill);fill.setColor(0xffd9a72c);c.drawCircle(bx+w*.078f,h*.635f,w*.014f,fill);}fill.setColor(0xe8ffffff);fill.setTextSize(Math.max(15,w*.016f));c.drawText("MIL HANGAR 01  •  TAXI A  •  RWY 27",w*.035f,h*.93f,fill);}

    private void drawOutside(Canvas c,float x0,float y0,float x1,float y1,int w,int h){fill.setShader(new LinearGradient(0,y0,0,y1,new int[]{0xff9dd2e5,0xff759fac,0xff465a3e},null,Shader.TileMode.CLAMP));c.drawRect(x0,y0,x1,y1,fill);fill.setShader(null);float cx=(x0+x1)/2;quad(c,cx-(x1-x0)*.055f,y0+(y1-y0)*.10f,cx+(x1-x0)*.055f,y0+(y1-y0)*.10f,x1,y1,x0,y1,0xff555b5e);stroke.setColor(0xffe6c42d);stroke.setStrokeWidth(4);c.drawLine(cx,y0+(y1-y0)*.10f,cx,y1,stroke);drawMilitaryTowers(c,(int)x0,(int)x1,(int)(y0+(y1-y0)*.42f),(int)(y1-y0),.70f);}

    private void drawTaxi(Canvas c,int w,int h,float hz){fill.setColor(0xff3f543b);c.drawRect(0,hz,w,h,fill);drawMountains(c,w,h,hz,.17f,false);drawMilitaryTowers(c,0,w,(int)hz,h,.90f);float cx=w*.5f,far=w*.043f,near=w*.30f;quad(c,cx-far,hz+h*.014f,cx+far,hz+h*.014f,cx+near,h,cx-near,h,0xff51575a);quad(c,cx-far*.78f,hz+h*.014f,cx+far*.78f,hz+h*.014f,cx+near*.78f,h,cx-near*.78f,h,0xff3b4043);stroke.setColor(0xffefca22);stroke.setStrokeWidth(5);c.drawLine(cx,hz+h*.015f,cx,h,stroke);for(int i=0;i<26;i++){float q=(i/26f+scroll*.56f)%1f,z=q*q,y=lerp(hz+h*.025f,h,z),hh=lerp(far,near,z);fill.setColor(0xff429cff);float r=1.2f+4.2f*z;c.drawCircle(cx-hh*.95f,y,r,fill);c.drawCircle(cx+hh*.95f,y,r,fill);if(i%3==0){stroke.setColor(0x355f6465);stroke.setStrokeWidth(1+2*z);c.drawLine(cx-hh*.75f,y,cx+hh*.75f,y,stroke);}}if(groundProgress>.55f){float y=h*.66f,hh=w*.145f;stroke.setColor(0xffffd43e);stroke.setStrokeWidth(5);c.drawLine(cx-hh,y,cx+hh,y,stroke);stroke.setStrokeWidth(2);for(int i=0;i<8;i++){float x=cx-hh+i*(2*hh/7f);c.drawLine(x,y+7,x+10,y+18,stroke);}fill.setColor(0xeeffffff);fill.setTextSize(Math.max(14,w*.015f));c.drawText("MIL RWY 27 HOLD SHORT",w*.64f,h*.72f,fill);}fill.setColor(0xe8ffffff);fill.setTextSize(Math.max(14,w*.015f));c.drawText("MIL AIR BASE  •  HDG "+String.format(Locale.US,"%03.0f",norm(headingDeg))+"  •  TAXI",w*.04f,h*.92f,fill);}

    private void drawRunway(Canvas c,int w,int h,float hz){float near=1-Math.min(1,altitudeM/1050f),err=angleError(headingDeg,270f),cx=w*.5f+clamp(err/22f,-1,1)*w*.095f;float fh=w*(.018f+.012f*near),nh=w*(onGround?.45f:(.12f+.30f*near)),fy=hz+h*.014f,ny=h*(onGround?.999f:(.72f+.26f*near));drawTerrain(c,w,h,hz);quad(c,cx-fh*1.28f,fy,cx+fh*1.28f,fy,cx+nh*1.10f,ny,cx-nh*1.10f,ny,0xff666a63);quad(c,cx-fh,fy,cx+fh,fy,cx+nh,ny,cx-nh,ny,0xff24282a);for(int i=-8;i<=8;i++){float a=i/8f;stroke.setColor(i%3==0?0x33484a4b:0x1d101112);stroke.setStrokeWidth(1+Math.abs(a)*1.2f);c.drawLine(cx+fh*a*.82f,fy,cx+nh*a*.82f,ny,stroke);}stroke.setColor(0xfff4f3ed);stroke.setStrokeWidth(Math.max(2,w*.0025f));c.drawLine(cx-fh,fy,cx-nh,ny,stroke);c.drawLine(cx+fh,fy,cx+nh,ny,stroke);for(int i=0;i<36;i++){float q=(i/36f+scroll)%1f,z=q*q,y=lerp(fy,ny,z),y2=Math.min(ny,y+4+46*z);stroke.setColor(0xfff5f5f0);stroke.setStrokeWidth(2+12*z);c.drawLine(cx,y,cx,y2,stroke);}for(int i=0;i<30;i++){float q=(i/30f+scroll*.62f)%1f,z=q*q,y=lerp(fy,ny,z),hh=lerp(fh,nh,z);fill.setColor(i>25?0xffffd56b:0xfff3f0d8);float r=1+4*z;c.drawCircle(cx-hh,y,r,fill);c.drawCircle(cx+hh,y,r,fill);}for(int set=0;set<3;set++){float q=(.31f+set*.17f+scroll*.14f)%1f,z=q*q,y=lerp(fy,ny,z),hh=lerp(fh,nh,z),bw=hh*.10f,bh=5+20*z;fill.setColor(0xffeeeeea);for(int s=-1;s<=1;s+=2){c.drawRect(cx+s*hh*.43f-bw,y,cx+s*hh*.43f+bw,y+bh,fill);c.drawRect(cx+s*hh*.66f-bw*.72f,y,cx+s*hh*.66f+bw*.72f,y+bh,fill);}}float nz=.48f+(phase.contains("TAKEOFF")?runwayMeters/310f:0);if(nz<=1.04f){float z=clamp(nz,0,1),y=lerp(fy,ny,z*z),hh=lerp(fh,nh,z);fill.setColor(0xfffafaf5);for(int i=-5;i<=5;i++){if(i==0)continue;float x=cx+i*hh*.095f;c.drawRect(x-hh*.030f,y,x+hh*.030f,y+13+38*z,fill);}fill.setTextAlign(Paint.Align.CENTER);fill.setTextSize(Math.max(27,w*(.033f+.030f*z)));c.drawText("27",cx,y+58+42*z,fill);fill.setTextAlign(Paint.Align.LEFT);}if(!onGround||phase.contains("APPROACH")||phase.contains("FLARE")){float py=lerp(fy,ny,.36f),ph=lerp(fh,nh,.36f);for(int i=0;i<4;i++){fill.setColor(i<2?0xffffffff:0xffff3b30);c.drawCircle(cx-ph*1.28f+i*6,py,3.2f,fill);}}if(phase.contains("APPROACH")||phase.contains("FLARE")){fill.setColor(Math.abs(err)<2.5?0xff7fe889:0xffffd35a);fill.setTextSize(Math.max(14,w*.015f));c.drawText(Math.abs(err)<2.5?"MIL RWY 27 • CENTERLINE CAPTURED":"MIL RWY 27 • ALIGNING",w*.62f,h*.92f,fill);}}

    private void drawTerrain(Canvas c,int w,int h,float hz){fill.setColor(0xff344b34);c.drawRect(0,hz,w,h,fill);drawMountains(c,w,h,hz,.23f,false);drawMilitaryTowers(c,0,w,(int)hz,h,.72f);}

    /** Military airbase skyline only: no civilian houses, apartment blocks or town structures. */
    private void drawMilitaryTowers(Canvas c,int x0,int x1,int baseY,int h,float density){int span=Math.max(1,x1-x0);float ground=baseY-2;
        drawControlTower(c,x0+span*.14f,ground,h,span*(.040f+.010f*density));
        drawRadarTower(c,x0+span*.82f,ground,h,span*(.032f+.008f*density));
        for(int i=0;i<5;i++){float x=x0+span*(.31f+i*.105f);float mastH=h*(.055f+.018f*((i*3)%4));drawAntennaMast(c,x,ground,mastH,Math.max(2f,span*.0024f));}
    }
    private void drawControlTower(Canvas c,float x,float ground,int h,float s){float shaftW=s*.46f,shaftH=h*.13f,cabW=s*1.42f,cabH=h*.048f;fill.setColor(0xff69736d);c.drawRect(x-shaftW*.5f,ground-shaftH,x+shaftW*.5f,ground,fill);fill.setColor(0xff252f31);c.drawRect(x-cabW*.5f,ground-shaftH-cabH,x+cabW*.5f,ground-shaftH,fill);fill.setColor(0xff6f9aa1);float pad=cabW*.08f;c.drawRect(x-cabW*.5f+pad,ground-shaftH-cabH+cabH*.18f,x+cabW*.5f-pad,ground-shaftH-cabH*.28f,fill);fill.setColor(0xff4b5551);c.drawRect(x-cabW*.64f,ground-shaftH-cabH*.10f,x+cabW*.64f,ground-shaftH+cabH*.03f,fill);stroke.setColor(0xff343d3a);stroke.setStrokeWidth(Math.max(2,s*.06f));c.drawLine(x,ground-shaftH-cabH,x,ground-shaftH-cabH-h*.045f,stroke);fill.setColor(0xffff4b42);c.drawCircle(x,ground-shaftH-cabH-h*.045f,Math.max(2,s*.055f),fill);}
    private void drawRadarTower(Canvas c,float x,float ground,int h,float s){float towerH=h*.14f,top=ground-towerH;stroke.setColor(0xff58615b);stroke.setStrokeWidth(Math.max(2,s*.055f));c.drawLine(x-s*.42f,ground,x-s*.14f,top,stroke);c.drawLine(x+s*.42f,ground,x+s*.14f,top,stroke);for(int i=1;i<5;i++){float y=lerp(ground,top,i/5f),half=lerp(s*.42f,s*.14f,i/5f);c.drawLine(x-half,y,x+half,y,stroke);}fill.setColor(0xff929b91);c.drawOval(x-s*.48f,top-h*.026f,x+s*.48f,top+h*.008f,fill);stroke.setColor(0xff38413d);stroke.setStrokeWidth(Math.max(2,s*.045f));c.drawLine(x,top,x+s*.42f,top-h*.018f,stroke);fill.setColor(0xffff4b42);c.drawCircle(x,top-h*.031f,Math.max(2,s*.050f),fill);}
    private void drawAntennaMast(Canvas c,float x,float ground,float mastH,float sw){stroke.setColor(0xff59635d);stroke.setStrokeWidth(sw);c.drawLine(x,ground,x,ground-mastH,stroke);c.drawLine(x-sw*2.5f,ground,x,ground-mastH*.62f,stroke);c.drawLine(x+sw*2.5f,ground,x,ground-mastH*.62f,stroke);stroke.setStrokeWidth(Math.max(1,sw*.65f));for(int i=1;i<4;i++){float y=ground-mastH*i/4f;c.drawLine(x-sw*2.1f,y,x+sw*2.1f,y,stroke);}fill.setColor(0xffff574d);c.drawCircle(x,ground-mastH,Math.max(1.8f,sw*1.05f),fill);}

    private void drawScenery(Canvas c,int w,int h,float hz){float t=Math.min(300,route);if(t<50){drawDepartureCoast(c,w,h,hz,t/50f);label(c,w,h,"ASKERİ ÜSTEN KIYIYA TIRMANIŞ");}else if(t<100){drawMountains(c,w,h,hz,.58f,false);label(c,w,h,"DAĞLARA YAKLAŞMA");}else if(t<155){drawMountains(c,w,h,hz,.83f,true);label(c,w,h,"VADİ UÇUŞU");}else if(t<215){drawMountains(c,w,h,hz,.96f,true);drawRoad(c,w,h,hz);label(c,w,h,"DAĞ YOLU TAKİBİ");}else if(t<255){drawLake(c,w,h,hz);label(c,w,h,"GÖL / KIYI GEÇİŞİ");}else if(t<280){drawMountains(c,w,h,hz,.72f,false);label(c,w,h,"YÜKSEK ARAZİ");}else{drawTerrain(c,w,h,hz);label(c,w,h,"MIL RWY 27 HİZALANMA");}}
    private void drawDepartureCoast(Canvas c,int w,int h,float hz,float t){float shore=hz+h*(.055f+.045f*t);drawMountains(c,w,h,hz,.20f+.13f*t,false);fill.setColor(0xff3d583c);path.reset();path.moveTo(0,shore);for(int i=0;i<=14;i++){float x=w*i/14f,y=shore+h*.020f*(float)Math.sin(i*.8+route*.03);path.lineTo(x,y);}path.lineTo(w,h);path.lineTo(0,h);path.close();c.drawPath(path,fill);drawWater(c,w,h,shore+h*.055f);}
    private void drawWater(Canvas c,int w,int h,float top){fill.setShader(new LinearGradient(0,top,0,h,new int[]{0xff5ea8bd,0xff1a6784,0xff062c45},null,Shader.TileMode.CLAMP));c.drawRect(0,top,w,h,fill);fill.setShader(null);float motion=route*12f+scroll*w*.9f;for(int i=0;i<58;i++){float z=((i*37)%100)/100f,y=top+(h-top)*(.05f+.90f*z),x=(i*113+motion*(.22f+z))%Math.max(1,w),ww=10+w*.025f*z,hh=1.1f+2.6f*z;fill.setColor(i%5==0?0x52ffffff:0x247ed2e4);c.drawOval(x,y,x+ww,y+hh,fill);}fill.setShader(new LinearGradient(w*.18f,top,w*.80f,h,0x00ffffff,0x24ffffff,Shader.TileMode.CLAMP));c.drawRect(w*.20f,top,w*.80f,h,fill);fill.setShader(null);}
    private void drawMountains(Canvas c,int w,int h,float hz,float scale,boolean valley){mountainLayer(c,w,h,hz,scale*.54f,0xff71868a,1.12f,valley);mountainLayer(c,w,h,hz,scale*.77f,0xff526a63,1.38f,valley);mountainLayer(c,w,h,hz,scale,0xff30483d,1.67f,valley);}
    private void mountainLayer(Canvas c,int w,int h,float hz,float scale,int col,float freq,boolean valley){path.reset();path.moveTo(0,h);for(int i=0;i<=24;i++){float x=w*i/24f,y=hz-h*scale*(.035f+.13f*(float)Math.abs(Math.sin(i*freq+route*.010)));if(valley&&i>10&&i<14)y+=h*.12f;path.lineTo(x,y);}path.lineTo(w,h);path.close();fill.setColor(col);c.drawPath(path,fill);}
    private void drawLake(Canvas c,int w,int h,float hz){drawMountains(c,w,h,hz,.56f,true);drawWater(c,w,h,hz+h*.12f);}
    private void drawRoad(Canvas c,int w,int h,float hz){stroke.setColor(0xff6f7472);stroke.setStrokeWidth(Math.max(12,w*.018f));path.reset();path.moveTo(w*.10f,h);path.cubicTo(w*.38f,h*.72f,w*.32f,h*.60f,w*.61f,hz+h*.06f);c.drawPath(path,stroke);stroke.setColor(0xffe8d15a);stroke.setStrokeWidth(2);c.drawPath(path,stroke);}
    private void label(Canvas c,int w,int h,String s){fill.setColor(0xe8ffffff);fill.setTextSize(Math.max(18,w*.019f));c.drawText(s,w*.04f,h*.89f,fill);}

    private void quad(Canvas c,float x1,float y1,float x2,float y2,float x3,float y3,float x4,float y4,int col){path.reset();path.moveTo(x1,y1);path.lineTo(x2,y2);path.lineTo(x3,y3);path.lineTo(x4,y4);path.close();fill.setColor(col);c.drawPath(path,fill);}
    private static float norm(float a){a%=360;if(a<0)a+=360;return a;}
    private static float angleError(float h,float t){float d=t-h;while(d>180)d-=360;while(d<-180)d+=360;return d;}
    private static float clamp(float v,float lo,float hi){return Math.max(lo,Math.min(hi,v));}
    private static float lerp(float a,float b,float t){return a+(b-a)*t;}
}
