plugins {
    id 'com.android.application'
}

android {
    namespace 'com.muhammetgecgil.morse'
    compileSdk 36

    defaultConfig {
        applicationId 'com.muhammetgecgil.morsekodcevirici'
        minSdk 26
        targetSdk 36
        versionCode 510
        versionName '5.1.0'

        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
        vectorDrawables.useSupportLibrary = false
    }

    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError true
        warningsAsErrors false
        checkReleaseBuilds true
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
