const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'../..'),A='https://appassets.androidplatform.net/assets/';
const out=process.env.UI_CAPTURE_DIR||'/tmp/radio-ui-preview';fs.mkdirSync(out,{recursive:true});
function source(p){return process.env.SOURCE_REF?execFileSync('git',['show',process.env.SOURCE_REF+':'+p],{cwd:ROOT,encoding:'utf8'}):fs.readFileSync(path.join(ROOT,p),'utf8')}
const names=['Power Türk','TRT FM','Radyo Voyage','Slow Türk','Kral Pop','Radyo D','Joy FM','Radyo Eksen'];
const stations=names.map((name,i)=>({name,stationuuid:'preview-'+i,url:'https://stream.test/'+i,url_resolved:'https://stream.test/'+i,bitrate:128,lastcheckok:1,clickcount:3000-i*100,tags:i===2||i===3?'slow,jazz':'pop',language:'turkish',countrycode:'TR'}));
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const page=await browser.newPage({viewport:{width:412,height:915},deviceScaleFactor:2});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const url=route.request().url();if(url.startsWith(A)){try{const name=new URL(url).pathname.replace('/assets/','');return route.fulfill({contentType:name.endsWith('.css')?'text/css':name.endsWith('.js')?'application/javascript':name.endsWith('.html')?'text/html':'application/json',body:source('turkradyo/app/src/main/assets/'+name)})}catch{return route.fulfill({status:404,body:''})}}if(url.includes('api.radio-browser.info'))return route.fulfill({contentType:'application/json',body:JSON.stringify(stations)});return route.abort()});
 await page.addInitScript(()=>{localStorage.setItem('p2Active','1');window.RadioNative={getTelemetry:()=>JSON.stringify({nativeRecovery:true,serviceActive:true,isPlaying:false,manualPause:true,playerState:3,networkType:'wifi',volume:0.75,station:'Power Türk',primaryUrl:'https://stream.test/0'}),getNowTitle:()=>'',getRecentTracks:()=>'[]',getStreamHealth:()=>'{}',getProductGuard:()=>'{}',getCatalogHealth:()=>'{}',getNotaAnalysis:()=>'{"state":"IDLE"}',getNotaTextArchive:()=>'[]',setQueue:()=>{}}});
 await page.goto(A+'index.html');const java=source('turkradyo/app/src/main/java/com/muhammetgecgil/turkradyo/MainActivity.java');const raw=java.match(/v\.evaluateJavascript\("(.*)",null\);/)[1].replaceAll('"+A+"',A);await page.evaluate(JSON.parse('"'+raw+'"'));await page.waitForTimeout(6500);
 const captures=[];
 const shot=async name=>{const overlay=await page.locator('.sheet.show,.nature-modal.show').count();if(!overlay)await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,name+'.png'),fullPage:!overlay,animations:'disabled'});captures.push({name,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)})};
 const feature=async(selector,name)=>{await page.locator(selector).click();await page.waitForTimeout(450);await shot(name);await page.evaluate(()=>window.trCloseTopOverlay())};
 await shot('profile2-home');
 await page.locator('.hero').screenshot({path:path.join(out,'transport-red.png'),animations:'disabled'});
 await page.locator('#p2UnifiedPremiumGrid263').screenshot({path:path.join(out,'premium-cards-red.png'),animations:'disabled'});
 const cards=await page.locator('#p2UnifiedPremiumGrid263>button').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBoundingClientRect(),icon=e.querySelector('.p263Icon'),label=e.querySelector('.p263Label'),ir=icon.getBoundingClientRect(),lr=label.getBoundingClientRect();return{id:e.id,art:icon.querySelector('svg')?.dataset.art||'slow-pulse',iconWidth:ir.width,cardHeight:r.height,overlaps:ir.bottom>lr.top,overflow:lr.bottom>r.bottom||ir.left<r.left||ir.right>r.right}}));
 const buttons=await page.locator('button').evaluateAll(a=>a.filter(e=>e.getBoundingClientRect().height>0).map(e=>({id:e.id,text:e.textContent.trim(),mode:e.dataset.mode,rect:{x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}})));
 await page.locator('#settingsBtn').click();await page.waitForTimeout(500);await shot('settings');await page.locator('#closeSheet').click();
 await page.locator('#p2DNA').click();await page.waitForTimeout(300);await shot('dna');await page.locator('#closeSheet').click();
 await page.locator('#p2Sleep').click();await page.waitForTimeout(300);await shot('timer');await page.locator('#closeSheet').click();
 await feature('#menuBtn','radio-list');
 await feature('.bottom [data-nav="favorites"]','favorites-empty');
 await feature('[data-mode="eq"]','equalizer');
 await feature('#p2Alarm','alarm');
 await feature('#p2Tracks','track-history');
 await feature('#p2Genres','turkey-groups');
 await feature('#v12Genres','genres');
 await feature('#v12Smart','slow-mode');
 await feature('[data-nota-ai]','nota-ai');
 await feature('.nature-profile-pill','profiles');
 await feature('[data-mode="themes"]','theme-gallery');
 await page.locator('#sigTools summary').click();await page.locator('#sigTools').screenshot({path:path.join(out,'broadcast-tools.png'),animations:'disabled'});await page.locator('#sigTools summary').click();
 await page.locator('[data-mode="themes"]').click();await page.locator('[data-use="orchid"]').click();await page.evaluate(()=>window.trCloseTopOverlay());await page.waitForTimeout(1400);
 await page.locator('#p2UnifiedPremiumGrid263').screenshot({path:path.join(out,'premium-cards-purple.png'),animations:'disabled'});
 await page.locator('.hero').screenshot({path:path.join(out,'transport-purple.png'),animations:'disabled'});
 await shot('profile2-purple');
 await page.setViewportSize({width:360,height:800});await page.locator('#p2UnifiedPremiumGrid263').screenshot({path:path.join(out,'premium-cards-small.png'),animations:'disabled'});
 await page.locator('[data-mode="themes"]').click();await page.locator('#natureReset').click();await page.evaluate(()=>window.trCloseTopOverlay());await page.setViewportSize({width:412,height:915});await page.waitForTimeout(500);
 await page.locator('.nature-profile-pill').click();await page.waitForTimeout(250);await page.locator('[data-prof="1"]').click();await page.waitForTimeout(1300);await shot('profile1-home');
 await page.setViewportSize({width:360,height:800});await shot('profile1-small');
 fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify({errors,buttons,cards,captures},null,2));await browser.close();
 if(errors.length||cards.some(c=>c.overlaps||c.overflow)||captures.some(c=>c.overflow))throw Error('UI review found an error, overlapping artwork, or horizontal overflow');
})().catch(e=>{console.error(e);process.exitCode=1});
