package com.mg.machineelementspro;

import android.app.Activity;
import android.graphics.*;
import android.os.Bundle;
import android.text.*;
import android.view.View;
import android.widget.*;
import java.util.Locale;

public class MachineElementVisualLabActivity extends Activity {
 private final EditText[] in=new EditText[6]; private Diagram d; private int mode=0;
 private static final String[] MODES={"Mil","Rulman","Civata"};
 private static final String[][] HINTS={{"M (N·m)","T (N·m)","d (mm)","Sy (MPa)","L (mm)","Yük konumu a (mm)"},{"Fr / P (N)","Fa (N)","C (N)","n (rpm)","Mil çapı (mm)",""},{"F eksenel (N)","V kesme (N)","d (mm)","Sy (MPa)","Bağlantı kalınlığı (mm)",""}};
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(build());select(0);}
 private View build(){ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.rgb(242,246,250));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(14),dp(16),dp(14),dp(24));s.addView(r);r.addView(t("VISUAL ENGINEERING LAB",24,true));r.addView(t("Teknik resim + serbest cisim diyagramı • girdiler canlı güncellenir",14,false));LinearLayout tabs=new LinearLayout(this);for(int i=0;i<3;i++){final int x=i;Button b=new Button(this);b.setText(MODES[i]);b.setAllCaps(false);b.setOnClickListener(v->select(x));tabs.addView(b,new LinearLayout.LayoutParams(0,dp(50),1));}r.addView(tabs);for(int i=0;i<6;i++){in[i]=new EditText(this);in[i].setSingleLine();in[i].setInputType(2|8192|16384);in[i].addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){if(d!=null){d.v=vals();d.invalidate();}}public void afterTextChanged(Editable e){}});r.addView(in[i],new LinearLayout.LayoutParams(-1,dp(52)));}TextView cap=t("CANLI MÜHENDİSLİK GÖRSELİ",12,true);cap.setTextColor(Color.rgb(30,64,175));r.addView(cap);d=new Diagram();r.addView(d,new LinearLayout.LayoutParams(-1,dp(430)));Button old=new Button(this);old.setText("TÜM MAKİNE ELEMANLARI GALERİSİ →");old.setAllCaps(false);old.setOnClickListener(v->startActivity(new android.content.Intent(this,MachineElementStudioActivity.class)));r.addView(old);return s;}
 private void select(int m){mode=m;for(int i=0;i<6;i++){in[i].setHint(HINTS[m][i]);in[i].setVisibility(HINTS[m][i].isEmpty()?View.GONE:View.VISIBLE);in[i].setText("");}if(d!=null){d.v=vals();d.invalidate();}}
 private double[] vals(){double[] v=new double[6];for(int i=0;i<6;i++){try{v[i]=Double.parseDouble(in[i].getText().toString().trim().replace(',','.'));}catch(Exception ignored){}}return v;}
 private TextView t(String s,int z,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(Color.rgb(20,30,45));if(b)x.setTypeface(Typeface.DEFAULT_BOLD);x.setPadding(0,dp(4),0,dp(8));return x;} private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 private class Diagram extends View{double[] v=new double[6];Paint p=new Paint(1),tx=new Paint(1);Diagram(){super(MachineElementVisualLabActivity.this);setLayerType(View.LAYER_TYPE_SOFTWARE,null);setBackgroundColor(Color.rgb(15,23,32));tx.setTypeface(Typeface.DEFAULT_BOLD);}protected void onDraw(Canvas c){super.onDraw(c);grid(c);header(c);if(mode==0)shaft(c);else if(mode==1)bearing(c);else bolt(c);}void grid(Canvas c){p.setStrokeWidth(1);p.setColor(Color.rgb(31,43,55));for(int x=0;x<getWidth();x+=dp(20))c.drawLine(x,0,x,getHeight(),p);for(int y=0;y<getHeight();y+=dp(20))c.drawLine(0,y,getWidth(),y,p);}void header(Canvas c){lab(c,MODES[mode].toUpperCase(Locale.ROOT)+" • FBD / TEKNİK ŞEMA",dp(12),dp(23),Color.rgb(125,211,252));line(c,Color.rgb(51,65,85),1,dp(10),dp(31),getWidth()-dp(10),dp(31));}void line(Canvas c,int col,float sw,float x1,float y1,float x2,float y2){p.setColor(col);p.setStrokeWidth(sw);p.setStyle(Paint.Style.STROKE);c.drawLine(x1,y1,x2,y2,p);p.setStyle(Paint.Style.FILL);}void lab(Canvas c,String s,float x,float y,int col){tx.setTextSize(dp(11));tx.setColor(col);c.drawText(s,x,y,tx);}void arrow(Canvas c,float x1,float y1,float x2,float y2,int col,String s){line(c,col,dp(3),x1,y1,x2,y2);double a=Math.atan2(y2-y1,x2-x1);float L=dp(10);Path q=new Path();q.moveTo(x2,y2);q.lineTo((float)(x2-L*Math.cos(a-.55)),(float)(y2-L*Math.sin(a-.55)));q.lineTo((float)(x2-L*Math.cos(a+.55)),(float)(y2-L*Math.sin(a+.55)));q.close();p.setColor(col);c.drawPath(q,p);lab(c,s,x2+dp(4),y2-dp(3),col);}void dim(Canvas c,float x1,float x2,float y,String s){line(c,Color.rgb(203,213,225),1,x1,y,x2,y);arrowHead(c,x1,y,0);arrowHead(c,x2,y,(float)Math.PI);lab(c,s,(x1+x2)/2-dp(25),y-dp(6),Color.WHITE);}void arrowHead(Canvas c,float x,float y,float a){float L=dp(7);line(c,Color.WHITE,1,x,y,x+(float)Math.cos(a+.55)*L,y+(float)Math.sin(a+.55)*L);line(c,Color.WHITE,1,x,y,x+(float)Math.cos(a-.55)*L,y+(float)Math.sin(a-.55)*L);}String f(double x){return String.format(Locale.US,"%.1f",x);}void support(Canvas c,float x,float y,String n){Path q=new Path();q.moveTo(x,y);q.lineTo(x-dp(20),y+dp(28));q.lineTo(x+dp(20),y+dp(28));q.close();p.setColor(Color.rgb(100,116,139));c.drawPath(q,p);line(c,Color.rgb(148,163,184),2,x-dp(27),y+dp(31),x+dp(27),y+dp(31));lab(c,n,x-dp(8),y+dp(47),Color.rgb(147,197,253));}
 void shaft(Canvas c){float w=getWidth(),h=getHeight(),y=h*.48f,xA=w*.14f,xB=w*.86f;double L=v[4]>0?v[4]:500,a=v[5]>0?v[5]:L*.58;float xF=(float)(xA+(xB-xA)*Math.max(0,Math.min(1,a/L)));p.setShadowLayer(dp(7),0,0,Color.argb(100,125,211,252));line(c,Color.rgb(203,213,225),dp(18),xA,y,xB,y);p.clearShadowLayer();support(c,xA,y+dp(12),"A");support(c,xB,y+dp(12),"B");arrow(c,xF,y-dp(95),xF,y-dp(15),Color.rgb(248,113,113),"M = "+f(v[0])+" N·m");arrow(c,w*.34f,y+dp(105),w*.34f,y+dp(18),Color.rgb(74,222,128),"T = "+f(v[1])+" N·m");arrow(c,xA,y+dp(92),xA,y+dp(20),Color.rgb(96,165,250),"RA");arrow(c,xB,y+dp(92),xB,y+dp(20),Color.rgb(96,165,250),"RB");dim(c,xA,xF,h*.79f,"a = "+f(a)+" mm");dim(c,xF,xB,h*.87f,"b = "+f(Math.max(0,L-a))+" mm");dim(c,xA,xB,h*.94f,"L = "+f(L)+" mm");p.setColor(Color.argb(180,239,68,68));c.drawRect(xF-dp(6),y-dp(30),xF+dp(6),y+dp(30),p);lab(c,"▲ KRİTİK KESİT",xF-dp(42),y-dp(38),Color.rgb(248,113,113));lab(c,"Ø"+f(v[2])+" mm",w*.48f,y+dp(38),Color.WHITE);lab(c,"Malzeme Sy = "+f(v[3])+" MPa",dp(12),dp(53),Color.rgb(167,243,208));}
 void bearing(Canvas c){float w=getWidth(),h=getHeight(),cx=w*.50f,cy=h*.51f,r=Math.min(w,h)*.24f;p.setShadowLayer(dp(9),0,0,Color.argb(100,148,163,184));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(15));p.setColor(Color.rgb(203,213,225));c.drawCircle(cx,cy,r,p);p.clearShadowLayer();p.setStrokeWidth(dp(5));p.setColor(Color.rgb(100,116,139));c.drawCircle(cx,cy,r*.50f,p);p.setStyle(Paint.Style.FILL);for(int k=0;k<12;k++){double a=k*2*Math.PI/12;p.setColor(Color.rgb(226,232,240));c.drawCircle((float)(cx+Math.cos(a)*r*.75),(float)(cy+Math.sin(a)*r*.75),dp(7),p);}line(c,Color.rgb(71,85,105),2,cx-r-dp(20),cy,cx+r+dp(20),cy);line(c,Color.rgb(71,85,105),2,cx,cy-r-dp(20),cx,cy+r+dp(20));arrow(c,cx,dp(52),cx,cy-r-dp(5),Color.rgb(248,113,113),"Fr = "+f(v[0])+" N");arrow(c,dp(20),cy,cx-r-dp(5),cy,Color.rgb(96,165,250),"Fa = "+f(v[1])+" N");lab(c,"C = "+f(v[2])+" N",dp(12),dp(54),Color.rgb(167,243,208));lab(c,"n = "+f(v[3])+" rpm",dp(12),h-dp(20),Color.WHITE);lab(c,"bore Ø ≈ "+f(v[4])+" mm",w*.55f,h-dp(20),Color.rgb(147,197,253));lab(c,"DIŞ BİLEZİK",w*.67f,cy-r-dp(12),Color.rgb(203,213,225));lab(c,"İÇ BİLEZİK",cx-dp(30),cy+dp(7),Color.rgb(148,163,184));}
 void bolt(Canvas c){float w=getWidth(),h=getHeight(),y=h*.50f,x1=w*.16f,x2=w*.84f;float dia=(float)Math.max(dp(10),Math.min(dp(25),v[2]*getResources().getDisplayMetrics().density*.65));line(c,Color.rgb(226,232,240),dia,x1,y,x2,y);p.setColor(Color.rgb(148,163,184));Path head=new Path();head.moveTo(x1-dp(8),y-dp(30));head.lineTo(x1+dp(22),y-dp(30));head.lineTo(x1+dp(35),y);head.lineTo(x1+dp(22),y+dp(30));head.lineTo(x1-dp(8),y+dp(30));head.close();c.drawPath(head,p);float grip=Math.min(dp(82),Math.max(dp(22),(float)v[4]));p.setColor(Color.rgb(71,85,105));c.drawRect(w*.37f,y-grip*.55f,w*.62f,y+grip*.55f,p);for(int k=0;k<9;k++)line(c,Color.rgb(100,116,139),dp(2),x2-dp(75)+k*dp(8),y-dia*.65f,x2-dp(67)+k*dp(8),y+dia*.65f);arrow(c,x2+dp(5),y,x2+dp(70),y,Color.rgb(248,113,113),"F = "+f(v[0])+" N");arrow(c,w*.50f,y+dp(105),w*.50f,y+dp(25),Color.rgb(96,165,250),"V = "+f(v[1])+" N");p.setColor(Color.argb(190,239,68,68));c.drawRect(w*.62f-dp(3),y-dp(24),w*.62f+dp(4),y+dp(24),p);lab(c,"▲ KRİTİK İLK DİŞ / KESİT",w*.48f,y-dp(43),Color.rgb(248,113,113));lab(c,"Ø"+f(v[2])+" mm   Sy="+f(v[3])+" MPa",dp(12),dp(54),Color.WHITE);dim(c,w*.37f,w*.62f,h*.82f,"grip = "+f(v[4])+" mm");lab(c,"BAŞ",x1-dp(12),y+dp(55),Color.rgb(147,197,253));lab(c,"DİŞ",x2-dp(25),y+dp(55),Color.rgb(147,197,253));}
 }
}
