package com.mg.machineelementspro;

import android.app.Activity;
import android.content.Intent;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.View;
import android.widget.*;

public class VisualHomeActivity extends Activity {
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(build());}
 private View build(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(Color.rgb(8,14,22));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(14),dp(16),dp(14),dp(28));s.addView(r);
  r.addView(title("MACHINE ELEMENTS PRO",26,true,Color.WHITE));r.addView(title("Hesapla • Görselleştir • Gerçek ürünü seç",14,false,Color.rgb(148,163,184)));
  HeroView hero=new HeroView();r.addView(hero,new LinearLayout.LayoutParams(-1,dp(245)));
  r.addView(section("MAKİNE ELEMANI SEÇ"));
  GridLayout g=new GridLayout(this);g.setColumnCount(2);r.addView(g,new LinearLayout.LayoutParams(-1,-2));
  card(g,"MIL / SHAFT","M • T • reaksiyon • kritik kesit",0);card(g,"RULMAN","Fr • Fa • C • L10h",1);card(g,"CIVATA","F • V • preload • ilk diş",2);card(g,"DİŞLİ","Ft • Fr • modül • temas",3);card(g,"YAY","F • k • sehim • gerilme",4);card(g,"KAPLİN","Tork • PCD • civata",5);card(g,"KAYIŞ / KASNAK","Güç • hız • gerilmeler",6);card(g,"TÜM ELEMANLAR","8+ görsel hesap modülü",7);
  r.addView(section("MÜHENDİSLİK ARAÇLARI"));
  LinearLayout q=new LinearLayout(this);q.setOrientation(LinearLayout.HORIZONTAL);r.addView(q,new LinearLayout.LayoutParams(-1,dp(68)));
  quick(q,"ÜRÜN\nSEÇ",ProductCatalogActivity.class,Color.rgb(5,150,105));quick(q,"GEARBOX",GearboxDesignerActivity.class,Color.rgb(14,116,144));quick(q,"DRIVE\nTRAIN",DrivetrainActivity.class,Color.rgb(2,132,199));quick(q,"RAPOR",EngineeringReportActivity.class,Color.rgb(100,116,139));
  TextView note=title("Görsel hesap ekranlarında boyut, kuvvet, tork, reaksiyon ve kritik bölgeler canlı güncellenir.",13,false,Color.rgb(148,163,184));note.setPadding(0,dp(14),0,0);r.addView(note);return s;}
 private void card(GridLayout g,String a,String b,int id){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(20,31,45),Color.rgb(10,17,26)});bg.setCornerRadius(dp(16));bg.setStroke(dp(1),Color.rgb(51,65,85));c.setBackground(bg);MiniPart v=new MiniPart(id);c.addView(v,new LinearLayout.LayoutParams(-1,dp(92)));c.addView(title(a,15,true,Color.WHITE));c.addView(title(b,11,false,Color.rgb(148,163,184)));c.setOnClickListener(x->{Intent i;if(id<=2)i=new Intent(this,MachineElementVisualLabActivity.class).putExtra("mode",id);else i=new Intent(this,MachineElementStudioActivity.class);startActivity(i);});GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=dp(155);gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);gp.setMargins(dp(4),dp(4),dp(4),dp(4));g.addView(c,gp);}
 private void quick(LinearLayout q,String s,Class<?> cl,int col){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTextSize(12);b.setBackgroundColor(col);b.setOnClickListener(v->startActivity(new Intent(this,cl)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(3),0,dp(3),0);q.addView(b,p);}
 private TextView section(String s){TextView t=title(s,13,true,Color.rgb(125,211,252));t.setPadding(0,dp(18),0,dp(6));return t;}private TextView title(String s,int z,boolean b,int col){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);if(b)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 private class HeroView extends View{Paint p=new Paint(1),tx=new Paint(1);HeroView(){super(VisualHomeActivity.this);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();p.setShader(new LinearGradient(0,0,w,h,new int[]{Color.rgb(17,29,44),Color.rgb(5,10,16)},null,Shader.TileMode.CLAMP));c.drawRoundRect(new RectF(0,dp(10),w,h-dp(4)),dp(22),dp(22),p);p.setShader(null);for(int x=0;x<w;x+=dp(24)){p.setColor(Color.rgb(25,39,55));p.setStrokeWidth(1);c.drawLine(x,dp(10),x,h,p);}for(int y=dp(10);y<h;y+=dp(24))c.drawLine(0,y,w,y,p);float cy=h*.56f;drawShaft(c,w*.18f,w*.82f,cy);drawBearing(c,w*.23f,cy,dp(34));drawBearing(c,w*.77f,cy,dp(34));drawGear(c,w*.54f,cy-dp(8),dp(42));arrow(c,w*.54f,dp(40),w*.54f,cy-dp(55),Color.rgb(248,113,113));arc(c,w*.40f,cy,dp(48),Color.rgb(74,222,128));tx.setTypeface(Typeface.DEFAULT_BOLD);tx.setTextSize(dp(13));tx.setColor(Color.WHITE);c.drawText("VISUAL ENGINEERING",dp(16),dp(35),tx);tx.setTextSize(dp(11));tx.setColor(Color.rgb(148,163,184));c.drawText("Kuvvet • Tork • Reaksiyon • Kritik Kesit • Ürün",dp(16),dp(54),tx);}}
 private class MiniPart extends View{int id;Paint p=new Paint(1);MiniPart(int i){super(VisualHomeActivity.this);id=i;}protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),cx=w*.5f,cy=h*.52f;p.setColor(Color.rgb(203,213,225));if(id==0){p.setStrokeWidth(dp(12));c.drawLine(w*.18f,cy,w*.82f,cy,p);p.setColor(Color.rgb(248,113,113));c.drawRect(cx-dp(4),cy-dp(18),cx+dp(4),cy+dp(18),p);}else if(id==1){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(9));c.drawCircle(cx,cy,dp(30),p);p.setStrokeWidth(dp(4));c.drawCircle(cx,cy,dp(15),p);p.setStyle(Paint.Style.FILL);for(int k=0;k<8;k++){double a=k*Math.PI/4;c.drawCircle((float)(cx+Math.cos(a)*dp(23)),(float)(cy+Math.sin(a)*dp(23)),dp(4),p);}}else if(id==2){p.setStrokeWidth(dp(11));c.drawLine(w*.20f,cy,w*.78f,cy,p);Path q=new Path();q.moveTo(w*.18f,cy-dp(18));q.lineTo(w*.32f,cy-dp(18));q.lineTo(w*.38f,cy);q.lineTo(w*.32f,cy+dp(18));q.lineTo(w*.18f,cy+dp(18));q.close();c.drawPath(q,p);}else if(id==3){drawGear(c,cx,cy,dp(30));}else if(id==4){Path q=new Path();q.moveTo(cx,dp(12));for(int k=1;k<70;k++)q.lineTo((float)(cx+Math.sin(k*.8)*dp(24)),dp(12)+k*(h-dp(24))/70f);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(5));c.drawPath(q,p);p.setStyle(Paint.Style.FILL);}else if(id==5){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(8));c.drawCircle(cx,cy,dp(31),p);p.setStyle(Paint.Style.FILL);for(int k=0;k<6;k++){double a=k*Math.PI/3;c.drawCircle((float)(cx+Math.cos(a)*dp(22)),(float)(cy+Math.sin(a)*dp(22)),dp(4),p);}}else if(id==6){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(5));c.drawCircle(w*.30f,cy,dp(21),p);c.drawCircle(w*.70f,cy,dp(30),p);c.drawLine(w*.30f,cy-dp(21),w*.70f,cy-dp(30),p);c.drawLine(w*.30f,cy+dp(21),w*.70f,cy+dp(30),p);p.setStyle(Paint.Style.FILL);}else{drawGear(c,w*.38f,cy,dp(24));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(6));c.drawCircle(w*.68f,cy,dp(20),p);p.setStyle(Paint.Style.FILL);}}}
 private void drawShaft(Canvas c,float x1,float x2,float y){Paint p=new Paint(1);p.setShader(new LinearGradient(0,y-dp(12),0,y+dp(12),new int[]{Color.WHITE,Color.rgb(148,163,184),Color.rgb(71,85,105)},null,Shader.TileMode.CLAMP));p.setStrokeWidth(dp(22));p.setStrokeCap(Paint.Cap.ROUND);c.drawLine(x1,y,x2,y,p);p.setShader(null);}private void drawBearing(Canvas c,float cx,float cy,float r){Paint p=new Paint(1);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(10));p.setColor(Color.rgb(203,213,225));c.drawCircle(cx,cy,r,p);p.setStrokeWidth(dp(4));p.setColor(Color.rgb(100,116,139));c.drawCircle(cx,cy,r*.52f,p);p.setStyle(Paint.Style.FILL);}private void drawGear(Canvas c,float cx,float cy,float r){Paint p=new Paint(1);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(7));p.setColor(Color.rgb(203,213,225));c.drawCircle(cx,cy,r,p);for(int k=0;k<16;k++){double a=k*Math.PI*2/16;c.drawLine((float)(cx+Math.cos(a)*r),(float)(cy+Math.sin(a)*r),(float)(cx+Math.cos(a)*(r+dp(9))),(float)(cy+Math.sin(a)*(r+dp(9))),p);}p.setStyle(Paint.Style.FILL);}private void arrow(Canvas c,float x1,float y1,float x2,float y2,int col){Paint p=new Paint(1);p.setColor(col);p.setStrokeWidth(dp(4));c.drawLine(x1,y1,x2,y2,p);Path q=new Path();q.moveTo(x2,y2);q.lineTo(x2-dp(9),y2-dp(12));q.lineTo(x2+dp(9),y2-dp(12));q.close();c.drawPath(q,p);}private void arc(Canvas c,float cx,float cy,float r,int col){Paint p=new Paint(1);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(4));p.setColor(col);c.drawArc(new RectF(cx-r,cy-r,cx+r,cy+r),-210,250,false,p);p.setStyle(Paint.Style.FILL);}
}
