package com.mg.machineelementspro;

import android.app.Activity;
import android.content.Intent;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.View;
import android.widget.*;
import java.util.Locale;

public class VisualWorkbenchActivity extends Activity {
 private static final String[] N={"MIL","RULMAN","CIVATA","DİŞLİ","KAMA","YAY","KAPLİN","KAYIŞ"};
 private int mode=0; private ModelView model; private TextView status; private final SeekBar[] bars=new SeekBar[3]; private final TextView[] vals=new TextView[3];
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(build());}
 private View build(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(Color.rgb(6,11,18));LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(16),dp(14),dp(28));s.addView(root);
  TextView h=t("MACHINE ELEMENTS PRO",26,true,Color.WHITE);root.addView(h);root.addView(t("VISUAL WORKBENCH • canlı teknik model",13,false,Color.rgb(125,211,252)));
  GridLayout g=new GridLayout(this);g.setColumnCount(4);for(int i=0;i<8;i++){final int x=i;Button b=new Button(this);b.setText(N[i]);b.setTextSize(11);b.setTextColor(Color.WHITE);b.setAllCaps(false);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(18,29,43));bg.setCornerRadius(dp(12));bg.setStroke(dp(1),Color.rgb(51,65,85));b.setBackground(bg);b.setOnClickListener(v->{mode=x;resetBars();model.invalidate();updateStatus();});GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(48);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(3),dp(3),dp(3),dp(3));g.addView(b,p);}root.addView(g);
  model=new ModelView();LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,dp(430));mp.topMargin=dp(10);root.addView(model,mp);
  String[] lb={"YÜK / TORK","BOYUT","HIZ / KONUM"};for(int i=0;i<3;i++){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);TextView l=t(lb[i],11,true,Color.rgb(148,163,184));row.addView(l);vals[i]=t("",12,true,Color.WHITE);row.addView(vals[i]);bars[i]=new SeekBar(this);bars[i].setMax(100);bars[i].setProgress(i==0?55:i==1?45:60);final int k=i;bars[i].setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean u){model.invalidate();updateStatus();}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});row.addView(bars[i]);root.addView(row);}
  status=t("",13,false,Color.rgb(203,213,225));status.setPadding(dp(10),dp(8),dp(10),dp(10));root.addView(status);updateStatus();
  Button calc=new Button(this);calc.setText("HESAP MODÜLÜNE GEÇ →");calc.setAllCaps(false);calc.setTextColor(Color.WHITE);calc.setBackgroundColor(Color.rgb(2,132,199));calc.setOnClickListener(v->{if(mode<=2)startActivity(new Intent(this,MachineElementVisualLabActivity.class).putExtra("mode",mode));else startActivity(new Intent(this,MachineElementStudioActivity.class));});root.addView(calc,new LinearLayout.LayoutParams(-1,dp(56)));
  Button products=new Button(this);products.setText("GERÇEK ÜRÜN SEÇİMİ / TÜRKİYE + AVRUPA");products.setAllCaps(false);products.setTextColor(Color.WHITE);products.setBackgroundColor(Color.rgb(5,150,105));products.setOnClickListener(v->startActivity(new Intent(this,ProductCatalogActivity.class)));root.addView(products,new LinearLayout.LayoutParams(-1,dp(56)));return s;}
 private void resetBars(){bars[0].setProgress(55);bars[1].setProgress(45);bars[2].setProgress(60);}
 private void updateStatus(){if(vals[0]==null)return;double a=bars[0].getProgress(),b=bars[1].getProgress(),c=bars[2].getProgress();String[] u=units();vals[0].setText(value(a,0)+" "+u[0]);vals[1].setText(value(b,1)+" "+u[1]);vals[2].setText(value(c,2)+" "+u[2]);status.setText(N[mode]+" • kırmızı: yük/kritik • mavi: reaksiyon/eksenel • yeşil: tork/hareket\nBoyut ve yük değiştikçe model geometrisi ve oklar canlı güncellenir.");}
 private String[] units(){switch(mode){case 0:return new String[]{"N·m","mm","mm"};case 1:return new String[]{"N","mm","rpm"};case 2:return new String[]{"N","mm","mm"};case 3:return new String[]{"N","modül","rpm"};case 4:return new String[]{"N·m","mm","mm"};case 5:return new String[]{"N","mm","mm"};case 6:return new String[]{"N·m","mm","rpm"};default:return new String[]{"kW","mm","rpm"};}}
 private String value(double x,int i){double q=i==0?(x+10)*12:i==1?(x+10)*.65:(x+10)*18;return String.format(Locale.US,"%.1f",q);}
 private TextView t(String s,int z,boolean bold,int col){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(col);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);v.setPadding(0,dp(3),0,dp(5));return v;}private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 private class ModelView extends View{Paint p=new Paint(1),tx=new Paint(1);ModelView(){super(VisualWorkbenchActivity.this);setLayerType(View.LAYER_TYPE_SOFTWARE,null);tx.setTypeface(Typeface.DEFAULT_BOLD);}protected void onDraw(Canvas c){super.onDraw(c);bg(c);title(c);switch(mode){case 0:shaft(c);break;case 1:bearing(c);break;case 2:bolt(c);break;case 3:gear(c);break;case 4:key(c);break;case 5:spring(c);break;case 6:coupling(c);break;default:belt(c);}}
  void bg(Canvas c){p.setShader(new LinearGradient(0,0,getWidth(),getHeight(),new int[]{Color.rgb(17,29,44),Color.rgb(7,12,19)},null,Shader.TileMode.CLAMP));c.drawRoundRect(new RectF(0,0,getWidth(),getHeight()),dp(22),dp(22),p);p.setShader(null);p.setStrokeWidth(1);p.setColor(Color.rgb(27,41,56));for(int x=0;x<getWidth();x+=dp(22))c.drawLine(x,0,x,getHeight(),p);for(int y=0;y<getHeight();y+=dp(22))c.drawLine(0,y,getWidth(),y,p);}void title(Canvas c){label(c,N[mode]+" • TEKNİK MODEL / FBD",dp(14),dp(25),Color.rgb(125,211,252),12);dot(c,dp(14),dp(45),Color.rgb(248,113,113));label(c,"Yük/Kritik",dp(24),dp(49),Color.LTGRAY,10);dot(c,dp(100),dp(45),Color.rgb(96,165,250));label(c,"Reaksiyon",dp(110),dp(49),Color.LTGRAY,10);dot(c,dp(190),dp(45),Color.rgb(74,222,128));label(c,"Tork/Hareket",dp(200),dp(49),Color.LTGRAY,10);}void dot(Canvas c,float x,float y,int co){p.setColor(co);c.drawCircle(x,y,dp(4),p);}void label(Canvas c,String s,float x,float y,int co,int z){tx.setTextSize(dp(z));tx.setColor(co);tx.setShadowLayer(2,0,1,Color.BLACK);c.drawText(s,x,y,tx);tx.clearShadowLayer();}void line(Canvas c,float x1,float y1,float x2,float y2,int co,float sw){p.setShader(null);p.setColor(co);p.setStrokeWidth(sw);p.setStyle(Paint.Style.STROKE);c.drawLine(x1,y1,x2,y2,p);p.setStyle(Paint.Style.FILL);}void arrow(Canvas c,float x1,float y1,float x2,float y2,int co,String s){line(c,x1,y1,x2,y2,co,dp(3));double a=Math.atan2(y2-y1,x2-x1);float L=dp(11);Path q=new Path();q.moveTo(x2,y2);q.lineTo((float)(x2-L*Math.cos(a-.55)),(float)(y2-L*Math.sin(a-.55)));q.lineTo((float)(x2-L*Math.cos(a+.55)),(float)(y2-L*Math.sin(a+.55)));q.close();p.setColor(co);c.drawPath(q,p);label(c,s,x2+dp(4),y2-dp(4),co,10);}float size(){return dp(12)+(bars[1]==null?30:bars[1].getProgress())*.18f;}float pos(){return .22f+(bars[2]==null?50:bars[2].getProgress())*.0055f;}
  void shaft(Canvas c){float w=getWidth(),h=getHeight(),y=h*.53f,x1=w*.13f,x2=w*.87f,d=size();p.setShader(new LinearGradient(0,y-d,0,y+d,new int[]{Color.WHITE,Color.rgb(148,163,184),Color.rgb(55,65,81)},null,Shader.TileMode.CLAMP));p.setShadowLayer(dp(9),0,dp(4),Color.BLACK);c.drawRoundRect(new RectF(x1,y-d,x2,y+d),d,d,p);p.clearShadowLayer();p.setShader(null);float xf=x1+(x2-x1)*pos();bearingAt(c,x1,y,dp(30));bearingAt(c,x2,y,dp(30));arrow(c,xf,y-dp(105),xf,y-d-dp(5),Color.rgb(248,113,113),"M");arc(c,w*.37f,y,dp(50),Color.rgb(74,222,128));arrow(c,x1,y+dp(100),x1,y+d+dp(4),Color.rgb(96,165,250),"RA");arrow(c,x2,y+dp(100),x2,y+d+dp(4),Color.rgb(96,165,250),"RB");p.setColor(Color.argb(120,239,68,68));c.drawRect(xf-dp(8),y-d-dp(8),xf+dp(8),y+d+dp(8),p);label(c,"KRİTİK KESİT",xf-dp(38),y-d-dp(16),Color.rgb(248,113,113),10);dim(c,x1,xf,h*.84f,"a");dim(c,xf,x2,h*.91f,"b");}
  void bearing(Canvas c){float w=getWidth(),h=getHeight(),cx=w*.5f,cy=h*.55f,r=dp(78)+bars[1].getProgress()*.22f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(18));p.setShader(new RadialGradient(cx-r*.3f,cy-r*.3f,r*1.4f,Color.WHITE,Color.rgb(71,85,105),Shader.TileMode.CLAMP));p.setShadowLayer(dp(9),0,dp(4),Color.BLACK);c.drawCircle(cx,cy,r,p);p.clearShadowLayer();p.setShader(null);p.setStrokeWidth(dp(7));p.setColor(Color.rgb(100,116,139));c.drawCircle(cx,cy,r*.48f,p);p.setStyle(Paint.Style.FILL);for(int k=0;k<12;k++){double a=k*Math.PI*2/12;float bx=(float)(cx+Math.cos(a)*r*.74),by=(float)(cy+Math.sin(a)*r*.74);p.setShader(new RadialGradient(bx-dp(2),by-dp(2),dp(11),Color.WHITE,Color.rgb(100,116,139),Shader.TileMode.CLAMP));c.drawCircle(bx,by,dp(9),p);}p.setShader(null);arrow(c,cx,dp(75),cx,cy-r-dp(5),Color.rgb(248,113,113),"Fr");arrow(c,dp(24),cy,cx-r-dp(5),cy,Color.rgb(96,165,250),"Fa");}
  void bolt(Canvas c){float w=getWidth(),h=getHeight(),y=h*.54f,x1=w*.16f,x2=w*.84f,d=size();p.setShader(new LinearGradient(0,y-d,0,y+d,Color.WHITE,Color.rgb(71,85,105),Shader.TileMode.CLAMP));p.setStrokeWidth(d*1.5f);p.setStrokeCap(Paint.Cap.ROUND);c.drawLine(x1+dp(28),y,x2,y,p);p.setStrokeCap(Paint.Cap.BUTT);p.setShader(null);Path q=new Path();q.moveTo(x1-dp(10),y-dp(32));q.lineTo(x1+dp(24),y-dp(32));q.lineTo(x1+dp(40),y);q.lineTo(x1+dp(24),y+dp(32));q.lineTo(x1-dp(10),y+dp(32));q.close();p.setColor(Color.rgb(148,163,184));c.drawPath(q,p);for(int k=0;k<10;k++)line(c,x2-dp(80)+k*dp(8),y-d,x2-dp(72)+k*dp(8),y+d,Color.rgb(71,85,105),dp(2));p.setColor(Color.rgb(55,65,81));c.drawRect(w*.39f,y-dp(52),w*.61f,y+dp(52),p);arrow(c,x2+dp(4),y,x2+dp(72),y,Color.rgb(248,113,113),"F");arrow(c,w*.5f,y+dp(110),w*.5f,y+d,Color.rgb(96,165,250),"V");p.setColor(Color.argb(140,239,68,68));c.drawRect(w*.61f-dp(4),y-dp(28),w*.61f+dp(5),y+dp(28),p);label(c,"KRİTİK İLK DİŞ",w*.49f,y-dp(45),Color.rgb(248,113,113),10);}
  void gear(Canvas c){float w=getWidth(),h=getHeight(),cx=w*.5f,cy=h*.56f,r=dp(72)+bars[1].getProgress()*.25f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(10));p.setColor(Color.rgb(203,213,225));c.drawCircle(cx,cy,r,p);for(int k=0;k<22;k++){double a=k*Math.PI*2/22;line(c,(float)(cx+Math.cos(a)*r),(float)(cy+Math.sin(a)*r),(float)(cx+Math.cos(a)*(r+dp(16))),(float)(cy+Math.sin(a)*(r+dp(16))),Color.rgb(203,213,225),dp(8));}p.setStyle(Paint.Style.FILL);c.drawCircle(cx,cy,dp(24),p);arrow(c,cx+r+dp(65),cy,cx+r+dp(8),cy,Color.rgb(248,113,113),"Ft");arrow(c,cx,cy-dp(130),cx,cy-r-dp(8),Color.rgb(96,165,250),"Fr");label(c,"TEMAS HATTI",cx+r*.45f,cy-r*.72f,Color.rgb(248,113,113),10);}
  void key(Canvas c){float w=getWidth(),h=getHeight(),y=h*.58f,d=size();p.setShader(new LinearGradient(0,y-d,0,y+d,Color.WHITE,Color.rgb(71,85,105),Shader.TileMode.CLAMP));c.drawRoundRect(new RectF(w*.16f,y-d,w*.84f,y+d),d,d,p);p.setShader(null);p.setColor(Color.rgb(234,179,8));c.drawRoundRect(new RectF(w*.41f,y-d-dp(10),w*.62f,y-d+dp(7)),dp(3),dp(3),p);arc(c,w*.52f,y,dp(70),Color.rgb(74,222,128));p.setColor(Color.argb(120,239,68,68));c.drawRect(w*.41f,y-d-dp(12),w*.43f,y-d+dp(10),p);label(c,"KAMA KÖKÜ",w*.38f,y-d-dp(20),Color.rgb(248,113,113),10);}
  void spring(Canvas c){float w=getWidth(),h=getHeight(),cx=w*.5f,y0=dp(95),y1=h-dp(70),amp=dp(55)+bars[1].getProgress()*.35f;Path q=new Path();q.moveTo(cx,y0);for(int i=1;i<100;i++){float y=y0+(y1-y0)*i/100f;float x=(float)(cx+Math.sin(i*.65)*amp);q.lineTo(x,y);}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(8));p.setColor(Color.rgb(203,213,225));p.setShadowLayer(dp(5),0,dp(3),Color.BLACK);c.drawPath(q,p);p.clearShadowLayer();p.setStyle(Paint.Style.FILL);arrow(c,cx,y0-dp(20),cx,y0+dp(40),Color.rgb(248,113,113),"F");arrow(c,cx,y1+dp(35),cx,y1-dp(20),Color.rgb(248,113,113),"F");label(c,"AKTİF SARIM",cx+amp+dp(8),(y0+y1)/2,Color.rgb(125,211,252),10);}
  void coupling(Canvas c){float w=getWidth(),h=getHeight(),cx=w*.5f,cy=h*.56f,r=dp(82)+bars[1].getProgress()*.18f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(18));p.setColor(Color.rgb(203,213,225));c.drawCircle(cx,cy,r,p);p.setStrokeWidth(dp(7));c.drawCircle(cx,cy,r*.36f,p);p.setStyle(Paint.Style.FILL);for(int k=0;k<8;k++){double a=k*Math.PI/4;float x=(float)(cx+Math.cos(a)*r*.68),y=(float)(cy+Math.sin(a)*r*.68);p.setColor(Color.rgb(148,163,184));c.drawCircle(x,y,dp(9),p);p.setColor(Color.rgb(30,41,59));c.drawCircle(x,y,dp(4),p);}arc(c,cx,cy,r+dp(28),Color.rgb(74,222,128));arrow(c,cx+r+dp(60),cy,cx+r+dp(8),cy,Color.rgb(248,113,113),"Fbolt");}
  void belt(Canvas c){float w=getWidth(),h=getHeight(),cy=h*.57f,x1=w*.30f,x2=w*.72f,r1=dp(48)+bars[1].getProgress()*.12f,r2=dp(72)+bars[1].getProgress()*.18f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(10));p.setColor(Color.rgb(148,163,184));c.drawCircle(x1,cy,r1,p);c.drawCircle(x2,cy,r2,p);double a=Math.asin((r2-r1)/(x2-x1));float yTop=(float)(cy-r1*Math.cos(a));float yTop2=(float)(cy-r2*Math.cos(a));float yBot=(float)(cy+r1*Math.cos(a)),yBot2=(float)(cy+r2*Math.cos(a));line(c,x1,yTop,x2,yTop2,Color.rgb(234,179,8),dp(7));line(c,x1,yBot,x2,yBot2,Color.rgb(234,179,8),dp(7));p.setStyle(Paint.Style.FILL);arc(c,x1,cy,r1+dp(18),Color.rgb(74,222,128));arrow(c,w*.5f,yTop-dp(38),w*.5f,yTop-dp(3),Color.rgb(248,113,113),"T1");arrow(c,w*.5f,yBot+dp(38),w*.5f,yBot+dp(3),Color.rgb(96,165,250),"T2");}
  void bearingAt(Canvas c,float x,float y,float r){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(8));p.setColor(Color.rgb(148,163,184));c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.FILL);}void arc(Canvas c,float cx,float cy,float r,int co){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(4));p.setColor(co);c.drawArc(new RectF(cx-r,cy-r,cx+r,cy+r),-210,250,false,p);p.setStyle(Paint.Style.FILL);}void dim(Canvas c,float x1,float x2,float y,String s){line(c,x1,y,x2,y,Color.LTGRAY,1);label(c,s,(x1+x2)/2-dp(5),y-dp(6),Color.WHITE,10);}
 }
}
