package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.util.*;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;

public class CadSurfaceActivity extends Activity{
 static final int REQ=99; android.opengl.GLSurfaceView gl; SmoothRenderer renderer; TextView info,mode; ViewerActivity.Model model; CadViewerActivity.Bounds bounds; String fileName="";
 @Override public void onCreate(Bundle b){super.onCreate(b);build();Uri u=getIntent().getData();if(u!=null)load(u);}
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(12,7,12,7);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);return b;}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(8,10,14));root.setPadding(10,10,10,10);TextView title=tv("MG CAD CONTINUOUS SURFACE",21);title.setGravity(Gravity.CENTER);root.addView(title);Button open=btn("📂 DOSYA AÇ");open.setTextSize(16);open.setOnClickListener(v->pick());root.addView(open);info=tv("Model bekleniyor…",13);info.setTextColor(Color.LTGRAY);root.addView(info);mode=tv("Görünüş: İzometrik • Dolu ve düzgün surface",12);mode.setTextColor(Color.LTGRAY);root.addView(mode);HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);String[]n={"ISO","ÖN","SAĞ","ÜST","KENAR","SIFIRLA"};for(String x:n){Button b=btn(x);bar.addView(b);if(x.equals("ISO"))b.setOnClickListener(v->setView(20,-35,"İzometrik"));else if(x.equals("ÖN"))b.setOnClickListener(v->setView(0,0,"Ön"));else if(x.equals("SAĞ"))b.setOnClickListener(v->setView(0,90,"Sağ"));else if(x.equals("ÜST"))b.setOnClickListener(v->setView(90,0,"Üst"));else if(x.equals("KENAR"))b.setOnClickListener(v->{renderer.edges=!renderer.edges;mode.setText(renderer.edges?"Surface + teknik kenar":"Dolu continuous surface");});else b.setOnClickListener(v->{renderer.zoom=1;setView(20,-35,"İzometrik");});}hs.addView(bar);root.addView(hs);gl=new android.opengl.GLSurfaceView(this);gl.setEGLContextClientVersion(2);renderer=new SmoothRenderer();gl.setRenderer(renderer);gl.setRenderMode(android.opengl.GLSurfaceView.RENDERMODE_CONTINUOUSLY);gl.setOnTouchListener(new ViewerActivity.TouchControl(renderer));root.addView(gl,new LinearLayout.LayoutParams(-1,0,1));TextView foot=tv("Surface hattı: gürültü eleme → vertex welding → ortak topology → smooth normals → dolu yüzey.\nTek parmak döndür • iki parmak zoom",11);foot.setTextColor(Color.GRAY);root.addView(foot);setContentView(root);}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,REQ);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==REQ&&c==RESULT_OK&&d!=null&&d.getData()!=null)load(d.getData());}
 void load(Uri u){new Thread(()->{try{fileName=name(u);runOnUiThread(()->info.setText("Yükleniyor, topology birleştiriliyor…"));bounds=CadViewerActivity.BoundsReader.read(this,u,fileName);ViewerActivity.Model raw=ViewerActivity.ModelLoader.load(this,u,fileName);if(raw.idx==null||raw.idx.length<3)raw=CadViewerActivity.SurfaceMesher.build(raw);model=SurfaceRepair.weld(raw);renderer.setModel(model);runOnUiThread(this::updateInfo);}catch(Exception e){runOnUiThread(()->info.setText("Dosya açılamadı: "+e.getClass().getSimpleName()+" • "+e.getMessage()));}}).start();}
 void updateInfo(){String dim=bounds!=null&&bounds.valid()?String.format(Locale.US,"X %.4f   Y %.4f   Z %.4f",bounds.dx(),bounds.dy(),bounds.dz()):"ölçü okunamadı";info.setText(fileName+"\n"+model.vertexCount()+" welded vertex • "+model.triangleCount()+" connected triangle\nModel boyutları (dosya birimi): "+dim+"\nMod: SINGLE CONTINUOUS SHADED SURFACE");}
 void setView(float x,float y,String s){renderer.rx=x;renderer.ry=y;mode.setText("Görünüş: "+s+" • "+(renderer.edges?"Surface + kenar":"Dolu surface"));}
 String name(Uri u){String n="model";try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null){int ix=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&ix>=0)n=c.getString(ix);}}catch(Exception ignored){}return n;}
 @Override protected void onPause(){super.onPause();if(gl!=null)gl.onPause();}@Override protected void onResume(){super.onResume();if(gl!=null)gl.onResume();}

 static class SurfaceRepair{
  static ViewerActivity.Model weld(ViewerActivity.Model m){if(m==null||m.v==null||m.idx==null)return m;float[]v=m.v;int n=v.length/3;float eps=.0015f;HashMap<String,Integer>map=new HashMap<>();ArrayList<float[]>nv=new ArrayList<>();int[]remap=new int[n];for(int i=0;i<n;i++){int qx=Math.round(v[i*3]/eps),qy=Math.round(v[i*3+1]/eps),qz=Math.round(v[i*3+2]/eps);String k=qx+":"+qy+":"+qz;Integer id=map.get(k);if(id==null){id=nv.size();map.put(k,id);nv.add(new float[]{v[i*3],v[i*3+1],v[i*3+2]});}remap[i]=id;}ArrayList<Integer>ii=new ArrayList<>();HashSet<String>seen=new HashSet<>();for(int p=0;p+2<m.idx.length;p+=3){int a=remap[m.idx[p]],b=remap[m.idx[p+1]],c=remap[m.idx[p+2]];if(a==b||b==c||a==c)continue;int x=Math.min(a,Math.min(b,c)),z=Math.max(a,Math.max(b,c)),y=a+b+c-x-z;String k=x+":"+y+":"+z;if(seen.add(k)){ii.add(a);ii.add(b);ii.add(c);}}float[]out=new float[nv.size()*3];for(int i=0;i<nv.size();i++){out[i*3]=nv.get(i)[0];out[i*3+1]=nv.get(i)[1];out[i*3+2]=nv.get(i)[2];}int[]idx=new int[ii.size()];for(int i=0;i<idx.length;i++)idx[i]=ii.get(i);return new ViewerActivity.Model(out,idx);}
 }

 static class SmoothRenderer extends ViewerActivity.ModelRenderer{boolean edges=false;FloatBuffer pos,nor;int count,prog,aPos,aNor,uMvp,uRot,uColor;ViewerActivity.Model local;
  @Override void setModel(ViewerActivity.Model m){local=m;model=m;pos=null;nor=null;count=0;}
  @Override public void onSurfaceCreated(GL10 g,EGLConfig c){android.opengl.GLES20.glClearColor(.025f,.032f,.045f,1);android.opengl.GLES20.glEnable(android.opengl.GLES20.GL_DEPTH_TEST);String vs="attribute vec3 p;attribute vec3 n;uniform mat4 m;uniform mat4 r;varying vec3 N;varying vec3 P;void main(){gl_Position=m*vec4(p,1.0);N=normalize((r*vec4(n,0.0)).xyz);P=(r*vec4(p,1.0)).xyz;}";String fs="precision mediump float;varying vec3 N;varying vec3 P;uniform vec4 c;void main(){vec3 L=normalize(vec3(-0.35,0.55,0.75));float d=max(dot(normalize(N),L),0.0);float rim=pow(1.0-max(abs(N.z),0.0),2.2);vec3 col=c.rgb*(0.32+0.68*d)+vec3(0.08,0.22,0.34)*rim;gl_FragColor=vec4(col,1.0);}";prog=link(vs,fs);aPos=android.opengl.GLES20.glGetAttribLocation(prog,"p");aNor=android.opengl.GLES20.glGetAttribLocation(prog,"n");uMvp=android.opengl.GLES20.glGetUniformLocation(prog,"m");uRot=android.opengl.GLES20.glGetUniformLocation(prog,"r");uColor=android.opengl.GLES20.glGetUniformLocation(prog,"c");}
  @Override public void onSurfaceChanged(GL10 g,int w,int h){android.opengl.GLES20.glViewport(0,0,w,h);}
  void prepare(){ViewerActivity.Model m=local;if(m==null||m.idx==null)return;int vn=m.v.length/3;float[]acc=new float[vn*3];for(int i=0;i+2<m.idx.length;i+=3){int ia=m.idx[i],ib=m.idx[i+1],ic=m.idx[i+2];if(ia<0||ib<0||ic<0||ia>=vn||ib>=vn||ic>=vn)continue;float ax=m.v[ib*3]-m.v[ia*3],ay=m.v[ib*3+1]-m.v[ia*3+1],az=m.v[ib*3+2]-m.v[ia*3+2],bx=m.v[ic*3]-m.v[ia*3],by=m.v[ic*3+1]-m.v[ia*3+1],bz=m.v[ic*3+2]-m.v[ia*3+2];float nx=ay*bz-az*by,ny=az*bx-ax*bz,nz=ax*by-ay*bx;for(int q:new int[]{ia,ib,ic}){acc[q*3]+=nx;acc[q*3+1]+=ny;acc[q*3+2]+=nz;}}for(int i=0;i<vn;i++){float x=acc[i*3],y=acc[i*3+1],z=acc[i*3+2],l=(float)Math.sqrt(x*x+y*y+z*z);if(l<1e-8f){acc[i*3+2]=1;}else{acc[i*3]/=l;acc[i*3+1]/=l;acc[i*3+2]/=l;}}
   float[]pv=new float[m.idx.length*3],nn=new float[m.idx.length*3];int k=0;for(int id:m.idx){if(id<0||id>=vn)continue;pv[k*3]=m.v[id*3];pv[k*3+1]=m.v[id*3+1];pv[k*3+2]=m.v[id*3+2];nn[k*3]=acc[id*3];nn[k*3+1]=acc[id*3+1];nn[k*3+2]=acc[id*3+2];k++;}count=k;pos=ByteBuffer.allocateDirect(k*12).order(ByteOrder.nativeOrder()).asFloatBuffer();pos.put(pv,0,k*3).position(0);nor=ByteBuffer.allocateDirect(k*12).order(ByteOrder.nativeOrder()).asFloatBuffer();nor.put(nn,0,k*3).position(0);}
  @Override public void onDrawFrame(GL10 g){android.opengl.GLES20.glClear(android.opengl.GLES20.GL_COLOR_BUFFER_BIT|android.opengl.GLES20.GL_DEPTH_BUFFER_BIT);if(local==null||local.idx==null||local.idx.length<3)return;if(pos==null)prepare();if(pos==null||count<3)return;float[]pr=new float[16],mv=new float[16],rot=new float[16],mvp=new float[16];android.opengl.Matrix.perspectiveM(pr,0,45,1f,.1f,100);android.opengl.Matrix.setIdentityM(mv,0);android.opengl.Matrix.translateM(mv,0,0,0,-4f/Math.max(.25f,zoom));android.opengl.Matrix.rotateM(mv,0,rx,1,0,0);android.opengl.Matrix.rotateM(mv,0,ry,0,1,0);android.opengl.Matrix.multiplyMM(mvp,0,pr,0,mv,0);android.opengl.Matrix.setIdentityM(rot,0);android.opengl.Matrix.rotateM(rot,0,rx,1,0,0);android.opengl.Matrix.rotateM(rot,0,ry,0,1,0);android.opengl.GLES20.glUseProgram(prog);android.opengl.GLES20.glUniformMatrix4fv(uMvp,1,false,mvp,0);android.opengl.GLES20.glUniformMatrix4fv(uRot,1,false,rot,0);android.opengl.GLES20.glUniform4f(uColor,.18f,.67f,.84f,1);android.opengl.GLES20.glEnableVertexAttribArray(aPos);android.opengl.GLES20.glEnableVertexAttribArray(aNor);pos.position(0);nor.position(0);android.opengl.GLES20.glVertexAttribPointer(aPos,3,android.opengl.GLES20.GL_FLOAT,false,12,pos);android.opengl.GLES20.glVertexAttribPointer(aNor,3,android.opengl.GLES20.GL_FLOAT,false,12,nor);android.opengl.GLES20.glDrawArrays(android.opengl.GLES20.GL_TRIANGLES,0,count);if(edges){android.opengl.GLES20.glUniform4f(uColor,.05f,.08f,.11f,1);android.opengl.GLES20.glDrawArrays(android.opengl.GLES20.GL_LINES,0,count);}android.opengl.GLES20.glDisableVertexAttribArray(aPos);android.opengl.GLES20.glDisableVertexAttribArray(aNor);}
 }
}
