package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.regex.*;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;

public class CadViewerActivity extends Activity{
 static final int REQ=88; SurfaceRenderer renderer; android.opengl.GLSurfaceView gl; TextView info,viewName; ViewerActivity.Model current; Bounds bounds; String fileName="";
 @Override public void onCreate(Bundle b){super.onCreate(b);build();Uri u=getIntent().getData();if(u!=null)load(u);}
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(12,8,12,8);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);return b;}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(9,10,13));root.setPadding(10,10,10,10);TextView title=tv("MG CAD SURFACE VIEWER",22);title.setGravity(Gravity.CENTER);root.addView(title);Button open=btn("📂 DOSYA AÇ");open.setTextSize(16);open.setOnClickListener(v->pick());root.addView(open);info=tv("Model bekleniyor…\nOBJ • STL • PLY • XYZ • GLB • STEP • IGES",13);info.setTextColor(Color.LTGRAY);root.addView(info);viewName=tv("Görünüş: İzometrik",12);viewName.setTextColor(Color.LTGRAY);root.addView(viewName);
  HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);String[]names={"ISO","ÖN","SAĞ","ÜST","SURFACE","SIFIRLA"};for(String n:names){Button b=btn(n);bar.addView(b);if(n.equals("ISO"))b.setOnClickListener(v->setView(20,-35,"İzometrik"));else if(n.equals("ÖN"))b.setOnClickListener(v->setView(0,0,"Ön (XY)"));else if(n.equals("SAĞ"))b.setOnClickListener(v->setView(0,90,"Sağ (YZ)"));else if(n.equals("ÜST"))b.setOnClickListener(v->setView(90,0,"Üst (XZ)"));else if(n.equals("SURFACE"))b.setOnClickListener(v->{renderer.wireframe=!renderer.wireframe;viewName.setText(renderer.wireframe?"Görünüş: Surface + kenarlar":"Görünüş: Surface");});else b.setOnClickListener(v->{renderer.zoom=1;setView(20,-35,"İzometrik");});}hs.addView(bar);root.addView(hs);
  gl=new android.opengl.GLSurfaceView(this);gl.setEGLContextClientVersion(2);renderer=new SurfaceRenderer();gl.setRenderer(renderer);gl.setRenderMode(android.opengl.GLSurfaceView.RENDERMODE_CONTINUOUSLY);gl.setOnTouchListener(new ViewerActivity.TouchControl(renderer));root.addView(gl,new LinearLayout.LayoutParams(-1,0,1));TextView foot=tv("Tek parmak: döndür • iki parmak: zoom\nNokta bulutu otomatik yüzeye dönüştürülür; varsayılan görünüm sürekli surface mesh'tir.",12);foot.setTextColor(Color.GRAY);root.addView(foot);setContentView(root);}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,REQ);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==REQ&&c==RESULT_OK&&d!=null&&d.getData()!=null)load(d.getData());}
 void load(Uri u){new Thread(()->{try{fileName=name(u);runOnUiThread(()->info.setText("Yükleniyor ve surface oluşturuluyor: "+fileName));bounds=BoundsReader.read(this,u,fileName);current=ViewerActivity.ModelLoader.load(this,u,fileName);if(current.idx==null||current.idx.length<3)current=SurfaceMesher.build(current);renderer.setModel(current);runOnUiThread(this::updateInfo);}catch(Exception e){runOnUiThread(()->info.setText("Dosya açılamadı: "+e.getClass().getSimpleName()+" • "+e.getMessage()));}}).start();}
 void updateInfo(){String ext=ext(fileName).toUpperCase(Locale.US);String dim=bounds!=null&&bounds.valid()?String.format(Locale.US,"X: %.4f   Y: %.4f   Z: %.4f",bounds.dx(),bounds.dy(),bounds.dz()):"X/Y/Z ölçüsü okunamadı";info.setText(fileName+"\nFormat: "+ext+"   •   "+current.vertexCount()+" vertex   •   "+current.triangleCount()+" surface triangle\nModel boyutları (dosya birimi):\n"+dim+"\nMod: CONTINUOUS SURFACE MESH");}
 void setView(float x,float y,String n){renderer.rx=x;renderer.ry=y;viewName.setText("Görünüş: "+n);}
 String name(Uri u){String n="model";try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null){int ix=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&ix>=0)n=c.getString(ix);}}catch(Exception ignored){}return n;}
 static String ext(String n){int i=n.lastIndexOf('.');return i<0?"":n.substring(i+1);}
 @Override protected void onPause(){super.onPause();if(gl!=null)gl.onPause();}@Override protected void onResume(){super.onResume();if(gl!=null)gl.onResume();}

 static class SurfaceMesher{
  static ViewerActivity.Model build(ViewerActivity.Model src){float[]v=src.v;int n=v.length/3;if(n<3)return src;int sample=Math.max(1,n/12000);ArrayList<Integer> ids=new ArrayList<>();float cell=estimateCell(v,sample);HashMap<Long,ArrayList<Integer>> grid=new HashMap<>();for(int i=0;i<n;i+=sample){int gx=(int)Math.floor(v[i*3]/cell),gy=(int)Math.floor(v[i*3+1]/cell),gz=(int)Math.floor(v[i*3+2]/cell);long k=key(gx,gy,gz);grid.computeIfAbsent(k,z->new ArrayList<>()).add(i);}HashSet<Long>triSet=new HashSet<>();for(int i=0;i<n;i+=sample){int gx=(int)Math.floor(v[i*3]/cell),gy=(int)Math.floor(v[i*3+1]/cell),gz=(int)Math.floor(v[i*3+2]/cell);ArrayList<Integer>cand=new ArrayList<>();for(int dz=-1;dz<=1;dz++)for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){ArrayList<Integer>a=grid.get(key(gx+dx,gy+dy,gz+dz));if(a!=null)cand.addAll(a);}int a=-1,b=-1;float da=Float.MAX_VALUE,db=Float.MAX_VALUE;for(int j:cand){if(j==i)continue;float d=dist2(v,i,j);if(d<da){db=da;b=a;da=d;a=j;}else if(d<db){db=d;b=j;}}float max=cell*cell*3.5f;if(a<0||b<0||da>max||db>max)continue;if(area2(v,i,a,b)<cell*cell*.004f)continue;int x=i,y=a,z=b;int mn=Math.min(x,Math.min(y,z)),mx=Math.max(x,Math.max(y,z)),md=x+y+z-mn-mx;long tk=(((long)mn&0x1fffffL)<<42)|(((long)md&0x1fffffL)<<21)|((long)mx&0x1fffffL);if(triSet.add(tk)){ids.add(x);ids.add(y);ids.add(z);}}
   if(ids.size()<3){for(int i=2;i<n;i+=sample){ids.add(0);ids.add(Math.max(0,i-sample));ids.add(i);}}
   int[]idx=new int[ids.size()];for(int i=0;i<idx.length;i++)idx[i]=ids.get(i);return new ViewerActivity.Model(v,idx);
  }
  static float estimateCell(float[]v,int step){int n=v.length/3;float[]ds=new float[Math.min(1500,Math.max(1,n/step-1))];int c=0;int prev=0;for(int i=step;i<n&&c<ds.length;i+=step){float d=(float)Math.sqrt(dist2(v,prev,i));if(d>1e-5f&&Float.isFinite(d))ds[c++]=d;prev=i;}if(c==0)return .08f;Arrays.sort(ds,0,c);float m=ds[c/2];return Math.max(.025f,Math.min(.35f,m*2.2f));}
  static float dist2(float[]v,int a,int b){float x=v[a*3]-v[b*3],y=v[a*3+1]-v[b*3+1],z=v[a*3+2]-v[b*3+2];return x*x+y*y+z*z;}
  static float area2(float[]v,int a,int b,int c){float ax=v[b*3]-v[a*3],ay=v[b*3+1]-v[a*3+1],az=v[b*3+2]-v[a*3+2],bx=v[c*3]-v[a*3],by=v[c*3+1]-v[a*3+1],bz=v[c*3+2]-v[a*3+2];float x=ay*bz-az*by,y=az*bx-ax*bz,z=ax*by-ay*bx;return x*x+y*y+z*z;}
  static long key(int x,int y,int z){long a=(x+1048576)&0x1fffff,b=(y+1048576)&0x1fffff,c=(z+1048576)&0x1fffff;return(a<<42)|(b<<21)|c;}
 }

 static class SurfaceRenderer extends ViewerActivity.ModelRenderer{boolean wireframe=false;int surfaceProg,sPos,sMvp,sColor;FloatBuffer svb;IntBuffer sib;int scount;
  @Override void setModel(ViewerActivity.Model m){super.setModel(m);svb=null;sib=null;scount=0;}
  @Override public void onSurfaceCreated(GL10 g,EGLConfig c){android.opengl.GLES20.glClearColor(.035f,.04f,.055f,1);android.opengl.GLES20.glEnable(android.opengl.GLES20.GL_DEPTH_TEST);android.opengl.GLES20.glEnable(android.opengl.GLES20.GL_CULL_FACE);android.opengl.GLES20.glCullFace(android.opengl.GLES20.GL_BACK);String vs="attribute vec3 a;uniform mat4 m;varying float z;void main(){gl_Position=m*vec4(a,1.0);z=a.z;}";String fs="precision mediump float;uniform vec4 c;varying float z;void main(){float l=.82+clamp(z*.08,-.12,.12);gl_FragColor=vec4(c.rgb*l,c.a);}";surfaceProg=link2(vs,fs);sPos=android.opengl.GLES20.glGetAttribLocation(surfaceProg,"a");sMvp=android.opengl.GLES20.glGetUniformLocation(surfaceProg,"m");sColor=android.opengl.GLES20.glGetUniformLocation(surfaceProg,"c");}
  @Override public void onSurfaceChanged(GL10 g,int w,int h){android.opengl.GLES20.glViewport(0,0,w,h);}
  @Override public void onDrawFrame(GL10 g){android.opengl.GLES20.glClear(android.opengl.GLES20.GL_COLOR_BUFFER_BIT|android.opengl.GLES20.GL_DEPTH_BUFFER_BIT);ViewerActivity.Model m=model;if(m==null||m.v==null||m.v.length==0||m.idx==null||m.idx.length<3)return;if(svb==null){svb=ByteBuffer.allocateDirect(m.v.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();svb.put(m.v).position(0);sib=ByteBuffer.allocateDirect(m.idx.length*4).order(ByteOrder.nativeOrder()).asIntBuffer();sib.put(m.idx).position(0);scount=m.idx.length;}float[]pr=new float[16],mv=new float[16],mvp=new float[16];android.opengl.Matrix.perspectiveM(pr,0,45,1f,.1f,100);android.opengl.Matrix.setIdentityM(mv,0);android.opengl.Matrix.translateM(mv,0,0,0,-4f/Math.max(.25f,zoom));android.opengl.Matrix.rotateM(mv,0,rx,1,0,0);android.opengl.Matrix.rotateM(mv,0,ry,0,1,0);android.opengl.Matrix.multiplyMM(mvp,0,pr,0,mv,0);android.opengl.GLES20.glUseProgram(surfaceProg);android.opengl.GLES20.glUniformMatrix4fv(sMvp,1,false,mvp,0);android.opengl.GLES20.glEnableVertexAttribArray(sPos);android.opengl.GLES20.glVertexAttribPointer(sPos,3,android.opengl.GLES20.GL_FLOAT,false,12,svb);android.opengl.GLES20.glUniform4f(sColor,.28f,.72f,.88f,1);sib.position(0);android.opengl.GLES20.glDrawElements(android.opengl.GLES20.GL_TRIANGLES,scount,android.opengl.GLES20.GL_UNSIGNED_INT,sib);if(wireframe){android.opengl.GLES20.glDisable(android.opengl.GLES20.GL_CULL_FACE);android.opengl.GLES20.glUniform4f(sColor,.06f,.08f,.1f,1);sib.position(0);android.opengl.GLES20.glDrawElements(android.opengl.GLES20.GL_LINES,scount,android.opengl.GLES20.GL_UNSIGNED_INT,sib);android.opengl.GLES20.glEnable(android.opengl.GLES20.GL_CULL_FACE);}android.opengl.GLES20.glDisableVertexAttribArray(sPos);}
  int sh(int t,String s){int x=android.opengl.GLES20.glCreateShader(t);android.opengl.GLES20.glShaderSource(x,s);android.opengl.GLES20.glCompileShader(x);return x;}int link2(String v,String f){int p=android.opengl.GLES20.glCreateProgram();android.opengl.GLES20.glAttachShader(p,sh(android.opengl.GLES20.GL_VERTEX_SHADER,v));android.opengl.GLES20.glAttachShader(p,sh(android.opengl.GLES20.GL_FRAGMENT_SHADER,f));android.opengl.GLES20.glLinkProgram(p);return p;}
 }

 static class Bounds{float minx=Float.MAX_VALUE,miny=Float.MAX_VALUE,minz=Float.MAX_VALUE,maxx=-Float.MAX_VALUE,maxy=-Float.MAX_VALUE,maxz=-Float.MAX_VALUE;void add(float x,float y,float z){if(!Float.isFinite(x)||!Float.isFinite(y)||!Float.isFinite(z))return;minx=Math.min(minx,x);miny=Math.min(miny,y);minz=Math.min(minz,z);maxx=Math.max(maxx,x);maxy=Math.max(maxy,y);maxz=Math.max(maxz,z);}boolean valid(){return minx!=Float.MAX_VALUE;}float dx(){return maxx-minx;}float dy(){return maxy-miny;}float dz(){return maxz-minz;}}
 static class BoundsReader{
  static Bounds read(Context c,Uri u,String name)throws Exception{byte[]d=readAll(c.getContentResolver().openInputStream(u),60*1024*1024);String e=ext(name).toLowerCase(Locale.US);if(e.equals("glb"))return glb(d);if(e.equals("stl"))return stl(d);String s=new String(d,StandardCharsets.UTF_8);if(e.equals("obj"))return obj(s);if(e.equals("ply"))return ply(s);if(e.equals("xyz")||e.equals("pts"))return xyz(s);if(e.equals("step")||e.equals("stp"))return step(s);if(e.equals("igs")||e.equals("iges"))return iges(s);return generic(s);}
  static byte[] readAll(InputStream in,int max)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n,t=0;while((n=in.read(b))>0){t+=n;if(t>max)throw new IOException("Dosya çok büyük (>60 MB)");o.write(b,0,n);}in.close();return o.toByteArray();}
  static float f(String s){return Float.parseFloat(s.replace("D","E").replace("d","e"));}
  static Bounds obj(String s){Bounds b=new Bounds();for(String l:s.split("\\r?\\n")){l=l.trim();if(l.startsWith("v ")){String[]p=l.split("\\s+");if(p.length>=4)try{b.add(f(p[1]),f(p[2]),f(p[3]));}catch(Exception ignored){}}}return b;}
  static Bounds xyz(String s){Bounds b=new Bounds();for(String l:s.split("\\r?\\n")){String[]p=l.trim().split("[ ,;\\t]+");if(p.length>=3)try{b.add(f(p[0]),f(p[1]),f(p[2]));}catch(Exception ignored){}}return b;}
  static Bounds ply(String s){int h=s.indexOf("end_header");return h<0?xyz(s):xyz(s.substring(Math.min(s.length(),s.indexOf('\n',h)+1)));}
  static Bounds step(String s){Bounds b=new Bounds();Matcher m=Pattern.compile("CARTESIAN_POINT\\s*\\([^,]*,\\s*\\(([-+0-9.eEdD]+),\\s*([-+0-9.eEdD]+),\\s*([-+0-9.eEdD]+)\\)\\)",Pattern.CASE_INSENSITIVE).matcher(s);while(m.find())try{b.add(f(m.group(1)),f(m.group(2)),f(m.group(3)));}catch(Exception ignored){}return b;}
  static Bounds iges(String s){Bounds b=new Bounds();Matcher m=Pattern.compile("116,\\s*([-+0-9.eEdD]+),\\s*([-+0-9.eEdD]+),\\s*([-+0-9.eEdD]+)").matcher(s);while(m.find())try{b.add(f(m.group(1)),f(m.group(2)),f(m.group(3)));}catch(Exception ignored){}return b;}
  static Bounds generic(String s){Bounds b=new Bounds();Matcher m=Pattern.compile("([-+]?[0-9]*\\.?[0-9]+(?:[eEdD][-+]?\\d+)?)\\s*[,; ]+\\s*([-+]?[0-9]*\\.?[0-9]+(?:[eEdD][-+]?\\d+)?)\\s*[,; ]+\\s*([-+]?[0-9]*\\.?[0-9]+(?:[eEdD][-+]?\\d+)?)").matcher(s);int n=0;while(m.find()&&n++<500000)try{b.add(f(m.group(1)),f(m.group(2)),f(m.group(3)));}catch(Exception ignored){}return b;}
  static Bounds stl(byte[]d){Bounds out=new Bounds();if(d.length>=84){ByteBuffer b=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);b.position(80);long n=Integer.toUnsignedLong(b.getInt());if(84+n*50L==d.length){for(int i=0;i<n;i++){b.position(b.position()+12);for(int k=0;k<3;k++)out.add(b.getFloat(),b.getFloat(),b.getFloat());b.position(b.position()+2);}return out;}}String s=new String(d,StandardCharsets.UTF_8);Matcher m=Pattern.compile("vertex\\s+([-+0-9.eE]+)\\s+([-+0-9.eE]+)\\s+([-+0-9.eE]+)").matcher(s);while(m.find())out.add(f(m.group(1)),f(m.group(2)),f(m.group(3)));return out;}
  static Bounds glb(byte[]d)throws Exception{Bounds out=new Bounds();if(d.length<20)return out;ByteBuffer b=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);if(b.getInt()!=0x46546c67)return out;b.getInt();b.getInt();int jl=b.getInt();b.getInt();byte[]j=new byte[jl];b.get(j);String s=new String(j,StandardCharsets.UTF_8);Matcher mi=Pattern.compile("\\\"min\\\"\\s*:\\s*\\[\\s*([-+0-9.eE]+)\\s*,\\s*([-+0-9.eE]+)\\s*,\\s*([-+0-9.eE]+)\\s*\\]").matcher(s);Matcher ma=Pattern.compile("\\\"max\\\"\\s*:\\s*\\[\\s*([-+0-9.eE]+)\\s*,\\s*([-+0-9.eE]+)\\s*,\\s*([-+0-9.eE]+)\\s*\\]").matcher(s);if(mi.find()&&ma.find()){out.add(f(mi.group(1)),f(mi.group(2)),f(mi.group(3)));out.add(f(ma.group(1)),f(ma.group(2)),f(ma.group(3)));}return out;}
 }
}
