package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.regex.*;

public class CadViewerActivity extends Activity{
 static final int REQ=88; ViewerActivity.ModelRenderer renderer; android.opengl.GLSurfaceView gl; TextView info,viewName; ViewerActivity.Model current; int[] originalIdx; Bounds bounds; String fileName=""; boolean pointsOnly=false;
 @Override public void onCreate(Bundle b){super.onCreate(b);build();Uri u=getIntent().getData();if(u!=null)load(u);}
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(12,8,12,8);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);return b;}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(9,10,13));root.setPadding(10,10,10,10);TextView title=tv("MG CAD VIEWER",22);title.setGravity(Gravity.CENTER);root.addView(title);Button open=btn("📂 DOSYA AÇ");open.setTextSize(16);open.setOnClickListener(v->pick());root.addView(open);info=tv("Model bekleniyor…\nOBJ • STL • PLY • XYZ • GLB • STEP • IGES",13);info.setTextColor(Color.LTGRAY);root.addView(info);viewName=tv("Görünüş: İzometrik",12);viewName.setTextColor(Color.LTGRAY);root.addView(viewName);
  HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);String[]names={"ISO","ÖN","SAĞ","ÜST","NOKTA/MESH","SIFIRLA"};for(String n:names){Button b=btn(n);bar.addView(b);if(n.equals("ISO"))b.setOnClickListener(v->setView(20,-35,"İzometrik"));else if(n.equals("ÖN"))b.setOnClickListener(v->setView(0,0,"Ön (XY)"));else if(n.equals("SAĞ"))b.setOnClickListener(v->setView(0,90,"Sağ (YZ)"));else if(n.equals("ÜST"))b.setOnClickListener(v->setView(90,0,"Üst (XZ)"));else if(n.equals("NOKTA/MESH"))b.setOnClickListener(v->toggleMode());else b.setOnClickListener(v->{renderer.zoom=1;setView(20,-35,"İzometrik");});}hs.addView(bar);root.addView(hs);
  gl=new android.opengl.GLSurfaceView(this);gl.setEGLContextClientVersion(2);renderer=new ViewerActivity.ModelRenderer();gl.setRenderer(renderer);gl.setRenderMode(android.opengl.GLSurfaceView.RENDERMODE_CONTINUOUSLY);gl.setOnTouchListener(new ViewerActivity.TouchControl(renderer));root.addView(gl,new LinearLayout.LayoutParams(-1,0,1));TextView foot=tv("Tek parmak: döndür • iki parmak: zoom\nCAD paneli: görünüş seçimi + gerçek dosya ölçüleri + geometri sayıları",12);foot.setTextColor(Color.GRAY);root.addView(foot);setContentView(root);}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,REQ);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==REQ&&c==RESULT_OK&&d!=null&&d.getData()!=null)load(d.getData());}
 void load(Uri u){new Thread(()->{try{fileName=name(u);runOnUiThread(()->info.setText("Yükleniyor: "+fileName));bounds=BoundsReader.read(this,u,fileName);current=ViewerActivity.ModelLoader.load(this,u,fileName);originalIdx=current.idx;renderer.setModel(current);pointsOnly=false;runOnUiThread(this::updateInfo);}catch(Exception e){runOnUiThread(()->info.setText("Dosya açılamadı: "+e.getClass().getSimpleName()+" • "+e.getMessage()));}}).start();}
 void updateInfo(){String ext=ext(fileName).toUpperCase(Locale.US);String dim=bounds!=null&&bounds.valid()?String.format(Locale.US,"X: %.4f   Y: %.4f   Z: %.4f",bounds.dx(),bounds.dy(),bounds.dz()):"X/Y/Z ölçüsü okunamadı";info.setText(fileName+"\nFormat: "+ext+"   •   "+current.vertexCount()+" vertex   •   "+current.triangleCount()+" triangle\nModel boyutları (dosya birimi):\n"+dim+"\nMod: "+(pointsOnly?"NOKTA BULUTU":"MESH / GEOMETRİ"));}
 void setView(float x,float y,String n){renderer.rx=x;renderer.ry=y;viewName.setText("Görünüş: "+n);}
 void toggleMode(){if(current==null)return;pointsOnly=!pointsOnly;ViewerActivity.Model m=new ViewerActivity.Model(current.v,pointsOnly?null:originalIdx);renderer.setModel(m);updateInfo();}
 String name(Uri u){String n="model";try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null){int ix=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&ix>=0)n=c.getString(ix);}}catch(Exception ignored){}return n;}
 static String ext(String n){int i=n.lastIndexOf('.');return i<0?"":n.substring(i+1);}
 @Override protected void onPause(){super.onPause();if(gl!=null)gl.onPause();}@Override protected void onResume(){super.onResume();if(gl!=null)gl.onResume();}

 static class Bounds{float minx=Float.MAX_VALUE,miny=Float.MAX_VALUE,minz=Float.MAX_VALUE,maxx=-Float.MAX_VALUE,maxy=-Float.MAX_VALUE,maxz=-Float.MAX_VALUE;void add(float x,float y,float z){if(!Float.isFinite(x)||!Float.isFinite(y)||!Float.isFinite(z))return;minx=Math.min(minx,x);miny=Math.min(miny,y);minz=Math.min(minz,z);maxx=Math.max(maxx,x);maxy=Math.max(maxy,y);maxz=Math.max(maxz,z);}boolean valid(){return minx!=Float.MAX_VALUE;}float dx(){return maxx-minx;}float dy(){return maxy-miny;}float dz(){return maxz-minz;}}
 static class BoundsReader{
  static Bounds read(Context c,Uri u,String name)throws Exception{byte[]d=readAll(c.getContentResolver().openInputStream(u),60*1024*1024);String e=ext(name).toLowerCase(Locale.US);if(e.equals("glb"))return glb(d);if(e.equals("stl"))return stl(d);String s=new String(d,StandardCharsets.UTF_8);if(e.equals("obj"))return obj(s);if(e.equals("ply"))return ply(s);if(e.equals("xyz")||e.equals("pts"))return xyz(s);if(e.equals("step")||e.equals("stp"))return step(s);if(e.equals("igs")||e.equals("iges"))return iges(s);return generic(s);}
  static byte[] readAll(InputStream in,int max)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n,t=0;while((n=in.read(b))>0){t+=n;if(t>max)throw new IOException("Dosya çok büyük (>60 MB)");o.write(b,0,n);}in.close();return o.toByteArray();}
  static float f(String s){return Float.parseFloat(s.replace("D","E").replace("d","e"));}
  static Bounds obj(String s){Bounds b=new Bounds();for(String l:s.split("\\r?\\n")){l=l.trim();if(l.startsWith("v ")){String[]p=l.split("\\s+");if(p.length>=4)try{b.add(f(p[1]),f(p[2]),f(p[3]));}catch(Exception ignored){}}}return b;}
  static Bounds xyz(String s){Bounds b=new Bounds();for(String l:s.split("\\r?\\n")){String[]p=l.trim().split("[ ,;\\t]+");if(p.length>=3)try{b.add(f(p[0]),f(p[1]),f(p[2]));}catch(Exception ignored){}}return b;}
  static Bounds ply(String s){int h=s.indexOf("end_header");return h<0?xyz(s):xyz(s.substring(Math.min(s.length(),s.indexOf('\n',h)+1)));}
  static Bounds step(String s){Bounds b=new Bounds();Matcher m=Pattern.compile("CARTESIAN_POINT\\s*\\([^,]*,\\s*\\(([-+0-9.eEdD]+),\\s*([-+0-9.eEdD]+),\\s*([-+0-9.eEdD]+)\\)\\)",Pattern.CASE_INSENSITIVE).matcher(s);while(m.find())try{b.add(f(m.group(1)),f(m.group(2)),f(m.group(3)));}catch(Exception ignored){}return b;}
  static Bounds iges(String s){Bounds b=new Bounds();Matcher m=Pattern.compile("116,\\s*([-+0-9.eEdD]+),\\s*([-+0-9.eEdD]+),\\s*([-+0-9.eEdD]+)").matcher(s);while(m.find())try{b.add(f(m.group(1)),f(m.group(2)),f(m.group(3)));}catch(Exception ignored){}return b;}
  static Bounds generic(String s){Bounds b=new Bounds();Matcher m=Pattern.compile("([-+]?[0-9]*\\.?[0-9]+(?:[eEdD][-+]?\\d+)?)\\s*[,; ]+\\s*([-+]?[0-9]*\\.?[0-9]+(?:[eEdD][-+]?\\d+)?)\\s*[,; ]+\\s*([-+]?[0-9]*\\.?[0-9]+(?:[eEdD][-+]?\\d+)?)").matcher(s);int n=0;while(m.find()&&n++<500000)try{b.add(f(m.group(1)),f(m.group(2)),f(m.group(3)));}catch(Exception ignored){}return b;}
  static Bounds stl(byte[]d){Bounds out=new Bounds();if(d.length>=84){ByteBuffer b=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);b.position(80);long n=Integer.toUnsignedLong(b.getInt());if(84+n*50L==d.length){for(int i=0;i<n;i++){b.position(b.position()+12);for(int k=0;k<3;k++)out.add(b.getFloat(),b.getFloat(),b.getFloat());b.position(b.position()+2);}return out;}}String s=new String(d,StandardCharsets.UTF_8);Matcher m=Pattern.compile("vertex\\s+([-+0-9.eE]+)\\s+([-+0-9.eE]+)\\s+([-+0-9.eE]+)").matcher(s);while(m.find())out.add(f(m.group(1)),f(m.group(2)),f(m.group(3)));return out;}
  static Bounds glb(byte[]d)throws Exception{Bounds out=new Bounds();if(d.length<20)return out;ByteBuffer b=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);if(b.getInt()!=0x46546c67)return out;b.getInt();b.getInt();int jl=b.getInt();b.getInt();byte[]j=new byte[jl];b.get(j);String s=new String(j,StandardCharsets.UTF_8);Matcher mi=Pattern.compile("\\\"min\\\"\\s*:\\s*\\[\\s*([-+0-9.eE]+)\\s*,\\s*([-+0-9.eE]+)\\s*,\\s*([-+0-9.eE]+)\\s*\\]").matcher(s);Matcher ma=Pattern.compile("\\\"max\\\"\\s*:\\s*\\[\\s*([-+0-9.eE]+)\\s*,\\s*([-+0-9.eE]+)\\s*,\\s*([-+0-9.eE]+)\\s*\\]").matcher(s);if(mi.find()&&ma.find()){out.add(f(mi.group(1)),f(mi.group(2)),f(mi.group(3)));out.add(f(ma.group(1)),f(ma.group(2)),f(ma.group(3)));}return out;}
 }
}
