package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;

public class HomeActivity extends Activity{
 private TextView txt(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(22,16,22,16);return v;}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(18);b.setMinHeight(72);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(12,13,16));ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,32,24,32);r.setBackgroundColor(Color.rgb(12,13,16));sv.addView(r);TextView t=txt("MG 3D STUDIO PRO",30);t.setGravity(Gravity.CENTER);r.addView(t);TextView s=txt("Yönlendirilmiş fotoğraf + akıllı video görünüş sınıflandırma → 3D CAD surface",15);s.setTextColor(Color.LTGRAY);s.setGravity(Gravity.CENTER);r.addView(s);Space sp=new Space(this);r.addView(sp,new LinearLayout.LayoutParams(1,28));Button ortho=btn("📐 ORTHO CAD v2.8 • 6 YÖN + DİĞER FOTO + VİDEO");ortho.setOnClickListener(v->startActivity(new Intent(this,OrthographicCadActivityV26.class)));r.addView(ortho);Button scan=btn("🎥 VIDEO 3D v2.9 • OTOMATİK YÖN SINIFLANDIRMA • ÖNERİLEN");scan.setOnClickListener(v->startActivity(new Intent(this,RobustPoseSurfaceActivityV29.class)));r.addView(scan);Button safe=btn("🛡 KARARLI SİLUET SURFACE");safe.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));r.addView(safe);Button view=btn("🧊 CAD DOSYA AÇ / PRO VIEWER");view.setOnClickListener(v->startActivity(new Intent(this,CadSurfaceActivity.class)));r.addView(view);TextView f=txt("v2.9 video motoru: bulanık/bozuk ve sınır taşan kareleri eler; göreli kamera pozunu çözer; kareleri ÖN/SAĞ/ARKA/SOL/ÜST/ALT yönlerine sınıflandırır; her yönden en güvenilir kareyi seçer. Poz sınıflaması zayıfsa tüm kareleri rastgele birleştirmek yerine kararlı dört-yön orbit yedeğine geçer. Böylece yan saçaklar ve yanlış birleşmeler azaltılır. Sonuç OBJ olarak kaydedilir ve CAD Viewer otomatik açılır.",14);f.setTextColor(Color.LTGRAY);r.addView(f);setContentView(sv);}
}
