package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.graphics.*;import android.net.*;import android.provider.*;import android.view.*;import android.widget.*;import java.util.*;

public class HomeActivity extends Activity{
 private TextView txt(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(22,16,22,16);return v;}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(18);b.setMinHeight(72);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(12,13,16));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,32,24,32);r.setBackgroundColor(Color.rgb(12,13,16));TextView t=txt("MG 3D STUDIO PRO",30);t.setGravity(Gravity.CENTER);r.addView(t);TextView s=txt("Fotoğraftan mühendislik görünüşü → 3D CAD surface → mobil CAD viewer",15);s.setTextColor(Color.LTGRAY);s.setGravity(Gravity.CENTER);r.addView(s);Space sp=new Space(this);r.addView(sp,new LinearLayout.LayoutParams(1,28));Button ortho=btn("📐 ORTHO CAD v2.6 • ÖN + YAN + ÜST • ÖNERİLEN");ortho.setOnClickListener(v->startActivity(new Intent(this,OrthographicCadActivityV26.class)));r.addView(ortho);Button scan=btn("🎥 ROBUST v2.5.2 • ÇOKLU VİDEO/FOTO");scan.setOnClickListener(v->startActivity(new Intent(this,RobustPoseSurfaceActivityV251.class)));r.addView(scan);Button safe=btn("🛡 KARARLI SİLUET SURFACE");safe.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));r.addView(safe);Button view=btn("🧊 CAD DOSYA AÇ / PRO VIEWER");view.setOnClickListener(v->startActivity(new Intent(this,CadSurfaceActivity.class)));r.addView(view);TextView f=txt("v2.6: Ana geometri rastgele açılardan değil, kullanıcı tarafından etiketlenmiş ÖN + YAN + ÜST mühendislik görünüşlerinden kurulur. Ön görünüş genişlik/yüksekliği, yan görünüş derinlik/yüksekliği, üst görünüş genişlik/derinliği kilitler. Izgara/delik gibi iç detaylar ana hacmi küp/kaya gibi bozmasın diye dış kontur envelope esas alınır. Sonuç OBJ olarak kaydedilir ve CAD Viewer otomatik açılır.",14);f.setTextColor(Color.LTGRAY);r.addView(f);setContentView(r);}
}
