package com.muhammetgecgil.mg3dscanner;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.*; import android.media.MediaMetadataRetriever; import android.net.Uri; import android.provider.MediaStore; import android.view.*; import android.widget.*; import java.io.*; import java.util.*;

public class MainActivity extends Activity {
 private static final int REQ_IMAGES=10,REQ_VIDEO=11; private final ArrayList<Bitmap> frames=new ArrayList<>(); private TextView status,quality;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(16,17,20));buildUi();}
 private TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sp);v.setPadding(18,12,18,12);return v;}
 private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setMinHeight(56);return b;}
 private void buildUi(){ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,24,20,30);root.setBackgroundColor(Color.rgb(16,17,20));sc.addView(root);TextView t=text("MG 3D SCANNER",28);t.setGravity(Gravity.CENTER);root.addView(t);TextView sub=text("Fotoğraf + video fotogrametri • cihaz üzerinde",14);sub.setGravity(Gravity.CENTER);sub.setTextColor(Color.LTGRAY);root.addView(sub);Button p=button("📷 Fotoğrafları seç");p.setOnClickListener(v->pickImages());root.addView(p);Button vid=button("🎥 Video seç / keyframe çıkar");vid.setOnClickListener(v->pickVideo());root.addView(vid);Button clr=button("🗑 Çekimi temizle");clr.setOnClickListener(v->{frames.clear();refresh();});root.addView(clr);status=text("Hazır. Fotoğraf veya video ekle.",16);status.setBackgroundColor(Color.rgb(35,37,43));root.addView(status);quality=text("Kalite: veri bekleniyor",14);quality.setTextColor(Color.LTGRAY);root.addView(quality);Button build=button("🧊 3D MODEL OLUŞTUR (DEVAM ET)");build.setOnClickListener(v->reconstruct());root.addView(build);TextView info=text("Az fotoğraf = düşük kalite, çok ve farklı açılı fotoğraf = daha yüksek kalite. Eşleşme zayıf olsa bile uygulama elindeki tüm görüntülerden mümkün olan en iyi 3B sonucu üretmeyi dener.",13);info.setTextColor(Color.LTGRAY);root.addView(info);setContentView(sc);}
 private void updateStatus(String s){runOnUiThread(()->status.setText(s));}
 private void refresh(){runOnUiThread(()->{int n=frames.size();status.setText(n+" kare hazır. Model oluşturma engellenmeyecek.");String q=n<4?"ÇOK DÜŞÜK":n<10?"DÜŞÜK":n<25?"ORTA":n<60?"İYİ":"ÇOK İYİ";quality.setText("Tahmini kalite: "+q+" • "+n+" görüntü");});}
 private void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_IMAGES);}
 private void pickVideo(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("video/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_VIDEO);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;new Thread(()->{try{if(r==REQ_IMAGES){if(d.getClipData()!=null)for(int k=0;k<d.getClipData().getItemCount();k++)addBitmap(d.getClipData().getItemAt(k).getUri());else if(d.getData()!=null)addBitmap(d.getData());}else if(r==REQ_VIDEO&&d.getData()!=null)extractVideoFrames(d.getData());refresh();}catch(Exception e){updateStatus("Girdi okunamadı: "+e.getMessage());}}).start();}
 private void addBitmap(Uri u)throws Exception{Bitmap b=MediaStore.Images.Media.getBitmap(getContentResolver(),u);if(b!=null)frames.add(scale(b,960));}
 private Bitmap scale(Bitmap b,int max){int w=b.getWidth(),h=b.getHeight();if(Math.max(w,h)<=max)return b;float f=max/(float)Math.max(w,h);return Bitmap.createScaledBitmap(b,(int)(w*f),(int)(h*f),true);}
 private void extractVideoFrames(Uri u)throws Exception{MediaMetadataRetriever m=new MediaMetadataRetriever();m.setDataSource(this,u);long dur=Long.parseLong(m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION))*1000L;int n=24;for(int k=0;k<n;k++){Bitmap b=m.getFrameAtTime((long)((k+.5)*dur/n),MediaMetadataRetriever.OPTION_CLOSEST);if(b!=null)frames.add(scale(b,960));}m.release();}
 private void reconstruct(){if(frames.isEmpty()){updateStatus("Önce en az 1 fotoğraf veya video ekle.");return;}new Thread(()->{try{updateStatus("Görüntüler analiz ediliyor… Elimizdeki veriyle devam ediliyor.");ArrayList<float[]> all=new ArrayList<>();int pairs=0,goodPairs=0;for(int i=0;i<frames.size()-1;i++){Bitmap a=scale(frames.get(i),640),b=scale(frames.get(i+1),640);ArrayList<float[]> p=StereoReconstructor.reconstruct(a,b);pairs++;if(p.size()>=12)goodPairs++;float ang=(float)(2*Math.PI*i/Math.max(1,frames.size()-1));for(float[]x:p){float X=(float)(x[0]*Math.cos(ang)+x[2]*Math.sin(ang));float Z=(float)(-x[0]*Math.sin(ang)+x[2]*Math.cos(ang));all.add(new float[]{X,x[1],Z});}if(all.size()>250000)break;}
 if(all.isEmpty())all.addAll(fallbackCloud(frames.get(0)));else if(all.size()<80)all.addAll(fallbackCloud(frames.get(0)));
 updateStatus("3B veri üretiliyor… "+all.size()+" nokta • kullanılabilir çift "+goodPairs+"/"+pairs);Uri uri=saveObj(all);String q=all.size()<200?"ÇOK DÜŞÜK":all.size()<1000?"DÜŞÜK":all.size()<5000?"ORTA":"İYİ";updateStatus("TAMAMLANDI • "+q+" KALİTE\n"+all.size()+" 3B nokta üretildi.\nEşleşme zayıf olsa da işlem durdurulmadı.\nOBJ: Downloads/MG3DScanner\n"+uri);}catch(Exception e){updateStatus("Model oluşturma hatası: "+e.getClass().getSimpleName()+" • "+e.getMessage());}}).start();}
 private ArrayList<float[]> fallbackCloud(Bitmap src){Bitmap b=scale(src,320);ArrayList<float[]> out=new ArrayList<>();for(int y=4;y<b.getHeight()-4;y+=5)for(int x=4;x<b.getWidth()-4;x+=5){int c=gray(b.getPixel(x,y));int gx=Math.abs(gray(b.getPixel(x+2,y))-gray(b.getPixel(x-2,y)));int gy=Math.abs(gray(b.getPixel(x,y+2))-gray(b.getPixel(x,y-2)));if(gx+gy<35)continue;float X=(x-b.getWidth()/2f)/b.getWidth()*2f,Y=-(y-b.getHeight()/2f)/b.getWidth()*2f,Z=1.0f+(255-c)/255f*.12f;out.add(new float[]{X,Y,Z});}return out;}
 private int gray(int c){return(Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;}
 private Uri saveObj(ArrayList<float[]>pts)throws Exception{ContentValues cv=new ContentValues();cv.put(MediaStore.Downloads.DISPLAY_NAME,"MG3D_"+System.currentTimeMillis()+".obj");cv.put(MediaStore.Downloads.MIME_TYPE,"text/plain");cv.put(MediaStore.Downloads.RELATIVE_PATH,"Download/MG3DScanner");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,cv);if(u==null)throw new IOException("Dosya oluşturulamadı");try(Writer w=new BufferedWriter(new OutputStreamWriter(getContentResolver().openOutputStream(u)))){w.write("# MG 3D Scanner adaptive point cloud OBJ\n");for(float[]p:pts)w.write(String.format(Locale.US,"v %.6f %.6f %.6f\n",p[0],p[1],p[2]));}return u;}
 static class StereoReconstructor{static ArrayList<float[]> reconstruct(Bitmap A,Bitmap B){int w=Math.min(A.getWidth(),B.getWidth()),h=Math.min(A.getHeight(),B.getHeight());A=Bitmap.createScaledBitmap(A,w,h,true);B=Bitmap.createScaledBitmap(B,w,h,true);int step=7,rad=3,search=Math.min(90,w/4);ArrayList<float[]>out=new ArrayList<>();for(int y=rad+2;y<h-rad-2;y+=step)for(int x=rad+search+2;x<w-rad-2;x+=step){int gx=Math.abs(g(A,x+1,y)-g(A,x-1,y))+Math.abs(g(A,x,y+1)-g(A,x,y-1));if(gx<28)continue;int bestX=-1;long best=Long.MAX_VALUE,second=Long.MAX_VALUE;for(int xb=Math.max(rad+1,x-search);xb<=Math.min(w-rad-2,x+20);xb+=2){long e=0;for(int yy=-rad;yy<=rad;yy++)for(int xx=-rad;xx<=rad;xx++)e+=Math.abs(g(A,x+xx,y+yy)-g(B,xb+xx,y+yy));if(e<best){second=best;best=e;bestX=xb;}else if(e<second)second=e;}if(bestX<0||best>3200||best*100L>second*98L)continue;float disp=x-bestX;if(Math.abs(disp)<1)continue;float z=120f/Math.abs(disp),X=(x-w/2f)*z/w,Y=-(y-h/2f)*z/w;if(z>.3f&&z<100f)out.add(new float[]{X,Y,z});}return out;}static int g(Bitmap b,int x,int y){int c=b.getPixel(x,y);return(Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;}}
}
