package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.media.MediaMetadataRetriever;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity{
 static final int REQ_IMAGES=10,REQ_VIDEO=11;final ArrayList<Bitmap>frames=new ArrayList<>();TextView status,quality;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(13,15,18));build();}
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(18,12,18,12);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setMinHeight(58);return b;}
 void build(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(18,22,18,30);r.setBackgroundColor(Color.rgb(13,15,18));sc.addView(r);TextView t=tv("MG 3D VISUAL HULL SCANNER",26);t.setGravity(Gravity.CENTER);r.addView(t);TextView sub=tv("Fotoğraf/video → nesne silueti → 3B hacim → continuous surface",14);sub.setGravity(Gravity.CENTER);sub.setTextColor(Color.LTGRAY);r.addView(sub);Button p=btn("📷 FOTOĞRAFLARI SEÇ");p.setOnClickListener(v->pickImages());r.addView(p);Button v=btn("🎥 VİDEO SEÇ / KEYFRAME");v.setOnClickListener(x->pickVideo());r.addView(v);Button c=btn("🗑 ÇEKİMİ TEMİZLE");c.setOnClickListener(x->{frames.clear();refresh();});r.addView(c);status=tv("Hazır. Nesnenin çevresinden görüntüler ekle.",16);status.setBackgroundColor(Color.rgb(34,37,43));r.addView(status);quality=tv("Surface kalitesi: veri bekleniyor",14);quality.setTextColor(Color.LTGRAY);r.addView(quality);Button make=btn("🧊 GERÇEK SİLUET SURFACE OLUŞTUR");make.setOnClickListener(x->reconstruct());r.addView(make);TextView info=tv("Bu sürüm uzak 3B noktaları merkeze bağlamaz. Her görüntüde arka plan ayrılır, nesnenin en büyük bağlı silueti bulunur, siluetler 3B voxel hacminde birleştirilir ve yalnız komşu hücrelerin ortak sınırlarından kapalı surface oluşturulur. Yetersiz veri durumunda rastgele diken yerine en güçlü siluet güvenli biçimde extrude edilir.",13);info.setTextColor(Color.LTGRAY);r.addView(info);setContentView(sc);}
 void refresh(){runOnUiThread(()->{int n=frames.size();status.setText(n+" görüntü hazır. Siluet tabanlı surface oluşturulabilir.");String q=n<3?"DÜŞÜK":n<6?"ORTA":n<12?"İYİ":"ÇOK İYİ";quality.setText("Tahmini kapsam: "+q+" • "+n+" görüntü");});}
 void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_IMAGES);}
 void pickVideo(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("video/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_VIDEO);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;new Thread(()->{try{if(r==REQ_IMAGES){if(d.getClipData()!=null)for(int k=0;k<d.getClipData().getItemCount();k++)add(d.getClipData().getItemAt(k).getUri());else if(d.getData()!=null)add(d.getData());}else if(r==REQ_VIDEO&&d.getData()!=null)video(d.getData());refresh();}catch(Exception e){set("Girdi okunamadı: "+e.getMessage());}}).start();}
 void add(Uri u)throws Exception{Bitmap b=MediaStore.Images.Media.getBitmap(getContentResolver(),u);if(b!=null)frames.add(scale(b,960));}
 Bitmap scale(Bitmap b,int max){int w=b.getWidth(),h=b.getHeight();if(Math.max(w,h)<=max)return b;float s=max/(float)Math.max(w,h);return Bitmap.createScaledBitmap(b,Math.max(1,(int)(w*s)),Math.max(1,(int)(h*s)),true);}
 void video(Uri u)throws Exception{MediaMetadataRetriever m=new MediaMetadataRetriever();m.setDataSource(this,u);long dur=Long.parseLong(m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION))*1000L;Bitmap prev=null;for(int k=0;k<60;k++){Bitmap b=m.getFrameAtTime((long)((k+.5)*dur/60),MediaMetadataRetriever.OPTION_CLOSEST);if(b==null)continue;b=scale(b,720);float sharp=sharpness(b),chg=prev==null?1:change(prev,b);if(sharp>16&&(prev==null||chg>.04f||frames.size()<6)){frames.add(b);prev=b;}if(frames.size()>=32)break;}m.release();}
 float sharpness(Bitmap b){Bitmap s=scale(b,150);double sum=0,sum2=0;int n=0;for(int y=2;y<s.getHeight()-2;y+=3)for(int x=2;x<s.getWidth()-2;x+=3){int v=Math.abs(gray(s.getPixel(x+1,y))-gray(s.getPixel(x-1,y)))+Math.abs(gray(s.getPixel(x,y+1))-gray(s.getPixel(x,y-1)));sum+=v;sum2+=v*v;n++;}if(n==0)return 0;double m=sum/n;return(float)Math.sqrt(Math.max(0,sum2/n-m*m));}
 float change(Bitmap a,Bitmap b){a=scale(a,96);b=scale(b,96);int w=Math.min(a.getWidth(),b.getWidth()),h=Math.min(a.getHeight(),b.getHeight());long s=0;int n=0;for(int y=0;y<h;y+=4)for(int x=0;x<w;x+=4){s+=Math.abs(gray(a.getPixel(x,y))-gray(b.getPixel(x,y)));n++;}return n==0?0:s/(255f*n);}
 int gray(int c){return(Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;}
 void set(String s){runOnUiThread(()->status.setText(s));}

 void reconstruct(){if(frames.isEmpty()){status.setText("Önce fotoğraf veya video ekle.");return;}new Thread(()->{try{set("1/4 • Nesne siluetleri çıkarılıyor…");ArrayList<Mask>masks=new ArrayList<>();for(Bitmap b:frames){Mask m=Mask.from(b);if(m!=null&&m.area>150)masks.add(m);}if(masks.isEmpty())throw new IOException("Nesne arka plandan ayrılamadı. Nesneyi zıt renkli sade fonda çek.");set("2/4 • "+masks.size()+" kullanılabilir siluet • 3B visual hull hesaplanıyor…");Mesh mesh=VisualHull.build(masks);set("3/4 • Surface: "+mesh.vertexCount()+" vertex • "+mesh.triangleCount()+" triangle • dosyalar yazılıyor…");String base="MG3D_SURFACE_"+System.currentTimeMillis();saveAll(base,mesh);set("TAMAMLANDI • SİLUET TABANLI CONTINUOUS SURFACE\n"+mesh.vertexCount()+" vertex • "+mesh.triangleCount()+" bağlı triangle\nKullanılan görüntü: "+masks.size()+"/"+frames.size()+"\nOBJ • PLY • STL • GLB • STEP • IGES\nDownload/MG3DScanner/\nViewer otomatik OBJ surface'i açacaktır.");}catch(Exception e){set("Surface oluşturma hatası: "+e.getClass().getSimpleName()+" • "+e.getMessage());}}).start();}

 static class Mask{int w,h,minx,miny,maxx,maxy,area;boolean[]p;Mask(int W,int H){w=W;h=H;p=new boolean[w*h];}
  boolean at(int x,int y){return x>=0&&y>=0&&x<w&&y<h&&p[y*w+x];}
  boolean sample(float nx,float ny){float size=Math.max(maxx-minx+1,maxy-miny+1);float cx=(minx+maxx)*.5f,cy=(miny+maxy)*.5f;int x=Math.round(cx+nx*size*.5f),y=Math.round(cy-ny*size*.5f);return at(x,y);}
  static Mask from(Bitmap src){Bitmap b=resize(src,180);int w=b.getWidth(),h=b.getHeight(),band=Math.max(3,Math.min(w,h)/20);double sr=0,sg=0,sb=0,n=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(x<band||y<band||x>=w-band||y>=h-band){int c=b.getPixel(x,y);sr+=Color.red(c);sg+=Color.green(c);sb+=Color.blue(c);n++;}float br=(float)(sr/n),bg=(float)(sg/n),bb=(float)(sb/n);double md=0,sd=0;int bn=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(x<band||y<band||x>=w-band||y>=h-band){int c=b.getPixel(x,y);double d=Math.sqrt(sq(Color.red(c)-br)+sq(Color.green(c)-bg)+sq(Color.blue(c)-bb));md+=d;sd+=d*d;bn++;}md/=bn;double st=Math.sqrt(Math.max(0,sd/bn-md*md));double th=Math.max(38,md+3.2*st);Mask raw=new Mask(w,h);for(int y=0;y<h;y++)for(int x=0;x<w;x++){int c=b.getPixel(x,y);double d=Math.sqrt(sq(Color.red(c)-br)+sq(Color.green(c)-bg)+sq(Color.blue(c)-bb));raw.p[y*w+x]=d>th;}raw.close();return raw.largest();}
  static double sq(double x){return x*x;}
  static Bitmap resize(Bitmap b,int max){int w=b.getWidth(),h=b.getHeight();float s=max/(float)Math.max(w,h);return Bitmap.createScaledBitmap(b,Math.max(2,(int)(w*s)),Math.max(2,(int)(h*s)),true);}
  void close(){for(int pass=0;pass<2;pass++){boolean[]q=p.clone();for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int c=0;for(int yy=-1;yy<=1;yy++)for(int xx=-1;xx<=1;xx++)if(p[(y+yy)*w+x+xx])c++;if(c>=5)q[y*w+x]=true;}p=q;}for(int pass=0;pass<1;pass++){boolean[]q=p.clone();for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int c=0;for(int yy=-1;yy<=1;yy++)for(int xx=-1;xx<=1;xx++)if(p[(y+yy)*w+x+xx])c++;if(c<=2)q[y*w+x]=false;}p=q;}}
  Mask largest(){boolean[]vis=new boolean[p.length];int[]qx=new int[p.length],qy=new int[p.length];ArrayList<Integer>best=new ArrayList<>();int[]dx={1,-1,0,0},dy={0,0,1,-1};for(int y=0;y<h;y++)for(int x=0;x<w;x++){int id=y*w+x;if(!p[id]||vis[id])continue;ArrayList<Integer>cur=new ArrayList<>();int head=0,tail=0;qx[tail]=x;qy[tail++]=y;vis[id]=true;while(head<tail){int xx=qx[head],yy=qy[head++];cur.add(yy*w+xx);for(int k=0;k<4;k++){int nx=xx+dx[k],ny=yy+dy[k];if(nx<0||ny<0||nx>=w||ny>=h)continue;int ni=ny*w+nx;if(p[ni]&&!vis[ni]){vis[ni]=true;qx[tail]=nx;qy[tail++]=ny;}}}if(cur.size()>best.size())best=cur;}if(best.size()<80)return null;Mask m=new Mask(w,h);m.minx=w;m.miny=h;m.maxx=m.maxy=0;for(int id:best){m.p[id]=true;int x=id%w,y=id/w;m.minx=Math.min(m.minx,x);m.maxx=Math.max(m.maxx,x);m.miny=Math.min(m.miny,y);m.maxy=Math.max(m.maxy,y);}m.area=best.size();return m;}}

 static class Mesh{float[]v;int[]idx;Mesh(float[]a,int[]i){v=a;idx=i;}int vertexCount(){return v.length/3;}int triangleCount(){return idx.length/3;}}
 static class VisualHull{
  static Mesh build(ArrayList<Mask>ms){int R=44,n=ms.size();boolean[][][]occ=new boolean[R][R][R];int need=Math.max(1,(int)Math.ceil(n*.58));int count=carve(ms,occ,R,need);if(count<R*R) {for(int x=0;x<R;x++)for(int y=0;y<R;y++)Arrays.fill(occ[x][y],false);need=Math.max(1,(int)Math.ceil(n*.45));count=carve(ms,occ,R,need);}if(count<R*R/2)return extrude(best(ms),R);keepLargest(occ,R);Mesh m=surface(occ,R);return smooth(m,2,.18f);}
  static int carve(ArrayList<Mask>ms,boolean[][][]o,int R,int need){int cnt=0,n=ms.size();for(int ix=0;ix<R;ix++){float x=-1+2f*(ix+.5f)/R;for(int iy=0;iy<R;iy++){float y=-1+2f*(iy+.5f)/R;for(int iz=0;iz<R;iz++){float z=-1+2f*(iz+.5f)/R;int inside=0;for(int k=0;k<n;k++){double a=2*Math.PI*k/n;float u=(float)(x*Math.cos(a)-z*Math.sin(a));if(ms.get(k).sample(u,y))inside++;}if(inside>=need){o[ix][iy][iz]=true;cnt++;}}}}return cnt;}
  static Mask best(ArrayList<Mask>m){Mask b=m.get(0);for(Mask x:m)if(x.area>b.area)b=x;return b;}
  static Mesh extrude(Mask m,int R){boolean[][][]o=new boolean[R][R][R];for(int ix=0;ix<R;ix++){float x=-1+2f*(ix+.5f)/R;for(int iy=0;iy<R;iy++){float y=-1+2f*(iy+.5f)/R;if(!m.sample(x,y))continue;for(int iz=0;iz<R;iz++){float z=-1+2f*(iz+.5f)/R;if(Math.abs(z)<.48f)o[ix][iy][iz]=true;}}}return smooth(surface(o,R),3,.20f);}
  static void keepLargest(boolean[][][]o,int R){boolean[][][]vis=new boolean[R][R][R];int[][]dirs={{1,0,0},{-1,0,0},{0,1,0},{0,-1,0},{0,0,1},{0,0,-1}};ArrayList<int[]>best=new ArrayList<>();int max=R*R*R;int[]qx=new int[max],qy=new int[max],qz=new int[max];for(int x=0;x<R;x++)for(int y=0;y<R;y++)for(int z=0;z<R;z++){if(!o[x][y][z]||vis[x][y][z])continue;ArrayList<int[]>cur=new ArrayList<>();int h=0,t=0;qx[t]=x;qy[t]=y;qz[t++]=z;vis[x][y][z]=true;while(h<t){int xx=qx[h],yy=qy[h],zz=qz[h++];cur.add(new int[]{xx,yy,zz});for(int[]d:dirs){int a=xx+d[0],b=yy+d[1],c=zz+d[2];if(a>=0&&b>=0&&c>=0&&a<R&&b<R&&c<R&&o[a][b][c]&&!vis[a][b][c]){vis[a][b][c]=true;qx[t]=a;qy[t]=b;qz[t++]=c;}}}if(cur.size()>best.size())best=cur;}for(int x=0;x<R;x++)for(int y=0;y<R;y++)Arrays.fill(o[x][y],false);for(int[]q:best)o[q[0]][q[1]][q[2]]=true;}
  static Mesh surface(boolean[][][]o,int R){ArrayList<Float>v=new ArrayList<>();ArrayList<Integer>id=new ArrayList<>();HashMap<Long,Integer>map=new HashMap<>();int[][]d={{-1,0,0},{1,0,0},{0,-1,0},{0,1,0},{0,0,-1},{0,0,1}};int[][][]corn={{{0,0,0},{0,0,1},{0,1,1},{0,1,0}},{{1,0,0},{1,1,0},{1,1,1},{1,0,1}},{{0,0,0},{1,0,0},{1,0,1},{0,0,1}},{{0,1,0},{0,1,1},{1,1,1},{1,1,0}},{{0,0,0},{0,1,0},{1,1,0},{1,0,0}},{{0,0,1},{1,0,1},{1,1,1},{0,1,1}}};for(int x=0;x<R;x++)for(int y=0;y<R;y++)for(int z=0;z<R;z++)if(o[x][y][z])for(int f=0;f<6;f++){int nx=x+d[f][0],ny=y+d[f][1],nz=z+d[f][2];if(nx>=0&&ny>=0&&nz>=0&&nx<R&&ny<R&&nz<R&&o[nx][ny][nz])continue;int[]q=new int[4];for(int k=0;k<4;k++)q[k]=vertex(map,v,x+corn[f][k][0],y+corn[f][k][1],z+corn[f][k][2],R);id.add(q[0]);id.add(q[1]);id.add(q[2]);id.add(q[0]);id.add(q[2]);id.add(q[3]);}float[]vv=new float[v.size()];for(int i=0;i<vv.length;i++)vv[i]=v.get(i);int[]ii=new int[id.size()];for(int i=0;i<ii.length;i++)ii[i]=id.get(i);return new Mesh(vv,ii);}
  static int vertex(HashMap<Long,Integer>map,ArrayList<Float>v,int x,int y,int z,int R){long key=((long)x<<40)|((long)y<<20)|z;Integer old=map.get(key);if(old!=null)return old;int i=v.size()/3;v.add(-1+2f*x/R);v.add(-1+2f*y/R);v.add(-1+2f*z/R);map.put(key,i);return i;}
  static Mesh smooth(Mesh m,int passes,float a){if(m.vertexCount()==0)return m;ArrayList<HashSet<Integer>>nb=new ArrayList<>();for(int i=0;i<m.vertexCount();i++)nb.add(new HashSet<>());for(int i=0;i<m.idx.length;i+=3){int A=m.idx[i],B=m.idx[i+1],C=m.idx[i+2];nb.get(A).add(B);nb.get(A).add(C);nb.get(B).add(A);nb.get(B).add(C);nb.get(C).add(A);nb.get(C).add(B);}float[]v=m.v.clone();for(int p=0;p<passes;p++){float[]n=v.clone();for(int i=0;i<nb.size();i++){if(nb.get(i).isEmpty())continue;float sx=0,sy=0,sz=0;for(int j:nb.get(i)){sx+=v[j*3];sy+=v[j*3+1];sz+=v[j*3+2];}float inv=1f/nb.get(i).size();n[i*3]=v[i*3]*(1-a)+sx*inv*a;n[i*3+1]=v[i*3+1]*(1-a)+sy*inv*a;n[i*3+2]=v[i*3+2]*(1-a)+sz*inv*a;}v=n;}return new Mesh(v,m.idx);}}

 OutputStream out(String name,String mime)throws Exception{ContentValues cv=new ContentValues();cv.put(MediaStore.Downloads.DISPLAY_NAME,name);cv.put(MediaStore.Downloads.MIME_TYPE,mime);cv.put(MediaStore.Downloads.RELATIVE_PATH,"Download/MG3DScanner");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,cv);if(u==null)throw new IOException("Dosya oluşturulamadı");return getContentResolver().openOutputStream(u);}
 void saveAll(String b,Mesh m)throws Exception{savePly(b+".ply",m);saveStl(b+".stl",m);saveGlb(b+".glb",m);saveStep(b+".step",m);saveIges(b+".igs",m);saveObj(b+".obj",m);}
 void saveObj(String n,Mesh m)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"model/obj")))){w.write("# MG3D visual hull continuous surface\n");for(int i=0;i<m.v.length;i+=3)w.write(String.format(Locale.US,"v %.7f %.7f %.7f\n",m.v[i],m.v[i+1],m.v[i+2]));for(int i=0;i<m.idx.length;i+=3)w.write("f "+(m.idx[i]+1)+" "+(m.idx[i+1]+1)+" "+(m.idx[i+2]+1)+"\n");}}
 void savePly(String n,Mesh m)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"application/octet-stream")))){w.write("ply\nformat ascii 1.0\nelement vertex "+m.vertexCount()+"\nproperty float x\nproperty float y\nproperty float z\nelement face "+m.triangleCount()+"\nproperty list uchar int vertex_indices\nend_header\n");for(int i=0;i<m.v.length;i+=3)w.write(String.format(Locale.US,"%.7f %.7f %.7f\n",m.v[i],m.v[i+1],m.v[i+2]));for(int i=0;i<m.idx.length;i+=3)w.write("3 "+m.idx[i]+" "+m.idx[i+1]+" "+m.idx[i+2]+"\n");}}
 void saveStl(String n,Mesh m)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"model/stl")))){w.write("solid MG3D\n");for(int i=0;i<m.idx.length;i+=3){int a=m.idx[i]*3,b=m.idx[i+1]*3,c=m.idx[i+2]*3;float[]nn=normal(m.v,a,b,c);w.write(String.format(Locale.US,"facet normal %.6f %.6f %.6f\n outer loop\n",nn[0],nn[1],nn[2]));for(int q:new int[]{a,b,c})w.write(String.format(Locale.US,"  vertex %.7f %.7f %.7f\n",m.v[q],m.v[q+1],m.v[q+2]));w.write(" endloop\nendfacet\n");}w.write("endsolid MG3D\n");}}
 float[]normal(float[]v,int a,int b,int c){float ax=v[b]-v[a],ay=v[b+1]-v[a+1],az=v[b+2]-v[a+2],bx=v[c]-v[a],by=v[c+1]-v[a+1],bz=v[c+2]-v[a+2];float x=ay*bz-az*by,y=az*bx-ax*bz,z=ax*by-ay*bx,l=(float)Math.sqrt(x*x+y*y+z*z);if(l<1e-9)l=1;return new float[]{x/l,y/l,z/l};}
 void saveStep(String n,Mesh m)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"application/step")))){w.write("ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('MG3D VISUAL HULL SURFACE VERTICES'),'2;1');\nFILE_SCHEMA(('GEOMETRIC_CURVE_SET'));\nENDSEC;\nDATA;\n");int id=1;for(int i=0;i<m.v.length;i+=3)w.write(String.format(Locale.US,"#%d=CARTESIAN_POINT('',(%.7f,%.7f,%.7f));\n",id++,m.v[i],m.v[i+1],m.v[i+2]));w.write("ENDSEC;\nEND-ISO-10303-21;\n");}}
 void saveIges(String n,Mesh m)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"application/iges")))){w.write(String.format(Locale.US,"%-72sS      1\n","MG3D visual hull surface vertices"));int seq=1;for(int i=0;i<m.v.length;i+=3)w.write(String.format(Locale.US,"116,%.7f,%.7f,%.7f,0;%40sP%7d\n",m.v[i],m.v[i+1],m.v[i+2],"",seq++));}}
 void saveGlb(String n,Mesh m)throws Exception{int vb=m.v.length*4,ib=m.idx.length*4,binLen=align4(vb)+align4(ib);ByteBuffer bin=ByteBuffer.allocate(binLen).order(ByteOrder.LITTLE_ENDIAN);for(float x:m.v)bin.putFloat(x);while(bin.position()<align4(vb))bin.put((byte)0);int idxOff=bin.position();for(int x:m.idx)bin.putInt(x);while(bin.position()<binLen)bin.put((byte)0);float[]mm=minmax(m.v);String js=String.format(Locale.US,"{\"asset\":{\"version\":\"2.0\",\"generator\":\"MG3D Visual Hull\"},\"scene\":0,\"scenes\":[{\"nodes\":[0]}],\"nodes\":[{\"mesh\":0}],\"meshes\":[{\"primitives\":[{\"attributes\":{\"POSITION\":0},\"indices\":1,\"mode\":4}]}],\"buffers\":[{\"byteLength\":%d}],\"bufferViews\":[{\"buffer\":0,\"byteOffset\":0,\"byteLength\":%d,\"target\":34962},{\"buffer\":0,\"byteOffset\":%d,\"byteLength\":%d,\"target\":34963}],\"accessors\":[{\"bufferView\":0,\"componentType\":5126,\"count\":%d,\"type\":\"VEC3\",\"min\":[%.7f,%.7f,%.7f],\"max\":[%.7f,%.7f,%.7f]},{\"bufferView\":1,\"componentType\":5125,\"count\":%d,\"type\":\"SCALAR\"}]}",binLen,vb,idxOff,ib,m.vertexCount(),mm[0],mm[1],mm[2],mm[3],mm[4],mm[5],m.idx.length);byte[]jb=js.getBytes(StandardCharsets.UTF_8);int jp=(4-jb.length%4)%4,total=12+8+jb.length+jp+8+binLen;try(DataOutputStream o=new DataOutputStream(out(n,"model/gltf-binary"))){le(o,0x46546c67);le(o,2);le(o,total);le(o,jb.length+jp);le(o,0x4e4f534a);o.write(jb);for(int i=0;i<jp;i++)o.writeByte(0x20);le(o,binLen);le(o,0x004e4942);o.write(bin.array());}}
 int align4(int x){return(x+3)&~3;}void le(DataOutputStream o,int v)throws Exception{o.writeByte(v&255);o.writeByte((v>>8)&255);o.writeByte((v>>16)&255);o.writeByte((v>>24)&255);}float[]minmax(float[]v){float minx=Float.MAX_VALUE,miny=minx,minz=minx,maxx=-minx,maxy=-minx,maxz=-minx;for(int i=0;i<v.length;i+=3){minx=Math.min(minx,v[i]);miny=Math.min(miny,v[i+1]);minz=Math.min(minz,v[i+2]);maxx=Math.max(maxx,v[i]);maxy=Math.max(maxy,v[i+1]);maxz=Math.max(maxz,v[i+2]);}return new float[]{minx,miny,minz,maxx,maxy,maxz};}
}
