package com.muhammetgecgil.mg3dscanner;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.*; import android.media.MediaMetadataRetriever; import android.net.Uri; import android.provider.MediaStore; import android.view.*; import android.widget.*; import java.io.*; import java.nio.*; import java.nio.charset.StandardCharsets; import java.util.*;

public class MainActivity extends Activity {
 private static final int REQ_IMAGES=10,REQ_VIDEO=11; private final ArrayList<Bitmap> frames=new ArrayList<>(); private TextView status,quality;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(16,17,20));buildUi();}
 private TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sp);v.setPadding(18,12,18,12);return v;}
 private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setMinHeight(56);return b;}
 private void buildUi(){ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,24,20,30);root.setBackgroundColor(Color.rgb(16,17,20));sc.addView(root);TextView t=text("MG 3D SCANNER",28);t.setGravity(Gravity.CENTER);root.addView(t);TextView sub=text("Fotoğraf + video fotogrametri • çoklu 3D/CAD dışa aktarım",14);sub.setGravity(Gravity.CENTER);sub.setTextColor(Color.LTGRAY);root.addView(sub);Button p=button("📷 Fotoğrafları seç");p.setOnClickListener(v->pickImages());root.addView(p);Button vid=button("🎥 Video seç / keyframe çıkar");vid.setOnClickListener(v->pickVideo());root.addView(vid);Button clr=button("🗑 Çekimi temizle");clr.setOnClickListener(v->{frames.clear();refresh();});root.addView(clr);status=text("Hazır. Fotoğraf veya video ekle.",16);status.setBackgroundColor(Color.rgb(35,37,43));root.addView(status);quality=text("Kalite: veri bekleniyor",14);quality.setTextColor(Color.LTGRAY);root.addView(quality);Button build=button("🧊 3D MODEL OLUŞTUR + TÜM FORMATLAR");build.setOnClickListener(v->reconstruct());root.addView(build);TextView info=text("Çıktılar: OBJ, PLY, XYZ, STL, GLB, STEP/STP, IGES/IGS. STEP ve IGES mevcut 3B noktaları CAD değişim yapısında taşır; katı parametrik CAD'e dönüştürme sonraki aşamadır.",13);info.setTextColor(Color.LTGRAY);root.addView(info);setContentView(sc);}
 private void updateStatus(String s){runOnUiThread(()->status.setText(s));}
 private void refresh(){runOnUiThread(()->{int n=frames.size();status.setText(n+" kare hazır. Model oluşturma engellenmeyecek.");String q=n<4?"ÇOK DÜŞÜK":n<10?"DÜŞÜK":n<25?"ORTA":n<60?"İYİ":"ÇOK İYİ";quality.setText("Tahmini kalite: "+q+" • "+n+" görüntü");});}
 private void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_IMAGES);}
 private void pickVideo(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("video/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_VIDEO);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;new Thread(()->{try{if(r==REQ_IMAGES){if(d.getClipData()!=null)for(int k=0;k<d.getClipData().getItemCount();k++)addBitmap(d.getClipData().getItemAt(k).getUri());else if(d.getData()!=null)addBitmap(d.getData());}else if(r==REQ_VIDEO&&d.getData()!=null)extractVideoFrames(d.getData());refresh();}catch(Exception e){updateStatus("Girdi okunamadı: "+e.getMessage());}}).start();}
 private void addBitmap(Uri u)throws Exception{Bitmap b=MediaStore.Images.Media.getBitmap(getContentResolver(),u);if(b!=null)frames.add(scale(b,960));}
 private Bitmap scale(Bitmap b,int max){int w=b.getWidth(),h=b.getHeight();if(Math.max(w,h)<=max)return b;float f=max/(float)Math.max(w,h);return Bitmap.createScaledBitmap(b,(int)(w*f),(int)(h*f),true);}
 private void extractVideoFrames(Uri u)throws Exception{MediaMetadataRetriever m=new MediaMetadataRetriever();m.setDataSource(this,u);long dur=Long.parseLong(m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION))*1000L;int n=24;for(int k=0;k<n;k++){Bitmap b=m.getFrameAtTime((long)((k+.5)*dur/n),MediaMetadataRetriever.OPTION_CLOSEST);if(b!=null)frames.add(scale(b,960));}m.release();}
 private void reconstruct(){if(frames.isEmpty()){updateStatus("Önce en az 1 fotoğraf veya video ekle.");return;}new Thread(()->{try{updateStatus("Görüntüler analiz ediliyor…");ArrayList<float[]>all=new ArrayList<>();int pairs=0,good=0;for(int i=0;i<frames.size()-1;i++){ArrayList<float[]>p=StereoReconstructor.reconstruct(scale(frames.get(i),640),scale(frames.get(i+1),640));pairs++;if(p.size()>=12)good++;float a=(float)(2*Math.PI*i/Math.max(1,frames.size()-1));for(float[]x:p){float X=(float)(x[0]*Math.cos(a)+x[2]*Math.sin(a));float Z=(float)(-x[0]*Math.sin(a)+x[2]*Math.cos(a));all.add(new float[]{X,x[1],Z});}if(all.size()>250000)break;}if(all.size()<80)all.addAll(fallbackCloud(frames.get(0)));updateStatus("3B veri hazır: "+all.size()+" nokta. Formatlar yazılıyor…");String base="MG3D_"+System.currentTimeMillis();saveAll(base,all);String q=all.size()<200?"ÇOK DÜŞÜK":all.size()<1000?"DÜŞÜK":all.size()<5000?"ORTA":"İYİ";updateStatus("TAMAMLANDI • "+q+" KALİTE\n"+all.size()+" 3B nokta • eşleşen çift "+good+"/"+pairs+"\n7 FORMAT KAYDEDİLDİ:\nOBJ • PLY • XYZ • STL • GLB • STEP • IGES\nDownload/MG3DScanner/");}catch(Exception e){updateStatus("Model/dışa aktarma hatası: "+e.getClass().getSimpleName()+" • "+e.getMessage());}}).start();}
 private ArrayList<float[]> fallbackCloud(Bitmap src){Bitmap b=scale(src,320);ArrayList<float[]>o=new ArrayList<>();for(int y=4;y<b.getHeight()-4;y+=5)for(int x=4;x<b.getWidth()-4;x+=5){int c=gray(b.getPixel(x,y));int gx=Math.abs(gray(b.getPixel(x+2,y))-gray(b.getPixel(x-2,y))),gy=Math.abs(gray(b.getPixel(x,y+2))-gray(b.getPixel(x,y-2)));if(gx+gy<35)continue;o.add(new float[]{(x-b.getWidth()/2f)/b.getWidth()*2f,-(y-b.getHeight()/2f)/b.getWidth()*2f,1f+(255-c)/255f*.12f});}return o;}
 private int gray(int c){return(Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;}
 private OutputStream out(String name,String mime)throws Exception{ContentValues cv=new ContentValues();cv.put(MediaStore.Downloads.DISPLAY_NAME,name);cv.put(MediaStore.Downloads.MIME_TYPE,mime);cv.put(MediaStore.Downloads.RELATIVE_PATH,"Download/MG3DScanner");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,cv);if(u==null)throw new IOException("Dosya oluşturulamadı: "+name);return getContentResolver().openOutputStream(u);}
 private void saveAll(String b,ArrayList<float[]>p)throws Exception{saveObj(b+".obj",p);savePly(b+".ply",p);saveXyz(b+".xyz",p);saveStl(b+".stl",p);saveGlb(b+".glb",p);saveStep(b+".step",p);saveIges(b+".igs",p);}
 private void saveObj(String n,ArrayList<float[]>p)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"text/plain")))){w.write("# MG3D point cloud\n");for(float[]x:p)w.write(String.format(Locale.US,"v %.6f %.6f %.6f\n",x[0],x[1],x[2]));}}
 private void savePly(String n,ArrayList<float[]>p)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"application/octet-stream")))){w.write("ply\nformat ascii 1.0\nelement vertex "+p.size()+"\nproperty float x\nproperty float y\nproperty float z\nend_header\n");for(float[]x:p)w.write(String.format(Locale.US,"%.6f %.6f %.6f\n",x[0],x[1],x[2]));}}
 private void saveXyz(String n,ArrayList<float[]>p)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"text/plain")))){for(float[]x:p)w.write(String.format(Locale.US,"%.6f %.6f %.6f\n",x[0],x[1],x[2]));}}
 private void saveStl(String n,ArrayList<float[]>p)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"model/stl")))){w.write("solid MG3D\n");for(int i=0;i+2<p.size();i+=3){float[]a=p.get(i),b=p.get(i+1),c=p.get(i+2);w.write(" facet normal 0 0 0\n  outer loop\n");for(float[]x:new float[][]{a,b,c})w.write(String.format(Locale.US,"   vertex %.6f %.6f %.6f\n",x[0],x[1],x[2]));w.write("  endloop\n endfacet\n");}w.write("endsolid MG3D\n");}}
 private void saveStep(String n,ArrayList<float[]>p)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"application/step")))){w.write("ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('MG3D point cloud'),'2;1');\nFILE_NAME('MG3D','',('MG'),('ChatGPT'),'MG3D','MG3D','');\nFILE_SCHEMA(('GEOMETRIC_CURVE_SET'));\nENDSEC;\nDATA;\n");int id=1;ArrayList<Integer>ids=new ArrayList<>();for(float[]x:p){w.write(String.format(Locale.US,"#%d=CARTESIAN_POINT('',(%.6f,%.6f,%.6f));\n",id,x[0],x[1],x[2]));ids.add(id++);}w.write("#"+id+"=GEOMETRIC_SET('',(");for(int i=0;i<ids.size();i++){if(i>0)w.write(",");w.write("#"+ids.get(i));}w.write("));\nENDSEC;\nEND-ISO-10303-21;\n");}}
 private void saveIges(String n,ArrayList<float[]>p)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"application/iges")))){w.write(pad72("MG3D Scanner IGES point cloud")+"S      1\n");w.write(pad72("1H,,1H;,4HMG3D,4HMG3D,32,38,6,308,15,6HMG3D,1.0,2,2HMM,1,0.01,15H20260817.000000,1.0E-6,1000.0,2HMG,6HMG3D,11,0,15H20260817.000000;")+"G      1\n");int d=1,seq=1;for(float[]x:p){String de=String.format(Locale.US,"%8d%8d%8d%8d%8d%8d%8d%8d",116,seq,0,0,0,0,0,0);w.write(pad72(de)+String.format(Locale.US,"D%7d\n",d++));w.write(pad72(String.format(Locale.US,"%8d%8d%8d%8d%8d%8d%8d%8d",116,0,0,1,0,0,0,0))+String.format(Locale.US,"D%7d\n",d++));w.write(pad64(String.format(Locale.US,"116,%.6f,%.6f,%.6f,0;",x[0],x[1],x[2]))+String.format(Locale.US,"%8dP%7d\n",d-1,seq++));}w.write(pad72(String.format(Locale.US,"S%7dG%7dD%7dP%7d",1,1,d-1,seq-1))+"T      1\n");}}
 private String pad72(String s){return String.format(Locale.US,"%-72.72s",s);} private String pad64(String s){return String.format(Locale.US,"%-64.64s",s);}
 private void saveGlb(String n,ArrayList<float[]>p)throws Exception{int count=p.size();ByteBuffer bin=ByteBuffer.allocate(count*12).order(ByteOrder.LITTLE_ENDIAN);float minX=Float.MAX_VALUE,minY=Float.MAX_VALUE,minZ=Float.MAX_VALUE,maxX=-Float.MAX_VALUE,maxY=-Float.MAX_VALUE,maxZ=-Float.MAX_VALUE;for(float[]x:p){bin.putFloat(x[0]);bin.putFloat(x[1]);bin.putFloat(x[2]);minX=Math.min(minX,x[0]);minY=Math.min(minY,x[1]);minZ=Math.min(minZ,x[2]);maxX=Math.max(maxX,x[0]);maxY=Math.max(maxY,x[1]);maxZ=Math.max(maxZ,x[2]);}String js=String.format(Locale.US,"{\"asset\":{\"version\":\"2.0\",\"generator\":\"MG3D Scanner\"},\"scene\":0,\"scenes\":[{\"nodes\":[0]}],\"nodes\":[{\"mesh\":0}],\"meshes\":[{\"primitives\":[{\"attributes\":{\"POSITION\":0},\"mode\":0}]}],\"buffers\":[{\"byteLength\":%d}],\"bufferViews\":[{\"buffer\":0,\"byteOffset\":0,\"byteLength\":%d,\"target\":34962}],\"accessors\":[{\"bufferView\":0,\"componentType\":5126,\"count\":%d,\"type\":\"VEC3\",\"min\":[%.6f,%.6f,%.6f],\"max\":[%.6f,%.6f,%.6f]}]}",count*12,count*12,count,minX,minY,minZ,maxX,maxY,maxZ);byte[]jb=js.getBytes(StandardCharsets.UTF_8);int jp=(4-jb.length%4)%4,bp=(4-bin.position()%4)%4,total=12+8+jb.length+jp+8+bin.position()+bp;try(DataOutputStream o=new DataOutputStream(out(n,"model/gltf-binary"))){writeLE(o,0x46546C67);writeLE(o,2);writeLE(o,total);writeLE(o,jb.length+jp);writeLE(o,0x4E4F534A);o.write(jb);for(int i=0;i<jp;i++)o.writeByte(0x20);writeLE(o,bin.position()+bp);writeLE(o,0x004E4942);o.write(bin.array(),0,bin.position());for(int i=0;i<bp;i++)o.writeByte(0);}}
 private void writeLE(DataOutputStream o,int v)throws Exception{o.writeByte(v&255);o.writeByte((v>>8)&255);o.writeByte((v>>16)&255);o.writeByte((v>>24)&255);}
 static class StereoReconstructor{static ArrayList<float[]> reconstruct(Bitmap A,Bitmap B){int w=Math.min(A.getWidth(),B.getWidth()),h=Math.min(A.getHeight(),B.getHeight());A=Bitmap.createScaledBitmap(A,w,h,true);B=Bitmap.createScaledBitmap(B,w,h,true);int step=7,rad=3,search=Math.min(90,w/4);ArrayList<float[]>out=new ArrayList<>();for(int y=rad+2;y<h-rad-2;y+=step)for(int x=rad+search+2;x<w-rad-2;x+=step){int gx=Math.abs(g(A,x+1,y)-g(A,x-1,y))+Math.abs(g(A,x,y+1)-g(A,x,y-1));if(gx<28)continue;int bestX=-1;long best=Long.MAX_VALUE,second=Long.MAX_VALUE;for(int xb=Math.max(rad+1,x-search);xb<=Math.min(w-rad-2,x+20);xb+=2){long e=0;for(int yy=-rad;yy<=rad;yy++)for(int xx=-rad;xx<=rad;xx++)e+=Math.abs(g(A,x+xx,y+yy)-g(B,xb+xx,y+yy));if(e<best){second=best;best=e;bestX=xb;}else if(e<second)second=e;}if(bestX<0||best>3200||best*100L>second*98L)continue;float disp=x-bestX;if(Math.abs(disp)<1)continue;float z=120f/Math.abs(disp),X=(x-w/2f)*z/w,Y=-(y-h/2f)*z/w;if(z>.3f&&z<100f)out.add(new float[]{X,Y,z});}return out;}static int g(Bitmap b,int x,int y){int c=b.getPixel(x,y);return(Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;}}
}
