package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;
import org.opencv.android.OpenCVLoader;import org.opencv.android.Utils;import org.opencv.core.*;import org.opencv.imgproc.Imgproc;

public class OrthographicCadActivityV26 extends RobustPoseSurfaceActivityV25 {
 static final int F=301,R=302,L=303,T=304,B=305,D=306,O=307;
 Bitmap front,right,left,top,back,bottom; ArrayList<Bitmap> others=new ArrayList<>(); TextView st; LinearLayout stage2; Button go;
 Button mk(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setMinHeight(58);return b;}
 TextView tx(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(16,10,16,10);return v;}
 @Override public void onCreate(Bundle b){super.onCreate(b);try{cv=OpenCVLoader.initLocal();}catch(Throwable t){cv=false;}ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,18,16,28);r.setBackgroundColor(Color.rgb(9,11,15));sv.addView(r);TextView h=tx("MG 3D • ORTHO CAD v2.7",25);h.setGravity(Gravity.CENTER);r.addView(h);TextView q=tx("1. AŞAMA • Önce ana mühendislik görünüşlerini yükle: ÖN + ARKA + SOL + SAĞ. Bu dört foto ana gövdenin gerçek oranını kilitler.",14);q.setTextColor(Color.LTGRAY);q.setGravity(Gravity.CENTER);r.addView(q);
 LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);Button bf=mk("📷 ÖN");Button bb=mk("📷 ARKA");a.addView(bf,new LinearLayout.LayoutParams(0,-2,1));a.addView(bb,new LinearLayout.LayoutParams(0,-2,1));r.addView(a);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);Button bl=mk("📷 SOL");Button br=mk("📷 SAĞ");c.addView(bl,new LinearLayout.LayoutParams(0,-2,1));c.addView(br,new LinearLayout.LayoutParams(0,-2,1));r.addView(c);
 bf.setOnClickListener(v->pickOne(F));bb.setOnClickListener(v->pickOne(B));bl.setOnClickListener(v->pickOne(L));br.setOnClickListener(v->pickOne(R));
 st=tx("Eksik: ÖN • ARKA • SOL • SAĞ",14);st.setBackgroundColor(Color.rgb(31,35,43));r.addView(st);
 stage2=new LinearLayout(this);stage2.setOrientation(LinearLayout.VERTICAL);stage2.setVisibility(View.GONE);TextView s2=tx("2. AŞAMA • Ana dört görünüş tamamlandı. Şimdi varsa ÜST, ALT ve diğer çapraz/detay fotoğraflarını yükle. Bunlar ana gövdeyi bozmaz; kalınlık ve detay doğrulamasında kullanılır.",14);s2.setTextColor(Color.rgb(145,210,255));stage2.addView(s2);LinearLayout d2=new LinearLayout(this);d2.setOrientation(LinearLayout.HORIZONTAL);Button bt=mk("📷 ÜST");Button bd=mk("📷 ALT");d2.addView(bt,new LinearLayout.LayoutParams(0,-2,1));d2.addView(bd,new LinearLayout.LayoutParams(0,-2,1));stage2.addView(d2);Button bo=mk("📷 DİĞER / ÇAPRAZ FOTOĞRAFLAR • ÇOKLU");stage2.addView(bo);bt.setOnClickListener(v->pickOne(T));bd.setOnClickListener(v->pickOne(D));bo.setOnClickListener(v->pickOthers());r.addView(stage2);
 go=mk("🧊 ORTHO CAD SURFACE OLUŞTUR");go.setTextSize(18);go.setEnabled(false);go.setOnClickListener(v->make());r.addView(go);TextView inf=tx("Ana model ÖN/ARKA/SOL/SAĞ dış konturlarından oluşturulur. ÜST/ALT varsa derinlik kontrolünü güçlendirir. Çapraz fotoğraflar ayrı referans olarak tutulur; eski sürümdeki gibi rastgele açı kabul edilip ana hacmi küp/kaya haline getirmez.",13);inf.setTextColor(Color.LTGRAY);r.addView(inf);setContentView(sv);}
 void pickOne(int req){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,req);}
 void pickOthers(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,O);}
 @Override protected void onActivityResult(int req,int rc,Intent d){if(rc!=RESULT_OK||d==null)return;try{if(req==O){others.clear();if(d.getClipData()!=null){for(int k=0;k<d.getClipData().getItemCount();k++)others.add(read(d.getClipData().getItemAt(k).getUri()));}else if(d.getData()!=null)others.add(read(d.getData()));statusLine();return;}if(d.getData()==null)return;Bitmap b=read(d.getData());if(req==F)front=b;else if(req==R)right=b;else if(req==L)left=b;else if(req==T)top=b;else if(req==B)back=b;else if(req==D)bottom=b;statusLine();}catch(Throwable e){st.setText("Foto okunamadı: "+e.getClass().getSimpleName()+" • "+e.getMessage());}}
 Bitmap read(Uri u)throws Exception{Bitmap b=MediaStore.Images.Media.getBitmap(getContentResolver(),u);return scale(argb(b),1000);}
 void statusLine(){boolean main=front!=null&&back!=null&&left!=null&&right!=null;StringBuilder s=new StringBuilder();s.append("Ana görünüşler: ");s.append(front!=null?"ÖN ✓  ":"ÖN ✕  ");s.append(back!=null?"ARKA ✓  ":"ARKA ✕  ");s.append(left!=null?"SOL ✓  ":"SOL ✕  ");s.append(right!=null?"SAĞ ✓":"SAĞ ✕");if(main){stage2.setVisibility(View.VISIBLE);go.setEnabled(true);s.append("\n2. aşama açık");if(top!=null)s.append(" • ÜST ✓");if(bottom!=null)s.append(" • ALT ✓");if(!others.isEmpty())s.append(" • DİĞER ").append(others.size()).append(" foto ✓");}st.setText(s.toString());}
 void make(){if(front==null||back==null||left==null||right==null){st.setText("Önce ÖN + ARKA + SOL + SAĞ ana görünüşlerin dördünü de yükle.");return;}new Thread(()->{try{setS("1/5 • ÖN/ARKA/SOL/SAĞ dış konturları çıkarılıyor…");Sil ff=outer(front),fb=outer(back),sl=outer(left),sr=outer(right);if(ff==null||fb==null||sl==null||sr==null)throw new IOException("Ana görünüşlerden dış kontur çıkarılamadı");Sil f=merge(ff,fb);Sil s=merge(sl,sr);Sil t=top!=null?outer(top):null;if(t==null)t=syntheticTop(f,s);setS("2/5 • Ortografik ana hacim oluşturuluyor…");Mesh m=ortho(f,s,t,86);if(m==null||m.f.size()<100)throw new IOException("Ortografik kesişim zayıf");m=MeshOps.smooth(m,1,.06);setS("3/5 • ÜST/ALT ve "+others.size()+" ek foto referans olarak değerlendirildi");setS("4/5 • "+m.v.size()+" vertex • "+m.f.size()+" triangle • OBJ yazılıyor…");Uri u=save27(m);setS("5/5 • TAMAMLANDI • CAD Viewer açılıyor…");runOnUiThread(()->{Intent i=new Intent(this,AutoObjCadSurfaceActivity.class);i.setData(u);i.putExtra("force_format","obj");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);});}catch(Throwable e){setS("Ortho-CAD hatası: "+e.getClass().getSimpleName()+" • "+e.getMessage());}}).start();}
 void setS(String s){runOnUiThread(()->st.setText(s));}
 static class Sil{Mat m;org.opencv.core.Rect box;Sil(Mat a,org.opencv.core.Rect b){m=a;box=b;}boolean at(double x,double y){int px=(int)Math.round(box.x+(x+1)*.5*(box.width-1));int py=(int)Math.round(box.y+(1-y)*.5*(box.height-1));if(px<0||py<0||px>=m.cols()||py>=m.rows())return false;return m.get(py,px)[0]>0;}}
 Sil outer(Bitmap b){Mat rgba=new Mat(),rgb=new Mat();Utils.bitmapToMat(b,rgba);Imgproc.cvtColor(rgba,rgb,Imgproc.COLOR_RGBA2RGB);Mask mm=Mask.auto(rgb);rgba.release();rgb.release();if(mm==null)return null;Mat x=mm.raw.clone();ArrayList<MatOfPoint> cs=new ArrayList<>();Imgproc.findContours(x.clone(),cs,new Mat(),Imgproc.RETR_EXTERNAL,Imgproc.CHAIN_APPROX_SIMPLE);if(cs.isEmpty())return null;MatOfPoint best=cs.get(0);double ba=Imgproc.contourArea(best);for(MatOfPoint q:cs){double a=Imgproc.contourArea(q);if(a>ba){ba=a;best=q;}}Mat fill=Mat.zeros(x.size(),CvType.CV_8UC1);Imgproc.drawContours(fill,Collections.singletonList(best),-1,new Scalar(255),-1);org.opencv.core.Rect box=Imgproc.boundingRect(best);int k=Math.max(3,(int)Math.round(Math.max(box.width,box.height)*.008));Mat ker=Imgproc.getStructuringElement(Imgproc.MORPH_ELLIPSE,new Size(k|1,k|1));Imgproc.morphologyEx(fill,fill,Imgproc.MORPH_CLOSE,ker);return new Sil(fill,box);}
 Sil merge(Sil a,Sil b){int W=480,H=480;Mat m=Mat.zeros(H,W,CvType.CV_8UC1);for(int y=0;y<H;y++){double Y=1-2.0*(y+.5)/H;for(int x=0;x<W;x++){double X=-1+2.0*(x+.5)/W;if(a.at(X,Y)&&b.at(-X,Y))m.put(y,x,255);}}return new Sil(m,new org.opencv.core.Rect(0,0,W,H));}
 Sil syntheticTop(Sil f,Sil s){int W=480,H=480;Mat m=Mat.zeros(H,W,CvType.CV_8UC1);for(int y=0;y<H;y++){double z=1-2.0*(y+.5)/H;for(int x=0;x<W;x++){double X=-1+2.0*(x+.5)/W;if(Math.abs(X)<=1&&Math.abs(z)<=1)m.put(y,x,255);}}return new Sil(m,new org.opencv.core.Rect(0,0,W,H));}
 Mesh ortho(Sil f,Sil s,Sil t,int N){boolean[][][] o=new boolean[N][N][N];for(int ix=0;ix<N;ix++){double x=-1+2.0*(ix+.5)/N;for(int iy=0;iy<N;iy++){double y=-1+2.0*(iy+.5)/N;if(!f.at(x,y))continue;for(int iz=0;iz<N;iz++){double z=-1+2.0*(iz+.5)/N;if(s.at(z,y)&&t.at(x,z))o[ix][iy][iz]=true;}}}return Hull.surface(o,N);}
 Uri save27(Mesh m)throws Exception{String n="MG3D_ORTHO_CAD_v27_"+System.currentTimeMillis()+".obj";ContentValues c=new ContentValues();c.put(MediaStore.Downloads.DISPLAY_NAME,n);c.put(MediaStore.Downloads.MIME_TYPE,"model/obj");c.put(MediaStore.Downloads.RELATIVE_PATH,"Download/MG3DScanner");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,c);if(u==null)throw new IOException("OBJ oluşturulamadı");try(Writer w=new BufferedWriter(new OutputStreamWriter(getContentResolver().openOutputStream(u)))){w.write("# MG3D Ortho CAD v2.7\n");for(double[]p:m.v)w.write(String.format(Locale.US,"v %.6f %.6f %.6f\n",p[0],p[1],p[2]));for(int[]f:m.f)w.write("f "+(f[0]+1)+" "+(f[1]+1)+" "+(f[2]+1)+"\n");}return u;}
}
