package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;
import org.opencv.android.OpenCVLoader;import org.opencv.android.Utils;import org.opencv.core.*;import org.opencv.imgproc.Imgproc;

public class OrthographicCadActivityV26 extends RobustPoseSurfaceActivityV25 {
 static final int F=301,R=302,L=303,T=304,B=305,D=306;
 Bitmap front,right,left,top,back,bottom; TextView st;
 Button mk(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setMinHeight(58);return b;}
 TextView tx(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(16,10,16,10);return v;}
 @Override public void onCreate(Bundle b){super.onCreate(b);try{cv=OpenCVLoader.initLocal();}catch(Throwable t){cv=false;}LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,18,16,18);r.setBackgroundColor(Color.rgb(9,11,15));TextView h=tx("MG 3D • ORTHO CAD v2.6",25);h.setGravity(Gravity.CENTER);r.addView(h);TextView q=tx("Ana geometri: ÖN + YAN + ÜST ortografik görünüşlerden kurulur. ARKA/ALT varsa doğruluk artar.",13);q.setTextColor(Color.LTGRAY);q.setGravity(Gravity.CENTER);r.addView(q);
 LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);Button bf=mk("📷 ÖN");Button br=mk("📷 SAĞ");Button bl=mk("📷 SOL");a.addView(bf,new LinearLayout.LayoutParams(0,-2,1));a.addView(br,new LinearLayout.LayoutParams(0,-2,1));a.addView(bl,new LinearLayout.LayoutParams(0,-2,1));r.addView(a);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);Button bt=mk("📷 ÜST");Button bb=mk("📷 ARKA");Button bd=mk("📷 ALT");c.addView(bt,new LinearLayout.LayoutParams(0,-2,1));c.addView(bb,new LinearLayout.LayoutParams(0,-2,1));c.addView(bd,new LinearLayout.LayoutParams(0,-2,1));r.addView(c);
 bf.setOnClickListener(v->pickOne(F));br.setOnClickListener(v->pickOne(R));bl.setOnClickListener(v->pickOne(L));bt.setOnClickListener(v->pickOne(T));bb.setOnClickListener(v->pickOne(B));bd.setOnClickListener(v->pickOne(D));
 st=tx("ÖN + bir YAN + ÜST seç. Fan/ızgara delikleri ana hacmi oymayacak; dış kontur esas alınacak.",14);st.setBackgroundColor(Color.rgb(31,35,43));r.addView(st);Button go=mk("🧊 ORTHO CAD SURFACE OLUŞTUR");go.setTextSize(18);go.setOnClickListener(v->make());r.addView(go);TextView inf=tx("Bu mod özellikle ürün/mekanik parça taramasında kullanılır. Ön görünüş genişlik-yükseklik, yan görünüş derinlik-yükseklik, üst görünüş genişlik-derinlik oranını kilitler. İç ızgara/delikler ana gövdeden ayrı detay kabul edilir; böylece visual-hull küp/kaya hatası önlenir.",13);inf.setTextColor(Color.LTGRAY);r.addView(inf);setContentView(r);}
 void pickOne(int req){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,req);}
 @Override protected void onActivityResult(int req,int rc,Intent d){if(rc!=RESULT_OK||d==null||d.getData()==null)return;try{Bitmap b=MediaStore.Images.Media.getBitmap(getContentResolver(),d.getData());b=scale(argb(b),1000);if(req==F)front=b;else if(req==R)right=b;else if(req==L)left=b;else if(req==T)top=b;else if(req==B)back=b;else if(req==D)bottom=b;statusLine();}catch(Throwable e){st.setText("Foto okunamadı: "+e.getClass().getSimpleName()+" • "+e.getMessage());}}
 void statusLine(){st.setText("Seçilen: "+(front!=null?"ÖN ✓  ":"")+(right!=null?"SAĞ ✓  ":"")+(left!=null?"SOL ✓  ":"")+(top!=null?"ÜST ✓  ":"")+(back!=null?"ARKA ✓  ":"")+(bottom!=null?"ALT ✓":""));}
 void make(){if(front==null||top==null||(right==null&&left==null)){st.setText("Ana CAD için ÖN + en az bir YAN + ÜST gerekli.");return;}new Thread(()->{try{setS("1/4 • Dış konturlar çıkarılıyor…");Sil f=outer(front),s=outer(right!=null?right:left),t=outer(top);if(f==null||s==null||t==null)throw new IOException("Ana görünüşlerden dış kontur çıkarılamadı");setS("2/4 • Ortografik hacim kesiştiriliyor…");Mesh m=ortho(f,s,t,82);if(m==null||m.f.size()<100)throw new IOException("Ortografik kesişim zayıf");m=MeshOps.smooth(m,1,.08);setS("3/4 • "+m.v.size()+" vertex • "+m.f.size()+" triangle • OBJ yazılıyor…");Uri u=save26(m);setS("4/4 • TAMAMLANDI • CAD Viewer açılıyor…");runOnUiThread(()->{Intent i=new Intent(this,AutoObjCadSurfaceActivity.class);i.setData(u);i.putExtra("force_format","obj");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);});}catch(Throwable e){setS("Ortho-CAD hatası: "+e.getClass().getSimpleName()+" • "+e.getMessage());}}).start();}
 void setS(String s){runOnUiThread(()->st.setText(s));}
 static class Sil{Mat m;org.opencv.core.Rect box;Sil(Mat a,org.opencv.core.Rect b){m=a;box=b;}boolean at(double x,double y){int px=(int)Math.round(box.x+(x+1)*.5*(box.width-1));int py=(int)Math.round(box.y+(1-y)*.5*(box.height-1));if(px<0||py<0||px>=m.cols()||py>=m.rows())return false;return m.get(py,px)[0]>0;}}
 Sil outer(Bitmap b){Mat rgba=new Mat(),rgb=new Mat();Utils.bitmapToMat(b,rgba);Imgproc.cvtColor(rgba,rgb,Imgproc.COLOR_RGBA2RGB);Mask mm=Mask.auto(rgb);rgba.release();rgb.release();if(mm==null)return null;Mat x=mm.raw.clone();ArrayList<MatOfPoint> cs=new ArrayList<>();Imgproc.findContours(x.clone(),cs,new Mat(),Imgproc.RETR_EXTERNAL,Imgproc.CHAIN_APPROX_SIMPLE);if(cs.isEmpty())return null;MatOfPoint best=cs.get(0);double ba=Imgproc.contourArea(best);for(MatOfPoint q:cs){double a=Imgproc.contourArea(q);if(a>ba){ba=a;best=q;}}Mat fill=Mat.zeros(x.size(),CvType.CV_8UC1);Imgproc.drawContours(fill,Collections.singletonList(best),-1,new Scalar(255),-1);org.opencv.core.Rect box=Imgproc.boundingRect(best);int k=Math.max(3,(int)Math.round(Math.max(box.width,box.height)*.008));Mat ker=Imgproc.getStructuringElement(Imgproc.MORPH_ELLIPSE,new Size(k|1,k|1));Imgproc.morphologyEx(fill,fill,Imgproc.MORPH_CLOSE,ker);return new Sil(fill,box);}
 Mesh ortho(Sil f,Sil s,Sil t,int N){boolean[][][] o=new boolean[N][N][N];for(int ix=0;ix<N;ix++){double x=-1+2.0*(ix+.5)/N;for(int iy=0;iy<N;iy++){double y=-1+2.0*(iy+.5)/N;if(!f.at(x,y))continue;for(int iz=0;iz<N;iz++){double z=-1+2.0*(iz+.5)/N;if(s.at(z,y)&&t.at(x,z))o[ix][iy][iz]=true;}}}return Hull.surface(o,N);}
 Uri save26(Mesh m)throws Exception{String n="MG3D_ORTHO_CAD_v26_"+System.currentTimeMillis()+".obj";ContentValues c=new ContentValues();c.put(MediaStore.Downloads.DISPLAY_NAME,n);c.put(MediaStore.Downloads.MIME_TYPE,"model/obj");c.put(MediaStore.Downloads.RELATIVE_PATH,"Download/MG3DScanner");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,c);if(u==null)throw new IOException("OBJ oluşturulamadı");try(Writer w=new BufferedWriter(new OutputStreamWriter(getContentResolver().openOutputStream(u)))){w.write("# MG3D Ortho CAD v2.6\n");for(double[]p:m.v)w.write(String.format(Locale.US,"v %.6f %.6f %.6f\n",p[0],p[1],p[2]));for(int[]f:m.f)w.write("f "+(f[0]+1)+" "+(f[1]+1)+" "+(f[2]+1)+"\n");}return u;}
}
