package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.media.MediaMetadataRetriever;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class ProSurfaceActivity extends Activity{
 static final int RI=40,RV=41; final ArrayList<Bitmap>frames=new ArrayList<>(); TextView status,quality;
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(18,12,18,12);return v;} Button bt(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setMinHeight(58);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(10,12,15));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(18,22,18,26);r.setBackgroundColor(Color.rgb(10,12,15));TextView t=tv("MG 3D • PRO SURFACE",27);t.setGravity(Gravity.CENTER);r.addView(t);TextView s=tv("Siluet sıralama • 64³ adaptive hull • topology • Taubin smooth",13);s.setTextColor(Color.LTGRAY);s.setGravity(Gravity.CENTER);r.addView(s);Button p=bt("📷 FOTOĞRAFLARI SEÇ");p.setOnClickListener(v->pick(false));r.addView(p);Button v=bt("🎥 VİDEO SEÇ / AKILLI KEYFRAME");v.setOnClickListener(x->pick(true));r.addView(v);Button c=bt("🗑 ÇEKİMİ TEMİZLE");c.setOnClickListener(x->{frames.clear();refresh();});r.addView(c);status=tv("Hazır. Aynı nesnenin farklı açılarını ekle.",15);status.setBackgroundColor(Color.rgb(32,35,41));r.addView(status);quality=tv("PRO kalite: veri bekleniyor",14);quality.setTextColor(Color.LTGRAY);r.addView(quality);Button go=bt("🧊 PRO SURFACE OLUŞTUR");go.setOnClickListener(x->runPro());r.addView(go);TextView info=tv("PRO motor: arka planı ayırır → en büyük nesne siluetini bulur → benzer açıları otomatik sıralar → 3B visual hull oluşturur → küçük boşlukları kapatır → tek connected component seçer → ortak vertex topology kurar → hacmi koruyan Taubin smoothing uygular. Uzak noktalar birbirine bağlanmaz; diken/radyal yüzey üretilmez.",13);info.setTextColor(Color.LTGRAY);r.addView(info);setContentView(r);}
 void pick(boolean video){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(video?"video/*":"image/*");if(!video)i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,video?RV:RI);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;new Thread(()->{try{if(r==RI){if(d.getClipData()!=null)for(int k=0;k<d.getClipData().getItemCount();k++)add(d.getClipData().getItemAt(k).getUri());else if(d.getData()!=null)add(d.getData());}else if(r==RV&&d.getData()!=null)video(d.getData());refresh();}catch(Exception e){set("Girdi hatası: "+e.getMessage());}}).start();}
 void add(Uri u)throws Exception{Bitmap b=MediaStore.Images.Media.getBitmap(getContentResolver(),u);if(b!=null)frames.add(scale(b,1200));}
 Bitmap scale(Bitmap b,int max){int w=b.getWidth(),h=b.getHeight();if(Math.max(w,h)<=max)return b;float q=max/(float)Math.max(w,h);return Bitmap.createScaledBitmap(b,Math.max(2,(int)(w*q)),Math.max(2,(int)(h*q)),true);}
 void video(Uri u)throws Exception{MediaMetadataRetriever m=new MediaMetadataRetriever();m.setDataSource(this,u);long dur=Long.parseLong(m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION))*1000L;Bitmap last=null;for(int k=0;k<80;k++){Bitmap b=m.getFrameAtTime((long)((k+.5)*dur/80),MediaMetadataRetriever.OPTION_CLOSEST);if(b==null)continue;b=scale(b,800);float sh=sharp(b),ch=last==null?1:change(last,b);if(sh>17&&(last==null||ch>.05f||frames.size()<8)){frames.add(b);last=b;}if(frames.size()>=40)break;}m.release();}
 float sharp(Bitmap b){Bitmap s=scale(b,150);double a=0,a2=0;int n=0;for(int y=2;y<s.getHeight()-2;y+=3)for(int x=2;x<s.getWidth()-2;x+=3){int q=Math.abs(g(s.getPixel(x+1,y))-g(s.getPixel(x-1,y)))+Math.abs(g(s.getPixel(x,y+1))-g(s.getPixel(x,y-1)));a+=q;a2+=q*q;n++;}double m=a/Math.max(1,n);return(float)Math.sqrt(Math.max(0,a2/Math.max(1,n)-m*m));}
 float change(Bitmap a,Bitmap b){a=scale(a,96);b=scale(b,96);int w=Math.min(a.getWidth(),b.getWidth()),h=Math.min(a.getHeight(),b.getHeight()),n=0;long s=0;for(int y=0;y<h;y+=4)for(int x=0;x<w;x+=4){s+=Math.abs(g(a.getPixel(x,y))-g(b.getPixel(x,y)));n++;}return s/(255f*Math.max(1,n));}int g(int c){return(Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;}
 void refresh(){runOnUiThread(()->{int n=frames.size();status.setText(n+" görüntü hazır.");String q=n<4?"DÜŞÜK":n<8?"ORTA":n<16?"İYİ":"ÇOK İYİ";quality.setText("PRO kapsam: "+q+" • "+n+" görüntü");});}void set(String s){runOnUiThread(()->status.setText(s));}
 void runPro(){if(frames.isEmpty()){status.setText("Önce fotoğraf veya video ekle.");return;}new Thread(()->{try{set("1/6 • Yüksek çözünürlüklü nesne maskeleri çıkarılıyor…");ArrayList<Mask>m=new ArrayList<>();for(Bitmap b:frames){Mask x=Mask.from(b);if(x!=null&&x.area>300)m.add(x);}if(m.isEmpty())throw new IOException("Nesne maskesi bulunamadı. Sade/zıt fonda çek.");set("2/6 • "+m.size()+" siluet • açı sırası optimize ediliyor…");m=order(m);set("3/6 • 64³ adaptive visual hull hesaplanıyor…");Mesh mesh=Hull.build(m);set("4/6 • Topology + hacim koruyan smoothing…");mesh=MeshOps.taubin(mesh,5,.28f,-.30f);set("5/6 • "+mesh.v.length/3+" vertex • "+mesh.i.length/3+" triangle • CAD dosyaları yazılıyor…");String b="MG3D_SURFACE_PRO_"+System.currentTimeMillis();saveAll(b,mesh);set("TAMAMLANDI • PRO CONTINUOUS SURFACE\n"+(mesh.v.length/3)+" vertex • "+(mesh.i.length/3)+" connected triangle\nKullanılan görüntü: "+m.size()+"/"+frames.size()+"\nOBJ • PLY • STL • GLB\nDownload/MG3DScanner/");}catch(Exception e){set("PRO Surface hatası: "+e.getClass().getSimpleName()+" • "+e.getMessage());}}).start();}

 static ArrayList<Mask>order(ArrayList<Mask>a){if(a.size()<4)return a;ArrayList<Mask>left=new ArrayList<>(a),out=new ArrayList<>();Mask cur=left.remove(0);out.add(cur);while(!left.isEmpty()){int bi=0;float bs=Float.MAX_VALUE;for(int i=0;i<left.size();i++){float d=cur.distance(left.get(i));if(d<bs){bs=d;bi=i;}}cur=left.remove(bi);out.add(cur);}return out;}
 static class Mask{int w,h,minx,miny,maxx,maxy,area;boolean[]p;float[]sig;Mask(int W,int H){w=W;h=H;p=new boolean[w*h];}
  boolean at(int x,int y){return x>=0&&y>=0&&x<w&&y<h&&p[y*w+x];} boolean sample(float nx,float ny){float sx=Math.max(1,maxx-minx+1),sy=Math.max(1,maxy-miny+1);int x=Math.round((minx+maxx)*.5f+nx*sx*.5f),y=Math.round((miny+maxy)*.5f-ny*sy*.5f);return at(x,y);}
  float distance(Mask o){float d=0;for(int i=0;i<sig.length;i++){float q=sig[i]-o.sig[i];d+=q*q;}return d;}
  static Mask from(Bitmap src){Bitmap b=resize(src,240);int w=b.getWidth(),h=b.getHeight(),band=Math.max(4,Math.min(w,h)/18);double sr=0,sg=0,sb=0,n=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(x<band||y<band||x>=w-band||y>=h-band){int c=b.getPixel(x,y);sr+=Color.red(c);sg+=Color.green(c);sb+=Color.blue(c);n++;}float br=(float)(sr/n),bg=(float)(sg/n),bb=(float)(sb/n);double md=0,sd=0;int bn=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(x<band||y<band||x>=w-band||y>=h-band){int c=b.getPixel(x,y);double d=dist(c,br,bg,bb);md+=d;sd+=d*d;bn++;}md/=bn;double st=Math.sqrt(Math.max(0,sd/bn-md*md)),th=Math.max(30,md+2.7*st);Mask r=new Mask(w,h);for(int y=0;y<h;y++)for(int x=0;x<w;x++)r.p[y*w+x]=dist(b.getPixel(x,y),br,bg,bb)>th;r.morph();Mask m=r.largest();if(m!=null)m.signature();return m;}
  static double dist(int c,float r,float g,float b){double x=Color.red(c)-r,y=Color.green(c)-g,z=Color.blue(c)-b;return Math.sqrt(x*x+y*y+z*z);}static Bitmap resize(Bitmap b,int max){float s=max/(float)Math.max(b.getWidth(),b.getHeight());return Bitmap.createScaledBitmap(b,Math.max(2,(int)(b.getWidth()*s)),Math.max(2,(int)(b.getHeight()*s)),true);}
  void morph(){for(int pass=0;pass<2;pass++){boolean[]q=p.clone();for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int c=0;for(int yy=-1;yy<=1;yy++)for(int xx=-1;xx<=1;xx++)if(p[(y+yy)*w+x+xx])c++;q[y*w+x]=c>=4;}p=q;}}
  Mask largest(){boolean[]v=new boolean[p.length];int[]qx=new int[p.length],qy=new int[p.length];ArrayList<Integer>best=new ArrayList<>();int[]dx={1,-1,0,0},dy={0,0,1,-1};for(int y=0;y<h;y++)for(int x=0;x<w;x++){int id=y*w+x;if(!p[id]||v[id])continue;ArrayList<Integer>cur=new ArrayList<>();int hd=0,tl=0;qx[tl]=x;qy[tl++]=y;v[id]=true;while(hd<tl){int xx=qx[hd],yy=qy[hd++];cur.add(yy*w+xx);for(int k=0;k<4;k++){int a=xx+dx[k],b=yy+dy[k];if(a<0||b<0||a>=w||b>=h)continue;int ni=b*w+a;if(p[ni]&&!v[ni]){v[ni]=true;qx[tl]=a;qy[tl++]=b;}}}if(cur.size()>best.size())best=cur;}if(best.size()<120)return null;Mask m=new Mask(w,h);m.minx=w;m.miny=h;for(int id:best){m.p[id]=true;int x=id%w,y=id/w;m.minx=Math.min(m.minx,x);m.maxx=Math.max(m.maxx,x);m.miny=Math.min(m.miny,y);m.maxy=Math.max(m.maxy,y);}m.area=best.size();return m;}
  void signature(){sig=new float[18];float cx=(minx+maxx)*.5f,cy=(miny+maxy)*.5f,sc=Math.max(maxx-minx+1,maxy-miny+1);for(int k=0;k<16;k++){double a=2*Math.PI*k/16;float best=0;for(int s=1;s<120;s++){float r=s/120f;int x=Math.round(cx+(float)Math.cos(a)*r*sc*.6f),y=Math.round(cy+(float)Math.sin(a)*r*sc*.6f);if(at(x,y))best=r;}sig[k]=best;}sig[16]=(maxx-minx+1)/(float)Math.max(1,maxy-miny+1);sig[17]=area/(float)Math.max(1,(maxx-minx+1)*(maxy-miny+1));}
 }
 static class Mesh{float[]v;int[]i;Mesh(float[]a,int[]b){v=a;i=b;}}
 static class Hull{
  static Mesh build(ArrayList<Mask>m){int R=64,n=m.size();boolean[][][]o=new boolean[R][R][R];int need=Math.max(1,(int)Math.ceil(n*.60));int cnt=carve(m,o,R,need);if(cnt<R*R*2){o=new boolean[R][R][R];cnt=carve(m,o,R,Math.max(1,(int)Math.ceil(n*.48)));}if(cnt<R*R)return extrude(best(m),R);majority(o,R,2);largest(o,R);return surface(o,R);}
  static int carve(ArrayList<Mask>m,boolean[][][]o,int R,int need){int n=m.size(),c=0;for(int x=0;x<R;x++){float X=-1+2f*(x+.5f)/R;for(int y=0;y<R;y++){float Y=-1+2f*(y+.5f)/R;for(int z=0;z<R;z++){float Z=-1+2f*(z+.5f)/R;int in=0;for(int k=0;k<n;k++){double a=2*Math.PI*k/n;float u=(float)(X*Math.cos(a)-Z*Math.sin(a));if(m.get(k).sample(u,Y))in++;}if(in>=need){o[x][y][z]=true;c++;}}}}return c;}
  static void majority(boolean[][][]o,int R,int passes){int[][]d={{1,0,0},{-1,0,0},{0,1,0},{0,-1,0},{0,0,1},{0,0,-1}};for(int p=0;p<passes;p++){boolean[][][]q=new boolean[R][R][R];for(int x=1;x<R-1;x++)for(int y=1;y<R-1;y++)for(int z=1;z<R-1;z++){int c=o[x][y][z]?3:0;for(int[]a:d)if(o[x+a[0]][y+a[1]][z+a[2]])c++;q[x][y][z]=c>=5;}oCopy(q,o,R);}}
  static void oCopy(boolean[][][]a,boolean[][][]b,int R){for(int x=0;x<R;x++)for(int y=0;y<R;y++)System.arraycopy(a[x][y],0,b[x][y],0,R);}
  static Mask best(ArrayList<Mask>m){Mask b=m.get(0);for(Mask x:m)if(x.area>b.area)b=x;return b;}
  static Mesh extrude(Mask m,int R){boolean[][][]o=new boolean[R][R][R];for(int x=0;x<R;x++){float X=-1+2f*(x+.5f)/R;for(int y=0;y<R;y++){float Y=-1+2f*(y+.5f)/R;if(!m.sample(X,Y))continue;for(int z=R/4;z<3*R/4;z++)o[x][y][z]=true;}}return surface(o,R);}
  static void largest(boolean[][][]o,int R){boolean[][][]v=new boolean[R][R][R];int max=R*R*R;int[]qx=new int[max],qy=new int[max],qz=new int[max];ArrayList<int[]>best=new ArrayList<>();int[][]d={{1,0,0},{-1,0,0},{0,1,0},{0,-1,0},{0,0,1},{0,0,-1}};for(int x=0;x<R;x++)for(int y=0;y<R;y++)for(int z=0;z<R;z++){if(!o[x][y][z]||v[x][y][z])continue;ArrayList<int[]>cur=new ArrayList<>();int h=0,t=0;qx[t]=x;qy[t]=y;qz[t++]=z;v[x][y][z]=true;while(h<t){int a=qx[h],b=qy[h],c=qz[h++];cur.add(new int[]{a,b,c});for(int[]e:d){int A=a+e[0],B=b+e[1],C=c+e[2];if(A>=0&&B>=0&&C>=0&&A<R&&B<R&&C<R&&o[A][B][C]&&!v[A][B][C]){v[A][B][C]=true;qx[t]=A;qy[t]=B;qz[t++]=C;}}}if(cur.size()>best.size())best=cur;}for(int x=0;x<R;x++)for(int y=0;y<R;y++)Arrays.fill(o[x][y],false);for(int[]p:best)o[p[0]][p[1]][p[2]]=true;}
  static Mesh surface(boolean[][][]o,int R){HashMap<Long,Integer>map=new HashMap<>();ArrayList<Float>v=new ArrayList<>();ArrayList<Integer>id=new ArrayList<>();int[][]face={{0,0,-1},{0,0,1},{-1,0,0},{1,0,0},{0,-1,0},{0,1,0}};int[][]corn={{0,0,0,1,0,0,1,1,0,0,1,0},{0,0,1,0,1,1,1,1,1,1,0,1},{0,0,0,0,1,0,0,1,1,0,0,1},{1,0,0,1,0,1,1,1,1,1,1,0},{0,0,0,0,0,1,1,0,1,1,0,0},{0,1,0,1,1,0,1,1,1,0,1,1}};for(int x=0;x<R;x++)for(int y=0;y<R;y++)for(int z=0;z<R;z++)if(o[x][y][z])for(int f=0;f<6;f++){int nx=x+face[f][0],ny=y+face[f][1],nz=z+face[f][2];if(nx>=0&&ny>=0&&nz>=0&&nx<R&&ny<R&&nz<R&&o[nx][ny][nz])continue;int[]q=new int[4];for(int k=0;k<4;k++){int X=x+corn[f][k*3],Y=y+corn[f][k*3+1],Z=z+corn[f][k*3+2];long key=((long)X<<42)|((long)Y<<21)|Z;Integer ix=map.get(key);if(ix==null){ix=v.size()/3;map.put(key,ix);v.add(-1+2f*X/R);v.add(-1+2f*Y/R);v.add(-1+2f*Z/R);}q[k]=ix;}id.add(q[0]);id.add(q[1]);id.add(q[2]);id.add(q[0]);id.add(q[2]);id.add(q[3]);}float[]va=new float[v.size()];for(int k=0;k<va.length;k++)va[k]=v.get(k);int[]ia=new int[id.size()];for(int k=0;k<ia.length;k++)ia[k]=id.get(k);return new Mesh(va,ia);}
 }
 static class MeshOps{static Mesh taubin(Mesh m,int it,float la,float mu){int n=m.v.length/3;ArrayList<HashSet<Integer>>adj=new ArrayList<>();for(int k=0;k<n;k++)adj.add(new HashSet<>());for(int k=0;k<m.i.length;k+=3){int a=m.i[k],b=m.i[k+1],c=m.i[k+2];adj.get(a).add(b);adj.get(a).add(c);adj.get(b).add(a);adj.get(b).add(c);adj.get(c).add(a);adj.get(c).add(b);}float[]v=m.v.clone();for(int p=0;p<it;p++){smooth(v,adj,la);smooth(v,adj,mu);}return new Mesh(v,m.i);}static void smooth(float[]v,ArrayList<HashSet<Integer>>a,float l){float[]q=v.clone();for(int i=0;i<a.size();i++){if(a.get(i).size()<3)continue;float x=0,y=0,z=0;for(int j:a.get(i)){x+=v[j*3];y+=v[j*3+1];z+=v[j*3+2];}float n=a.get(i).size();q[i*3]=v[i*3]+l*(x/n-v[i*3]);q[i*3+1]=v[i*3+1]+l*(y/n-v[i*3+1]);q[i*3+2]=v[i*3+2]+l*(z/n-v[i*3+2]);}System.arraycopy(q,0,v,0,v.length);}}

 OutputStream out(String n,String mime)throws Exception{ContentValues c=new ContentValues();c.put(MediaStore.Downloads.DISPLAY_NAME,n);c.put(MediaStore.Downloads.MIME_TYPE,mime);c.put(MediaStore.Downloads.RELATIVE_PATH,"Download/MG3DScanner");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,c);if(u==null)throw new IOException("Dosya oluşturulamadı");return getContentResolver().openOutputStream(u);}void saveAll(String b,Mesh m)throws Exception{saveObj(b+".obj",m);savePly(b+".ply",m);saveStl(b+".stl",m);saveGlb(b+".glb",m);}
 void saveObj(String n,Mesh m)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"model/obj")))){w.write("# MG3D PRO continuous surface\n");for(int k=0;k<m.v.length;k+=3)w.write(String.format(Locale.US,"v %.7f %.7f %.7f\n",m.v[k],m.v[k+1],m.v[k+2]));for(int k=0;k<m.i.length;k+=3)w.write("f "+(m.i[k]+1)+" "+(m.i[k+1]+1)+" "+(m.i[k+2]+1)+"\n");}}
 void savePly(String n,Mesh m)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"application/octet-stream")))){w.write("ply\nformat ascii 1.0\nelement vertex "+m.v.length/3+"\nproperty float x\nproperty float y\nproperty float z\nelement face "+m.i.length/3+"\nproperty list uchar int vertex_indices\nend_header\n");for(int k=0;k<m.v.length;k+=3)w.write(String.format(Locale.US,"%.7f %.7f %.7f\n",m.v[k],m.v[k+1],m.v[k+2]));for(int k=0;k<m.i.length;k+=3)w.write("3 "+m.i[k]+" "+m.i[k+1]+" "+m.i[k+2]+"\n");}}
 void saveStl(String n,Mesh m)throws Exception{try(Writer w=new BufferedWriter(new OutputStreamWriter(out(n,"model/stl")))){w.write("solid MG3D_PRO\n");for(int k=0;k<m.i.length;k+=3){int a=m.i[k]*3,b=m.i[k+1]*3,c=m.i[k+2]*3;float[]nn=norm(m.v,a,b,c);w.write(String.format(Locale.US,"facet normal %.6f %.6f %.6f\n outer loop\n",nn[0],nn[1],nn[2]));for(int j:new int[]{a,b,c})w.write(String.format(Locale.US,"  vertex %.7f %.7f %.7f\n",m.v[j],m.v[j+1],m.v[j+2]));w.write(" endloop\nendfacet\n");}w.write("endsolid MG3D_PRO\n");}}
 float[]norm(float[]v,int a,int b,int c){float ax=v[b]-v[a],ay=v[b+1]-v[a+1],az=v[b+2]-v[a+2],bx=v[c]-v[a],by=v[c+1]-v[a+1],bz=v[c+2]-v[a+2],x=ay*bz-az*by,y=az*bx-ax*bz,z=ax*by-ay*bx,l=(float)Math.sqrt(x*x+y*y+z*z);if(l<1e-8)l=1;return new float[]{x/l,y/l,z/l};}
 void saveGlb(String n,Mesh m)throws Exception{int vb=m.v.length*4,ib=m.i.length*4,vo=(vb+3)&~3,io=(ib+3)&~3;ByteBuffer bin=ByteBuffer.allocate(vo+io).order(ByteOrder.LITTLE_ENDIAN);for(float x:m.v)bin.putFloat(x);while(bin.position()<vo)bin.put((byte)0);int idxOff=bin.position();for(int x:m.i)bin.putInt(x);while(bin.position()<vo+io)bin.put((byte)0);String js="{\"asset\":{\"version\":\"2.0\"},\"scene\":0,\"scenes\":[{\"nodes\":[0]}],\"nodes\":[{\"mesh\":0}],\"meshes\":[{\"primitives\":[{\"attributes\":{\"POSITION\":0},\"indices\":1}]}],\"buffers\":[{\"byteLength\":"+(vo+io)+"}],\"bufferViews\":[{\"buffer\":0,\"byteOffset\":0,\"byteLength\":"+vb+",\"target\":34962},{\"buffer\":0,\"byteOffset\":"+idxOff+",\"byteLength\":"+ib+",\"target\":34963}],\"accessors\":[{\"bufferView\":0,\"componentType\":5126,\"count\":"+(m.v.length/3)+",\"type\":\"VEC3\"},{\"bufferView\":1,\"componentType\":5125,\"count\":"+m.i.length+",\"type\":\"SCALAR\"}]}";byte[]jb=js.getBytes(StandardCharsets.UTF_8);int jp=(4-jb.length%4)%4,total=12+8+jb.length+jp+8+bin.capacity();try(DataOutputStream o=new DataOutputStream(out(n,"model/gltf-binary"))){le(o,0x46546c67);le(o,2);le(o,total);le(o,jb.length+jp);le(o,0x4e4f534a);o.write(jb);for(int k=0;k<jp;k++)o.writeByte(32);le(o,bin.capacity());le(o,0x004e4942);o.write(bin.array());}}
 void le(DataOutputStream o,int x)throws Exception{o.writeByte(x&255);o.writeByte((x>>8)&255);o.writeByte((x>>16)&255);o.writeByte((x>>24)&255);}
}
