package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.media.MediaMetadataRetriever;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;
import org.opencv.android.OpenCVLoader;import org.opencv.android.Utils;import org.opencv.core.*;import org.opencv.features2d.*;import org.opencv.imgproc.Imgproc;

public class RobustPoseSurfaceActivityV25 extends RobustPoseSurfaceActivity{
 static final int MV=91,MI=92;
 TextView tv2(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(18,12,18,12);return v;}
 Button bt2(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(17);b.setMinHeight(62);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(18,22,18,24);r.setBackgroundColor(Color.rgb(10,12,15));TextView h=tv2("MG 3D • ROBUST POSE SURFACE v2.5",25);h.setGravity(Gravity.CENTER);r.addView(h);TextView d=tv2("Çoklu video/foto → robust pose → yetersizse otomatik approx surface → her durumda 3B çıktı",13);d.setTextColor(Color.LTGRAY);d.setGravity(Gravity.CENTER);r.addView(d);Button v=bt2("🎥 VİDEOLARI SEÇ • ÇOKLU");v.setOnClickListener(x->pick(true));r.addView(v);Button p=bt2("📷 FOTOĞRAFLARI SEÇ • ÇOKLU");p.setOnClickListener(x->pick(false));r.addView(p);Button c=bt2("🗑 TEMİZLE");c.setOnClickListener(x->{frames.clear();set("Hazır.");});r.addView(c);status=tv2("OpenCV başlatılıyor…",15);status.setBackgroundColor(Color.rgb(34,37,43));r.addView(status);Button go=bt2("🧊 3D SURFACE OLUŞTUR • ENGELLEME YOK");go.setOnClickListener(x->build());r.addView(go);TextView i=tv2("Yetersiz özellik/poz artık işlemi durdurmaz. Yeterli veri varsa Robust-Pose; değilse mevcut maskelerden yaklaşık visual-hull, o da mümkün değilse en iyi siluetten kapalı extrude surface oluşturulur. Sonuçta kalite uyarısı ayrıca gösterilir.",13);i.setTextColor(Color.LTGRAY);r.addView(i);setContentView(r);try{cv=OpenCVLoader.initLocal();}catch(Throwable t){cv=false;}set(cv?"Hazır • OpenCV aktif • çoklu video seçilebilir.":"OpenCV başlatılamadı.");}

 @Override void pick(boolean vid){videoMode=vid;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(vid?"video/*":"image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,vid?MV:MI);}

 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;new Thread(()->{try{frames.clear();videoMode=r==MV;int files=0;if(d.getClipData()!=null){for(int k=0;k<d.getClipData().getItemCount();k++){Uri u=d.getClipData().getItemAt(k).getUri();if(videoMode)video(u);else add(u);files++;}}else if(d.getData()!=null){if(videoMode)video(d.getData());else add(d.getData());files=1;}set(files+" "+(videoMode?"video":"foto")+" • "+frames.size()+" keyframe hazır. Veri az olsa da 3D üretim yapılacak.");}catch(Throwable e){fail("Girdi",e);}}).start();}

 @Override void video(Uri u)throws Exception{if(u==null)return;MediaMetadataRetriever m=new MediaMetadataRetriever();int before=frames.size();Bitmap best=null;double bestSharp=-1;try{m.setDataSource(this,u);String ds=m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);if(ds==null)return;long du=Long.parseLong(ds)*1000L;Bitmap last=null;for(int k=0;k<72;k++){Bitmap b=m.getFrameAtTime((long)((k+.5)*du/72),MediaMetadataRetriever.OPTION_CLOSEST);if(b==null)continue;b=scale(argb(b),800);double sh=sharp(b);if(sh>bestSharp){bestSharp=sh;best=b;}double ch=last==null?1:change(last,b);if(sh>9&&(last==null||ch>.025||frames.size()-before<4)){frames.add(b);last=b;}if(frames.size()-before>=18||frames.size()>=72)break;}}finally{try{m.release();}catch(Throwable ignored){}}if(frames.size()==before&&best!=null)frames.add(best);}

 @Override void build(){if(!cv){set("OpenCV aktif değil; bu motor için OpenCV gerekli.");return;}if(frames.isEmpty()){set("Önce en az 1 fotoğraf veya video seç.");return;}new Thread(()->{try{set("1/5 • Maskeler hazırlanıyor…");ArrayList<ViewData> all=new ArrayList<>();int emergency=0;for(Bitmap b:frames){ViewData v=null;try{v=looseView(b);}catch(Throwable ignored){}if(v==null){v=emergencyView(b);emergency++;}if(v!=null)all.add(v);}if(all.isEmpty())throw new IOException("Görüntü okunamadı");boolean approx=false;String reason="";ArrayList<ViewData> use=new ArrayList<>();int bgUsed=0,objUsed=0;if(all.size()>=3){set("2/5 • Robust pose deneniyor…");Mat cum=Mat.eye(3,3,CvType.CV_64F);all.get(0).R=cum.clone();use.add(all.get(0));for(int k=1;k<all.size();k++){PoseResult pr=Pose.solve(use.get(use.size()-1),all.get(k),videoMode);if(pr==null)continue;Mat nx=new Mat();Core.gemm(pr.R,cum,1,new Mat(),0,nx);cum.release();cum=nx;all.get(k).R=cum.clone();use.add(all.get(k));if(pr.background)bgUsed++;else objUsed++;}}if(use.size()<3){approx=true;reason="Poz/özellik yetersiz; yaklaşık açı dağılımı kullanıldı";use.clear();use.addAll(all);for(int k=0;k<use.size();k++)use.get(k).R=yaw(2.0*Math.PI*k/Math.max(1,use.size()));}set("3/5 • "+use.size()+" görünüş • "+(approx?"APPROX":"ROBUST")+" surface…");Mesh mesh;if(use.size()>=3)mesh=Hull.build(use,58);else mesh=extrude(bestMask(use),58);if(mesh==null||mesh.f.size()<120){approx=true;reason=(reason.length()>0?reason+" • ":"")+"ortak hacim zayıf; en iyi siluet extrude edildi";mesh=extrude(bestMask(use),58);}mesh=MeshOps.smooth(mesh,2,.14);set("4/5 • "+mesh.v.size()+" vertex • "+mesh.f.size()+" triangle • OBJ yazılıyor…");Uri u=save25(mesh);String q=approx?"DÜŞÜK/TAHMİNİ":"İYİ/ROBUST";set("TAMAMLANDI • v2.5\nKalite: "+q+(approx?"\nUyarı: "+reason:"")+"\n"+mesh.v.size()+" vertex • "+mesh.f.size()+" triangle\nKullanılan görünüş: "+use.size()+"/"+all.size()+" • BG:"+bgUsed+" OBJ:"+objUsed+"\nOBJ: Download/MG3DScanner\n"+u);}catch(Throwable e){fail("v2.5 Surface",e);}}).start();}

 ViewData looseView(Bitmap b){Mat rgba=new Mat(),rgb=new Mat(),g=new Mat();Utils.bitmapToMat(b,rgba);Imgproc.cvtColor(rgba,rgb,Imgproc.COLOR_RGBA2RGB);Mask mk=Mask.auto(rgb);if(mk==null){rgba.release();rgb.release();return null;}Imgproc.cvtColor(rgb,g,Imgproc.COLOR_RGB2GRAY);ORB orb=ORB.create(5000);MatOfKeyPoint ok=new MatOfKeyPoint();Mat od=new Mat();orb.detectAndCompute(g,mk.raw,ok,od);Mat dil=new Mat();Imgproc.dilate(mk.raw,dil,Imgproc.getStructuringElement(Imgproc.MORPH_ELLIPSE,new Size(25,25)));Mat bgm=new Mat();Core.bitwise_not(dil,bgm);MatOfKeyPoint bk=new MatOfKeyPoint();Mat bd=new Mat();orb.detectAndCompute(g,bgm,bk,bd);dil.release();bgm.release();rgba.release();rgb.release();ViewData v=new ViewData();v.gray=g;v.objKp=ok;v.objDesc=od;v.bgKp=bk;v.bgDesc=bd;v.mask=mk;return v;}

 ViewData emergencyView(Bitmap b){try{int w=Math.max(80,b.getWidth()/4),h=Math.max(80,b.getHeight()/4);Mat m=Mat.zeros(h,w,CvType.CV_8UC1);int mx=w/7,my=h/10;org.opencv.core.Rect r=new org.opencv.core.Rect(mx,my,w-2*mx,h-2*my);Imgproc.rectangle(m,new org.opencv.core.Point(r.x,r.y),new org.opencv.core.Point(r.x+r.width-1,r.y+r.height-1),new Scalar(255),-1);ViewData v=new ViewData();v.mask=new Mask(m,r);v.gray=Mat.zeros(h,w,CvType.CV_8UC1);v.objKp=new MatOfKeyPoint();v.bgKp=new MatOfKeyPoint();v.objDesc=new Mat();v.bgDesc=new Mat();return v;}catch(Throwable t){return null;}}

 Mat yaw(double a){Mat r=Mat.eye(3,3,CvType.CV_64F);double c=Math.cos(a),s=Math.sin(a);r.put(0,0,c);r.put(0,2,s);r.put(2,0,-s);r.put(2,2,c);return r;}

 Mask bestMask(ArrayList<ViewData> a){Mask b=a.get(0).mask;double ba=b.box.area();for(ViewData v:a){double ar=v.mask.box.area();if(ar>ba){ba=ar;b=v.mask;}}return b;}
 Mesh extrude(Mask m,int R){boolean[][][]o=new boolean[R][R][R];for(int x=0;x<R;x++){double X=-1+2.0*(x+.5)/R;for(int y=0;y<R;y++){double Y=-1+2.0*(y+.5)/R;if(!m.sample(X,Y))continue;for(int z=0;z<R;z++){double Z=-1+2.0*(z+.5)/R;if(Math.abs(Z)<.42)o[x][y][z]=true;}}}return Hull.surface(o,R);}

 Uri save25(Mesh m)throws Exception{String n="MG3D_SURFACE_ROBUST_v25_"+System.currentTimeMillis()+".obj";ContentValues cvv=new ContentValues();cvv.put(MediaStore.Downloads.DISPLAY_NAME,n);cvv.put(MediaStore.Downloads.MIME_TYPE,"text/plain");cvv.put(MediaStore.Downloads.RELATIVE_PATH,"Download/MG3DScanner");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,cvv);if(u==null)throw new IOException("OBJ oluşturulamadı");try(Writer w=new BufferedWriter(new OutputStreamWriter(getContentResolver().openOutputStream(u)))){w.write("# MG3D Robust Pose Surface v2.5\n");for(double[]p:m.v)w.write(String.format(Locale.US,"v %.6f %.6f %.6f\n",p[0],p[1],p[2]));for(int[]f:m.f)w.write("f "+(f[0]+1)+" "+(f[1]+1)+" "+(f[2]+1)+"\n");}return u;}
}
