package com.muhammetgecgil.mg3dscanner;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.*;import android.opengl.*;import android.provider.OpenableColumns;import android.database.Cursor;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.regex.*;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;

public class ViewerActivity extends Activity{
 static final int REQ=77; GLSurfaceView gl; ModelRenderer renderer; TextView info;
 @Override public void onCreate(Bundle b){super.onCreate(b);build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(10,11,14));root.setPadding(12,12,12,12);TextView title=new TextView(this);title.setText("MG 3D VIEWER");title.setTextColor(Color.WHITE);title.setTextSize(24);title.setGravity(Gravity.CENTER);root.addView(title);Button open=new Button(this);open.setText("📂 3D DOSYA AÇ");open.setAllCaps(false);open.setTextSize(17);open.setOnClickListener(v->pick());root.addView(open);info=new TextView(this);info.setText("OBJ • STL • PLY • XYZ • GLB • STEP • IGES\nDosya seç. Tek parmak: döndür • iki parmak: zoom");info.setTextColor(Color.LTGRAY);info.setTextSize(13);info.setPadding(12,8,12,8);root.addView(info);gl=new GLSurfaceView(this);gl.setEGLContextClientVersion(2);renderer=new ModelRenderer();gl.setRenderer(renderer);gl.setRenderMode(GLSurfaceView.RENDERMODE_CONTINUOUSLY);gl.setOnTouchListener(new TouchControl(renderer));root.addView(gl,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,REQ);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r!=REQ||c!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();new Thread(()->{try{String name=name(u);runOnUiThread(()->info.setText("Yükleniyor: "+name));Model m=ModelLoader.load(this,u,name);renderer.setModel(m);runOnUiThread(()->info.setText(name+"\n"+m.vertexCount()+" vertex • "+m.triangleCount()+" triangle\nTek parmak döndür • iki parmak zoom"));}catch(Exception e){runOnUiThread(()->info.setText("Dosya açılamadı: "+e.getClass().getSimpleName()+" • "+e.getMessage()));}}).start();}
 String name(Uri u){String n="model";Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){int ix=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&ix>=0)n=c.getString(ix);c.close();}return n;}
 @Override protected void onPause(){super.onPause();gl.onPause();}@Override protected void onResume(){super.onResume();if(gl!=null)gl.onResume();}

 static class Model{float[] v;int[] idx;Model(float[]a,int[]i){v=a;idx=i;}int vertexCount(){return v==null?0:v.length/3;}int triangleCount(){return idx==null?0:idx.length/3;}}
 static class ModelLoader{
  static Model load(Context c,Uri u,String name)throws Exception{String e=ext(name);byte[] data=readAll(c.getContentResolver().openInputStream(u),40*1024*1024);if(e.equals("obj"))return obj(new String(data,StandardCharsets.UTF_8));if(e.equals("ply"))return ply(data);if(e.equals("xyz")||e.equals("pts"))return xyz(new String(data,StandardCharsets.UTF_8));if(e.equals("stl"))return stl(data);if(e.equals("step")||e.equals("stp"))return step(new String(data,StandardCharsets.UTF_8));if(e.equals("igs")||e.equals("iges"))return iges(new String(data,StandardCharsets.UTF_8));if(e.equals("glb"))return glb(data);throw new IOException("Desteklenmeyen format: ."+e);}
  static String ext(String n){int i=n.lastIndexOf('.');return i<0?"":n.substring(i+1).toLowerCase(Locale.US);}
  static byte[] readAll(InputStream in,int max)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n,total=0;while((n=in.read(b))>0){total+=n;if(total>max)throw new IOException("Dosya çok büyük (>40 MB)");o.write(b,0,n);}in.close();return o.toByteArray();}
  static Model obj(String s){ArrayList<float[]>v=new ArrayList<>();ArrayList<Integer>id=new ArrayList<>();for(String l:s.split("\\r?\\n")){l=l.trim();if(l.startsWith("v ")){String[]p=l.split("\\s+");if(p.length>=4)v.add(new float[]{f(p[1]),f(p[2]),f(p[3])});}else if(l.startsWith("f ")){String[]p=l.substring(2).trim().split("\\s+");if(p.length>=3){int a=face(p[0],v.size()),b=face(p[1],v.size());for(int k=2;k<p.length;k++){int c=face(p[k],v.size());id.add(a);id.add(b);id.add(c);b=c;}}}}return build(v,id);}
  static int face(String x,int n){String q=x.split("/")[0];int i=Integer.parseInt(q);return i<0?n+i:i-1;}
  static Model xyz(String s){ArrayList<float[]>v=new ArrayList<>();for(String l:s.split("\\r?\\n")){String[]p=l.trim().split("[ ,;\\t]+");if(p.length>=3)try{v.add(new float[]{f(p[0]),f(p[1]),f(p[2])});}catch(Exception z){}}return build(v,new ArrayList<>());}
  static Model ply(byte[]d){String s=new String(d,StandardCharsets.UTF_8);int h=s.indexOf("end_header");if(h<0)return xyz(s);int end=s.indexOf('\n',h);String head=s.substring(0,end);if(!head.contains("format ascii"))throw new IllegalArgumentException("Şimdilik binary PLY değil, ASCII PLY destekleniyor");int vc=0,fc=0;for(String l:head.split("\\r?\\n")){if(l.startsWith("element vertex"))vc=Integer.parseInt(l.replace("element vertex","").trim());if(l.startsWith("element face"))fc=Integer.parseInt(l.replace("element face","").trim());}String[]lines=s.substring(end+1).split("\\r?\\n");ArrayList<float[]>v=new ArrayList<>();ArrayList<Integer>id=new ArrayList<>();int pos=0;for(int i=0;i<vc&&pos<lines.length;i++,pos++){String[]p=lines[pos].trim().split("\\s+");if(p.length>=3)v.add(new float[]{f(p[0]),f(p[1]),f(p[2])});}for(int i=0;i<fc&&pos<lines.length;i++,pos++){String[]p=lines[pos].trim().split("\\s+");if(p.length>=4){int n=Integer.parseInt(p[0]);int a=Integer.parseInt(p[1]),b=Integer.parseInt(p[2]);for(int k=3;k<=n&&k<p.length;k++){int c=Integer.parseInt(p[k]);id.add(a);id.add(b);id.add(c);b=c;}}}return build(v,id);}
  static Model stl(byte[]d){if(d.length>=84){ByteBuffer b=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);b.position(80);long n=Integer.toUnsignedLong(b.getInt());if(84+n*50L==d.length){ArrayList<float[]>v=new ArrayList<>();ArrayList<Integer>id=new ArrayList<>();for(int i=0;i<n;i++){b.position(b.position()+12);for(int k=0;k<3;k++){v.add(new float[]{b.getFloat(),b.getFloat(),b.getFloat()});id.add(v.size()-1);}b.position(b.position()+2);}return build(v,id);}}String s=new String(d,StandardCharsets.UTF_8);ArrayList<float[]>v=new ArrayList<>();ArrayList<Integer>id=new ArrayList<>();Matcher m=Pattern.compile("vertex\\s+([-+0-9.eE]+)\\s+([-+0-9.eE]+)\\s+([-+0-9.eE]+)").matcher(s);while(m.find()){v.add(new float[]{f(m.group(1)),f(m.group(2)),f(m.group(3))});id.add(v.size()-1);}return build(v,id);}
  static Model step(String s){ArrayList<float[]>v=new ArrayList<>();Matcher m=Pattern.compile("CARTESIAN_POINT\\s*\\([^,]*,\\s*\\(([-+0-9.eE]+),\\s*([-+0-9.eE]+),\\s*([-+0-9.eE]+)\\)\\)",Pattern.CASE_INSENSITIVE).matcher(s);while(m.find())v.add(new float[]{f(m.group(1)),f(m.group(2)),f(m.group(3))});return build(v,new ArrayList<>());}
  static Model iges(String s){ArrayList<float[]>v=new ArrayList<>();Matcher m=Pattern.compile("116,\\s*([-+0-9.eE]+),\\s*([-+0-9.eE]+),\\s*([-+0-9.eE]+)").matcher(s);while(m.find())v.add(new float[]{f(m.group(1)),f(m.group(2)),f(m.group(3))});return build(v,new ArrayList<>());}
  static Model glb(byte[]d)throws Exception{if(d.length<20)throw new IOException("GLB bozuk");ByteBuffer b=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);if(b.getInt()!=0x46546c67)throw new IOException("GLB magic hatalı");b.getInt();b.getInt();int jl=b.getInt();int jt=b.getInt();if(jt!=0x4e4f534a)throw new IOException("GLB JSON yok");byte[]j=new byte[jl];b.get(j);String js=new String(j,StandardCharsets.UTF_8).trim();int count=intField(js,"\"count\"\\s*:\\s*(\\d+)");int offset=0;Matcher mo=Pattern.compile("\"byteOffset\"\\s*:\\s*(\\d+)").matcher(js);if(mo.find())offset=Integer.parseInt(mo.group(1));int bl=b.getInt();int bt=b.getInt();if(bt!=0x004e4942)throw new IOException("GLB BIN yok");int base=b.position()+offset;if(count<=0||base+count*12>d.length)throw new IOException("GLB POSITION okunamadı");float[]v=new float[count*3];ByteBuffer q=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);q.position(base);for(int i=0;i<v.length;i++)v[i]=q.getFloat();return new Model(normalize(v),null);}
  static int intField(String s,String p){Matcher m=Pattern.compile(p).matcher(s);return m.find()?Integer.parseInt(m.group(1)):0;}
  static float f(String x){return Float.parseFloat(x.replace("D","E").replace("d","e"));}
  static Model build(ArrayList<float[]>a,ArrayList<Integer>ids){float[]v=new float[a.size()*3];for(int i=0;i<a.size();i++){v[i*3]=a.get(i)[0];v[i*3+1]=a.get(i)[1];v[i*3+2]=a.get(i)[2];}v=normalize(v);int[]ii=null;if(ids!=null&&!ids.isEmpty()){ii=new int[ids.size()];for(int i=0;i<ii.length;i++)ii[i]=ids.get(i);}return new Model(v,ii);}
  static float[] normalize(float[]v){if(v.length<3)return v;float minx=Float.MAX_VALUE,miny=minx,minz=minx,maxx=-minx,maxy=-minx,maxz=-minx;for(int i=0;i<v.length;i+=3){minx=Math.min(minx,v[i]);miny=Math.min(miny,v[i+1]);minz=Math.min(minz,v[i+2]);maxx=Math.max(maxx,v[i]);maxy=Math.max(maxy,v[i+1]);maxz=Math.max(maxz,v[i+2]);}float cx=(minx+maxx)/2,cy=(miny+maxy)/2,cz=(minz+maxz)/2,span=Math.max(maxx-minx,Math.max(maxy-miny,maxz-minz));if(span<1e-9)span=1;float sc=2.6f/span;for(int i=0;i<v.length;i+=3){v[i]=(v[i]-cx)*sc;v[i+1]=(v[i+1]-cy)*sc;v[i+2]=(v[i+2]-cz)*sc;}return v;}
 }

 static class ModelRenderer implements GLSurfaceView.Renderer{volatile Model model=new Model(new float[0],null);volatile float rx=20,ry=-25,zoom=1f;int prog,aPos,uMvp,uColor;FloatBuffer vb;IntBuffer ib;int count,icount;
  void setModel(Model m){model=m;vb=null;ib=null;}
  public void onSurfaceCreated(GL10 g,EGLConfig c){GLES20.glClearColor(.035f,.04f,.055f,1);GLES20.glEnable(GLES20.GL_DEPTH_TEST);String vs="attribute vec3 a;uniform mat4 m;void main(){gl_Position=m*vec4(a,1.0);gl_PointSize=4.0;}";String fs="precision mediump float;uniform vec4 c;void main(){gl_FragColor=c;}";prog=link(vs,fs);aPos=GLES20.glGetAttribLocation(prog,"a");uMvp=GLES20.glGetUniformLocation(prog,"m");uColor=GLES20.glGetUniformLocation(prog,"c");}
  public void onSurfaceChanged(GL10 g,int w,int h){GLES20.glViewport(0,0,w,h);}
  public void onDrawFrame(GL10 g){GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);Model m=model;if(m.v.length==0)return;if(vb==null){vb=ByteBuffer.allocateDirect(m.v.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();vb.put(m.v).position(0);count=m.v.length/3;if(m.idx!=null){ib=ByteBuffer.allocateDirect(m.idx.length*4).order(ByteOrder.nativeOrder()).asIntBuffer();ib.put(m.idx).position(0);icount=m.idx.length;}}float[]pr=new float[16],mv=new float[16],tmp=new float[16],mvp=new float[16];Matrix.perspectiveM(pr,0,45,1f,0.1f,100);Matrix.setIdentityM(mv,0);Matrix.translateM(mv,0,0,0,-4f/Math.max(.25f,zoom));Matrix.rotateM(mv,0,rx,1,0,0);Matrix.rotateM(mv,0,ry,0,1,0);Matrix.multiplyMM(mvp,0,pr,0,mv,0);GLES20.glUseProgram(prog);GLES20.glUniformMatrix4fv(uMvp,1,false,mvp,0);GLES20.glEnableVertexAttribArray(aPos);GLES20.glVertexAttribPointer(aPos,3,GLES20.GL_FLOAT,false,12,vb);if(ib!=null&&icount>=3){GLES20.glUniform4f(uColor,.25f,.72f,.95f,1);GLES20.glDrawElements(GLES20.GL_TRIANGLES,icount,GLES20.GL_UNSIGNED_INT,ib);GLES20.glUniform4f(uColor,1,1,1,1);GLES20.glDrawArrays(GLES20.GL_POINTS,0,count);}else{GLES20.glUniform4f(uColor,.35f,.85f,1,1);GLES20.glDrawArrays(GLES20.GL_POINTS,0,count);}GLES20.glDisableVertexAttribArray(aPos);}
  int shader(int t,String s){int x=GLES20.glCreateShader(t);GLES20.glShaderSource(x,s);GLES20.glCompileShader(x);return x;}int link(String v,String f){int p=GLES20.glCreateProgram();GLES20.glAttachShader(p,shader(GLES20.GL_VERTEX_SHADER,v));GLES20.glAttachShader(p,shader(GLES20.GL_FRAGMENT_SHADER,f));GLES20.glLinkProgram(p);return p;}
 }
 static class TouchControl implements View.OnTouchListener{ModelRenderer r;float lx,ly,ld;TouchControl(ModelRenderer x){r=x;}public boolean onTouch(View v,android.view.MotionEvent e){if(e.getPointerCount()==1){float x=e.getX(),y=e.getY();if(e.getAction()==MotionEvent.ACTION_MOVE){r.ry+=(x-lx)*.35f;r.rx+=(y-ly)*.35f;}lx=x;ly=y;}else if(e.getPointerCount()>=2){float dx=e.getX(0)-e.getX(1),dy=e.getY(0)-e.getY(1),d=(float)Math.hypot(dx,dy);if(ld>0&&e.getAction()==MotionEvent.ACTION_MOVE)r.zoom=Math.max(.25f,Math.min(6f,r.zoom*d/ld));ld=d;}if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL)ld=0;return true;}}
}
