plugins { id 'com.android.application' }

android {
    namespace 'com.mg.fixturecockpitsim'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mg.fixturecockpitsim'
        minSdk 26
        targetSdk 35
        versionCode 15
        versionName '15.0'
    }

    packagingOptions {
        jniLibs { useLegacyPackaging = false }
    }
}

dependencies {
    implementation 'com.google.android.filament:filament-android:1.72.0'
    implementation 'com.google.android.filament:gltfio-android:1.72.0'
    implementation 'com.google.android.filament:filament-utils-android:1.72.0'
}
