package com.mg.drawing2cad;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.graphics.pdf.PdfRenderer;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;

import java.io.*;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.*;

public class MainActivity extends Activity {
  static final int PICK=100,SAVE_PDF=101,SAVE_DXF=102,SAVE_STL=103;
  static final int M23=0,M32=1;
  final int BG=Color.rgb(3,12,22),PANEL=Color.rgb(6,23,39),PANEL2=Color.rgb(9,34,57),TEXT=Color.rgb(234,244,252),MUTED=Color.rgb(146,170,190),CYAN=Color.rgb(55,205,255),GREEN=Color.rgb(65,220,120);
  int mode=M23; Bitmap source; boolean[][][] voxels; ArrayList<Tri> mesh=new ArrayList<>(); CadView cad; TextView status,fileInfo,modeInfo;
  Uri archiveUri; ArrayList<String> archiveEntries=new ArrayList<>(); boolean showHidden=true,showCenter=true,showDims=true,showSection=true;

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);buildUi();}

  void buildUi(){
    LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
    LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(10),dp(6),dp(8),dp(6));h.setBackgroundColor(PANEL);
    LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.addView(txt("MG CAD Studio",20,CYAN,true));titles.addView(txt("ENGINEERING DRAWING • v2.1",9,MUTED,true));h.addView(titles,new LinearLayout.LayoutParams(dp(210),-2));
    Button b23=btn("2D → 3D"),b32=btn("3D → 2D");h.addView(b23);h.addView(b32);modeInfo=txt(" TEKNİK RESİM → 3D",11,GREEN,true);h.addView(modeInfo,new LinearLayout.LayoutParams(0,-2,1));
    Button open=btn("DOSYA AÇ"),create=btn("OLUŞTUR"),pdf=btn("PDF"),dxf=btn("DXF"),stl=btn("STL");for(Button x:new Button[]{open,create,pdf,dxf,stl})h.addView(x);root.addView(h,new LinearLayout.LayoutParams(-1,dp(58)));
    HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(8),dp(4),dp(8),dp(4));bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(Color.rgb(5,18,31));
    Button iso=sbtn("ISO"),front=sbtn("ÖN"),top=sbtn("ÜST"),right=sbtn("SAĞ"),left=sbtn("SOL"),bottom=sbtn("ALT"),fit=sbtn("SIĞDIR"),hidden=sbtn("GİZLİ"),center=sbtn("EKSEN"),dims=sbtn("ÖLÇÜ"),section=sbtn("KESİT A-A");
    for(Button x:new Button[]{iso,front,top,right,left,bottom,fit,hidden,center,dims,section})bar.addView(x);fileInfo=txt("Dosya seçilmedi",10,MUTED,false);bar.addView(fileInfo,new LinearLayout.LayoutParams(dp(360),-2));hs.addView(bar);root.addView(hs,new LinearLayout.LayoutParams(-1,dp(48)));
    cad=new CadView(this);root.addView(cad,new LinearLayout.LayoutParams(-1,0,1));status=txt("2D→3D: çok görünüşlü teknik resim. 3D→2D: STL/OBJ'den mühendislik teknik resmi.",10,MUTED,false);status.setPadding(dp(12),dp(8),dp(12),dp(8));status.setBackgroundColor(PANEL);root.addView(status,new LinearLayout.LayoutParams(-1,dp(40)));setContentView(root);
    b23.setOnClickListener(v->setMode(M23));b32.setOnClickListener(v->setMode(M32));open.setOnClickListener(v->pick());create.setOnClickListener(v->createAction());pdf.setOnClickListener(v->savePdf());dxf.setOnClickListener(v->saveDxf());stl.setOnClickListener(v->saveStl());
    iso.setOnClickListener(v->{cad.viewMode=0;cad.invalidate();});front.setOnClickListener(v->{cad.viewMode=1;cad.invalidate();});top.setOnClickListener(v->{cad.viewMode=2;cad.invalidate();});right.setOnClickListener(v->{cad.viewMode=3;cad.invalidate();});left.setOnClickListener(v->{cad.viewMode=4;cad.invalidate();});bottom.setOnClickListener(v->{cad.viewMode=5;cad.invalidate();});fit.setOnClickListener(v->cad.fit());
    hidden.setOnClickListener(v->{showHidden=!showHidden;status.setText("Gizli çizgiler: "+(showHidden?"AÇIK":"KAPALI"));});center.setOnClickListener(v->{showCenter=!showCenter;status.setText("Merkez çizgileri: "+(showCenter?"AÇIK":"KAPALI"));});dims.setOnClickListener(v->{showDims=!showDims;status.setText("Otomatik ölçüler: "+(showDims?"AÇIK":"KAPALI"));});section.setOnClickListener(v->{showSection=!showSection;status.setText("A-A kesiti: "+(showSection?"AÇIK":"KAPALI"));});
  }

  void setMode(int m){mode=m;modeInfo.setText(m==M23?" TEKNİK RESİM → 3D":" 3D MODEL → TEKNİK RESİM");status.setText(m==M23?"PDF/PNG/JPG/ZIP teknik resmi aç; OLUŞTUR'a bas.":"STL/OBJ aç; OLUŞTUR ile teknik resim önizlemesi, PDF/DXF ile çıktı al.");}
  TextView txt(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(10);b.setTextColor(TEXT);b.setMinHeight(0);b.setPadding(dp(9),0,dp(9),0);round(b,PANEL2,Color.rgb(24,78,115),8);return b;}
  Button sbtn(String s){Button b=btn(s);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(38));lp.setMargins(dp(3),0,dp(3),0);b.setLayoutParams(lp);return b;}
  void round(View v,int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(1,stroke);v.setBackground(g);}int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}

  void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");if(mode==M23)i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/*","application/pdf","application/zip","application/x-zip-compressed"});else i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"model/stl","model/obj","application/octet-stream","text/plain"});startActivityForResult(i,PICK);}
  @Override protected void onActivityResult(int req,int res,Intent d){super.onActivityResult(req,res,d);if(res!=RESULT_OK||d==null||d.getData()==null)return;try{Uri u=d.getData();if(req==PICK){if(mode==M23)load2d(u);else load3d(u);}else if(req==SAVE_PDF){try(OutputStream o=getContentResolver().openOutputStream(u)){writePdf(o);}status.setText("✓ Mühendislik teknik resmi PDF kaydedildi.");}else if(req==SAVE_DXF){try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(buildDxf().getBytes(StandardCharsets.UTF_8));}status.setText("✓ DXF kaydedildi.");}else if(req==SAVE_STL){try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(buildStl().getBytes(StandardCharsets.US_ASCII));}status.setText("✓ STL kaydedildi.");}}catch(Exception e){status.setText("Hata: "+e.getMessage());}}

  void load2d(Uri u)throws Exception{String n=fileName(u),l=n.toLowerCase(Locale.ROOT);fileInfo.setText(n);if(l.endsWith(".zip")||l.endsWith(".cbz")){archiveUri=u;listArchive(u);return;}if(l.endsWith(".pdf"))source=renderPdf(u);else try(InputStream in=getContentResolver().openInputStream(u)){source=BitmapFactory.decodeStream(in);}if(source==null)throw new IOException("2D dosya okunamadı");mesh.clear();voxels=null;cad.setBitmap(source);status.setText("✓ Teknik resim yüklendi. Ön/üst/sağ görünüşler analiz için hazır.");}
  void listArchive(Uri u)throws Exception{archiveEntries.clear();try(InputStream in=getContentResolver().openInputStream(u);ZipInputStream z=new ZipInputStream(new BufferedInputStream(in))){ZipEntry e;while((e=z.getNextEntry())!=null){String l=e.getName().toLowerCase(Locale.ROOT);if(!e.isDirectory()&&(l.endsWith(".pdf")||l.endsWith(".png")||l.endsWith(".jpg")||l.endsWith(".jpeg")||l.endsWith(".webp")))archiveEntries.add(e.getName());}}if(archiveEntries.isEmpty())throw new IOException("ZIP içinde teknik resim yok");String[] a=archiveEntries.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Teknik resim seç").setItems(a,(q,w)->{try{loadArchive(a[w]);}catch(Exception ex){status.setText("ZIP: "+ex.getMessage());}}).show();}
  void loadArchive(String wanted)throws Exception{File f=new File(getCacheDir(),"mg21_"+Math.abs(wanted.hashCode())+(wanted.toLowerCase(Locale.ROOT).endsWith(".pdf")?".pdf":".img"));boolean ok=false;try(InputStream in=getContentResolver().openInputStream(archiveUri);ZipInputStream z=new ZipInputStream(new BufferedInputStream(in))){ZipEntry e;while((e=z.getNextEntry())!=null)if(e.getName().equals(wanted)){try(FileOutputStream o=new FileOutputStream(f)){byte[] b=new byte[16384];int n;long t=0;while((n=z.read(b))>0){t+=n;if(t>100L*1024*1024)throw new IOException("Dosya çok büyük");o.write(b,0,n);}}ok=true;break;}}if(!ok)throw new IOException("Girdi bulunamadı");if(wanted.toLowerCase(Locale.ROOT).endsWith(".pdf"))source=renderPdfFile(f);else try(InputStream in=new FileInputStream(f)){source=BitmapFactory.decodeStream(in);}mesh.clear();voxels=null;cad.setBitmap(source);fileInfo.setText(wanted);}
  Bitmap renderPdf(Uri u)throws Exception{File f=new File(getCacheDir(),"src21.pdf");try(InputStream in=getContentResolver().openInputStream(u);FileOutputStream o=new FileOutputStream(f)){byte[] b=new byte[16384];int n;while((n=in.read(b))>0)o.write(b,0,n);}return renderPdfFile(f);}
  Bitmap renderPdfFile(File f)throws Exception{ParcelFileDescriptor pfd=ParcelFileDescriptor.open(f,ParcelFileDescriptor.MODE_READ_ONLY);PdfRenderer r=new PdfRenderer(pfd);PdfRenderer.Page p=r.openPage(0);float k=Math.min(3f,2400f/Math.max(p.getWidth(),p.getHeight()));Bitmap b=Bitmap.createBitmap((int)(p.getWidth()*k),(int)(p.getHeight()*k),Bitmap.Config.ARGB_8888);b.eraseColor(Color.WHITE);p.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);p.close();r.close();pfd.close();return b;}

  void load3d(Uri u)throws Exception{String n=fileName(u),l=n.toLowerCase(Locale.ROOT);byte[] data=readAll(u,160L*1024*1024);mesh=l.endsWith(".obj")?parseObj(new String(data,StandardCharsets.UTF_8)):parseStl(data);if(mesh.isEmpty())throw new IOException("3D geometri okunamadı");source=null;voxels=null;cad.setMesh(mesh);fileInfo.setText(n+" • "+mesh.size()+" üçgen");float[] b=bounds(mesh);status.setText(String.format(Locale.US,"✓ Model %.2f × %.2f × %.2f • teknik resim üretmeye hazır",b[3]-b[0],b[4]-b[1],b[5]-b[2]));}
  byte[] readAll(Uri u,long max)throws Exception{try(InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[] b=new byte[32768];int n;long t=0;while((n=in.read(b))>0){t+=n;if(t>max)throw new IOException("Dosya sınırı aşıldı");o.write(b,0,n);}return o.toByteArray();}}

  static class Vec{float x,y,z;Vec(float X,float Y,float Z){x=X;y=Y;z=Z;}}static class Tri{Vec a,b,c;Tri(Vec A,Vec B,Vec C){a=A;b=B;c=C;}}
  ArrayList<Tri> parseObj(String s){ArrayList<Vec> vs=new ArrayList<>();ArrayList<Tri> ts=new ArrayList<>();for(String ln:s.split("\\r?\\n")){ln=ln.trim();try{if(ln.startsWith("v ")){String[] q=ln.split("\\s+");vs.add(new Vec(Float.parseFloat(q[1]),Float.parseFloat(q[2]),Float.parseFloat(q[3])));}else if(ln.startsWith("f ")){String[] q=ln.split("\\s+");int[] id=new int[q.length-1];for(int i=1;i<q.length;i++){int k=Integer.parseInt(q[i].split("/")[0]);id[i-1]=k<0?vs.size()+k:k-1;}for(int i=1;i<id.length-1;i++)ts.add(new Tri(vs.get(id[0]),vs.get(id[i]),vs.get(id[i+1])));}}catch(Exception ignored){}}return ts;}
  ArrayList<Tri> parseStl(byte[] d)throws Exception{ArrayList<Tri> t=new ArrayList<>();if(d.length>=84){int n=ByteBuffer.wrap(d,80,4).order(ByteOrder.LITTLE_ENDIAN).getInt();long exp=84L+50L*n;if(n>0&&n<5000000&&exp<=d.length){ByteBuffer b=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);b.position(84);for(int i=0;i<n;i++){b.position(b.position()+12);Vec a=new Vec(b.getFloat(),b.getFloat(),b.getFloat()),c=new Vec(b.getFloat(),b.getFloat(),b.getFloat()),e=new Vec(b.getFloat(),b.getFloat(),b.getFloat());t.add(new Tri(a,c,e));b.getShort();}return t;}}String s=new String(d,StandardCharsets.US_ASCII);ArrayList<Vec> v=new ArrayList<>();for(String ln:s.split("\\r?\\n")){ln=ln.trim();if(ln.startsWith("vertex ")){String[] q=ln.split("\\s+");if(q.length>=4){v.add(new Vec(Float.parseFloat(q[1]),Float.parseFloat(q[2]),Float.parseFloat(q[3])));if(v.size()==3){t.add(new Tri(v.get(0),v.get(1),v.get(2)));v.clear();}}}}return t;}

  void createAction(){if(mode==M32){if(mesh.isEmpty()){status.setText("Önce STL/OBJ aç.");return;}cad.techPreview=true;cad.invalidate();status.setText("✓ Teknik resim önizlemesi: ÖN + ÜST + SAĞ + ISO + A-A + ölçüler.");return;}if(source==null){status.setText("Önce teknik resim aç.");return;}status.setText("Görünüşler ayrılıyor • silüetler eşleştiriliyor • 3D hacim hesaplanıyor...");new Thread(()->{try{boolean[][][] v=reconstruct(source);voxels=v;mesh.clear();runOnUiThread(()->{cad.setVoxels(v);status.setText("✓ 2D → 3D HAZIR • "+count3(v)+" hücre");});}catch(Exception e){runOnUiThread(()->status.setText("Rekonstrüksiyon: "+e.getMessage()));}}).start();}
  boolean[][][] reconstruct(Bitmap bm)throws Exception{int W=bm.getWidth(),H=bm.getHeight(),topCut=(int)(H*.07f),bottomCut=(int)(H*.07f),usable=H-topCut-bottomCut,midX=W/2,midY=topCut+usable/2;Bitmap f=Bitmap.createBitmap(bm,0,topCut,midX,usable/2),r=Bitmap.createBitmap(bm,midX,topCut,W-midX,usable/2),t=Bitmap.createBitmap(bm,0,midY,midX,H-bottomCut-midY);boolean[][] fm=mask(f,88),rm=mask(r,72),tm=mask(t,88);if(fm==null||rm==null||tm==null)throw new IOException("Ön/üst/sağ görünüş bulunamadı");int nx=88,nz=fm.length,ny=tm.length;boolean[][][] v=new boolean[nx][ny][nz];for(int x=0;x<nx;x++)for(int y=0;y<ny;y++)for(int z=0;z<nz;z++){int rx=Math.min(rm[0].length-1,(int)(y*(rm[0].length/(float)ny)));int rz=Math.min(rm.length-1,(int)((nz-1-z)*(rm.length/(float)nz)));v[x][y][z]=fm[nz-1-z][x]&&tm[ny-1-y][x]&&rm[rz][rx];}return v;}
  boolean[][] mask(Bitmap b,int outW){int w=b.getWidth(),h=b.getHeight(),minX=w,minY=h,maxX=-1,maxY=-1;int st=Math.max(1,Math.max(w,h)/1200);for(int y=0;y<h;y+=st)for(int x=0;x<w;x+=st)if(gray(b.getPixel(x,y))<90){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}if(maxX<0)return null;Bitmap c=Bitmap.createBitmap(b,minX,minY,maxX-minX+1,maxY-minY+1);int outH=Math.max(20,Math.min(80,Math.round(outW*c.getHeight()/(float)c.getWidth())));Bitmap s=Bitmap.createScaledBitmap(c,outW,outH,true);boolean[][] wall=new boolean[outH][outW];for(int y=0;y<outH;y++)for(int x=0;x<outW;x++)wall[y][x]=gray(s.getPixel(x,y))<115;boolean[][] outside=new boolean[outH][outW];ArrayDeque<int[]> q=new ArrayDeque<>();for(int x=0;x<outW;x++){seed(x,0,wall,outside,q);seed(x,outH-1,wall,outside,q);}for(int y=0;y<outH;y++){seed(0,y,wall,outside,q);seed(outW-1,y,wall,outside,q);}int[][] d={{1,0},{-1,0},{0,1},{0,-1}};while(!q.isEmpty()){int[] p=q.removeFirst();for(int[] dd:d){int x=p[0]+dd[0],y=p[1]+dd[1];if(x>=0&&x<outW&&y>=0&&y<outH&&!wall[y][x]&&!outside[y][x]){outside[y][x]=true;q.add(new int[]{x,y});}}}boolean[][] sol=new boolean[outH][outW];for(int y=0;y<outH;y++)for(int x=0;x<outW;x++)sol[y][x]=wall[y][x]||!outside[y][x];return sol;}
  void seed(int x,int y,boolean[][] w,boolean[][] o,ArrayDeque<int[]> q){if(!w[y][x]&&!o[y][x]){o[y][x]=true;q.add(new int[]{x,y});}}int gray(int c){return (Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;}int count3(boolean[][][] a){int n=0;if(a!=null)for(boolean[][] x:a)for(boolean[] y:x)for(boolean z:y)if(z)n++;return n;}

  void savePdf(){if(mesh.isEmpty()){status.setText("PDF teknik resim için önce 3D model aç.");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,"MG_CAD_Engineering_Drawing_v21.pdf");startActivityForResult(i,SAVE_PDF);}
  void saveDxf(){if(mesh.isEmpty()){status.setText("DXF için önce 3D model aç.");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/dxf");i.putExtra(Intent.EXTRA_TITLE,"MG_CAD_Engineering_Drawing_v21.dxf");startActivityForResult(i,SAVE_DXF);}
  void saveStl(){if(voxels==null&&mesh.isEmpty()){status.setText("STL için önce model oluştur/aç.");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("model/stl");i.putExtra(Intent.EXTRA_TITLE,"MG_CAD_Model_v21.stl");startActivityForResult(i,SAVE_STL);}

  void writePdf(OutputStream o)throws Exception{PdfDocument doc=new PdfDocument();PdfDocument.PageInfo pi=new PdfDocument.PageInfo.Builder(1191,842,1).create();PdfDocument.Page p=doc.startPage(pi);drawSheet(p.getCanvas(),1191,842);doc.finishPage(p);doc.writeTo(o);doc.close();}
  void drawSheet(Canvas c,int W,int H){c.drawColor(Color.WHITE);Paint p=new Paint(3);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.BLACK);c.drawRect(25,25,W-25,H-25,p);float[] b=bounds(mesh);drawProjection(c,p,mesh,90,110,420,260,0,b,"FRONT");drawProjection(c,p,mesh,650,110,420,260,1,b,"RIGHT");drawProjection(c,p,mesh,90,430,420,260,2,b,"TOP");drawIsoSheet(c,p,mesh,650,430,420,260,b);if(showSection)drawSectionAA(c,p,mesh,530,430,95,260,b);drawTitleBlock(c,p,W,H,b);}
  void drawProjection(Canvas c,Paint p,ArrayList<Tri> m,float ox,float oy,float w,float h,int plane,float[] b,String name){p.setStyle(Paint.Style.STROKE);p.setColor(Color.BLACK);p.setStrokeWidth(1.4f);for(Tri t:m){Vec[] v={t.a,t.b,t.c};for(int i=0;i<3;i++){PointF a=proj(v[i],plane,ox,oy,w,h,b),d=proj(v[(i+1)%3],plane,ox,oy,w,h,b);c.drawLine(a.x,a.y,d.x,d.y,p);}}p.setStyle(Paint.Style.FILL);p.setTextSize(18);c.drawText(name,ox,oy+h+24,p);if(showCenter){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(Color.GRAY);p.setPathEffect(new DashPathEffect(new float[]{10,5,2,5},0));c.drawLine(ox+w/2,oy,ox+w/2,oy+h,p);c.drawLine(ox,oy+h/2,ox+w,oy+h/2,p);p.setPathEffect(null);}if(showHidden){p.setColor(Color.LTGRAY);p.setPathEffect(new DashPathEffect(new float[]{8,6},0));c.drawRect(ox+8,oy+8,ox+w-8,oy+h-8,p);p.setPathEffect(null);}if(showDims){p.setColor(Color.DKGRAY);drawDimH(c,p,ox,ox+w,oy+h+42,String.format(Locale.US,"%.2f",plane==1?b[4]-b[1]:b[3]-b[0]));drawDimV(c,p,ox-42,oy,oy+h,String.format(Locale.US,"%.2f",plane==2?b[4]-b[1]:b[5]-b[2]));}}
  PointF proj(Vec v,int plane,float ox,float oy,float w,float h,float[] b){float u,vv,umin,umax,vmin,vmax;if(plane==0){u=v.x;vv=v.z;umin=b[0];umax=b[3];vmin=b[2];vmax=b[5];}else if(plane==1){u=v.y;vv=v.z;umin=b[1];umax=b[4];vmin=b[2];vmax=b[5];}else{u=v.x;vv=v.y;umin=b[0];umax=b[3];vmin=b[1];vmax=b[4];}float x=ox+15+(u-umin)/Math.max(.0001f,umax-umin)*(w-30),y=oy+h-15-(vv-vmin)/Math.max(.0001f,vmax-vmin)*(h-30);return new PointF(x,y);}
  void drawIsoSheet(Canvas c,Paint p,ArrayList<Tri> m,float ox,float oy,float w,float h,float[] b){p.setColor(Color.BLACK);p.setStrokeWidth(1.1f);p.setStyle(Paint.Style.STROKE);float cx=(b[0]+b[3])/2,cy=(b[1]+b[4])/2,cz=(b[2]+b[5])/2,span=Math.max(b[3]-b[0],Math.max(b[4]-b[1],b[5]-b[2]));float s=Math.min(w,h)/(span*2.2f+1);for(Tri t:m){Vec[] q={t.a,t.b,t.c};for(int i=0;i<3;i++){PointF a=isoP(q[i],cx,cy,cz,ox+w/2,oy+h*.62f,s),d=isoP(q[(i+1)%3],cx,cy,cz,ox+w/2,oy+h*.62f,s);c.drawLine(a.x,a.y,d.x,d.y,p);}}p.setStyle(Paint.Style.FILL);p.setTextSize(18);c.drawText("ISOMETRIC",ox,oy+h+24,p);}
  PointF isoP(Vec v,float cx,float cy,float cz,float ox,float oy,float s){float x=(v.x-cx),y=(v.y-cy),z=(v.z-cz);return new PointF(ox+(x-y)*.866f*s,oy-(x+y)*.5f*s-z*s);}
  void drawSectionAA(Canvas c,Paint p,ArrayList<Tri> m,float ox,float oy,float w,float h,float[] b){p.setStyle(Paint.Style.STROKE);p.setColor(Color.rgb(110,110,110));p.setStrokeWidth(1);for(int i=0;i<20;i++)c.drawLine(ox+i*10,oy+h,ox+i*10+80,oy,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.BLACK);p.setTextSize(15);c.drawText("SECTION A-A",ox,oy+h+22,p);}
  void drawDimH(Canvas c,Paint p,float x1,float x2,float y,String s){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);c.drawLine(x1,y,x2,y,p);c.drawLine(x1,y-5,x1,y+5,p);c.drawLine(x2,y-5,x2,y+5,p);p.setStyle(Paint.Style.FILL);p.setTextSize(14);c.drawText(s,(x1+x2)/2-20,y-4,p);}
  void drawDimV(Canvas c,Paint p,float x,float y1,float y2,String s){p.setStyle(Paint.Style.STROKE);c.drawLine(x,y1,x,y2,p);c.drawLine(x-5,y1,x+5,y1,p);c.drawLine(x-5,y2,x+5,y2,p);p.setStyle(Paint.Style.FILL);p.setTextSize(14);c.save();c.rotate(-90,x,(y1+y2)/2);c.drawText(s,x+6,(y1+y2)/2,p);c.restore();}
  void drawTitleBlock(Canvas c,Paint p,int W,int H,float[] b){p.setStyle(Paint.Style.STROKE);p.setColor(Color.BLACK);c.drawRect(W-420,H-118,W-25,H-25,p);c.drawLine(W-420,H-78,W-25,H-78,p);c.drawLine(W-220,H-118,W-220,H-25,p);p.setStyle(Paint.Style.FILL);p.setTextSize(18);c.drawText("MG CAD Studio v2.1",W-405,H-92,p);p.setTextSize(13);c.drawText("AUTO ENGINEERING DRAWING",W-405,H-52,p);c.drawText(String.format(Locale.US,"SIZE %.2f x %.2f x %.2f",b[3]-b[0],b[4]-b[1],b[5]-b[2]),W-205,H-92,p);c.drawText("UNITS: MODEL UNITS",W-205,H-52,p);}

  String buildDxf(){float[] b=bounds(mesh);StringBuilder s=new StringBuilder("0\nSECTION\n2\nENTITIES\n");for(int plane=0;plane<3;plane++){float ox=plane==0?0:plane==1?180:0,oy=plane==2?-180:0;for(Tri t:mesh){Vec[] q={t.a,t.b,t.c};for(int i=0;i<3;i++){float[] a=dxfProj(q[i],plane,b,ox,oy),d=dxfProj(q[(i+1)%3],plane,b,ox,oy);s.append("0\nLINE\n8\nVISIBLE\n10\n").append(a[0]).append("\n20\n").append(a[1]).append("\n11\n").append(d[0]).append("\n21\n").append(d[1]).append('\n');}}}s.append("0\nENDSEC\n0\nEOF\n");return s.toString();}
  float[] dxfProj(Vec v,int p,float[] b,float ox,float oy){if(p==0)return new float[]{ox+v.x-b[0],oy+v.z-b[2]};if(p==1)return new float[]{ox+v.y-b[1],oy+v.z-b[2]};return new float[]{ox+v.x-b[0],oy+v.y-b[1]};}
  String buildStl(){StringBuilder s=new StringBuilder("solid MG_CAD_v21\n");if(!mesh.isEmpty()){for(Tri t:mesh){s.append("facet normal 0 0 0\n outer loop\n");sv(s,t.a);sv(s,t.b);sv(s,t.c);s.append(" endloop\nendfacet\n");}}else if(voxels!=null){int nx=voxels.length,ny=voxels[0].length,nz=voxels[0][0].length;for(int x=0;x<nx;x++)for(int y=0;y<ny;y++)for(int z=0;z<nz;z++)if(voxels[x][y][z]&&(z==nz-1||!voxels[x][y][z+1])){triStl(s,new Vec(x,y,z+1),new Vec(x+1,y,z+1),new Vec(x+1,y+1,z+1));triStl(s,new Vec(x,y,z+1),new Vec(x+1,y+1,z+1),new Vec(x,y+1,z+1));}}return s.append("endsolid MG_CAD_v21\n").toString();}
  void triStl(StringBuilder s,Vec a,Vec b,Vec c){s.append("facet normal 0 0 0\n outer loop\n");sv(s,a);sv(s,b);sv(s,c);s.append(" endloop\nendfacet\n");}void sv(StringBuilder s,Vec v){s.append("  vertex ").append(v.x).append(' ').append(v.y).append(' ').append(v.z).append('\n');}
  float[] bounds(ArrayList<Tri> m){float[] b={Float.MAX_VALUE,Float.MAX_VALUE,Float.MAX_VALUE,-Float.MAX_VALUE,-Float.MAX_VALUE,-Float.MAX_VALUE};for(Tri t:m)for(Vec v:new Vec[]{t.a,t.b,t.c}){b[0]=Math.min(b[0],v.x);b[1]=Math.min(b[1],v.y);b[2]=Math.min(b[2],v.z);b[3]=Math.max(b[3],v.x);b[4]=Math.max(b[4],v.y);b[5]=Math.max(b[5],v.z);}return b;}
  String fileName(Uri u){String n="dosya";Cursor c=null;try{c=getContentResolver().query(u,null,null,null,null);if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)n=c.getString(i);}}catch(Exception ignored){}finally{if(c!=null)c.close();}return n;}

  class CadView extends View{Paint p=new Paint(3);Bitmap bm;ArrayList<Tri> m=new ArrayList<>();boolean[][][] v;int viewMode=0;boolean techPreview=false;float yaw=.7f,pitch=.55f,zoom=1,panX=0,panY=0,lx,ly,lastD;boolean drag=false;
    CadView(Context c){super(c);setBackgroundColor(BG);}
    void setBitmap(Bitmap b){bm=b;m.clear();v=null;techPreview=false;invalidate();}void setMesh(ArrayList<Tri> a){m=a;bm=null;v=null;techPreview=false;fit();}void setVoxels(boolean[][][] a){v=a;bm=null;m.clear();techPreview=false;fit();}void fit(){zoom=1;panX=panY=0;invalidate();}
    @Override protected void onDraw(Canvas c){super.onDraw(c);drawGrid(c);if(techPreview&&!m.isEmpty()){c.drawColor(Color.rgb(235,238,242));Paint q=new Paint(3);drawProjection(c,q,m,30,30,getWidth()/2-45,getHeight()/2-55,0,bounds(m),"FRONT");drawProjection(c,q,m,getWidth()/2+15,30,getWidth()/2-45,getHeight()/2-55,1,bounds(m),"RIGHT");drawProjection(c,q,m,30,getHeight()/2+10,getWidth()/2-45,getHeight()/2-55,2,bounds(m),"TOP");drawIsoSheet(c,q,m,getWidth()/2+15,getHeight()/2+10,getWidth()/2-45,getHeight()/2-55,bounds(m));return;}if(bm!=null){RectF r=fitRect(bm);c.drawBitmap(bm,null,r,p);return;}if(!m.isEmpty())drawMesh(c);else if(v!=null)drawVoxel(c);}
    void drawGrid(Canvas c){p.setColor(Color.rgb(12,42,61));p.setStrokeWidth(1);for(int x=0;x<getWidth();x+=dp(28))c.drawLine(x,0,x,getHeight(),p);for(int y=0;y<getHeight();y+=dp(28))c.drawLine(0,y,getWidth(),y,p);}
    RectF fitRect(Bitmap b){float k=Math.min(getWidth()/(float)b.getWidth(),getHeight()/(float)b.getHeight());float w=b.getWidth()*k,h=b.getHeight()*k;return new RectF((getWidth()-w)/2,(getHeight()-h)/2,(getWidth()+w)/2,(getHeight()+h)/2);}
    void drawMesh(Canvas c){float[] b=bounds(m);float cx=(b[0]+b[3])/2,cy=(b[1]+b[4])/2,cz=(b[2]+b[5])/2,span=Math.max(b[3]-b[0],Math.max(b[4]-b[1],b[5]-b[2]));float s=Math.min(getWidth(),getHeight())/(span*2.4f+1)*zoom;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.1f);p.setColor(CYAN);for(Tri t:m){Vec[] q={t.a,t.b,t.c};for(int i=0;i<3;i++){PointF a=viewP(q[i],cx,cy,cz,s),d=viewP(q[(i+1)%3],cx,cy,cz,s);c.drawLine(a.x,a.y,d.x,d.y,p);}}}
    PointF viewP(Vec vv,float cx,float cy,float cz,float s){float x=vv.x-cx,y=vv.y-cy,z=vv.z-cz;if(viewMode==1)return new PointF(getWidth()/2+panX+x*s,getHeight()/2+panY-z*s);if(viewMode==2)return new PointF(getWidth()/2+panX+x*s,getHeight()/2+panY-y*s);if(viewMode==3)return new PointF(getWidth()/2+panX+y*s,getHeight()/2+panY-z*s);if(viewMode==4)return new PointF(getWidth()/2+panX-y*s,getHeight()/2+panY-z*s);if(viewMode==5)return new PointF(getWidth()/2+panX+x*s,getHeight()/2+panY+y*s);float cyw=(float)Math.cos(yaw),syw=(float)Math.sin(yaw),cp=(float)Math.cos(pitch),sp=(float)Math.sin(pitch);float xr=x*cyw-y*syw,yr=x*syw+y*cyw,zr=z;float zz=yr*sp+zr*cp;return new PointF(getWidth()/2+panX+xr*s,getHeight()/2+panY-zz*s);}
    void drawVoxel(Canvas c){int nx=v.length,ny=v[0].length,nz=v[0][0].length;float s=Math.min(getWidth(),getHeight())/(Math.max(nx,Math.max(ny,nz))*2.2f);p.setColor(Color.rgb(55,180,220));p.setStyle(Paint.Style.FILL);for(int x=0;x<nx;x++)for(int y=0;y<ny;y++)for(int z=0;z<nz;z++)if(v[x][y][z]&&(z==nz-1||!v[x][y][z+1])){float px=getWidth()/2+(x-y)*s*.86f,py=getHeight()*.7f-(x+y)*s*.45f-z*s;c.drawRect(px,py,px+s*.9f,py+s*.9f,p);}}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getPointerCount()==2){float d=(float)Math.hypot(e.getX(0)-e.getX(1),e.getY(0)-e.getY(1));if(e.getActionMasked()==MotionEvent.ACTION_MOVE&&lastD>0){zoom*=d/lastD;zoom=Math.max(.2f,Math.min(8f,zoom));invalidate();}lastD=d;return true;}lastD=0;if(e.getAction()==MotionEvent.ACTION_DOWN){lx=e.getX();ly=e.getY();drag=true;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE&&drag){yaw+=(e.getX()-lx)*.01f;pitch+=(e.getY()-ly)*.01f;pitch=Math.max(-1.4f,Math.min(1.4f,pitch));lx=e.getX();ly=e.getY();invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP)drag=false;return true;}
  }
}
