package com.mg.drawing2cad;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.graphics.pdf.PdfRenderer;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;

import java.io.*;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class MainActivityV3 extends Activity {
  static final int PICK=10,SAVE_PDF=11,SAVE_DXF=12,SAVE_STL=13;
  static final int MODE_2D3D=0,MODE_3D2D=1;
  final int BG=Color.rgb(3,11,20),PANEL=Color.rgb(8,24,39),PANEL2=Color.rgb(12,36,58),TEXT=Color.rgb(235,245,252),MUTED=Color.rgb(145,169,188),CYAN=Color.rgb(55,205,255),GREEN=Color.rgb(69,221,132),ORANGE=Color.rgb(255,184,77);

  int mode=MODE_2D3D; Bitmap source; boolean[][][] voxels; ArrayList<Tri> mesh=new ArrayList<>(); Uri archiveUri;
  CadView cad; TextView status,fileInfo,qualityInfo,modeInfo; ValidationEngine.Result validation;
  boolean showHidden=true,showCenter=true,showDims=true,showGrid=true,smooth=true;

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);buildUi();}

  void buildUi(){
    LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
    LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(10),dp(6),dp(8),dp(6));header.setBackgroundColor(PANEL);
    LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.addView(txt("MG CAD Studio",20,CYAN,true));brand.addView(txt("REQUIREMENTS-DRIVEN CAD • v3.0",9,MUTED,true));header.addView(brand,new LinearLayout.LayoutParams(dp(240),-2));
    Button m23=btn("2D → 3D"),m32=btn("3D → 2D");header.addView(m23);header.addView(m32);modeInfo=txt(" TEKNİK RESİM → 3D",11,GREEN,true);header.addView(modeInfo,new LinearLayout.LayoutParams(0,-2,1));
    Button open=btn("DOSYA AÇ"),create=btn("OLUŞTUR"),pdf=btn("PDF"),dxf=btn("DXF"),stl=btn("STL"),req=btn("1000 REQ");for(Button x:new Button[]{open,create,pdf,dxf,stl,req})header.addView(x);root.addView(header,new LinearLayout.LayoutParams(-1,dp(58)));

    HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(8),dp(4),dp(8),dp(4));bar.setBackgroundColor(Color.rgb(5,18,31));
    Button iso=sbtn("ISO"),front=sbtn("ÖN"),top=sbtn("ÜST"),right=sbtn("SAĞ"),left=sbtn("SOL"),fit=sbtn("SIĞDIR"),grid=sbtn("GRID"),hidden=sbtn("GİZLİ"),center=sbtn("EKSEN"),dims=sbtn("ÖLÇÜ"),smoothB=sbtn("SMOOTH");
    for(Button x:new Button[]{iso,front,top,right,left,fit,grid,hidden,center,dims,smoothB})bar.addView(x);fileInfo=txt("Dosya seçilmedi",10,MUTED,false);bar.addView(fileInfo,new LinearLayout.LayoutParams(dp(420),-2));hs.addView(bar);root.addView(hs,new LinearLayout.LayoutParams(-1,dp(48)));

    FrameLayout stage=new FrameLayout(this);cad=new CadView(this);stage.addView(cad,new FrameLayout.LayoutParams(-1,-1));
    qualityInfo=txt(RequirementRegistry.summary()+"\nGÜVEN — • KALİTE —",10,TEXT,true);qualityInfo.setPadding(dp(10),dp(7),dp(10),dp(7));round(qualityInfo,Color.argb(215,8,24,39),Color.rgb(26,91,128),10);FrameLayout.LayoutParams qlp=new FrameLayout.LayoutParams(dp(330),dp(58),Gravity.TOP|Gravity.RIGHT);qlp.setMargins(0,dp(10),dp(12),0);stage.addView(qualityInfo,qlp);
    root.addView(stage,new LinearLayout.LayoutParams(-1,0,1));status=txt("P0 çekirdek aktif: çift yönlü CAD • güvenli ZIP • doğrulama • offline PDF/DXF/STL.",10,MUTED,false);status.setPadding(dp(12),dp(8),dp(12),dp(8));status.setBackgroundColor(PANEL);root.addView(status,new LinearLayout.LayoutParams(-1,dp(42)));setContentView(root);

    m23.setOnClickListener(v->setMode(MODE_2D3D));m32.setOnClickListener(v->setMode(MODE_3D2D));open.setOnClickListener(v->pick());create.setOnClickListener(v->createAction());pdf.setOnClickListener(v->savePdf());dxf.setOnClickListener(v->saveDxf());stl.setOnClickListener(v->saveStl());req.setOnClickListener(v->showRequirements());
    iso.setOnClickListener(v->cad.setView(0));front.setOnClickListener(v->cad.setView(1));top.setOnClickListener(v->cad.setView(2));right.setOnClickListener(v->cad.setView(3));left.setOnClickListener(v->cad.setView(4));fit.setOnClickListener(v->cad.fit());grid.setOnClickListener(v->{showGrid=!showGrid;cad.invalidate();});hidden.setOnClickListener(v->{showHidden=!showHidden;cad.invalidate();});center.setOnClickListener(v->{showCenter=!showCenter;cad.invalidate();});dims.setOnClickListener(v->{showDims=!showDims;cad.invalidate();});smoothB.setOnClickListener(v->{smooth=!smooth;cad.invalidate();status.setText("Yüzey modu: "+(smooth?"SMOOTH":"EDGE"));});
  }

  void setMode(int m){mode=m;source=null;voxels=null;mesh.clear();cad.clear();validation=null;qualityInfo.setText(RequirementRegistry.summary()+"\nGÜVEN — • KALİTE —");modeInfo.setText(m==MODE_2D3D?" TEKNİK RESİM → 3D":" 3D MODEL → TEKNİK RESİM");status.setText(m==MODE_2D3D?"PDF/PNG/JPG/WEBP/ZIP aç; ön+üst+sağ görünüşlerden 3D oluştur.":"STL/OBJ/ZIP aç; otomatik mühendislik teknik resmi üret.");}

  void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);i.putExtra(Intent.EXTRA_MIME_TYPES,mode==MODE_2D3D?new String[]{"image/*","application/pdf","application/zip","application/x-zip-compressed","application/octet-stream"}:new String[]{"model/stl","model/obj","application/zip","application/x-zip-compressed","application/octet-stream","text/plain"});startActivityForResult(i,PICK);}

  @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null||data.getData()==null)return;try{Uri u=data.getData();if(req==PICK)loadPicked(u);else if(req==SAVE_PDF){try(OutputStream o=getContentResolver().openOutputStream(u)){writeTechnicalPdf(o);}status.setText("✓ PDF teknik resim kaydedildi.");}else if(req==SAVE_DXF){try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(buildDxf().getBytes(StandardCharsets.UTF_8));}status.setText("✓ DXF kaydedildi.");}else if(req==SAVE_STL){try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(buildStl().getBytes(StandardCharsets.US_ASCII));}status.setText("✓ STL kaydedildi.");}}catch(Exception e){status.setText("Hata: "+e.getMessage());}}

  void loadPicked(Uri u)throws Exception{String n=fileName(u),l=n.toLowerCase(Locale.ROOT);if(l.endsWith(".zip")||l.endsWith(".cbz")){archiveUri=u;ArrayList<String>a=ArchiveManager.list(this,u,mode==MODE_2D3D);if(a.isEmpty())throw new IOException("ZIP içinde bu moda uygun dosya yok");new AlertDialog.Builder(this).setTitle("ZIP içeriği").setItems(a.toArray(new String[0]),(d,w)->{try{loadExtracted(ArchiveManager.extract(this,archiveUri,a.get(w)),a.get(w));}catch(Exception ex){status.setText("ZIP: "+ex.getMessage());}}).show();return;}loadDirect(u,n);}
  void loadDirect(Uri u,String n)throws Exception{if(mode==MODE_2D3D){String l=n.toLowerCase(Locale.ROOT);if(l.endsWith(".pdf"))source=renderPdfUri(u);else try(InputStream in=getContentResolver().openInputStream(u)){source=BitmapFactory.decodeStream(in);}if(source==null)throw new IOException("2D dosya okunamadı");voxels=null;mesh.clear();cad.setBitmap(source);fileInfo.setText(n+" • 2D");status.setText("✓ Teknik resim yüklendi. OLUŞTUR ile görünüşleri eşleştir.");}else{byte[] d=readAll(u,160L*1024L*1024L);load3dBytes(d,n);}}
  void loadExtracted(File f,String n)throws Exception{if(mode==MODE_2D3D){if(n.toLowerCase(Locale.ROOT).endsWith(".pdf"))source=renderPdfFile(f);else try(InputStream in=new FileInputStream(f)){source=BitmapFactory.decodeStream(in);}if(source==null)throw new IOException("ZIP içi 2D dosya okunamadı");cad.setBitmap(source);fileInfo.setText(n+" • ZIP/2D");status.setText("✓ ZIP içinden teknik resim yüklendi.");}else{byte[] d=readFile(f,160L*1024L*1024L);load3dBytes(d,n);}}

  void load3dBytes(byte[] d,String n)throws Exception{String l=n.toLowerCase(Locale.ROOT);mesh=l.endsWith(".obj")?parseObj(new String(d,StandardCharsets.UTF_8)):parseStl(d);if(mesh.isEmpty())throw new IOException("3D geometri okunamadı");source=null;voxels=null;cad.setMesh(mesh);float[] b=bounds(mesh);validation=ValidationEngine.validate3d(mesh.size(),b);updateQuality();fileInfo.setText(n+" • "+mesh.size()+" üçgen");status.setText(String.format(Locale.US,"✓ Model %.2f × %.2f × %.2f • teknik resim üretmeye hazır",b[3]-b[0],b[4]-b[1],b[5]-b[2]));}

  void createAction(){if(mode==MODE_3D2D){if(mesh.isEmpty()){status.setText("Önce STL/OBJ model aç.");return;}cad.tech=true;cad.invalidate();validation=ValidationEngine.validate3d(mesh.size(),bounds(mesh));updateQuality();status.setText("✓ ÖN + ÜST + SAĞ + ISO teknik resim önizlemesi hazır.");return;}if(source==null){status.setText("Önce teknik resim aç.");return;}status.setText("Analiz: görünüşler ayrılıyor • konturlar dolduruluyor • visual hull oluşturuluyor...");new Thread(()->{try{boolean[][][] v=reconstruct(source);voxels=v;mesh.clear();validation=ValidationEngine.validate2d(source.getWidth(),source.getHeight(),true,true,true);runOnUiThread(()->{cad.setVoxels(v);updateQuality();status.setText("✓ 2D → 3D HAZIR • "+count3(v)+" voxel • belirsiz ölçü uydurulmadı");});}catch(Exception e){runOnUiThread(()->status.setText("Rekonstrüksiyon: "+e.getMessage()));}}).start();}

  boolean[][][] reconstruct(Bitmap bm)throws Exception{int W=bm.getWidth(),H=bm.getHeight(),tc=(int)(H*.07f),bc=(int)(H*.07f),usable=H-tc-bc,mx=W/2,my=tc+usable/2;Bitmap front=Bitmap.createBitmap(bm,0,tc,mx,usable/2),right=Bitmap.createBitmap(bm,mx,tc,W-mx,usable/2),top=Bitmap.createBitmap(bm,0,my,mx,H-bc-my);Mask f=mask(front),r=mask(right),t=mask(top);if(f==null||r==null||t==null)throw new IOException("Ön/üst/sağ görünüşlerden biri bulunamadı");int nx=84,nz=Math.max(18,Math.min(72,Math.round(nx*f.aspect))),ny=Math.max(18,Math.min(70,Math.round(nx*t.aspect)));boolean[][] fm=resample(f.m,nx,nz),rm=resample(r.m,ny,nz),tm=resample(t.m,nx,ny);boolean[][][] v=new boolean[nx][ny][nz];for(int x=0;x<nx;x++)for(int y=0;y<ny;y++)for(int z=0;z<nz;z++)v[x][y][z]=fm[nz-1-z][x]&&tm[ny-1-y][x]&&rm[nz-1-z][y];if(count3(v)<100)throw new IOException("Görünüşler yeterli ortak hacim üretmedi");return v;}
  static class Mask{boolean[][]m;float aspect;Mask(boolean[][]a,float s){m=a;aspect=s;}}
  Mask mask(Bitmap b){int w=b.getWidth(),h=b.getHeight(),minX=w,minY=h,maxX=-1,maxY=-1,step=Math.max(1,Math.max(w,h)/1200);for(int y=0;y<h;y+=step)for(int x=0;x<w;x+=step)if(gray(b.getPixel(x,y))<90){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}if(maxX<0)return null;int pad=Math.max(3,(maxX-minX)/100);minX=Math.max(0,minX-pad);minY=Math.max(0,minY-pad);maxX=Math.min(w-1,maxX+pad);maxY=Math.min(h-1,maxY+pad);Bitmap c=Bitmap.createBitmap(b,minX,minY,maxX-minX+1,maxY-minY+1);int ow=120,oh=Math.max(20,Math.min(100,Math.round(ow*c.getHeight()/(float)c.getWidth())));Bitmap s=Bitmap.createScaledBitmap(c,ow,oh,true);boolean[][] wall=new boolean[oh][ow];for(int y=0;y<oh;y++)for(int x=0;x<ow;x++)wall[y][x]=gray(s.getPixel(x,y))<115;wall=dilate(wall,1);boolean[][] outside=flood(wall);boolean[][] solid=new boolean[oh][ow];for(int y=0;y<oh;y++)for(int x=0;x<ow;x++)solid[y][x]=wall[y][x]||!outside[y][x];return new Mask(solid,oh/(float)ow);}
  int gray(int c){return (Color.red(c)*30+Color.green(c)*59+Color.blue(c)*11)/100;}
  boolean[][] dilate(boolean[][] a,int r){int h=a.length,w=a[0].length;boolean[][]o=new boolean[h][w];for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(a[y][x])for(int yy=Math.max(0,y-r);yy<=Math.min(h-1,y+r);yy++)for(int xx=Math.max(0,x-r);xx<=Math.min(w-1,x+r);xx++)o[yy][xx]=true;return o;}
  boolean[][] flood(boolean[][] wall){int h=wall.length,w=wall[0].length;boolean[][]o=new boolean[h][w];ArrayDeque<int[]>q=new ArrayDeque<>();for(int x=0;x<w;x++){seed(x,0,wall,o,q);seed(x,h-1,wall,o,q);}for(int y=0;y<h;y++){seed(0,y,wall,o,q);seed(w-1,y,wall,o,q);}int[][]d={{1,0},{-1,0},{0,1},{0,-1}};while(!q.isEmpty()){int[]p=q.removeFirst();for(int[]dd:d){int x=p[0]+dd[0],y=p[1]+dd[1];if(x>=0&&x<w&&y>=0&&y<h&&!wall[y][x]&&!o[y][x]){o[y][x]=true;q.add(new int[]{x,y});}}}return o;}
  void seed(int x,int y,boolean[][]w,boolean[][]o,ArrayDeque<int[]>q){if(!w[y][x]&&!o[y][x]){o[y][x]=true;q.add(new int[]{x,y});}}
  boolean[][] resample(boolean[][]a,int W,int H){Bitmap b=Bitmap.createBitmap(a[0].length,a.length,Bitmap.Config.ARGB_8888);for(int y=0;y<a.length;y++)for(int x=0;x<a[0].length;x++)b.setPixel(x,y,a[y][x]?Color.BLACK:Color.WHITE);Bitmap s=Bitmap.createScaledBitmap(b,W,H,false);boolean[][]o=new boolean[H][W];for(int y=0;y<H;y++)for(int x=0;x<W;x++)o[y][x]=gray(s.getPixel(x,y))<128;return o;}

  static class Vec{float x,y,z;Vec(float X,float Y,float Z){x=X;y=Y;z=Z;}}static class Tri{Vec a,b,c;Tri(Vec A,Vec B,Vec C){a=A;b=B;c=C;}}
  ArrayList<Tri> parseObj(String s){ArrayList<Vec>vs=new ArrayList<>();ArrayList<Tri>ts=new ArrayList<>();for(String ln:s.split("\\r?\\n")){ln=ln.trim();try{if(ln.startsWith("v ")){String[]q=ln.split("\\s+");vs.add(new Vec(Float.parseFloat(q[1]),Float.parseFloat(q[2]),Float.parseFloat(q[3])));}else if(ln.startsWith("f ")){String[]q=ln.split("\\s+");int[]id=new int[q.length-1];for(int i=1;i<q.length;i++){int k=Integer.parseInt(q[i].split("/")[0]);id[i-1]=k<0?vs.size()+k:k-1;}for(int i=1;i<id.length-1;i++)ts.add(new Tri(vs.get(id[0]),vs.get(id[i]),vs.get(id[i+1])));}}catch(Exception ignored){}}return ts;}
  ArrayList<Tri> parseStl(byte[]d)throws Exception{ArrayList<Tri>t=new ArrayList<>();if(d.length>=84){int n=ByteBuffer.wrap(d,80,4).order(ByteOrder.LITTLE_ENDIAN).getInt();long ex=84L+50L*n;if(n>0&&n<5000000&&ex<=d.length){ByteBuffer b=ByteBuffer.wrap(d).order(ByteOrder.LITTLE_ENDIAN);b.position(84);for(int i=0;i<n;i++){b.position(b.position()+12);Vec a=new Vec(b.getFloat(),b.getFloat(),b.getFloat()),c=new Vec(b.getFloat(),b.getFloat(),b.getFloat()),e=new Vec(b.getFloat(),b.getFloat(),b.getFloat());t.add(new Tri(a,c,e));b.getShort();}return t;}}String s=new String(d,StandardCharsets.US_ASCII);ArrayList<Vec>v=new ArrayList<>();for(String ln:s.split("\\r?\\n")){ln=ln.trim();if(ln.startsWith("vertex ")){String[]q=ln.split("\\s+");if(q.length>=4){v.add(new Vec(Float.parseFloat(q[1]),Float.parseFloat(q[2]),Float.parseFloat(q[3])));if(v.size()==3){t.add(new Tri(v.get(0),v.get(1),v.get(2)));v.clear();}}}}return t;}
  float[] bounds(ArrayList<Tri>m){float[]b={Float.MAX_VALUE,Float.MAX_VALUE,Float.MAX_VALUE,-Float.MAX_VALUE,-Float.MAX_VALUE,-Float.MAX_VALUE};for(Tri t:m)for(Vec v:new Vec[]{t.a,t.b,t.c}){b[0]=Math.min(b[0],v.x);b[1]=Math.min(b[1],v.y);b[2]=Math.min(b[2],v.z);b[3]=Math.max(b[3],v.x);b[4]=Math.max(b[4],v.y);b[5]=Math.max(b[5],v.z);}return b;}

  void savePdf(){if(mesh.isEmpty()&&voxels==null){status.setText("Önce 3D model oluştur/aç.");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,"MG_CAD_Technical_Drawing.pdf");startActivityForResult(i,SAVE_PDF);}
  void saveDxf(){if(mesh.isEmpty()&&voxels==null){status.setText("Önce model oluştur/aç.");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/dxf");i.putExtra(Intent.EXTRA_TITLE,"MG_CAD_Technical_Drawing.dxf");startActivityForResult(i,SAVE_DXF);}
  void saveStl(){if(voxels==null&&mesh.isEmpty()){status.setText("Önce 3D model oluştur/aç.");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("model/stl");i.putExtra(Intent.EXTRA_TITLE,"MG_CAD_Model.stl");startActivityForResult(i,SAVE_STL);}

  void writeTechnicalPdf(OutputStream out)throws Exception{PdfDocument d=new PdfDocument();PdfDocument.Page page=d.startPage(new PdfDocument.PageInfo.Builder(842,595,1).create());Canvas c=page.getCanvas();c.drawColor(Color.WHITE);Paint p=new Paint(3);p.setColor(Color.BLACK);p.setTextSize(14);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("MG CAD STUDIO — ENGINEERING DRAWING",28,30,p);p.setTextSize(9);p.setTypeface(Typeface.DEFAULT);c.drawText("FRONT",55,55,p);c.drawText("RIGHT",455,55,p);c.drawText("TOP",55,320,p);c.drawText("ISOMETRIC",455,320,p);drawTech(c,new RectF(40,65,390,285),1,p);drawTech(c,new RectF(440,65,790,285),3,p);drawTech(c,new RectF(40,330,390,540),2,p);drawTech(c,new RectF(440,330,790,540),0,p);p.setStyle(Paint.Style.STROKE);c.drawRect(20,20,822,575,p);c.drawRect(560,545,822,575,p);p.setStyle(Paint.Style.FILL);c.drawText("UNITS: mm   REV: A   "+(validation==null?"":validation.compact()),570,563,p);d.finishPage(page);d.writeTo(out);d.close();}
  void drawTech(Canvas c,RectF r,int view,Paint p){p.setColor(Color.BLACK);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.2f);if(!mesh.isEmpty()){float[]b=bounds(mesh);for(Tri t:mesh){float[]a=proj(t.a,view,b,r),bb=proj(t.b,view,b,r),cc=proj(t.c,view,b,r);c.drawLine(a[0],a[1],bb[0],bb[1],p);c.drawLine(bb[0],bb[1],cc[0],cc[1],p);c.drawLine(cc[0],cc[1],a[0],a[1],p);}}else if(voxels!=null){boolean[][]sil=silhouette(voxels,view);float sx=r.width()/sil[0].length,sy=r.height()/sil.length;for(int y=0;y<sil.length;y++)for(int x=0;x<sil[0].length;x++)if(sil[y][x]&&boundary(sil,x,y))c.drawRect(r.left+x*sx,r.top+y*sy,r.left+(x+1)*sx,r.top+(y+1)*sy,p);}if(showCenter){p.setColor(Color.GRAY);p.setPathEffect(new android.graphics.DashPathEffect(new float[]{8,5},0));c.drawLine(r.centerX(),r.top,r.centerX(),r.bottom,p);c.drawLine(r.left,r.centerY(),r.right,r.centerY(),p);p.setPathEffect(null);}p.setColor(Color.BLACK);}
  float[] proj(Vec v,int mode,float[]b,RectF r){float u=0,w=0;if(mode==1){u=v.x;w=v.z;}else if(mode==2){u=v.x;w=v.y;}else if(mode==3){u=v.y;w=v.z;}else{u=(v.x-v.y)*.866f;w=(v.x+v.y)*.5f+v.z;}float minU,maxU,minW,maxW;if(mode==1){minU=b[0];maxU=b[3];minW=b[2];maxW=b[5];}else if(mode==2){minU=b[0];maxU=b[3];minW=b[1];maxW=b[4];}else if(mode==3){minU=b[1];maxU=b[4];minW=b[2];maxW=b[5];}else{float m=Math.max(b[3]-b[0],Math.max(b[4]-b[1],b[5]-b[2]));minU=-m;maxU=m;minW=-m*.2f;maxW=m*1.8f;}float x=r.left+(u-minU)/Math.max(.0001f,maxU-minU)*r.width(),y=r.bottom-(w-minW)/Math.max(.0001f,maxW-minW)*r.height();return new float[]{x,y};}
  String buildDxf(){StringBuilder s=new StringBuilder("0\nSECTION\n2\nENTITIES\n");if(!mesh.isEmpty()){float[]b=bounds(mesh);for(Tri t:mesh){addDxfTri(s,t,1,b);}}else if(voxels!=null){boolean[][]sil=silhouette(voxels,1);for(int y=0;y<sil.length;y++)for(int x=0;x<sil[0].length;x++)if(sil[y][x]&&boundary(sil,x,y))s.append("0\nPOINT\n8\nVISIBLE\n10\n").append(x).append("\n20\n").append(y).append("\n");}return s.append("0\nENDSEC\n0\nEOF\n").toString();}
  void addDxfTri(StringBuilder s,Tri t,int mode,float[]b){Vec[]v={t.a,t.b,t.c,t.a};for(int i=0;i<3;i++){float[]a=projRaw(v[i],mode),c=projRaw(v[i+1],mode);s.append("0\nLINE\n8\nVISIBLE\n10\n").append(a[0]).append("\n20\n").append(a[1]).append("\n11\n").append(c[0]).append("\n21\n").append(c[1]).append("\n");}}
  float[] projRaw(Vec v,int m){if(m==1)return new float[]{v.x,v.z};if(m==2)return new float[]{v.x,v.y};if(m==3)return new float[]{v.y,v.z};return new float[]{(v.x-v.y)*.866f,(v.x+v.y)*.5f+v.z};}
  String buildStl(){if(!mesh.isEmpty()){StringBuilder s=new StringBuilder("solid MG\n");for(Tri t:mesh)stlTri(s,t.a,t.b,t.c);return s.append("endsolid MG\n").toString();}StringBuilder s=new StringBuilder("solid MG_voxel\n");int nx=voxels.length,ny=voxels[0].length,nz=voxels[0][0].length;for(int x=0;x<nx;x++)for(int y=0;y<ny;y++)for(int z=0;z<nz;z++)if(voxels[x][y][z]){if(x==0||!voxels[x-1][y][z])quad(s,x,y,z,x,y+1,z,x,y+1,z+1,x,y,z+1);if(x==nx-1||!voxels[x+1][y][z])quad(s,x+1,y,z,x+1,y,z+1,x+1,y+1,z+1,x+1,y+1,z);if(y==0||!voxels[x][y-1][z])quad(s,x,y,z,x,y,z+1,x+1,y,z+1,x+1,y,z);if(y==ny-1||!voxels[x][y+1][z])quad(s,x,y+1,z,x+1,y+1,z,x+1,y+1,z+1,x,y+1,z+1);if(z==0||!voxels[x][y][z-1])quad(s,x,y,z,x+1,y,z,x+1,y+1,z,x,y+1,z);if(z==nz-1||!voxels[x][y][z+1])quad(s,x,y,z+1,x,y+1,z+1,x+1,y+1,z+1,x+1,y,z+1);}return s.append("endsolid MG_voxel\n").toString();}
  void quad(StringBuilder s,float ax,float ay,float az,float bx,float by,float bz,float cx,float cy,float cz,float dx,float dy,float dz){stlTri(s,new Vec(ax,ay,az),new Vec(bx,by,bz),new Vec(cx,cy,cz));stlTri(s,new Vec(ax,ay,az),new Vec(cx,cy,cz),new Vec(dx,dy,dz));}
  void stlTri(StringBuilder s,Vec a,Vec b,Vec c){s.append("facet normal 0 0 0\n outer loop\n");for(Vec v:new Vec[]{a,b,c})s.append("  vertex ").append(v.x).append(' ').append(v.y).append(' ').append(v.z).append("\n");s.append(" endloop\nendfacet\n");}

  boolean[][] silhouette(boolean[][][]v,int mode){int nx=v.length,ny=v[0].length,nz=v[0][0].length;if(mode==2){boolean[][]o=new boolean[ny][nx];for(int x=0;x<nx;x++)for(int y=0;y<ny;y++)for(int z=0;z<nz;z++)o[ny-1-y][x]|=v[x][y][z];return o;}if(mode==3){boolean[][]o=new boolean[nz][ny];for(int y=0;y<ny;y++)for(int z=0;z<nz;z++)for(int x=0;x<nx;x++)o[nz-1-z][y]|=v[x][y][z];return o;}boolean[][]o=new boolean[nz][nx];for(int x=0;x<nx;x++)for(int z=0;z<nz;z++)for(int y=0;y<ny;y++)o[nz-1-z][x]|=v[x][y][z];return o;}
  boolean boundary(boolean[][]a,int x,int y){if(!a[y][x])return false;int h=a.length,w=a[0].length;return x==0||y==0||x==w-1||y==h-1||!a[y][x-1]||!a[y][x+1]||!a[y-1][x]||!a[y+1][x];}
  int count3(boolean[][][]a){int n=0;if(a!=null)for(boolean[][]x:a)for(boolean[]y:x)for(boolean z:y)if(z)n++;return n;}

  void showRequirements(){new AlertDialog.Builder(this).setTitle("1000 Engineering Requirements").setMessage(RequirementRegistry.summary()+"\n\n40 kategori: SYS, UX, IMP2D, IMP3D, ZIP, OCR, LINE, VIEW, DIM, TOL, HOLE, FEATURE, RECON, BREP, MESH, CAD3D, MEASURE, SECTION, DRAW2D, AUTOANN, EXPORT, VALID, CONF, PERF, MEM, ROBUST, SEC, OFFLINE, PROJECT, UNDO, ASSEM, META, MANUF, QA, ANDROID, ACCESS, I18N, REPORT, AI, FUTURE.\n\nP0 çekirdek işlevler v3.0'da uygulanır; P1/P2 geliştirmeleri izlenebilir backlog olarak tutulur. Uygulanmayan madde uygulanmış gösterilmez.").setPositiveButton("Tamam",null).show();}
  void updateQuality(){qualityInfo.setText(RequirementRegistry.summary()+"\n"+(validation==null?"GÜVEN — • KALİTE —":validation.compact()));}

  Bitmap renderPdfUri(Uri u)throws Exception{File f=new File(getCacheDir(),"v3.pdf");try(InputStream in=getContentResolver().openInputStream(u);OutputStream o=new FileOutputStream(f)){copy(in,o,80L*1024L*1024L);}return renderPdfFile(f);}
  Bitmap renderPdfFile(File f)throws Exception{ParcelFileDescriptor fd=ParcelFileDescriptor.open(f,ParcelFileDescriptor.MODE_READ_ONLY);PdfRenderer r=new PdfRenderer(fd);if(r.getPageCount()==0)throw new IOException("PDF boş");PdfRenderer.Page p=r.openPage(0);float k=Math.min(3f,2400f/Math.max(p.getWidth(),p.getHeight()));Bitmap b=Bitmap.createBitmap(Math.max(1,(int)(p.getWidth()*k)),Math.max(1,(int)(p.getHeight()*k)),Bitmap.Config.ARGB_8888);b.eraseColor(Color.WHITE);p.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);p.close();r.close();fd.close();return b;}
  byte[] readAll(Uri u,long max)throws Exception{try(InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream o=new ByteArrayOutputStream()){copy(in,o,max);return o.toByteArray();}}
  byte[] readFile(File f,long max)throws Exception{try(InputStream in=new FileInputStream(f);ByteArrayOutputStream o=new ByteArrayOutputStream()){copy(in,o,max);return o.toByteArray();}}
  void copy(InputStream in,OutputStream o,long max)throws IOException{byte[]b=new byte[32768];int n;long t=0;while((n=in.read(b))>0){t+=n;if(t>max)throw new IOException("Dosya boyutu sınırını aştı");o.write(b,0,n);}}
  String fileName(Uri u){String n="dosya";Cursor c=null;try{c=getContentResolver().query(u,null,null,null,null);if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)n=c.getString(i);}}finally{if(c!=null)c.close();}return n==null?"dosya":n;}

  TextView txt(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextColor(c);t.setTextSize(z);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setTextSize(10);b.setMinHeight(0);b.setPadding(dp(9),0,dp(9),0);round(b,PANEL2,Color.rgb(25,82,118),8);return b;}
  Button sbtn(String s){Button b=btn(s);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(38));lp.setMargins(dp(3),0,dp(3),0);b.setLayoutParams(lp);return b;}
  void round(View v,int fill,int stroke,int rad){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(rad));g.setStroke(1,stroke);v.setBackground(g);}int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}

  class CadView extends View{
    Paint p=new Paint(3),edge=new Paint(3),gridP=new Paint(3);Bitmap bm;boolean[][][]v;ArrayList<Tri>m=new ArrayList<>();int viewMode=0;boolean tech=false;float scale=1f,panX=0,panY=0,lastX,lastY;boolean drag=false;
    CadView(Context c){super(c);setBackgroundColor(BG);edge.setStyle(Paint.Style.STROKE);edge.setStrokeWidth(1);edge.setColor(Color.rgb(15,81,105));gridP.setColor(Color.rgb(15,45,65));}
    void clear(){bm=null;v=null;m.clear();tech=false;invalidate();}void setBitmap(Bitmap b){clear();bm=b;invalidate();}void setVoxels(boolean[][][]x){clear();v=x;fit();}void setMesh(ArrayList<Tri>x){clear();m=new ArrayList<>(x);fit();}void setView(int q){viewMode=q;tech=false;invalidate();}void fit(){scale=1;panX=panY=0;invalidate();}
    @Override protected void onDraw(Canvas c){super.onDraw(c);if(showGrid){for(int x=0;x<getWidth();x+=dp(28))c.drawLine(x,0,x,getHeight(),gridP);for(int y=0;y<getHeight();y+=dp(28))c.drawLine(0,y,getWidth(),y,gridP);}c.save();c.translate(panX,panY);c.scale(scale,scale,getWidth()/2f,getHeight()/2f);if(bm!=null){RectF r=fitRect(bm);c.drawBitmap(bm,null,r,p);}else if(tech&&!m.isEmpty())drawTechPreview(c);else if(!m.isEmpty())drawMesh(c);else if(v!=null)drawVoxel(c);c.restore();}
    RectF fitRect(Bitmap b){float k=Math.min(getWidth()/(float)b.getWidth(),getHeight()/(float)b.getHeight());float w=b.getWidth()*k,h=b.getHeight()*k;return new RectF((getWidth()-w)/2,(getHeight()-h)/2,(getWidth()+w)/2,(getHeight()+h)/2);}
    void drawMesh(Canvas c){float[]b=bounds(m);RectF r=new RectF(dp(80),dp(50),getWidth()-dp(80),getHeight()-dp(50));p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(56,164,197));edge.setColor(Color.rgb(12,77,101));for(Tri t:m){float[]a=proj(t.a,viewMode,b,r),bb=proj(t.b,viewMode,b,r),cc=proj(t.c,viewMode,b,r);Path q=new Path();q.moveTo(a[0],a[1]);q.lineTo(bb[0],bb[1]);q.lineTo(cc[0],cc[1]);q.close();if(smooth)c.drawPath(q,p);if(!smooth||showHidden)c.drawPath(q,edge);}}
    void drawTechPreview(Canvas c){p.setStyle(Paint.Style.FILL);p.setColor(Color.WHITE);c.drawRect(dp(30),dp(25),getWidth()-dp(30),getHeight()-dp(25),p);p.setStyle(Paint.Style.STROKE);p.setColor(Color.BLACK);RectF[]rs={new RectF(dp(55),dp(65),getWidth()*.46f,getHeight()*.46f),new RectF(getWidth()*.54f,dp(65),getWidth()-dp(55),getHeight()*.46f),new RectF(dp(55),getHeight()*.55f,getWidth()*.46f,getHeight()-dp(55)),new RectF(getWidth()*.54f,getHeight()*.55f,getWidth()-dp(55),getHeight()-dp(55))};int[]vm={1,3,2,0};float[]b=bounds(m);for(int k=0;k<4;k++){for(Tri t:m){float[]a=proj(t.a,vm[k],b,rs[k]),bb=proj(t.b,vm[k],b,rs[k]),cc=proj(t.c,vm[k],b,rs[k]);c.drawLine(a[0],a[1],bb[0],bb[1],p);c.drawLine(bb[0],bb[1],cc[0],cc[1],p);c.drawLine(cc[0],cc[1],a[0],a[1],p);}if(showCenter){p.setColor(Color.GRAY);p.setPathEffect(new android.graphics.DashPathEffect(new float[]{8,5},0));c.drawLine(rs[k].centerX(),rs[k].top,rs[k].centerX(),rs[k].bottom,p);c.drawLine(rs[k].left,rs[k].centerY(),rs[k].right,rs[k].centerY(),p);p.setPathEffect(null);p.setColor(Color.BLACK);}}}
    void drawVoxel(Canvas c){if(viewMode==0){int nx=v.length,ny=v[0].length,nz=v[0][0].length;float s=Math.min(getWidth()/(float)(nx+ny+8),getHeight()/(float)(nz+(nx+ny)*.45f+8));float ox=getWidth()/2f,oy=getHeight()*.72f;p.setStyle(Paint.Style.FILL);for(int z=0;z<nz;z++)for(int y=ny-1;y>=0;y--)for(int x=0;x<nx;x++)if(v[x][y][z]){float px=ox+(x-y)*s*.86f,py=oy-(x+y)*s*.43f-z*s;if(z==nz-1||!v[x][y][z+1])face(c,px,py,s,0);if(x==nx-1||!v[x+1][y][z])face(c,px,py,s,1);if(y==0||!v[x][y-1][z])face(c,px,py,s,2);}}else{boolean[][]sil=silhouette(v,viewMode==2?2:viewMode==3?3:1);float sx=(getWidth()-dp(120))/(float)sil[0].length,sy=(getHeight()-dp(100))/(float)sil.length;p.setColor(CYAN);p.setStyle(Paint.Style.FILL);for(int y=0;y<sil.length;y++)for(int x=0;x<sil[0].length;x++)if(sil[y][x])c.drawRect(dp(60)+x*sx,dp(50)+y*sy,dp(60)+(x+1)*sx,dp(50)+(y+1)*sy,p);}}
    void face(Canvas c,float x,float y,float s,int f){Path q=new Path();if(f==0){q.moveTo(x,y-s);q.lineTo(x+s*.86f,y-s-s*.43f);q.lineTo(x,y-s-s*.86f);q.lineTo(x-s*.86f,y-s-s*.43f);}else if(f==1){q.moveTo(x,y);q.lineTo(x+s*.86f,y-s*.43f);q.lineTo(x+s*.86f,y-s*.43f-s);q.lineTo(x,y-s);}else{q.moveTo(x,y);q.lineTo(x-s*.86f,y-s*.43f);q.lineTo(x-s*.86f,y-s*.43f-s);q.lineTo(x,y-s);}q.close();p.setColor(f==0?Color.rgb(105,222,240):f==1?Color.rgb(57,175,209):Color.rgb(39,137,171));c.drawPath(q,p);if(!smooth)c.drawPath(q,edge);}
    @Override public boolean onTouchEvent(android.view.MotionEvent e){if(e.getPointerCount()>=2){if(e.getActionMasked()==MotionEvent.ACTION_MOVE){float dx=Math.abs(e.getX(0)-e.getX(1)),dy=Math.abs(e.getY(0)-e.getY(1));float dist=(float)Math.sqrt(dx*dx+dy*dy);if(lastX>0){scale=Math.max(.4f,Math.min(4f,scale*(dist/lastX)));invalidate();}lastX=dist;}else lastX=0;return true;}if(e.getAction()==MotionEvent.ACTION_DOWN){lastX=e.getX();lastY=e.getY();drag=true;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE&&drag){panX+=e.getX()-lastX;panY+=e.getY()-lastY;lastX=e.getX();lastY=e.getY();invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP){drag=false;return true;}return true;}
  }
}
