plugins {
    id 'com.android.application'
}

android {
    namespace 'com.muhammetgecgil.turkradyo'
    compileSdk 36

    defaultConfig {
        applicationId 'com.muhammetgecgil.turkradyo'
        minSdk 26
        targetSdk 36
        versionCode 239
        versionName '2.3.9'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
