from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
PKG=ROOT/'app/src/main/java/com/mg/fixturecockpitsim'
WEATHER=PKG/'WeatherEffectsView.java'
CIN=PKG/'CinematicEnvironmentView.java'
RUNTIME=PKG/'FlightRuntimeActivity.java'
PILOT=PKG/'PilotCockpitActivity.java'
MANIFEST=ROOT/'app/src/main/AndroidManifest.xml'
GRADLE=ROOT/'app/build.gradle'


def rep(text,old,new,label):
    if new in text:return text
    if old not in text:raise SystemExit(f'v106 anchor missing: {label}')
    return text.replace(old,new,1)

# WeatherEffectsView: live current weather drives the existing atmosphere renderer.
w=WEATHER.read_text()
w=rep(w,'import android.graphics.Shader;\n\nimport java.util.Locale;',
'''import android.graphics.Shader;\n\nimport com.mg.fixturecockpitsim.sim.RealWeatherCoordinator;\nimport com.mg.fixturecockpitsim.sim.RealWeatherProfile;\n\nimport java.util.Locale;''','weather imports')
w=rep(w,
'''    public static float getSharedCrosswindMps(){return sharedWindy?sharedWindSign*(5f+15f*sharedWindStrength):0f;}\n    public static float getSharedCloudLayerCoverage(){return sharedCloudLayerCoverage;}\n    public static boolean hasSharedCloudLayer(){return sharedCloudLayerCoverage>=.36f;}\n''',
'''    public static float getSharedCrosswindMps(){RealWeatherProfile x=RealWeatherCoordinator.getProfile();return x!=null?RealWeatherCoordinator.crosswindMps(270.0):(sharedWindy?sharedWindSign*(5f+15f*sharedWindStrength):0f);}\n    public static float getSharedCloudLayerCoverage(){return sharedCloudLayerCoverage;}\n    public static boolean hasSharedCloudLayer(){return sharedCloudLayerCoverage>=.36f;}\n    public static boolean isSharedLiveWeather(){return RealWeatherCoordinator.hasLiveProfile();}\n    public static float getSharedSeaRoughness(){RealWeatherProfile x=RealWeatherCoordinator.getProfile();return x==null?.12f+sharedWindStrength*.55f:(float)x.seaRoughness01;}\n    public static float getSharedSkyHaze(){RealWeatherProfile x=RealWeatherCoordinator.getProfile();return x==null?(sharedCloudLayerCoverage*.28f+(sharedWindy?.05f:0f)):(float)x.skyHaze01;}\n    public static float getSharedMountainHaze(){RealWeatherProfile x=RealWeatherCoordinator.getProfile();return x==null?(sharedCloudLayerCoverage*.38f+.10f):(float)x.mountainHaze01;}\n    public static float getSharedTemperatureC(){RealWeatherProfile x=RealWeatherCoordinator.getProfile();return x==null?18f:(float)x.temperatureC;}\n    public static float getSharedVisibilityM(){RealWeatherProfile x=RealWeatherCoordinator.getProfile();return x==null?30000f:(float)x.visibilityM;}\n    public static float getSharedHumidity01(){RealWeatherProfile x=RealWeatherCoordinator.getProfile();return x==null?.55f:(float)x.humidity01;}\n    public static void setWeatherLocation(double lat,double lon){RealWeatherCoordinator.setLocation(lat,lon);}\n''','shared real weather getters')
w=rep(w,
'''    public String getModeLabel(){String d=DAY_LABELS[Math.max(0,Math.min(DAY_LABELS.length-1,dayPhase))],w=WEATHER_LABELS[Math.max(0,Math.min(WEATHER_LABELS.length-1,weather))],layer=hasSharedCloudLayer()?" / LAYER":"";return d+" / "+w+layer+(windy?String.format(Locale.US," + WIND %.0f m/s",Math.abs(getSharedCrosswindMps())):"");}\n''',
'''    public String getModeLabel(){RealWeatherProfile x=RealWeatherCoordinator.getProfile();if(x!=null)return RealWeatherCoordinator.statusLabel();String d=DAY_LABELS[Math.max(0,Math.min(DAY_LABELS.length-1,dayPhase))],ww=WEATHER_LABELS[Math.max(0,Math.min(WEATHER_LABELS.length-1,weather))],layer=hasSharedCloudLayer()?" / LAYER":"";return d+" / OFFLINE "+ww+layer+(windy?String.format(Locale.US," + WIND %.0f m/s",Math.abs(getSharedCrosswindMps())):"");}\n''','live weather label')
w=rep(w,
'''    @Override protected void onDraw(Canvas c){\n        super.onDraw(c);long now=System.currentTimeMillis();dayPhase=computeDayPhase(now);if(now>=nextWeatherChangeMs)chooseWeather(now,false);\n        int w=getWidth(),h=getHeight();if(w<=0||h<=0)return;float day01=((now-dayEpochMs)%DAY_CYCLE_MS)/(float)DAY_CYCLE_MS;if(day01<0)day01+=1f;\n        updateSharedCelestial(day01);drawTimeTint(c,w,h,now,day01);drawWeather(c,w,h,now);postInvalidateOnAnimation();\n    }\n\n    private int computeDayPhase(long now){float f=((now-dayEpochMs)%DAY_CYCLE_MS)/(float)DAY_CYCLE_MS;if(f<0)f+=1f;if(f<.14f)return DAWN;if(f<.34f)return MORNING;if(f<.58f)return NOON;if(f<.72f)return SUNSET;if(f<.82f)return EVENING;return NIGHT;}\n''',
'''    @Override protected void onDraw(Canvas c){\n        super.onDraw(c);long now=System.currentTimeMillis();RealWeatherCoordinator.requestIfNeeded();RealWeatherProfile live=RealWeatherCoordinator.getProfile();\n        float day01;if(live!=null){applyRealWeather(live);day01=(float)live.localDay01;dayPhase=computeDayPhase01(day01);}else{dayPhase=computeDayPhase(now);if(now>=nextWeatherChangeMs)chooseWeather(now,false);day01=((now-dayEpochMs)%DAY_CYCLE_MS)/(float)DAY_CYCLE_MS;if(day01<0)day01+=1f;}\n        int w=getWidth(),h=getHeight();if(w<=0||h<=0)return;\n        updateSharedCelestial(day01);drawTimeTint(c,w,h,now,day01);drawWeather(c,w,h,now);if(live!=null&&live.kind==RealWeatherProfile.FOG)drawLiveFog(c,w,h,live);if(live!=null&&live.kind==RealWeatherProfile.STORM)drawStormShade(c,w,h,now);postInvalidateOnAnimation();\n    }\n\n    private int computeDayPhase(long now){float f=((now-dayEpochMs)%DAY_CYCLE_MS)/(float)DAY_CYCLE_MS;if(f<0)f+=1f;return computeDayPhase01(f);}\n    private int computeDayPhase01(float f){if(f<.27f)return NIGHT;if(f<.32f)return DAWN;if(f<.45f)return MORNING;if(f<.68f)return NOON;if(f<.77f)return SUNSET;if(f<.83f)return EVENING;return NIGHT;}\n\n    private void applyRealWeather(RealWeatherProfile x){\n        if(x.kind==RealWeatherProfile.SNOW)weather=SNOW;else if(x.kind==RealWeatherProfile.RAIN||x.kind==RealWeatherProfile.STORM)weather=RAIN;else if(x.kind==RealWeatherProfile.CLOUDY||x.kind==RealWeatherProfile.FOG)weather=CLOUDY;else weather=CLEAR;\n        cloudCount=Math.max(1,Math.min(10,(int)Math.round(1+x.cloud01*9)));sharedCloudLayerCoverage=(float)clamp(Math.max(x.lowCloud01*.96,x.cloud01*.78),0,1);\n        windy=x.windSpeedMps>2.2;windStrength=(float)clamp(x.windSpeedMps/18.0,.05,1);float cross=RealWeatherCoordinator.crosswindMps(270.0);windSign=cross>=0?1:-1;sharedWindy=windy;sharedWindStrength=windStrength;sharedWindSign=windSign;\n    }\n\n    private void drawLiveFog(Canvas c,int w,int h,RealWeatherProfile x){float d=(float)clamp(.45+(1-x.visibilityM/10000.0)*.50,.45,.94);p.setShader(new LinearGradient(0,h*.08f,0,h,new int[]{0x18d9dfe0,((int)(150*d)<<24)|0x00d2d8d8,((int)(215*d)<<24)|0x00d8dcda},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);}\n    private void drawStormShade(Canvas c,int w,int h,long now){p.setColor(0x32111d26);c.drawRect(0,0,w,h,p);if(now%17000L<90){p.setColor(0x38ffffff);c.drawRect(0,0,w,h,p);}}\n''','live weather draw loop')
WEATHER.write_text(w)

# CinematicEnvironmentView: atmospheric perspective mountains + wind-driven sea.
c=CIN.read_text()
c=rep(c,
'''    private void drawBaseSkyBlend(Canvas c,int w,int h,float hz,int a,int b,float mix){\n        int top=mixColor(a==ARID?0xff287da8:0xff176a9c,b==ARID?0xff287da8:0xff176a9c,mix);\n        int mid=mixColor(a==ARID?0xff68b9d2:0xff43acd0,b==ARID?0xff68b9d2:0xff43acd0,mix);\n        int low=mixColor(a==ARID?0xffdfd7bd:0xffc8e9ef,b==ARID?0xffdfd7bd:0xffc8e9ef,mix);\n        p.setShader(new LinearGradient(0,0,0,hz,new int[]{top,mid,low},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,hz,p);p.setShader(null);\n        float haze=clamp(sharedAltitudeM/2200f,0f,1f);p.setColor(argb((int)(18+24*haze),0xe5eef0));c.drawRect(0,hz-h*.015f,w,hz+h*.025f,p);\n    }\n''',
'''    private void drawBaseSkyBlend(Canvas c,int w,int h,float hz,int a,int b,float mix){\n        float wxHaze=WeatherEffectsView.getSharedSkyHaze(),vis=clamp(WeatherEffectsView.getSharedVisibilityM()/30000f,0f,1f);\n        int clearTop=mixColor(a==ARID?0xff287da8:0xff176a9c,b==ARID?0xff287da8:0xff176a9c,mix),clearMid=mixColor(a==ARID?0xff68b9d2:0xff43acd0,b==ARID?0xff68b9d2:0xff43acd0,mix),clearLow=mixColor(a==ARID?0xffdfd7bd:0xffc8e9ef,b==ARID?0xffdfd7bd:0xffc8e9ef,mix);\n        int top=mixColor(clearTop,0xff667b87,wxHaze*.52f),mid=mixColor(clearMid,0xff93a5aa,wxHaze*.62f),low=mixColor(clearLow,0xffd0d5d3,wxHaze*.78f);\n        p.setShader(new LinearGradient(0,0,0,hz,new int[]{top,mid,low},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,hz,p);p.setShader(null);\n        float haze=clamp(wxHaze*.88f+clamp(sharedAltitudeM/2600f,0f,1f)*.18f+(1-vis)*.20f,0f,1f);p.setColor(argb((int)(18+105*haze),0xdce3e3));c.drawRect(0,hz-h*.022f,w,hz+h*(.025f+.050f*haze),p);\n    }\n''','weather sky realism')
c=rep(c,
'''    private void drawMountainValley(Canvas c,int w,int h,float hz,float local){\n        p.setShader(new LinearGradient(0,hz,0,h,new int[]{0xff829c69,0xff5f7f59,0xff3f6248},null,Shader.TileMode.CLAMP));c.drawRect(0,hz,w,h,p);p.setShader(null);\n        float pan=headingPan(w,.22f)+worldDistanceM*.012f;drawMountainLayer(c,w,h,hz,pan,.17f,0xff6b8968,1.2f);drawMountainLayer(c,w,h,hz,pan*.72f,.115f,0xff4d7359,2.0f);\n        float gh=h-hz;for(int i=0;i<34;i++){float q=.08f+((i*23)%33)/36f,y=hz+gh*q*q,x=wrap(i*117f-worldDistanceM*(.020f+.055f*q)+headingPan(w,.35f+.55f*q),w+w*.12f)-w*.06f,ww=w*(.012f+.043f*q);p.setColor(i%2==0?0x36577f43:0x2f3f6c3a);c.drawOval(x,y,x+ww,y+h*.006f+gh*.008f*q,p);}\n    }\n    private void drawMountainLayer(Canvas c,int w,int h,float hz,float pan,float scale,int color,float freq){path.reset();path.moveTo(0,hz);for(int i=0;i<=18;i++){float x=w*i/18f,n=.42f+.58f*Math.abs((float)Math.sin(i*freq+pan/w*2.2f));path.lineTo(x,hz-h*scale*n);}path.lineTo(w,hz);path.close();p.setColor(color);c.drawPath(path,p);}\n''',
'''    private void drawMountainValley(Canvas c,int w,int h,float hz,float local){\n        float haze=WeatherEffectsView.getSharedMountainHaze(),temp=WeatherEffectsView.getSharedTemperatureC(),humidity=WeatherEffectsView.getSharedHumidity01();\n        int grassTop=mixColor(0xff829c69,temp>28?0xffa89a62:0xff78976b,clamp(Math.abs(temp-18)/24f,0f,.55f)),grassNear=mixColor(0xff3f6248,humidity<.35f?0xff756446:0xff365b43,clamp(Math.abs(humidity-.55f),0f,.45f));\n        p.setShader(new LinearGradient(0,hz,0,h,new int[]{grassTop,0xff5f7f59,grassNear},null,Shader.TileMode.CLAMP));c.drawRect(0,hz,w,h,p);p.setShader(null);\n        float pan=headingPan(w,.22f)+worldDistanceM*.012f;drawMountainLayer(c,w,h,hz,pan*.42f,.205f,mixColor(0xff9aa3a1,0xff6f8179,1-haze),.82f);drawMountainLayer(c,w,h,hz,pan,.168f,mixColor(0xff7b887c,0xff607b62,1-haze*.55f),1.22f);drawMountainLayer(c,w,h,hz,pan*.72f,.116f,mixColor(0xff596c60,0xff456c52,1-haze*.35f),2.0f);drawSnowCaps(c,w,h,hz,pan,.168f,1.22f,clamp((4f-temp)/13f,0f,1f));\n        float gh=h-hz;for(int i=0;i<34;i++){float q=.08f+((i*23)%33)/36f,y=hz+gh*q*q,x=wrap(i*117f-worldDistanceM*(.020f+.055f*q)+headingPan(w,.35f+.55f*q),w+w*.12f)-w*.06f,ww=w*(.012f+.043f*q);p.setColor(i%2==0?0x36577f43:0x2f3f6c3a);c.drawOval(x,y,x+ww,y+h*.006f+gh*.008f*q,p);}\n        if(haze>.12f){p.setShader(new LinearGradient(0,hz-h*.24f,0,hz+h*.10f,new int[]{0x00d7dede,argb((int)(155*haze),0xd7dede)},null,Shader.TileMode.CLAMP));c.drawRect(0,hz-h*.28f,w,hz+h*.12f,p);p.setShader(null);}\n    }\n    private void drawMountainLayer(Canvas c,int w,int h,float hz,float pan,float scale,int color,float freq){path.reset();path.moveTo(0,hz);for(int i=0;i<=24;i++){float x=w*i/24f,n=.30f+.70f*Math.abs((float)(.62*Math.sin(i*freq+pan/w*2.2f)+.28*Math.sin(i*freq*.47+1.7)+.10*Math.sin(i*2.83)));path.lineTo(x,hz-h*scale*n);}path.lineTo(w,hz);path.close();p.setColor(color);c.drawPath(path,p);}\n    private void drawSnowCaps(Canvas c,int w,int h,float hz,float pan,float scale,float freq,float cold01){float snow=clamp(cold01,0f,1f);if(snow<.05f)return;for(int i=1;i<24;i+=3){float x=w*i/24f,n=.30f+.70f*Math.abs((float)(.62*Math.sin(i*freq+pan/w*2.2f)+.28*Math.sin(i*freq*.47+1.7)+.10*Math.sin(i*2.83))),peak=hz-h*scale*n,ww=w*(.014f+.018f*snow),hh=h*(.012f+.030f*snow);path.reset();path.moveTo(x-ww,peak+hh);path.lineTo(x,peak);path.lineTo(x+ww,peak+hh);path.lineTo(x+ww*.36f,peak+hh*.66f);path.lineTo(x,peak+hh*.40f);path.lineTo(x-ww*.32f,peak+hh*.70f);path.close();p.setColor(argb((int)(120+110*snow),0xf4f6f4));c.drawPath(path,p);}}\n''','mountain atmospheric realism')
c=rep(c,
'''    private void drawOpenOcean(Canvas c,int w,int h,float hz){\n        p.setShader(new LinearGradient(0,hz,0,h,new int[]{0xff3299b4,0xff126584,0xff073d59,0xff032c43},null,Shader.TileMode.CLAMP));c.drawRect(0,hz,w,h,p);p.setShader(null);p.setColor(0x70d9f2f4);c.drawRect(0,hz,w,hz+Math.max(2,h*.005f),p);\n        float low=clamp((120f-sharedAltitudeM)/120f,0,1),spd=clamp(sharedSpeedMps/270f,0,1),waveAmp=.45f+.75f*WeatherEffectsView.getSharedWindStrength();\n        for(int i=0;i<80;i++){float q=(i/80f+seaFlow*(.34f+spd*.90f))%1f,z=q*q,y=hz+(h-hz)*z,seg=w*(.012f+.075f*z)*(1f+.55f*spd),period=w+seg,yaw=headingPan(w,.20f+.80f*z),x=wrap(i*97.3f+clock*(12f+sharedSpeedMps*.36f)*(i%2==0?1f:-.45f)+yaw,period)-seg*.5f,dy=(float)Math.sin(i*1.73+clock*(1.8f+waveAmp))*h*(.0005f+.0032f*z)*waveAmp;int aa=(int)(30+88*z+45*low*z);stroke.setColor((Math.min(175,aa)<<24)|0x00bfeefa);stroke.setStrokeWidth(Math.max(1f,w*(.00045f+.0020f*z)));path.reset();path.moveTo(x,y+dy);path.quadTo(x+seg*.34f,y-dy*.55f,x+seg*.66f,y+dy*.22f);path.quadTo(x+seg*.84f,y-dy*.42f,x+seg,y+dy*.05f);c.drawPath(path,stroke);}\n        int caps=18+(int)(28*WeatherEffectsView.getSharedWindStrength());for(int i=0;i<caps;i++){float q=((i*.071f+seaFlow*.71f)%1f),z=.16f+.84f*q*q,y=hz+(h-hz)*z,period=w+w*.12f,x=wrap(i*131f+clock*sharedSpeedMps*.25f+headingPan(w,.30f+.70f*z),period)-w*.06f,len=w*(.006f+.032f*z)*(1f+.65f*low);stroke.setColor((int)(0x38+0x78*z)<<24|0x00ffffff);stroke.setStrokeWidth(Math.max(1f,w*(.0007f+.0022f*z)));c.drawLine(x,y,x+len,y+h*.0025f*z,stroke);}drawReflection(c,w,h,hz);\n    }\n''',
'''    private void drawOpenOcean(Canvas c,int w,int h,float hz){\n        float rough=WeatherEffectsView.getSharedSeaRoughness(),haze=WeatherEffectsView.getSharedSkyHaze(),cloud=WeatherEffectsView.getSharedCloudLayerCoverage();\n        int horizon=mixColor(0xff4aa8ba,0xff65777d,clamp(haze*.65f+cloud*.30f,0f,1f)),mid=mixColor(0xff126584,0xff294e59,clamp(haze*.40f+cloud*.22f,0f,1f)),deep=mixColor(0xff032c43,0xff102d36,clamp(haze*.28f+cloud*.18f,0f,1f));\n        p.setShader(new LinearGradient(0,hz,0,h,new int[]{horizon,mid,0xff073d59,deep},null,Shader.TileMode.CLAMP));c.drawRect(0,hz,w,h,p);p.setShader(null);p.setColor(argb((int)(55+80*(1-haze)),0xd9f2f4));c.drawRect(0,hz,w,hz+Math.max(2,h*(.004f+.004f*haze)),p);\n        float low=clamp((140f-sharedAltitudeM)/140f,0,1),spd=clamp(sharedSpeedMps/270f,0,1),waveAmp=.28f+1.55f*rough;int lines=90+(int)(55*rough);\n        for(int i=0;i<lines;i++){float q=(i/(float)lines+seaFlow*(.28f+spd*.86f))%1f,z=q*q,y=hz+(h-hz)*z,seg=w*(.008f+.085f*z)*(1f+.50f*spd)*(1f+.22f*rough),period=w+seg,yaw=headingPan(w,.18f+.82f*z),x=wrap(i*91.7f+clock*(8f+sharedSpeedMps*.31f)*(i%2==0?1f:-.38f)+yaw,period)-seg*.5f,phase=i*1.67f+clock*(1.2f+2.8f*rough),dy=(float)Math.sin(phase)*h*(.00035f+.0046f*z)*waveAmp;int aa=(int)(22+95*z+55*low*z+25*rough);stroke.setColor((Math.min(190,aa)<<24)|0x00bfeefa);stroke.setStrokeWidth(Math.max(1f,w*(.00035f+.0022f*z)));path.reset();path.moveTo(x,y+dy);path.cubicTo(x+seg*.22f,y-dy*.75f,x+seg*.45f,y+dy*.55f,x+seg*.66f,y-dy*.20f);path.cubicTo(x+seg*.80f,y-dy*.55f,x+seg*.92f,y+dy*.32f,x+seg,y+dy*.06f);c.drawPath(path,stroke);}\n        int caps=rough<.28f?4:(int)(8+70*rough);for(int i=0;i<caps;i++){float q=((i*.061f+seaFlow*(.52f+.34f*rough))%1f),z=.12f+.88f*q*q,y=hz+(h-hz)*z,period=w+w*.12f,x=wrap(i*127f+clock*sharedSpeedMps*.20f+headingPan(w,.25f+.75f*z),period)-w*.06f,len=w*(.004f+.040f*z)*(.45f+rough)*(1f+.55f*low);int alpha=(int)((35+145*z)*rough);stroke.setColor((Math.min(190,alpha)<<24)|0x00ffffff);stroke.setStrokeWidth(Math.max(1f,w*(.0006f+.0025f*z)));c.drawLine(x,y,x+len,y+h*.0028f*z,stroke);}\n        drawReflection(c,w,h,hz);\n    }\n''','realistic sea roughness')
CIN.write_text(c)

r=RUNTIME.read_text();r=rep(r,'        String wx=weather==null?"":weather.getModeLabel();\n','        WeatherEffectsView.setWeatherLocation(state.latitudeDeg,state.longitudeDeg);\n        String wx=weather==null?"":weather.getModeLabel();\n','runtime weather location');RUNTIME.write_text(r)
p=PILOT.read_text();p=rep(p,'        String phase=mission.getPhase().name();double along=autoSceneAlong();\n','        String phase=mission.getPhase().name();double along=autoSceneAlong();WeatherEffectsView.setWeatherLocation(state.latitudeDeg,state.longitudeDeg);\n','pilot weather location');PILOT.write_text(p)

mf=MANIFEST.read_text();mf=rep(mf,'<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n','<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n    <uses-permission android:name="android.permission.INTERNET" />\n','internet permission');MANIFEST.write_text(mf)

g=GRADLE.read_text();g=re.sub(r'versionCode\s+\d+','versionCode 106',g,count=1);g=re.sub(r"versionName\s+['\"][^'\"]+['\"]","versionName '26.24-avm33.0-dynamic-real-weather-world'",g,count=1);GRADLE.write_text(g)
print('v106 applied: live current weather, atmospheric mountains/sky, wind-driven sea')
