from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
REAL=ROOT/'app/src/main/java/com/mg/fixturecockpitsim/visual/RealisticFighterMesh.java'
CTRL=ROOT/'app/src/main/java/com/mg/fixturecockpitsim/visual/AircraftControlSurfaces.java'
MECH=ROOT/'app/src/main/java/com/mg/fixturecockpitsim/visual/MechanicalDynamicsOverlay.java'
JET=ROOT/'app/src/main/java/com/mg/fixturecockpitsim/Jet3DView.java'


def rep(text, old, new, label):
    if new in text:
        return text
    if old not in text:
        raise SystemExit(f'v88 wing patch anchor missing: {label}')
    return text.replace(old, new, 1)

# ---------------------------------------------------------------------------
# 4-5-6: primary aircraft geometry
# ---------------------------------------------------------------------------
r=REAL.read_text()
r=rep(r,
'''            HEAT_SHIELD=28f, DETAIL=29f;\n''',
'''            HEAT_SHIELD=28f, DETAIL=29f, LE_FLAP_L=50f, LE_FLAP_R=51f;\n''','LE flap part ids')

r=rep(r,
'''        b.fixedWing(-1f); b.fixedWing(1f);\n        b.wingLeadingEdge(-1f); b.wingLeadingEdge(1f);\n        b.fixedFin(-1f); b.fixedFin(1f);\n''',
'''        b.fixedWing(-1f); b.fixedWing(1f);\n        b.wingLeadingEdge(-1f); b.wingLeadingEdge(1f);\n        b.part=LE_FLAP_L; b.leadingEdgeFlap(-1f);\n        b.part=LE_FLAP_R; b.leadingEdgeFlap(1f);\n        b.part=DETAIL; b.wingHingeCavities(-1f); b.wingHingeCavities(1f);\n        b.part=SKIN;\n        b.fixedFin(-1f); b.fixedFin(1f);\n''','separate leading edge controls')

old='''    private void fixedWing(float side){\n        airfoil(new float[][]{\n                {.78f*side,-2.76f},{1.12f*side,-2.60f},{2.16f*side,-2.02f},{3.34f*side,-1.34f},{4.45f*side,-.69f},{5.30f*side,-.18f},\n                {5.12f*side,.04f},{4.50f*side,.48f},{3.56f*side,.69f},{2.32f*side,.72f},{1.28f*side,.72f},{.86f*side,.48f}\n        },.32f,.105f);\n    }\n\n    private void wingLeadingEdge(float side){\n        part=DETAIL;\n        ribbon(new float[][]{{.82f*side,.43f,-2.72f},{1.30f*side,.40f,-2.48f},{2.26f*side,.33f,-1.94f},{3.38f*side,.27f,-1.30f},{4.47f*side,.20f,-.66f},{5.28f*side,.145f,-.18f}},.020f,.026f);\n        part=SKIN;\n    }\n\n    private void flaperon(float side){\n        airfoil(new float[][]{{1.25f*side,.70f},{2.25f*side,.71f},{3.55f*side,.67f},{4.50f*side,.50f},{4.15f*side,1.12f},{3.22f*side,1.40f},{1.40f*side,1.48f}},.245f,.060f);\n    }\n'''
new='''    /** v88 refined main wing: cambered airfoil, rounded nose and spanwise taper. */\n    private void fixedWing(float side){\n        wingSurface(side,0f,1f,0f);\n    }\n\n    /** The former raised leading-edge rail is removed; the airfoil itself forms the nose. */\n    private void wingLeadingEdge(float side){\n        // Intentionally empty: rounded leading edge is generated by wingSurface().\n    }\n\n    /** Independent leading-edge flap shell. It sits flush at neutral and exposes the hinge cavity when deflected. */\n    private void leadingEdgeFlap(float side){\n        wingSurface(side,0f,.175f,.006f);\n    }\n\n    /** Dark recessed hinge lines for both the leading-edge flap and the trailing flaperon. */\n    private void wingHingeCavities(float side){\n        float s=side;\n        ribbon(new float[][]{\n                {1.04f*s,.397f,-2.13f},{1.72f*s,.350f,-1.76f},{2.55f*s,.300f,-1.29f},\n                {3.42f*s,.246f,-.82f},{4.18f*s,.202f,-.43f},{4.72f*s,.170f,-.19f}\n        },.040f,.034f);\n        ribbon(new float[][]{\n                {1.28f*s,.282f,.735f},{2.20f*s,.260f,.735f},{3.15f*s,.232f,.710f},\n                {3.92f*s,.205f,.625f},{4.48f*s,.180f,.505f}\n        },.050f,.040f);\n    }\n\n    private void wingSurface(float side,float f0,float f1,float yBias){\n        final float[] sx={.78f,1.28f,2.32f,3.56f,4.50f,5.30f};\n        final float[] le={-2.76f,-2.48f,-1.90f,-1.20f,-.58f,-.18f};\n        final float[] te={.48f,.72f,.72f,.69f,.48f,.04f};\n        final float[] yc={.318f,.310f,.286f,.247f,.204f,.164f};\n        final float[] ht={.118f,.108f,.088f,.066f,.044f,.017f};\n        final float[] q={0f,.012f,.032f,.065f,.11f,.18f,.28f,.40f,.54f,.68f,.80f,.90f,.965f,1f};\n        for(int s=0;s<sx.length-1;s++) for(int i=0;i<q.length-1;i++){\n            float a=f0+(f1-f0)*q[i],b=f0+(f1-f0)*q[i+1];\n            V at=wingV(side,sx[s],le[s],te[s],yc[s],ht[s],a,true,yBias);\n            V bt=wingV(side,sx[s+1],le[s+1],te[s+1],yc[s+1],ht[s+1],a,true,yBias);\n            V ct=wingV(side,sx[s+1],le[s+1],te[s+1],yc[s+1],ht[s+1],b,true,yBias);\n            V dt=wingV(side,sx[s],le[s],te[s],yc[s],ht[s],b,true,yBias);\n            quadSmooth(at,bt,ct,dt);\n            V ab=wingV(side,sx[s],le[s],te[s],yc[s],ht[s],a,false,yBias);\n            V db=wingV(side,sx[s],le[s],te[s],yc[s],ht[s],b,false,yBias);\n            V cb=wingV(side,sx[s+1],le[s+1],te[s+1],yc[s+1],ht[s+1],b,false,yBias);\n            V bb=wingV(side,sx[s+1],le[s+1],te[s+1],yc[s+1],ht[s+1],a,false,yBias);\n            quadSmooth(ab,db,cb,bb);\n        }\n        // Root/tip caps only; leading and trailing edges close naturally because the thickness law tends to zero.\n        for(int end:new int[]{0,sx.length-1}) for(int i=0;i<q.length-1;i++){\n            float a=f0+(f1-f0)*q[i],b=f0+(f1-f0)*q[i+1];\n            V A=wingV(side,sx[end],le[end],te[end],yc[end],ht[end],a,true,yBias);\n            V B=wingV(side,sx[end],le[end],te[end],yc[end],ht[end],b,true,yBias);\n            V C=wingV(side,sx[end],le[end],te[end],yc[end],ht[end],b,false,yBias);\n            V D=wingV(side,sx[end],le[end],te[end],yc[end],ht[end],a,false,yBias);\n            quad(new float[]{A.x,A.y,A.z},new float[]{B.x,B.y,B.z},new float[]{C.x,C.y,C.z},new float[]{D.x,D.y,D.z});\n        }\n    }\n\n    private V wingV(float side,float span,float zLe,float zTe,float yCenter,float half,float f,boolean top,float yBias){\n        f=Math.max(0f,Math.min(1f,f));\n        float z=zLe+(zTe-zLe)*f;\n        float sh=wingThicknessShape(f);\n        float rootFactor=1f-span/5.65f;\n        float camber=(.0045f+.017f*Math.max(0f,rootFactor))*4f*f*(1f-f);\n        float sign=top?1f:-1f;\n        float y=yCenter+camber+sign*half*sh+yBias;\n        float e=.0025f,fa=Math.max(0f,f-e),fb=Math.min(1f,f+e);\n        float ya=(.0045f+.017f*Math.max(0f,rootFactor))*4f*fa*(1f-fa)+sign*half*wingThicknessShape(fa);\n        float yb=(.0045f+.017f*Math.max(0f,rootFactor))*4f*fb*(1f-fb)+sign*half*wingThicknessShape(fb);\n        float dydz=(yb-ya)/Math.max(.0005f,(zTe-zLe)*(fb-fa));\n        return new V(span*side,y,z,0f,sign,-sign*dydz);\n    }\n\n    private float wingThicknessShape(float x){\n        x=Math.max(0f,Math.min(1f,x));\n        float raw=5f*(.2969f*(float)Math.sqrt(x)-.1260f*x-.3516f*x*x+.2843f*x*x*x-.1036f*x*x*x*x);\n        return Math.max(0f,Math.min(1.05f,2.02f*raw));\n    }\n\n    private void flaperon(float side){\n        // Small real hinge gap is left ahead of the flaperon; the cavity is generated separately.\n        airfoil(new float[][]{{1.28f*side,.795f},{2.24f*side,.795f},{3.52f*side,.755f},{4.48f*side,.555f},{4.15f*side,1.12f},{3.22f*side,1.40f},{1.40f*side,1.48f}},.245f,.052f);\n    }\n'''
r=rep(r,old,new,'real wing airfoil and hinge cavities')

old='''    private void wingRootFairing(float side){\n        prism(new float[][]{{.69f*side,.61f,-2.75f},{1.02f*side,.55f,-2.48f},{1.48f*side,.47f,-1.92f},{1.75f*side,.41f,-1.22f},{1.72f*side,.40f,-.44f},{1.50f*side,.42f,.28f},{1.16f*side,.49f,.88f},{.86f*side,.57f,1.02f},{.72f*side,.63f,.20f}},.024f);\n    }\n'''
new='''    /** Smooth wing-body blend; replaces the old thin plate-like root fairing. */\n    private void wingRootFairing(float side){\n        float saved=part;part=SKIN;\n        final float[] sx={.48f,.66f,.86f,1.10f,1.36f,1.62f,1.80f};\n        final float[] le={-3.08f,-2.98f,-2.83f,-2.57f,-2.20f,-1.78f,-1.42f};\n        final float[] te={1.30f,1.23f,1.14f,1.04f,.92f,.80f,.70f};\n        final float[] yc={.480f,.455f,.425f,.390f,.355f,.330f,.312f};\n        final float[] ht={.235f,.215f,.185f,.150f,.115f,.087f,.066f};\n        final float[] q={0f,.025f,.07f,.14f,.25f,.40f,.56f,.72f,.85f,.94f,.985f,1f};\n        for(int s=0;s<sx.length-1;s++)for(int i=0;i<q.length-1;i++){\n            V A=fairV(side,sx[s],le[s],te[s],yc[s],ht[s],q[i],true);\n            V B=fairV(side,sx[s+1],le[s+1],te[s+1],yc[s+1],ht[s+1],q[i],true);\n            V C=fairV(side,sx[s+1],le[s+1],te[s+1],yc[s+1],ht[s+1],q[i+1],true);\n            V D=fairV(side,sx[s],le[s],te[s],yc[s],ht[s],q[i+1],true);quadSmooth(A,B,C,D);\n            V a=fairV(side,sx[s],le[s],te[s],yc[s],ht[s],q[i],false);\n            V d=fairV(side,sx[s],le[s],te[s],yc[s],ht[s],q[i+1],false);\n            V c=fairV(side,sx[s+1],le[s+1],te[s+1],yc[s+1],ht[s+1],q[i+1],false);\n            V b=fairV(side,sx[s+1],le[s+1],te[s+1],yc[s+1],ht[s+1],q[i],false);quadSmooth(a,d,c,b);\n        }\n        part=saved;\n    }\n\n    private V fairV(float side,float span,float zLe,float zTe,float yc,float ht,float f,boolean top){\n        float z=zLe+(zTe-zLe)*f;\n        float sh=(float)Math.pow(Math.max(0f,Math.sin(Math.PI*f)),.62);\n        float sign=top?1f:-1f;\n        float y=yc+sign*ht*sh;\n        float e=.003f,fa=Math.max(0f,f-e),fb=Math.min(1f,f+e);\n        float ya=sign*ht*(float)Math.pow(Math.max(0f,Math.sin(Math.PI*fa)),.62);\n        float yb=sign*ht*(float)Math.pow(Math.max(0f,Math.sin(Math.PI*fb)),.62);\n        float dydz=(yb-ya)/Math.max(.0005f,(zTe-zLe)*(fb-fa));\n        return new V(span*side,y,z,0f,sign,-sign*dydz);\n    }\n'''
r=rep(r,old,new,'smooth wing body fairing')
REAL.write_text(r)

# ---------------------------------------------------------------------------
# Control law: independent automatic leading-edge flap commands.
# ---------------------------------------------------------------------------
c=CTRL.read_text()
c=rep(c,
'''    public float rightFlaperonDeg;\n    public float nozzle01;\n''',
'''    public float rightFlaperonDeg;\n    public float leftLeadingEdgeFlapDeg;\n    public float rightLeadingEdgeFlapDeg;\n    public float nozzle01;\n''','LE control fields')
c=rep(c,
'''        rightFlaperonDeg = clampDeg(-pitch * 8f - roll * 18f, 24f);\n        leftRudderDeg = clampDeg(yaw * 24f, 24f);\n''',
'''        rightFlaperonDeg = clampDeg(-pitch * 8f - roll * 18f, 24f);\n        float autoLe = 2f + Math.max(0f,pitch)*14f + Math.max(0f,.42f-throttle)*8f;\n        leftLeadingEdgeFlapDeg = Math.max(0f,Math.min(18f,autoLe-roll*1.5f));\n        rightLeadingEdgeFlapDeg = Math.max(0f,Math.min(18f,autoLe+roll*1.5f));\n        leftRudderDeg = clampDeg(yaw * 24f, 24f);\n''','LE automatic schedule')
CTRL.write_text(c)

# ---------------------------------------------------------------------------
# Mechanical hinge barrels and actuator arms for the new leading-edge flaps.
# ---------------------------------------------------------------------------
m=MECH.read_text()
m=rep(m,
'''            NOZZLE_PETAL=21f, HEAT_SHIELD=28f, PYLON=30f;\n''',
'''            NOZZLE_PETAL=21f, HEAT_SHIELD=28f, DETAIL=29f, PYLON=30f,\n            LE_FLAP_L=50f, LE_FLAP_R=51f;\n''','LE mechanical ids')
m=rep(m,
'''        b.controlSurfaceMechanics();\n        b.nozzleMechanics();\n''',
'''        b.controlSurfaceMechanics();\n        b.leadingEdgeFlapMechanics();\n        b.nozzleMechanics();\n''','LE mechanical build')
anchor='''    /** 12-13: synchronising rings, petal jacks and spherical pivots. */\n    private void nozzleMechanics(){\n'''
method='''    /** Leading-edge hinge barrels, crank arms and moving actuator brackets. */\n    private void leadingEdgeFlapMechanics(){\n        for(float side:new float[]{-1f,1f}){\n            float[] xs={1.05f,1.78f,2.58f,3.40f,4.18f,4.70f};\n            float[] ys={.365f,.325f,.278f,.230f,.195f,.168f};\n            float[] zs={-2.12f,-1.73f,-1.28f,-.83f,-.43f,-.19f};\n            part=DETAIL;\n            for(int i=0;i<xs.length-1;i++)\n                cylinderBetween(xs[i]*side,ys[i],zs[i],xs[i+1]*side,ys[i+1],zs[i+1],.018f,9);\n            part=side<0f?LE_FLAP_L:LE_FLAP_R;\n            for(int i=1;i<xs.length-1;i++){\n                float x=xs[i]*side,y=ys[i],z=zs[i];\n                ellipsoid(x,y,z,.034f,.026f,.038f,9,6);\n                cylinderBetween(x,y,z,x,y-.080f,z-.115f,.013f,8);\n                cylinderBetween(x,y-.080f,z-.115f,x+.095f*side,y-.105f,z-.155f,.010f,7);\n            }\n        }\n    }\n\n'''
m=rep(m,anchor,method+anchor,'LE hinge mechanics method')
MECH.write_text(m)

# ---------------------------------------------------------------------------
# Renderer: two extra animated control parts (50/51).
# This script runs after apply_v88_mechanical_upgrade.py, so anchors reflect that state.
# ---------------------------------------------------------------------------
j=JET.read_text()
j=rep(j,
'''        volatile float tr,tp,ty,thr=.6f,tg=1,tm,tn,ws,speed,vertical,tsl,tsr,trl,trr,tfl,tfr,tvec;\n''',
'''        volatile float tr,tp,ty,thr=.6f,tg=1,tm,tn,ws,speed,vertical,tsl,tsr,trl,trr,tfl,tfr,tleL,tleR,tvec;\n''','LE target fields')
j=rep(j,
'''        float roll,pitch,yaw,gear=1,mc,nc,spin,aspect=1.7f,t,sl,sr,rl,rrd,fl,fr,vec,camX,camY,camZ;\n''',
'''        float roll,pitch,yaw,gear=1,mc,nc,spin,aspect=1.7f,t,sl,sr,rl,rrd,fl,fr,leL,leR,vec,camX,camY,camZ;\n''','LE smoothed fields')
j=rep(j,
'''        int pg,ap,an,apart,umvp,umodel,uc,ul,ut,ug,um,un,uws,usl,usr,url,urr,ufl,ufr,uvec,utime,ucam,uspeed,uair,uroll,ubird;\n''',
'''        int pg,ap,an,apart,umvp,umodel,uc,ul,ut,ug,um,un,uws,usl,usr,url,urr,ufl,ufr,ulel,uler,uvec,utime,ucam,uspeed,uair,uroll,ubird;\n''','LE uniform handles')
j=rep(j,
'''        synchronized void controls(float p,float r,float y,float th){map.update(p,r,y,th);tsl=map.leftStabilatorDeg;tsr=map.rightStabilatorDeg;trl=map.leftRudderDeg;trr=map.rightRudderDeg;tfl=map.leftFlaperonDeg;tfr=map.rightFlaperonDeg;tvec=cl(p,-1,1)*8f;}\n''',
'''        synchronized void controls(float p,float r,float y,float th){map.update(p,r,y,th);tsl=map.leftStabilatorDeg;tsr=map.rightStabilatorDeg;trl=map.leftRudderDeg;trr=map.rightRudderDeg;tfl=map.leftFlaperonDeg;tfr=map.rightFlaperonDeg;tleL=map.leftLeadingEdgeFlapDeg;tleR=map.rightLeadingEdgeFlapDeg;tvec=cl(p,-1,1)*8f;}\n''','LE command mapping')
j=rep(j,
'''ufl=GLES20.glGetUniformLocation(pg,"uFlapL");ufr=GLES20.glGetUniformLocation(pg,"uFlapR");uvec=GLES20.glGetUniformLocation(pg,"uVector");''',
'''ufl=GLES20.glGetUniformLocation(pg,"uFlapL");ufr=GLES20.glGetUniformLocation(pg,"uFlapR");ulel=GLES20.glGetUniformLocation(pg,"uLeFlapL");uler=GLES20.glGetUniformLocation(pg,"uLeFlapR");uvec=GLES20.glGetUniformLocation(pg,"uVector");''','LE uniform lookup')
j=rep(j,
'''sl+=(tsl-sl)*ks;sr+=(tsr-sr)*ks;rl+=(trl-rl)*ks;rrd+=(trr-rrd)*ks;fl+=(tfl-fl)*ks;fr+=(tfr-fr)*ks;vec+=(tvec-vec)*ks;''',
'''sl+=(tsl-sl)*ks;sr+=(tsr-sr)*ks;rl+=(trl-rl)*ks;rrd+=(trr-rrd)*ks;fl+=(tfl-fl)*ks;fr+=(tfr-fr)*ks;leL+=(tleL-leL)*ks;leR+=(tleR-leR)*ks;vec+=(tvec-vec)*ks;''','LE smoothing')
j=rep(j,
'''GLES20.glUniform1f(ufl,fl);GLES20.glUniform1f(ufr,fr);GLES20.glUniform1f(uvec,vec);''',
'''GLES20.glUniform1f(ufl,fl);GLES20.glUniform1f(ufr,fr);GLES20.glUniform1f(ulel,leL);GLES20.glUniform1f(uler,leR);GLES20.glUniform1f(uvec,vec);''','LE uniform upload')
j=rep(j,
'''uniform float uThrottle,uGear,uMainComp,uNoseComp,uWheelSpin,uStabL,uStabR,uRudderL,uRudderR,uFlapL,uFlapR,uVector,uTime,uBirdAge;''',
'''uniform float uThrottle,uGear,uMainComp,uNoseComp,uWheelSpin,uStabL,uStabR,uRudderL,uRudderR,uFlapL,uFlapR,uLeFlapL,uLeFlapR,uVector,uTime,uBirdAge;''','LE shader uniforms')
needle='''else if(aPart>9.5&&aPart<10.5){float a=uFlapR*d;vec2 piv=vec2(.22,.70);p.yz=rr(a)*(p.yz-piv)+piv;n.yz=rr(a)*n.yz;}\"+\n'''
repl='''else if(aPart>9.5&&aPart<10.5){float a=uFlapR*d;vec2 piv=vec2(.22,.70);p.yz=rr(a)*(p.yz-piv)+piv;n.yz=rr(a)*n.yz;}\"+\n                \"if(aPart>49.5&&aPart<51.5){float a=(aPart<50.5?uLeFlapL:uLeFlapR)*d;float hz=-2.65+.50*abs(p.x);vec2 piv=vec2(.31,hz);p.yz=rr(-a)*(p.yz-piv)+piv;n.yz=rr(-a)*n.yz;}\"+\n'''
j=rep(j,needle,repl,'LE flap shader transform')
JET.write_text(j)

print('v88 wing geometry applied: smooth wing-body fairing, tapered airfoil, independent LE flap and visible hinge cavities')
