package com.mg.whiffletreeaero;

import android.app.*;
import android.os.Bundle;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
  final int NAVY=Color.rgb(7,20,34),PANEL=Color.rgb(16,36,55),BLUE=Color.rgb(55,132,238),CYAN=Color.rgb(51,205,220),ORANGE=Color.rgb(245,164,47),GREEN=Color.rgb(67,190,113),YELLOW=Color.rgb(247,207,77),RED=Color.rgb(229,82,74),STEEL=Color.rgb(160,180,198);
  LinearLayout root,inputs; RigView rig; TextView status,result,levelText; Spinner loadCase,viewMode,qProfile; EditText L,D,F,M,stations,layers,actCount,actCapacity,pressure,sf,padW,padL,deflection,linkLength,beamSpan,beamH,beamB,pinAllow,bearingAllow; SeekBar level;
  String[] CASES={"+Z Bending","-Z Bending","+Y Bending","-Y Bending","Pitch +My","Pitch -My","Roll +Mx","Roll -Mx","Yaw +Mz","Yaw -Mz","Combined Z+Pitch"};
  String[] VIEWS={"Side View","Top View","Front View","Symbolic Tree","Mechanical Rig","Beam Detail","Pin/Clevis Detail","Hydraulic Schematic","BOM"};
  String[] Q={"Elliptic","Uniform","Triangular root-high","Triangular tip-high","Parabolic"};

  @Override public void onCreate(Bundle b){super.onCreate(b);
    ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(10),dp(10),dp(10),dp(30));root.setBackgroundColor(NAVY);sv.addView(root);
    root.addView(tx("EFT WHIFFLETREE DIGITAL ENGINEER",25,true,Color.WHITE));root.addView(tx("v1.7 • Professional 2D details • Beam/Pin/Clevis • Hydraulic schematic",12,false,Color.rgb(180,205,225)));
    LinearLayout selectors=new LinearLayout(this);selectors.setOrientation(LinearLayout.HORIZONTAL);loadCase=spin(CASES);viewMode=spin(VIEWS);selectors.addView(loadCase,new LinearLayout.LayoutParams(0,dp(50),1));selectors.addView(viewMode,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(selectors,lp());
    status=card("Hazır",Color.rgb(13,47,70));root.addView(status,lp());
    rig=new RigView();root.addView(rig,new LinearLayout.LayoutParams(-1,dp(650)));
    LinearLayout lb=new LinearLayout(this);lb.setOrientation(LinearLayout.VERTICAL);lb.setPadding(dp(8),dp(4),dp(8),dp(4));lb.setBackground(bg(PANEL,10));levelText=tx("Load level: 100%",13,true,Color.WHITE);level=new SeekBar(this);level.setMax(100);level.setProgress(100);lb.addView(levelText);lb.addView(level);root.addView(lb,lp());
    inputs=new LinearLayout(this);inputs.setOrientation(LinearLayout.VERTICAL);inputs.setPadding(dp(10),dp(10),dp(10),dp(10));inputs.setBackground(bg(PANEL,12));root.addView(inputs,lp());inputs.addView(tx("DESIGN INPUTS — defaults are editable",17,true,Color.WHITE));
    F=field("Target total load [kN]","305.7");M=field("Target moment [kN·m]","1280");L=field("Tank length [m]","7.6");D=field("Tank diameter [m]","0.64");stations=field("Station count (4-16)","12");inputs.addView(tx("q(x) profile",12,true,Color.rgb(185,210,230)));qProfile=spin(Q);inputs.addView(qProfile,lp());layers=field("Whiffletree layers (1-3)","3");actCount=field("Actuator count (1-8)","4");actCapacity=field("Actuator nominal capacity [kN]","120");pressure=field("Hydraulic pressure [bar]","210");sf=field("Sizing factor","1.50");padW=field("Load pad width [mm]","150");padL=field("Load pad length [mm]","250");deflection=field("Expected max EFT deflection [mm]","60");linkLength=field("Nominal link length [mm]","600");beamSpan=field("Typical whiffletree beam span [mm]","600");beamH=field("Beam section height h [mm]","80");beamB=field("Beam section width b [mm]","40");pinAllow=field("Pin allowable shear [MPa] (training)","180");bearingAllow=field("Lug allowable bearing [MPa] (training)","250");
    Button auto=new Button(this);auto.setText("AUTO OPTIMIZE ACTUATOR COUNT");auto.setOnClickListener(v->{try{Calc c=compute(true);actCount.setText(String.valueOf(c.nAct));preview(c);result.setText("Auto topology: "+c.nAct+" actuators. All 2D/detail/BOM views updated.");}catch(Exception e){}});inputs.addView(auto,lp());Button calc=new Button(this);calc.setText("HESAPLA + TÜM ÇİZİMLERİ GÜNCELLE");calc.setOnClickListener(v->calculate());inputs.addView(calc,lp());
    result=card("View menüsünden Side/Top/Front, Symbolic, Mechanical, Beam, Pin/Clevis, Hydraulic ve BOM ekranlarını seçebilirsin.",Color.rgb(12,34,52));result.setTextSize(13);root.addView(result,lp());
    root.addView(card("Ön tasarım/eğitim aracıdır. Nihai boyutlar onaylı loads report, FEM, malzeme allowables, gerçek katalog ratingleri ve kurum prosedürü ile doğrulanmalıdır.",Color.rgb(66,46,12)),lp());
    TextWatcher tw=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){safe();}public void afterTextChanged(Editable e){}};for(EditText e:new EditText[]{F,M,L,D,stations,layers,actCount,actCapacity,pressure,sf,padW,padL,deflection,linkLength,beamSpan,beamH,beamB,pinAllow,bearingAllow})e.addTextChangedListener(tw);
    android.widget.AdapterView.OnItemSelectedListener lis=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){safe();}public void onNothingSelected(android.widget.AdapterView<?>p){}};loadCase.setOnItemSelectedListener(lis);viewMode.setOnItemSelectedListener(lis);qProfile.setOnItemSelectedListener(lis);level.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean u){levelText.setText("Load level: "+p+"%");safe();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});
    setContentView(sv);safe();
  }

  Spinner spin(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
  EditText field(String label,String def){inputs.addView(tx(label,12,true,Color.rgb(185,210,230)));EditText e=new EditText(this);e.setText(def);e.setTextColor(Color.WHITE);e.setTextSize(16);e.setSingleLine(true);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);e.setBackground(bg(Color.rgb(25,52,75),8));e.setPadding(dp(10),0,dp(10),0);inputs.addView(e,new LinearLayout.LayoutParams(-1,dp(44)));return e;}
  void safe(){try{preview(compute(false));}catch(Exception ignored){}}
  void preview(Calc c){rig.set(c,loadCase.getSelectedItemPosition(),viewMode.getSelectedItemPosition(),level.getProgress()/100.0);status.setText(String.format(Locale.US,"%s • %s • S%d L%d A%d • ΣF %.1f kN • M %.1f kN·m",CASES[loadCase.getSelectedItemPosition()],VIEWS[viewMode.getSelectedItemPosition()],c.n,c.layers,c.nAct,c.sumF,c.calcM));}
  void calculate(){try{Calc c=compute(false);preview(c);StringBuilder s=new StringBuilder();s.append("EFT ENGINEERING SUMMARY\n\n");s.append(String.format(Locale.US,"Case: %s\nTank L/D %.2f / %.2f m\nStations %d | Layers %d | Actuators %d\nΣF %.1f kN | M %.1f kN·m | M error %.2f%%\n\n",CASES[loadCase.getSelectedItemPosition()],c.L,c.D,c.n,c.layers,c.nAct,c.sumF,c.calcM,c.mErr));s.append(String.format(Locale.US,"Actuator demand %.1f kN | bore %.1f mm @ %.0f bar\nLoad cell preselect ≥ %.0f kN\nStroke envelope %.1f mm | link angle %.1f°\n\n",c.actLoad,c.bore,c.pbar,c.lc,c.strokeReq,c.linkAngle));s.append(String.format(Locale.US,"Beam precheck: Mmax %.2f kN·m | σ %.1f MPa | defl %.2f mm\nPin precheck: d_req %.1f mm | selected schematic Ø%.0f mm\nClevis/lug min t (bearing-only precheck): %.1f mm\nPad mean pressure %.2f MPa\n\n",c.beamM,c.beamStress,c.beamDefl,c.pinReq,c.pinSel,c.lugT,c.padPressure));s.append("TREE\n").append(c.tree).append("\nBOM\n").append(c.bom).append("\nGATES\n").append(c.gates);result.setText(s.toString());}catch(Exception e){result.setText("Girişleri kontrol et.");}}

  Calc compute(boolean opt){Calc c=new Calc();c.L=Math.max(.5,d(L));c.D=Math.max(.1,d(D));c.targetF=Math.abs(d(F));c.targetM=d(M);c.n=clamp((int)Math.round(d(stations)),4,16);c.layers=clamp((int)Math.round(d(layers)),1,3);double cap=Math.max(1,d(actCapacity));c.pbar=Math.max(1,d(pressure));c.sf=Math.max(1,d(sf));c.designF=c.targetF*c.sf;int manual=clamp((int)Math.round(d(actCount)),1,8);int minCap=(int)Math.ceil(c.designF/cap);int minTopo=Math.max(1,(int)Math.ceil(c.n/Math.pow(2,c.layers)));c.nAct=opt?clamp(Math.max(minCap,minTopo),1,8):manual;c.actLoad=c.designF/c.nAct;c.bore=Math.sqrt(4*(c.actLoad*1000)/(c.pbar*100000)/Math.PI)*1000;c.lc=std(c.actLoad*1.2);
    c.x=new double[c.n];c.fi=new double[c.n];double[] w=new double[c.n];double sw=0;int q=qProfile.getSelectedItemPosition();for(int i=0;i<c.n;i++){double u=(i+.5)/c.n;c.x[i]=u*c.L;if(q==0)w[i]=Math.sqrt(Math.max(0,1-Math.pow(2*u-1,2)))+.05;else if(q==1)w[i]=1;else if(q==2)w[i]=1.15-u;else if(q==3)w[i]=.15+u;else w[i]=.25+4*u*(1-u);sw+=w[i];}for(int i=0;i<c.n;i++)c.fi[i]=c.targetF*w[i]/sw;
    double desired=Math.abs(c.targetM),base=0;for(int i=0;i<c.n;i++)base+=c.fi[i]*c.x[i];double mean=0;for(double xx:c.x)mean+=xx;mean/=c.n;double den=0;for(double xx:c.x)den+=(xx-mean)*(xx-mean);double delta=desired-base;if(Math.abs(delta)>1e-9&&den>1e-9)for(int i=0;i<c.n;i++)c.fi[i]+=delta*(c.x[i]-mean)/den;boolean neg=false;for(double v:c.fi)if(v<0)neg=true;if(neg){for(int i=0;i<c.n;i++)c.fi[i]=Math.max(.001,c.fi[i]);double ss=0;for(double v:c.fi)ss+=v;for(int i=0;i<c.n;i++)c.fi[i]*=c.targetF/ss;}c.sumF=0;c.calcM=0;for(int i=0;i<c.n;i++){c.sumF+=c.fi[i];c.calcM+=c.fi[i]*c.x[i];}if(c.targetM<0)c.calcM=-c.calcM;c.mErr=Math.abs(c.targetM)>1e-6?100*(c.calcM-c.targetM)/Math.abs(c.targetM):0;
    int branch=c.n,beams=0;for(int l=0;l<c.layers&&branch>1;l++){beams+=branch/2;branch=(branch+1)/2;}c.beams=beams;c.topBranches=branch;c.tree=synth(c);c.bom=bom(c);
    double def=Math.max(0,d(deflection)),link=Math.max(50,d(linkLength));c.strokeReq=def*1.25+20;c.linkAngle=Math.toDegrees(Math.atan2(def,link));c.sideLoad=c.actLoad*Math.sin(Math.toRadians(c.linkAngle));double maxFi=0;for(double f:c.fi)maxFi=Math.max(maxFi,f);c.padArea=Math.max(1,d(padW)*d(padL));c.padPressure=maxFi*1000/(c.padArea/1e6)/1e6;
    double span=Math.max(100,d(beamSpan))/1000.0,bh=Math.max(10,d(beamH))/1000.0,bb=Math.max(10,d(beamB))/1000.0;double Fbeam=Math.max(maxFi*c.sf,c.actLoad)*1000;c.beamM=Fbeam*span/4/1000.0;double I=bb*Math.pow(bh,3)/12;c.beamStress=(c.beamM*1000*(bh/2)/I)/1e6;c.beamDefl=(Fbeam*Math.pow(span,3)/(48*70e9*I))*1000;
    double tauAllow=Math.max(20,d(pinAllow))*1e6;c.pinReq=Math.sqrt(2*Fbeam/(Math.PI*tauAllow))*1000;c.pinSel=Math.ceil(c.pinReq/2.0)*2.0;double bear=Math.max(20,d(bearingAllow))*1e6;c.lugT=(Fbeam/(bear*(c.pinSel/1000.0)))*1000;c.gates=gates(c,cap);return c;}

  String synth(Calc c){StringBuilder sb=new StringBuilder();ArrayList<Double> vals=new ArrayList<>();for(double f:c.fi)vals.add(f*c.sf);for(int lev=1;lev<=c.layers&&vals.size()>1;lev++){ArrayList<Double> nx=new ArrayList<>();sb.append("Layer ").append(lev).append(":\n");for(int i=0;i<vals.size();i+=2){if(i+1<vals.size()){double a=vals.get(i),b=vals.get(i+1),sum=a+b;sb.append(String.format(Locale.US," B%d %.1f+%.1f=%.1f kN pivot %.0f/%.0f%%\n",i/2+1,a,b,sum,100*b/sum,100*a/sum));nx.add(sum);}else nx.add(vals.get(i));}vals=nx;}return sb.toString();}
  String bom(Calc c){int piv=c.beams*3,links=c.n+Math.max(0,c.beams-c.topBranches),anchors=Math.max(4,c.nAct*2);return "Actuator: "+c.nAct+" ea\nLoad cell: "+c.nAct+" ea ≥"+fmt(c.lc)+" kN\nServo valve: "+c.nAct+" ea\nActuator spherical bearing: "+c.nAct+" ea\nWhiffletree beam: "+c.beams+" ea\nPivot/pin set: "+piv+" sets\nTie rod/link: "+links+" ea\nStation rod-end: "+c.n+" ea\nClevis: "+(c.n+c.nAct)+" ea\nLoad pad/saddle: "+c.n+" ea\nHydraulic hose pair: "+c.nAct+" sets\nHP manifold: 1 set\nPressure transducer: 1 ch\nLVDT/position: "+c.nAct+" ch\nForce DAQ: "+c.nAct+" ch\nEmergency dump valve: 1 set\nStrongback: 1 assembly\nFloor anchor: "+anchors+" ea";}
  String gates(Calc c,double cap){return (Math.abs(c.mErr)<=1?"PASS":"WARN")+" force/moment equivalence\n"+(c.actLoad<=cap?"PASS":"FAIL")+" actuator capacity\n"+(c.linkAngle<=6?"PASS":"WARN")+" link angle\n"+(c.beamStress<180?"PASS":"REVIEW")+" beam training stress\n"+(c.padPressure<8?"PASS":"REVIEW")+" pad mean pressure\n";}

  class RigView extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),t=new Paint(Paint.ANTI_ALIAS_FLAG);Calc c;int ci,mode;double lf;RigView(){super(MainActivity.this);setBackgroundColor(Color.rgb(4,15,27));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));}void set(Calc x,int cidx,int m,double l){c=x;ci=cidx;mode=m;lf=l;invalidate();}protected void onDraw(Canvas cn){super.onDraw(cn);if(c==null)return;if(mode<=2)drawArticle(cn);else if(mode==3)drawTree(cn,false);else if(mode==4)drawTree(cn,true);else if(mode==5)drawBeam(cn);else if(mode==6)drawPin(cn);else if(mode==7)drawHyd(cn);else drawBom(cn);}
    void title(Canvas cn,String s){t.setColor(Color.WHITE);t.setTextSize(dp(14));cn.drawText(s,dp(12),dp(24),t);t.setTextSize(dp(10));t.setColor(Color.rgb(190,210,225));cn.drawText("Case "+CASES[ci]+" | L"+c.layers+" | A"+c.nAct+" | load "+(int)(lf*100)+"%",dp(12),dp(42),t);}
    void drawTank(Canvas cn,float left,float right,float y){p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(48,60,73));cn.drawRoundRect(new RectF(left,y-dp(24),right,y+dp(24)),dp(24),dp(24),p);p.setStyle(Paint.Style.STROKE);p.setColor(STEEL);p.setStrokeWidth(2);cn.drawRoundRect(new RectF(left,y-dp(24),right,y+dp(24)),dp(24),dp(24),p);}
    void arrow(Canvas cn,float x,float y,float dx,float dy,int color){p.setColor(color);p.setStrokeWidth(4);cn.drawLine(x,y,x+dx,y+dy,p);double a=Math.atan2(dy,dx);float ex=x+dx,ey=y+dy;cn.drawLine(ex,ey,ex-(float)(12*Math.cos(a-.55)),ey-(float)(12*Math.sin(a-.55)),p);cn.drawLine(ex,ey,ex-(float)(12*Math.cos(a+.55)),ey-(float)(12*Math.sin(a+.55)),p);}
    void drawArticle(Canvas cn){title(cn,VIEWS[mode]);int w=getWidth(),h=getHeight();float left=w*.08f,right=w*.94f,y=h*.38f;if(mode==2){float cx=w*.5f,rad=Math.min(w*.22f,h*.13f);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(48,60,73));cn.drawCircle(cx,y,rad,p);p.setStyle(Paint.Style.STROKE);p.setColor(STEEL);p.setStrokeWidth(2);cn.drawCircle(cx,y,rad,p);for(int i=0;i<8;i++){double a=2*Math.PI*i/8;float x=cx+(float)Math.cos(a)*rad,y1=y+(float)Math.sin(a)*rad;arrow(cn,x,y1,(float)Math.cos(a)*dp(42)*(float)lf,(float)Math.sin(a)*dp(42)*(float)lf,BLUE);}cn.drawText("Front cross-section / circumferential load representation",dp(12),h-dp(28),t);return;}drawTank(cn,left,right,y);for(int i=0;i<c.n;i++){float x=left+(float)(c.x[i]/c.L)*(right-left);p.setColor(CYAN);p.setStrokeWidth(1);cn.drawLine(x,y-dp(25),x,y+dp(25),p);t.setColor(Color.WHITE);t.setTextSize(dp(8));cn.drawText("S"+(i+1),x-dp(7),y+dp(42),t);double f=c.fi[i]*lf;float mag=dp(20)+(float)Math.min(dp(60),f*.8);if(mode==0){boolean up=ci!=1&&ci!=3;arrow(cn,x,y-dp(28),0,up?-mag:mag,BLUE);}else{boolean rightDir=ci!=3&&ci!=9;arrow(cn,x,y,rightDir?mag:-mag,0,ORANGE);}if(i<c.n-1){float xn=left+(float)(c.x[i+1]/c.L)*(right-left);p.setColor(Color.rgb(105,125,145));p.setStrokeWidth(1);cn.drawLine(x,y+dp(62),xn,y+dp(62),p);} }
      dimension(cn,left,right,y+dp(90),String.format(Locale.US,"L = %.2f m",c.L));cn.drawText("Station/load-pad layout is scaled to EFT length",dp(12),h-dp(24),t);}
    void dimension(Canvas cn,float a,float b,float y,String s){p.setColor(STEEL);p.setStrokeWidth(1);cn.drawLine(a,y,b,y,p);cn.drawLine(a,y-dp(5),a,y+dp(5),p);cn.drawLine(b,y-dp(5),b,y+dp(5),p);t.setColor(Color.WHITE);t.setTextSize(dp(9));cn.drawText(s,(a+b)/2-dp(28),y-dp(6),t);}
    ArrayList<float[]> baseNodes(float left,float right,float y){ArrayList<float[]> n=new ArrayList<>();for(int i=0;i<c.n;i++){float x=left+(float)(c.x[i]/c.L)*(right-left);n.add(new float[]{x,y,(float)(c.fi[i]*c.sf*lf)});}return n;}
    void drawTree(Canvas cn,boolean mech){title(cn,mech?"Mechanical load path":"Symbolic whiffletree");int w=getWidth(),h=getHeight();float left=w*.06f,right=w*.95f,tankY=dp(100);drawTank(cn,left,right,tankY);ArrayList<float[]> nodes=baseNodes(left,right,tankY+dp(30));for(int i=0;i<c.n;i++){float x=nodes.get(i)[0];if(mech){p.setStyle(Paint.Style.FILL);p.setColor(YELLOW);cn.drawRoundRect(new RectF(x-dp(9),tankY+dp(21),x+dp(9),tankY+dp(30)),dp(3),dp(3),p);} }
      float base=tankY+dp(78);for(int lev=1;lev<=c.layers&&nodes.size()>1;lev++){ArrayList<float[]> nx=new ArrayList<>();float yy=base+dp(62)*(lev-1);p.setColor(lev==1?ORANGE:(lev==2?YELLOW:CYAN));p.setStrokeWidth(mech?7:4);for(int i=0;i<nodes.size();i+=2){if(i+1<nodes.size()){float[]a=nodes.get(i),b=nodes.get(i+1);float sum=a[2]+b[2],px=sum>0?(a[0]*b[2]+b[0]*a[2])/sum:(a[0]+b[0])/2;cn.drawLine(a[0],yy,b[0],yy,p);p.setStrokeWidth(2);cn.drawLine(a[0],a[1],a[0],yy,p);cn.drawLine(b[0],b[1],b[0],yy,p);p.setStyle(Paint.Style.FILL);cn.drawCircle(px,yy,dp(5),p);p.setStyle(Paint.Style.STROKE);t.setColor(Color.WHITE);t.setTextSize(dp(8));cn.drawText(String.format(Locale.US,"%.0f kN",sum),px-dp(18),yy-dp(7),t);nx.add(new float[]{px,yy,sum});}else nx.add(nodes.get(i));}nodes=nx;}
      float ay=Math.min(h-dp(110),base+dp(62)*c.layers+dp(25));for(int a=0;a<c.nAct;a++){float x=w*(a+1f)/(c.nAct+1f);if(mech){p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(80,95,110));cn.drawRoundRect(new RectF(x-dp(18),ay-dp(40),x+dp(18),ay+dp(4)),dp(5),dp(5),p);p.setColor(GREEN);cn.drawRect(x-dp(6),ay-dp(70),x+dp(6),ay-dp(40),p);p.setColor(RED);cn.drawRect(x-dp(14),ay-dp(86),x+dp(14),ay-dp(72),p);p.setColor(YELLOW);cn.drawCircle(x,ay-dp(96),dp(7),p);t.setTextSize(dp(8));t.setColor(Color.WHITE);cn.drawText("LC",x-dp(8),ay-dp(75),t);cn.drawText("SB",x-dp(8),ay-dp(93),t);}else{p.setStyle(Paint.Style.FILL);p.setColor(GREEN);cn.drawRect(x-dp(12),ay-dp(35),x+dp(12),ay,p);}p.setStyle(Paint.Style.STROKE);p.setColor(Color.WHITE);p.setStrokeWidth(2);float tx=nodes.get(Math.min(a,nodes.size()-1))[0],ty=nodes.get(Math.min(a,nodes.size()-1))[1];cn.drawLine(x,ay-dp(40),tx,ty,p);t.setTextSize(dp(9));cn.drawText("A"+(a+1),x-dp(8),ay+dp(18),t);}p.setColor(Color.rgb(85,100,115));p.setStrokeWidth(8);cn.drawLine(left,ay+dp(35),right,ay+dp(35),p);if(mech){t.setTextSize(dp(9));t.setColor(Color.WHITE);cn.drawText("ACT → Load cell → spherical bearing → beam → link → pad → EFT",dp(12),h-dp(22),t);} }
    void drawBeam(Canvas cn){title(cn,"Whiffletree beam detail — preliminary");int w=getWidth(),h=getHeight();float x1=w*.15f,x2=w*.85f,y=h*.36f;p.setColor(ORANGE);p.setStrokeWidth(dp(12));cn.drawLine(x1,y,x2,y,p);p.setColor(YELLOW);p.setStyle(Paint.Style.FILL);cn.drawCircle((x1+x2)/2,y,dp(8),p);arrow(cn,x1,y-dp(5),0,dp(70),BLUE);arrow(cn,x2,y-dp(5),0,dp(70),BLUE);dimension(cn,x1,x2,y+dp(110),String.format(Locale.US,"span %.0f mm",d(beamSpan)));t.setColor(Color.WHITE);t.setTextSize(dp(11));cn.drawText(String.format(Locale.US,"Mmax ≈ %.2f kN·m",c.beamM),dp(20),h*.62f,t);cn.drawText(String.format(Locale.US,"Section b×h = %.0f×%.0f mm",d(beamB),d(beamH)),dp(20),h*.68f,t);cn.drawText(String.format(Locale.US,"Training stress ≈ %.1f MPa",c.beamStress),dp(20),h*.74f,t);cn.drawText(String.format(Locale.US,"Elastic deflection scale ≈ %.2f mm",c.beamDefl),dp(20),h*.80f,t);cn.drawText("Actual section must include holes, local bearing, material allowables and fatigue.",dp(20),h*.88f,t);}
    void drawPin(Canvas cn){title(cn,"Pin / Clevis / Lug detail — preliminary");int w=getWidth(),h=getHeight();float cx=w*.5f,cy=h*.33f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(12));p.setColor(STEEL);cn.drawLine(cx-dp(70),cy-dp(80),cx-dp(70),cy+dp(80),p);cn.drawLine(cx+dp(70),cy-dp(80),cx+dp(70),cy+dp(80),p);p.setStyle(Paint.Style.FILL);p.setColor(ORANGE);cn.drawRect(cx-dp(60),cy-dp(30),cx+dp(60),cy+dp(30),p);p.setColor(YELLOW);cn.drawCircle(cx,cy,dp(18),p);dimension(cn,cx-dp(18),cx+dp(18),cy+dp(75),String.format(Locale.US,"Ø %.0f mm",c.pinSel));t.setColor(Color.WHITE);t.setTextSize(dp(11));cn.drawText(String.format(Locale.US,"Required pin d (double-shear precheck): %.1f mm",c.pinReq),dp(20),h*.62f,t);cn.drawText(String.format(Locale.US,"Schematic selected pin: Ø%.0f mm",c.pinSel),dp(20),h*.68f,t);cn.drawText(String.format(Locale.US,"Minimum lug t by bearing-only precheck: %.1f mm",c.lugT),dp(20),h*.74f,t);cn.drawText("Also check pin bending, net section, tear-out, edge distance and fatigue.",dp(20),h*.84f,t);}
    void drawHyd(Canvas cn){title(cn,"Hydraulic architecture — schematic");int w=getWidth(),h=getHeight();float y=dp(120);box(cn,dp(20),y,dp(90),dp(55),"HPU");box(cn,dp(135),y,dp(100),dp(55),"Manifold");box(cn,dp(260),y,dp(105),dp(55),"Dump/relief");p.setColor(BLUE);p.setStrokeWidth(4);cn.drawLine(dp(110),y+dp(27),dp(135),y+dp(27),p);cn.drawLine(dp(235),y+dp(27),dp(260),y+dp(27),p);float startY=y+dp(110);for(int a=0;a<c.nAct;a++){float yy=startY+a*dp(48);box(cn,dp(55),yy,dp(110),dp(34),"SV"+(a+1));box(cn,dp(205),yy,dp(125),dp(34),"ACT"+(a+1));p.setColor(CYAN);p.setStrokeWidth(3);cn.drawLine(dp(165),yy+dp(17),dp(205),yy+dp(17),p);}t.setColor(Color.WHITE);t.setTextSize(dp(10));cn.drawText("HPU → manifold → servo valves → actuators",dp(20),h-dp(54),t);cn.drawText("Independent force channels use load cells; emergency dump remains common schematic element.",dp(20),h-dp(30),t);}
    void box(Canvas cn,float x,float y,float ww,float hh,String s){p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(40,63,82));cn.drawRoundRect(new RectF(x,y,x+ww,y+hh),dp(6),dp(6),p);p.setStyle(Paint.Style.STROKE);p.setColor(STEEL);p.setStrokeWidth(2);cn.drawRoundRect(new RectF(x,y,x+ww,y+hh),dp(6),dp(6),p);t.setColor(Color.WHITE);t.setTextSize(dp(9));cn.drawText(s,x+dp(8),y+hh/2+dp(4),t);}
    void drawBom(Canvas cn){title(cn,"Dynamic BOM");String[] lines=c.bom.split("\\n");t.setColor(Color.WHITE);t.setTextSize(dp(10));float y=dp(75);for(String s:lines){cn.drawText(s,dp(18),y,t);y+=dp(28);} }
  }

  static class Calc{double L,D,targetF,targetM,pbar,sf,designF,actLoad,bore,lc,sumF,calcM,mErr,strokeReq,linkAngle,sideLoad,padArea,padPressure,beamM,beamStress,beamDefl,pinReq,pinSel,lugT;int n,layers,nAct,beams,topBranches;double[]x,fi;String tree,bom,gates;}
  double std(double v){double[]a={10,20,25,50,75,100,150,200,250,300,500,750,1000};for(double x:a)if(x>=v)return x;return Math.ceil(v/100)*100;}double d(EditText e){return Double.parseDouble(e.getText().toString().trim().replace(',','.'));}int clamp(int v,int a,int b){return Math.max(a,Math.min(b,v));}String fmt(double v){return String.format(Locale.US,"%.1f",v);}int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(4));return p;}TextView tx(String s,int z,boolean b,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,b?Typeface.BOLD:Typeface.NORMAL);return v;}TextView card(String s,int c){TextView v=tx(s,13,false,Color.WHITE);v.setPadding(dp(10),dp(10),dp(10),dp(10));v.setBackground(bg(c,10));return v;}GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
}
