package com.mg.whiffletreeaero;

import android.app.*;
import android.os.Bundle;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
  final int NAVY=Color.rgb(7,20,34),PANEL=Color.rgb(16,36,55),BLUE=Color.rgb(55,132,238),CYAN=Color.rgb(51,205,220),ORANGE=Color.rgb(245,164,47),GREEN=Color.rgb(67,190,113),YELLOW=Color.rgb(247,207,77),RED=Color.rgb(229,82,74),STEEL=Color.rgb(160,180,198),PURPLE=Color.rgb(160,110,230);
  LinearLayout root,inputs; RigView rig; TextView status,result,levelText,inspector; Spinner loadCase,viewMode,qProfile; EditText L,D,F,M,stations,layers,actCount,actCapacity,pressure,sf,padW,padL,deflection,linkLength,beamSpan,beamH,beamB,pinAllow,bearingAllow; SeekBar level;
  String[] CASES={"+Z Bending","-Z Bending","+Y Bending","-Y Bending","Pitch +My","Pitch -My","Roll +Mx","Roll -Mx","Yaw +Mz","Yaw -Mz","Combined Z+Pitch"};
  String[] VIEWS={"Interactive Side","Interactive Tree","Mechanical Rig","Beam Detail","Pin/Clevis Detail","Hydraulic","BOM","Validation"};
  String[] Q={"Elliptic","Uniform","Triangular root-high","Triangular tip-high","Parabolic"};

  @Override public void onCreate(Bundle b){super.onCreate(b);
    ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(10),dp(10),dp(10),dp(30));root.setBackgroundColor(NAVY);sv.addView(root);
    root.addView(tx("EFT WHIFFLETREE DIGITAL ENGINEER",25,true,Color.WHITE));root.addView(tx("v1.9 • interactive inspector • load-path trace • PASS/WARN/FAIL overlay",12,false,Color.rgb(180,205,225)));
    LinearLayout selectors=new LinearLayout(this);selectors.setOrientation(LinearLayout.HORIZONTAL);loadCase=spin(CASES);viewMode=spin(VIEWS);selectors.addView(loadCase,new LinearLayout.LayoutParams(0,dp(50),1));selectors.addView(viewMode,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(selectors,lp());
    status=card("Hazır",Color.rgb(13,47,70));root.addView(status,lp());
    rig=new RigView();root.addView(rig,new LinearLayout.LayoutParams(-1,dp(680)));
    inspector=card("Çizimde bir station, beam, load-cell veya actuator'a dokun.",Color.rgb(22,45,68));inspector.setTextSize(13);root.addView(inspector,lp());
    LinearLayout lb=new LinearLayout(this);lb.setOrientation(LinearLayout.VERTICAL);lb.setPadding(dp(8),dp(4),dp(8),dp(4));lb.setBackground(bg(PANEL,10));levelText=tx("Load level: 100%",13,true,Color.WHITE);level=new SeekBar(this);level.setMax(100);level.setProgress(100);lb.addView(levelText);lb.addView(level);root.addView(lb,lp());
    inputs=new LinearLayout(this);inputs.setOrientation(LinearLayout.VERTICAL);inputs.setPadding(dp(10),dp(10),dp(10),dp(10));inputs.setBackground(bg(PANEL,12));root.addView(inputs,lp());inputs.addView(tx("DESIGN INPUTS — defaults are editable",17,true,Color.WHITE));
    F=field("Target total load [kN]","305.7");M=field("Target moment [kN·m]","1280");L=field("Tank length [m]","7.6");D=field("Tank diameter [m]","0.64");stations=field("Station count (4-16)","12");inputs.addView(tx("q(x) profile",12,true,Color.rgb(185,210,230)));qProfile=spin(Q);inputs.addView(qProfile,lp());layers=field("Whiffletree layers (1-3)","3");actCount=field("Actuator count (1-8)","4");actCapacity=field("Actuator nominal capacity [kN]","120");pressure=field("Hydraulic pressure [bar]","210");sf=field("Sizing factor","1.50");padW=field("Load pad width [mm]","150");padL=field("Load pad length [mm]","250");deflection=field("Expected max EFT deflection [mm]","60");linkLength=field("Nominal link length [mm]","600");beamSpan=field("Typical beam span [mm]","600");beamH=field("Beam section height [mm]","80");beamB=field("Beam section width [mm]","40");pinAllow=field("Pin allowable shear [MPa]","180");bearingAllow=field("Lug allowable bearing [MPa]","250");
    Button auto=new Button(this);auto.setText("AUTO OPTIMIZE ACTUATOR COUNT");auto.setOnClickListener(v->{try{Calc c=compute(true);actCount.setText(String.valueOf(c.nAct));preview(c);}catch(Exception e){}});inputs.addView(auto,lp());
    Button calc=new Button(this);calc.setText("HESAPLA + TÜM GÖRÜNÜMLERİ GÜNCELLE");calc.setOnClickListener(v->calculate());inputs.addView(calc,lp());
    result=card("v1.9: seçilen elemanın load-path'i çizimde vurgulanır; inspector panelinde kuvvet, kapasite kullanımı, moment katkısı ve durum görünür.",Color.rgb(12,34,52));root.addView(result,lp());
    root.addView(card("Ön tasarım/eğitim aracıdır. Gerçek rig release için onaylı loads report, FEM, gerçek katalog ratingleri ve kurum prosedürleri gerekir.",Color.rgb(66,46,12)),lp());
    TextWatcher tw=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){safe();}public void afterTextChanged(Editable e){}};for(EditText e:new EditText[]{F,M,L,D,stations,layers,actCount,actCapacity,pressure,sf,padW,padL,deflection,linkLength,beamSpan,beamH,beamB,pinAllow,bearingAllow})e.addTextChangedListener(tw);
    android.widget.AdapterView.OnItemSelectedListener lis=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){rig.clearSelection();safe();}public void onNothingSelected(android.widget.AdapterView<?>p){}};loadCase.setOnItemSelectedListener(lis);viewMode.setOnItemSelectedListener(lis);qProfile.setOnItemSelectedListener(lis);
    level.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean u){levelText.setText("Load level: "+p+"%");safe();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});
    setContentView(sv);safe();
  }

  Spinner spin(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
  EditText field(String label,String def){inputs.addView(tx(label,12,true,Color.rgb(185,210,230)));EditText e=new EditText(this);e.setText(def);e.setTextColor(Color.WHITE);e.setTextSize(16);e.setSingleLine(true);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);e.setBackground(bg(Color.rgb(25,52,75),8));e.setPadding(dp(10),0,dp(10),0);inputs.addView(e,new LinearLayout.LayoutParams(-1,dp(44)));return e;}
  void safe(){try{preview(compute(false));}catch(Exception ignored){}}
  void preview(Calc c){rig.set(c,viewMode.getSelectedItemPosition(),level.getProgress()/100.0);status.setText(String.format(Locale.US,"%s • %s • S%d L%d A%d • %.0f%% load",CASES[loadCase.getSelectedItemPosition()],VIEWS[viewMode.getSelectedItemPosition()],c.n,c.layers,c.nAct,level.getProgress()*1.0));}
  void calculate(){try{Calc c=compute(false);preview(c);result.setText(String.format(Locale.US,"ΣF %.1f kN | M %.1f kN·m | M error %.2f%%\nActuator %.1f kN ea | bore %.1f mm | LC ≥ %.0f kN\nBeam %.1f MPa | Pin Ø%.0f mm | Pad %.2f MPa\n\n%s",c.sumF,c.calcM,c.mErr,c.actLoad,c.bore,c.lc,c.beamStress,c.pinSel,c.padPressure,c.gates));}catch(Exception e){result.setText("Girişleri kontrol et.");}}

  Calc compute(boolean opt){Calc c=new Calc();c.L=Math.max(.5,d(L));c.D=Math.max(.1,d(D));c.targetF=Math.abs(d(F));c.targetM=d(M);c.n=clamp((int)Math.round(d(stations)),4,16);c.layers=clamp((int)Math.round(d(layers)),1,3);double cap=Math.max(1,d(actCapacity));c.pbar=Math.max(1,d(pressure));c.sf=Math.max(1,d(sf));c.designF=c.targetF*c.sf;int manual=clamp((int)Math.round(d(actCount)),1,8);int minCap=(int)Math.ceil(c.designF/cap);int minTopo=Math.max(1,(int)Math.ceil(c.n/Math.pow(2,c.layers)));c.nAct=opt?clamp(Math.max(minCap,minTopo),1,8):manual;c.actLoad=c.designF/c.nAct;c.bore=Math.sqrt(4*(c.actLoad*1000)/(c.pbar*100000)/Math.PI)*1000;c.lc=std(c.actLoad*1.2);
    c.x=new double[c.n];c.fi=new double[c.n];double[] w=new double[c.n];double sw=0;int q=qProfile.getSelectedItemPosition();for(int i=0;i<c.n;i++){double u=(i+.5)/c.n;c.x[i]=u*c.L;if(q==0)w[i]=Math.sqrt(Math.max(0,1-Math.pow(2*u-1,2)))+.05;else if(q==1)w[i]=1;else if(q==2)w[i]=1.15-u;else if(q==3)w[i]=.15+u;else w[i]=.25+4*u*(1-u);sw+=w[i];}for(int i=0;i<c.n;i++)c.fi[i]=c.targetF*w[i]/sw;
    double desired=Math.abs(c.targetM),base=0;for(int i=0;i<c.n;i++)base+=c.fi[i]*c.x[i];double mean=0;for(double xx:c.x)mean+=xx;mean/=c.n;double den=0;for(double xx:c.x)den+=(xx-mean)*(xx-mean);double delta=desired-base;if(Math.abs(delta)>1e-9&&den>1e-9)for(int i=0;i<c.n;i++)c.fi[i]+=delta*(c.x[i]-mean)/den;boolean neg=false;for(double v:c.fi)if(v<0)neg=true;if(neg){for(int i=0;i<c.n;i++)c.fi[i]=Math.max(.001,c.fi[i]);double ss=0;for(double v:c.fi)ss+=v;for(int i=0;i<c.n;i++)c.fi[i]*=c.targetF/ss;}c.sumF=0;c.calcM=0;for(int i=0;i<c.n;i++){c.sumF+=c.fi[i];c.calcM+=c.fi[i]*c.x[i];}if(c.targetM<0)c.calcM=-c.calcM;c.mErr=Math.abs(c.targetM)>1e-6?100*(c.calcM-c.targetM)/Math.abs(c.targetM):0;
    int branch=c.n,beams=0;for(int l=0;l<c.layers&&branch>1;l++){beams+=branch/2;branch=(branch+1)/2;}c.beams=beams;c.topBranches=branch;
    double def=Math.max(0,d(deflection)),link=Math.max(50,d(linkLength));c.strokeReq=def*1.25+20;c.linkAngle=Math.toDegrees(Math.atan2(def,link));double maxFi=0;for(double f:c.fi)maxFi=Math.max(maxFi,f);c.padArea=Math.max(1,d(padW)*d(padL));c.padPressure=maxFi*1000/(c.padArea/1e6)/1e6;
    double span=Math.max(100,d(beamSpan))/1000.0,bh=Math.max(10,d(beamH))/1000.0,bb=Math.max(10,d(beamB))/1000.0;double Fbeam=Math.max(maxFi*c.sf,c.actLoad)*1000;c.beamM=Fbeam*span/4/1000.0;double I=bb*Math.pow(bh,3)/12;c.beamStress=(c.beamM*1000*(bh/2)/I)/1e6;c.beamDefl=(Fbeam*Math.pow(span,3)/(48*70e9*I))*1000;
    double tauAllow=Math.max(20,d(pinAllow))*1e6;c.pinReq=Math.sqrt(2*Fbeam/(Math.PI*tauAllow))*1000;c.pinSel=Math.ceil(c.pinReq/2.0)*2.0;double bear=Math.max(20,d(bearingAllow))*1e6;c.lugT=(Fbeam/(bear*(c.pinSel/1000.0)))*1000;c.gates=gates(c,cap);c.bom=bom(c);return c;}
  String gates(Calc c,double cap){StringBuilder s=new StringBuilder();s.append(Math.abs(c.mErr)<=1?"PASS":"WARN").append(" force/moment equivalence\n");s.append(c.actLoad<=cap?"PASS":"FAIL").append(" actuator capacity\n");s.append(c.linkAngle<=6?"PASS":"WARN").append(" link angle\n");s.append(c.beamStress<180?"PASS":"REVIEW").append(" beam training stress\n");s.append(c.padPressure<8?"PASS":"REVIEW").append(" pad mean pressure\n");s.append(c.strokeReq<=120?"PASS":"WARN").append(" stroke envelope");return s.toString();}
  String bom(Calc c){int piv=c.beams*3,links=c.n+Math.max(0,c.beams-c.topBranches),anchors=Math.max(4,c.nAct*2);return "Actuator "+c.nAct+" | Load cell "+c.nAct+" | Servo valve "+c.nAct+" | Beam "+c.beams+" | Pivot/pin "+piv+" | Tie rod "+links+" | Pad "+c.n+" | Floor anchor "+anchors;}

  void showInspector(String s){inspector.setText(s);}

  class Hit {RectF r;String type;int idx;double load;Hit(RectF rr,String t,int i,double l){r=rr;type=t;idx=i;load=l;}}
  class RigView extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),t=new Paint(Paint.ANTI_ALIAS_FLAG);Calc c;int mode;double lf;ArrayList<Hit> hits=new ArrayList<>();String selType="";int selIdx=-1;
    RigView(){super(MainActivity.this);setBackgroundColor(Color.rgb(4,15,27));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));setClickable(true);}
    void set(Calc x,int m,double l){c=x;mode=m;lf=l;invalidate();}
    void clearSelection(){selType="";selIdx=-1;showInspector("Çizimde bir station, beam, load-cell veya actuator'a dokun.");invalidate();}
    public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;for(Hit h:hits){if(h.r.contains(e.getX(),e.getY())){selType=h.type;selIdx=h.idx;describe(h);invalidate();return true;}}return true;}
    void describe(Hit h){if(c==null)return;String state="PASS";if(h.type.equals("ACT")&&c.actLoad>d(actCapacity))state="FAIL";if(h.type.equals("BEAM")&&c.beamStress>=180)state="REVIEW";if(h.type.equals("ST")&&c.padPressure>=8)state="REVIEW";if(h.type.equals("LC")&&c.actLoad/c.lc>.9)state="WARN";
      if(h.type.equals("ST")){int i=Math.min(h.idx,c.n-1);showInspector(String.format(Locale.US,"S%d • %.1f kN @ %.0f%% • x=%.2f m • moment contribution %.1f kN·m • pad mean pressure %.2f MPa • %s\nLoad path: EFT → pad → rod-end/link → whiffletree → actuator",i+1,c.fi[i]*lf,lf*100,c.x[i],c.fi[i]*c.x[i]*lf,c.padPressure*lf,state));}
      else if(h.type.equals("ACT"))showInspector(String.format(Locale.US,"ACT%d • design demand %.1f kN • current %.1f kN • bore %.1f mm @ %.0f bar • stroke envelope %.1f mm • %s\nLoad path: HPU → servo valve → actuator → load cell → spherical joint → tree",h.idx+1,c.actLoad,c.actLoad*lf,c.bore,c.pbar,c.strokeReq,state));
      else if(h.type.equals("LC"))showInspector(String.format(Locale.US,"LC%d • preselect ≥ %.0f kN • current %.1f kN • utilization %.0f%% • %s",h.idx+1,c.lc,c.actLoad*lf,100*c.actLoad*lf/c.lc,state));
      else showInspector(String.format(Locale.US,"Beam B%d • representative load %.1f kN • Mmax %.2f kN·m • stress %.1f MPa • deflection %.2f mm • %s",h.idx+1,h.load*lf,c.beamM,c.beamStress*lf,c.beamDefl*lf,state));}
    protected void onDraw(Canvas cn){super.onDraw(cn);hits.clear();if(c==null)return;if(mode==0)drawArticle(cn);else if(mode==1)drawTree(cn,false);else if(mode==2)drawTree(cn,true);else if(mode==3)drawBeam(cn);else if(mode==4)drawPin(cn);else if(mode==5)drawHyd(cn);else if(mode==6)drawBom(cn);else drawValidation(cn);}
    void title(Canvas cn,String s){t.setColor(Color.WHITE);t.setTextSize(dp(14));cn.drawText(s,dp(12),dp(24),t);t.setTextSize(dp(10));t.setColor(Color.rgb(190,210,225));cn.drawText("Tap components to inspect • "+(int)(lf*100)+"% load",dp(12),dp(43),t);}
    void drawTank(Canvas cn,float left,float right,float y){p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(48,60,73));cn.drawRoundRect(new RectF(left,y-dp(24),right,y+dp(24)),dp(24),dp(24),p);p.setStyle(Paint.Style.STROKE);p.setColor(STEEL);p.setStrokeWidth(2);cn.drawRoundRect(new RectF(left,y-dp(24),right,y+dp(24)),dp(24),dp(24),p);}
    void drawArticle(Canvas cn){title(cn,"Interactive EFT side view");int w=getWidth(),h=getHeight();float left=w*.07f,right=w*.95f,y=h*.38f;drawTank(cn,left,right,y);for(int i=0;i<c.n;i++){float x=left+(float)(c.x[i]/c.L)*(right-left);boolean selected=selType.equals("ST")&&selIdx==i;p.setColor(selected?PURPLE:CYAN);p.setStrokeWidth(selected?5:2);cn.drawLine(x,y-dp(28),x,y+dp(28),p);double f=c.fi[i]*lf;float mag=dp(18)+(float)Math.min(dp(68),f*.8);arrow(cn,x,y-dp(30),0,-mag,selected?PURPLE:BLUE);t.setColor(Color.WHITE);t.setTextSize(dp(8));cn.drawText("S"+(i+1),x-dp(7),y+dp(43),t);RectF hr=new RectF(x-dp(18),y-dp(100),x+dp(18),y+dp(50));hits.add(new Hit(hr,"ST",i,c.fi[i]));}dimension(cn,left,right,y+dp(95),String.format(Locale.US,"L = %.2f m",c.L));}
    ArrayList<float[]> baseNodes(float left,float right,float y){ArrayList<float[]> n=new ArrayList<>();for(int i=0;i<c.n;i++){float x=left+(float)(c.x[i]/c.L)*(right-left);n.add(new float[]{x,y,(float)(c.fi[i]*c.sf)});}return n;}
    void drawTree(Canvas cn,boolean mech){title(cn,mech?"Mechanical load path":"Interactive whiffletree");int w=getWidth(),h=getHeight();float left=w*.05f,right=w*.95f,tankY=dp(95);drawTank(cn,left,right,tankY);ArrayList<float[]> nodes=baseNodes(left,right,tankY+dp(30));int beamId=0;float base=tankY+dp(75);for(int lev=1;lev<=c.layers&&nodes.size()>1;lev++){ArrayList<float[]> nx=new ArrayList<>();float yy=base+dp(62)*(lev-1);for(int i=0;i<nodes.size();i+=2){if(i+1<nodes.size()){float[]a=nodes.get(i),b=nodes.get(i+1);float sum=a[2]+b[2],px=sum>0?(a[0]*b[2]+b[0]*a[2])/sum:(a[0]+b[0])/2;boolean selected=selType.equals("BEAM")&&selIdx==beamId;p.setColor(selected?PURPLE:(lev==1?ORANGE:(lev==2?YELLOW:CYAN)));p.setStrokeWidth(selected?10:(mech?7:4));cn.drawLine(a[0],yy,b[0],yy,p);p.setStrokeWidth(2);cn.drawLine(a[0],a[1],a[0],yy,p);cn.drawLine(b[0],b[1],b[0],yy,p);p.setStyle(Paint.Style.FILL);cn.drawCircle(px,yy,dp(5),p);p.setStyle(Paint.Style.STROKE);hits.add(new Hit(new RectF(Math.min(a[0],b[0])-dp(8),yy-dp(18),Math.max(a[0],b[0])+dp(8),yy+dp(18)),"BEAM",beamId,sum));beamId++;nx.add(new float[]{px,yy,sum});}else nx.add(nodes.get(i));}nodes=nx;}
      float ay=Math.min(h-dp(105),base+dp(62)*c.layers+dp(30));for(int a=0;a<c.nAct;a++){float x=w*(a+1f)/(c.nAct+1f);boolean selected=selType.equals("ACT")&&selIdx==a;p.setStyle(Paint.Style.FILL);p.setColor(selected?PURPLE:Color.rgb(80,95,110));RectF ar=new RectF(x-dp(17),ay-dp(45),x+dp(17),ay);cn.drawRoundRect(ar,dp(5),dp(5),p);hits.add(new Hit(new RectF(ar.left-dp(8),ar.top-dp(35),ar.right+dp(8),ar.bottom+dp(10)),"ACT",a,c.actLoad));if(mech){p.setColor(selType.equals("LC")&&selIdx==a?PURPLE:RED);RectF lr=new RectF(x-dp(14),ay-dp(64),x+dp(14),ay-dp(48));cn.drawRect(lr,p);hits.add(new Hit(new RectF(lr.left-dp(8),lr.top-dp(8),lr.right+dp(8),lr.bottom+dp(8)),"LC",a,c.lc));p.setColor(YELLOW);cn.drawCircle(x,ay-dp(74),dp(7),p);}p.setStyle(Paint.Style.STROKE);p.setColor(Color.WHITE);float tx=nodes.get(Math.min(a,nodes.size()-1))[0],ty=nodes.get(Math.min(a,nodes.size()-1))[1];cn.drawLine(x,ay-dp(45),tx,ty,p);t.setColor(Color.WHITE);t.setTextSize(dp(8));cn.drawText("A"+(a+1),x-dp(7),ay+dp(16),t);} }
    void drawBeam(Canvas cn){title(cn,"Beam detail");int w=getWidth(),h=getHeight();float x1=w*.15f,x2=w*.85f,y=h*.35f;p.setColor(c.beamStress<180?GREEN:RED);p.setStrokeWidth(dp(12));cn.drawLine(x1,y,x2,y,p);p.setColor(YELLOW);p.setStyle(Paint.Style.FILL);cn.drawCircle((x1+x2)/2,y,dp(8),p);arrow(cn,x1,y-dp(5),0,dp(70),BLUE);arrow(cn,x2,y-dp(5),0,dp(70),BLUE);dimension(cn,x1,x2,y+dp(110),String.format(Locale.US,"span %.0f mm",d(beamSpan)));textBlock(cn,new String[]{String.format(Locale.US,"Mmax %.2f kN·m",c.beamM),String.format(Locale.US,"Stress %.1f MPa",c.beamStress),String.format(Locale.US,"Deflection %.2f mm",c.beamDefl)},dp(20),h*.62f);}
    void drawPin(Canvas cn){title(cn,"Pin / Clevis detail");int w=getWidth(),h=getHeight();float cx=w*.5f,cy=h*.33f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(12));p.setColor(STEEL);cn.drawLine(cx-dp(70),cy-dp(80),cx-dp(70),cy+dp(80),p);cn.drawLine(cx+dp(70),cy-dp(80),cx+dp(70),cy+dp(80),p);p.setStyle(Paint.Style.FILL);p.setColor(ORANGE);cn.drawRect(cx-dp(60),cy-dp(30),cx+dp(60),cy+dp(30),p);p.setColor(YELLOW);cn.drawCircle(cx,cy,dp(18),p);textBlock(cn,new String[]{String.format(Locale.US,"Required pin %.1f mm",c.pinReq),String.format(Locale.US,"Selected schematic Ø%.0f mm",c.pinSel),String.format(Locale.US,"Lug t min %.1f mm",c.lugT)},dp(20),h*.62f);}
    void drawHyd(Canvas cn){title(cn,"Hydraulic architecture");float y=dp(120);box(cn,dp(20),y,dp(90),dp(55),"HPU");box(cn,dp(135),y,dp(100),dp(55),"Manifold");box(cn,dp(260),y,dp(105),dp(55),"Dump/relief");float sy=y+dp(110);for(int a=0;a<c.nAct;a++){float yy=sy+a*dp(48);box(cn,dp(55),yy,dp(110),dp(34),"SV"+(a+1));box(cn,dp(205),yy,dp(125),dp(34),"ACT"+(a+1));p.setColor(CYAN);p.setStrokeWidth(3);cn.drawLine(dp(165),yy+dp(17),dp(205),yy+dp(17),p);} }
    void drawBom(Canvas cn){title(cn,"Dynamic BOM");textBlock(cn,c.bom.split(" \\| "),dp(18),dp(80));}
    void drawValidation(Canvas cn){title(cn,"Validation Matrix");String[] ls=c.gates.split("\\n");float y=dp(90);for(String s:ls){if(s.length()==0)continue;boolean pass=s.startsWith("PASS"),fail=s.startsWith("FAIL");p.setStyle(Paint.Style.FILL);p.setColor(pass?GREEN:(fail?RED:YELLOW));cn.drawRoundRect(new RectF(dp(18),y,getWidth()-dp(18),y+dp(50)),dp(8),dp(8),p);t.setColor(Color.WHITE);t.setTextSize(dp(10));cn.drawText(s,dp(28),y+dp(30),t);y+=dp(64);} }
    void arrow(Canvas cn,float x,float y,float dx,float dy,int color){p.setColor(color);p.setStrokeWidth(4);cn.drawLine(x,y,x+dx,y+dy,p);double a=Math.atan2(dy,dx);float ex=x+dx,ey=y+dy;cn.drawLine(ex,ey,ex-(float)(12*Math.cos(a-.55)),ey-(float)(12*Math.sin(a-.55)),p);cn.drawLine(ex,ey,ex-(float)(12*Math.cos(a+.55)),ey-(float)(12*Math.sin(a+.55)),p);}
    void dimension(Canvas cn,float a,float b,float y,String s){p.setColor(STEEL);p.setStrokeWidth(1);cn.drawLine(a,y,b,y,p);cn.drawLine(a,y-dp(5),a,y+dp(5),p);cn.drawLine(b,y-dp(5),b,y+dp(5),p);t.setColor(Color.WHITE);t.setTextSize(dp(9));cn.drawText(s,(a+b)/2-dp(28),y-dp(6),t);}
    void box(Canvas cn,float x,float y,float ww,float hh,String s){p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(40,63,82));cn.drawRoundRect(new RectF(x,y,x+ww,y+hh),dp(6),dp(6),p);p.setStyle(Paint.Style.STROKE);p.setColor(STEEL);p.setStrokeWidth(2);cn.drawRoundRect(new RectF(x,y,x+ww,y+hh),dp(6),dp(6),p);t.setColor(Color.WHITE);t.setTextSize(dp(9));cn.drawText(s,x+dp(8),y+hh/2+dp(4),t);}
    void textBlock(Canvas cn,String[] lines,float x,float y){t.setColor(Color.WHITE);t.setTextSize(dp(10));for(String s:lines){cn.drawText(s,x,y,t);y+=dp(28);}}
  }

  static class Calc{double L,D,targetF,targetM,pbar,sf,designF,actLoad,bore,lc,sumF,calcM,mErr,strokeReq,linkAngle,padArea,padPressure,beamM,beamStress,beamDefl,pinReq,pinSel,lugT;int n,layers,nAct,beams,topBranches;double[]x,fi;String bom,gates;}
  double std(double v){double[]a={10,20,25,50,75,100,150,200,250,300,500,750,1000};for(double x:a)if(x>=v)return x;return Math.ceil(v/100)*100;}double d(EditText e){return Double.parseDouble(e.getText().toString().trim().replace(',','.'));}int clamp(int v,int a,int b){return Math.max(a,Math.min(b,v));}int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(4));return p;}TextView tx(String s,int z,boolean b,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,b?Typeface.BOLD:Typeface.NORMAL);return v;}TextView card(String s,int c){TextView v=tx(s,13,false,Color.WHITE);v.setPadding(dp(10),dp(10),dp(10),dp(10));v.setBackground(bg(c,10));return v;}GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
}
