package com.mg.whiffletreeaero;

import android.app.*;
import android.os.Bundle;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    final int NAVY=Color.rgb(8,22,38), PANEL=Color.rgb(17,38,58), BLUE=Color.rgb(44,120,235), CYAN=Color.rgb(45,200,220), ORANGE=Color.rgb(245,160,40), GREEN=Color.rgb(55,190,105);
    LinearLayout root,wizard; TankView tankView; TextView stepTitle,help,status,result; Spinner loadCase,qProfile; EditText L,D,F,M,stations,layers,actCapacity,actCount,pressure,sf,padW,padL; Button back,next,autoBtn,calcBtn; int step=0;
    String[] CASES={"+Z Bending","-Z Bending","+Y Bending","-Y Bending","Pitch +My","Pitch -My","Roll +Mx","Roll -Mx","Yaw +Mz","Yaw -Mz","Combined Z+Pitch"};
    String[] QPROFILES={"Elliptic","Uniform","Triangular root-high","Triangular tip-high","Parabolic"};
    String[] ST={"1/7 Problem","2/7 Tank geometry","3/7 q(x) and stations","4/7 Whiffletree layers","5/7 Actuator optimization","6/7 Hardware defaults","7/7 Verify"};
    String[] HELP={"Test yönünü seç. Bilmiyorsan +Z Bending ile başla; varsayılanlar otomatik yüklenir.","Tank boyu ve çapı station konumlarını ve moment kollarını belirler.","Dağıtılmış q(x) profilini seç. Uygulama bunu Fi station kuvvetlerine dönüştürür ve ΣF/ΣM için düzeltir.","Katman arttıkça daha az actuator ile daha çok pad sürülebilir; fakat beam/pin/rod sayısı artar.","AUTO OPTIMIZE, toplam tasarım yüküne göre minimum actuator sayısını ve actuator başına yükü önerir.","Basınç, safety factor ve pad ölçüleri ön boyutlandırma için kullanılır.","Tank üzerindeki S1…Sn kuvvetlerini, ΣF/ΣM, actuator yüklerini ve whiffletree oranlarını kontrol et."};

    @Override public void onCreate(Bundle b){ super.onCreate(b);
      ScrollView sv=new ScrollView(this); root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(dp(10),dp(10),dp(10),dp(30)); root.setBackgroundColor(NAVY); sv.addView(root);
      root.addView(tx("EFT WHIFFLETREE SMART DESIGNER",25,true,Color.WHITE)); TextView sub=tx("v1.3 • Akıllı sentez • q(x)→Fi • actuator optimizer",13,false,Color.rgb(180,205,225)); sub.setPadding(0,0,0,dp(8)); root.addView(sub);
      LinearLayout presets=new LinearLayout(this); presets.setOrientation(LinearLayout.HORIZONTAL); HorizontalScrollView hs=new HorizontalScrollView(this); hs.addView(presets); root.addView(hs,lp());
      for(String c:CASES){Button btt=small(c); btt.setOnClickListener(v->{applyPreset(((Button)v).getText().toString());}); presets.addView(btt,new LinearLayout.LayoutParams(dp(118),dp(44)));}
      status=card("Hazır",Color.rgb(14,48,72)); root.addView(status,lp()); tankView=new TankView(); root.addView(tankView,new LinearLayout.LayoutParams(-1,dp(440)));
      wizard=new LinearLayout(this); wizard.setOrientation(LinearLayout.VERTICAL); wizard.setPadding(dp(10),dp(10),dp(10),dp(10)); wizard.setBackground(bg(PANEL,12)); root.addView(wizard,lp());
      stepTitle=tx("",18,true,Color.WHITE); help=tx("",13,false,Color.rgb(190,215,232)); wizard.addView(stepTitle); wizard.addView(help);
      loadCase=new Spinner(this); loadCase.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,CASES)); wizard.addView(loadCase,lp());
      qProfile=new Spinner(this); qProfile.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,QPROFILES)); wizard.addView(qProfile,lp());
      L=field("Tank length L [m]","7.6"); D=field("Tank diameter D [m]","0.64"); F=field("Target total load |F| [kN]","305.7"); M=field("Target moment [kN·m]","1280"); stations=field("Station count","12"); layers=field("Whiffletree layers","3"); actCapacity=field("Available actuator nominal capacity [kN]","120"); actCount=field("Actuator count","4"); pressure=field("Hydraulic pressure [bar]","210"); sf=field("Sizing factor","1.50"); padW=field("Pad width [mm]","150"); padL=field("Pad length [mm]","250");
      autoBtn=new Button(this); autoBtn.setText("AUTO OPTIMIZE ACTUATORS"); autoBtn.setOnClickListener(v->{try{Calc c=compute(true); actCount.setText(String.valueOf(c.nAct)); preview(c); result.setText("Actuator sayısı otomatik optimize edildi: "+c.nAct+" adet.\nTasarım yükü/actuator: "+fmt(c.actLoad)+" kN");}catch(Exception e){result.setText("Girişleri kontrol et.");}}); wizard.addView(autoBtn,lp());
      LinearLayout nav=new LinearLayout(this); back=new Button(this); next=new Button(this); calcBtn=new Button(this); back.setText("← Geri"); next.setText("Devam →"); calcBtn.setText("HESAPLA + SENTEZLE"); nav.addView(back,new LinearLayout.LayoutParams(0,dp(48),1)); nav.addView(next,new LinearLayout.LayoutParams(0,dp(48),1)); wizard.addView(nav,lp()); wizard.addView(calcBtn,lp());
      back.setOnClickListener(v->{if(step>0){step--;render();}}); next.setOnClickListener(v->{if(step<6){step++;render();}else calculate();}); calcBtn.setOnClickListener(v->calculate());
      loadCase.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){safePreview();} public void onNothingSelected(android.widget.AdapterView<?> p){}});
      qProfile.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){safePreview();} public void onNothingSelected(android.widget.AdapterView<?> p){}});
      result=card("Sihirbazı ilerlet veya HESAPLA + SENTEZLE'ye bas.",Color.rgb(12,34,52)); result.setTextSize(14); root.addView(result,lp());
      root.addView(card("Ön tasarım/eğitim aracıdır. Nihai test rig'i için onaylı load report, FEM, üretici katalog limitleri ve kurum prosedürü gereklidir.",Color.rgb(63,45,12)),lp());
      setContentView(sv); applyPreset("+Z Bending"); render();
    }

    EditText field(String label,String def){TextView l=tx(label,12,true,Color.rgb(185,210,230)); l.setPadding(0,dp(5),0,dp(2)); wizard.addView(l); EditText e=new EditText(this); e.setText(def); e.setTextColor(Color.WHITE); e.setSingleLine(true); e.setTextSize(16); e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED); e.setBackground(bg(Color.rgb(25,52,75),8)); e.setPadding(dp(10),0,dp(10),0); wizard.addView(e,new LinearLayout.LayoutParams(-1,dp(44))); e.setOnFocusChangeListener((v,h)->{if(!h)safePreview();}); return e;}
    void render(){stepTitle.setText(ST[step]); help.setText(HELP[step]); loadCase.setVisibility(step==0?View.VISIBLE:View.GONE); qProfile.setVisibility(step==2?View.VISIBLE:View.GONE); show(L,step==1);show(D,step==1);show(F,step==0||step==5);show(M,step==0||step==5);show(stations,step==2);show(layers,step==3);show(actCapacity,step==4);show(actCount,step==4);show(pressure,step==5);show(sf,step==5);show(padW,step==5);show(padL,step==5);autoBtn.setVisibility(step==4?View.VISIBLE:View.GONE);calcBtn.setVisibility(step==6?View.VISIBLE:View.GONE);back.setEnabled(step>0);next.setText(step==6?"Hesapla":"Devam →");safePreview();}
    void show(EditText e,boolean on){int i=wizard.indexOfChild(e); if(i>0)wizard.getChildAt(i-1).setVisibility(on?View.VISIBLE:View.GONE); e.setVisibility(on?View.VISIBLE:View.GONE);}
    void applyPreset(String p){int ix=Arrays.asList(CASES).indexOf(p); if(ix>=0)loadCase.setSelection(ix); if(p.contains("+Z")){F.setText("305.7");M.setText("1280");} else if(p.contains("-Z")){F.setText("260");M.setText("-1080");} else if(p.contains("+Y")){F.setText("90");M.setText("360");} else if(p.contains("-Y")){F.setText("90");M.setText("-360");} else if(p.contains("Pitch")){F.setText("120");M.setText(p.contains("-")?"-150":"150");} else if(p.contains("Roll")){F.setText("40");M.setText(p.contains("-")?"-18":"18");} else if(p.contains("Yaw")){F.setText("50");M.setText(p.contains("-")?"-90":"90");} else {F.setText("220");M.setText("820");} safePreview();}
    void safePreview(){try{preview(compute(false));}catch(Exception ignored){}}
    void preview(Calc c){tankView.set(c); status.setText(String.format(Locale.US,"%s • q=%s • ΣF %.1f kN • M %.1f kN·m • %d stations • %d actuators",CASES[loadCase.getSelectedItemPosition()],QPROFILES[qProfile.getSelectedItemPosition()],c.sumF,c.calcM,c.n,c.nAct));}
    void calculate(){try{Calc c=compute(false); preview(c); StringBuilder s=new StringBuilder(); s.append("SMART SYNTHESIS RESULT\n"); s.append("Load case: "+CASES[loadCase.getSelectedItemPosition()]+"\nq(x): "+QPROFILES[qProfile.getSelectedItemPosition()]+"\n\n"); s.append(String.format(Locale.US,"ΣF target / calc: %.1f / %.1f kN\nM target / calc: %.1f / %.1f kN·m\nMoment error: %.2f %%\n\n",c.targetF,c.sumF,c.targetM,c.calcM,c.mErr)); s.append(String.format(Locale.US,"Design load: %.1f kN\nActuators: %d\nDesign load / actuator: %.1f kN\nEquivalent bore @ %.0f bar: %.1f mm\nPreselect load cell: ≥ %.0f kN\n\n",c.designF,c.nAct,c.actLoad,c.pbar,c.bore,c.lc)); s.append("STATIONS\n"); for(int i=0;i<c.n;i++)s.append(String.format(Locale.US,"S%-2d x=%5.2f m  F=%6.1f kN\n",i+1,c.x[i],c.fi[i])); s.append("\nWHIFFLETREE SYNTHESIS\n"); s.append(c.tree); s.append("\nCHECKS\n"); s.append(Math.abs(c.mErr)<1?"✓ Force/moment match good\n":"! Moment error >1%; revise station/pad geometry\n"); s.append(c.padP<8?"✓ Mean pad pressure preliminary-low/moderate\n":"! Mean pad pressure high; local FEM required\n"); result.setText(s.toString()); step=6;render();}catch(Exception e){result.setText("Geçersiz giriş. Tüm alanları sayısal olarak kontrol et.");}}

    Calc compute(boolean auto){Calc c=new Calc(); c.L=d(L); c.D=d(D); c.targetF=Math.abs(d(F)); c.targetM=d(M); c.n=clamp((int)Math.round(d(stations)),4,16); c.layers=clamp((int)Math.round(d(layers)),1,3); c.pbar=Math.max(1,d(pressure)); c.sf=Math.max(1,d(sf)); double cap=Math.max(1,d(actCapacity)); int manual=clamp((int)Math.round(d(actCount)),1,12); c.designF=c.targetF*c.sf; int minByCapacity=(int)Math.ceil(c.designF/cap); int minByTopology=Math.max(1,(int)Math.ceil(c.n/Math.pow(2,c.layers))); c.nAct=auto?Math.max(minByCapacity,minByTopology):manual; c.actLoad=c.designF/c.nAct; c.bore=Math.sqrt(4*(c.actLoad*1000)/(c.pbar*100000)/Math.PI)*1000; c.lc=stdClass(c.actLoad*1.2); c.x=new double[c.n]; c.fi=new double[c.n]; double[] w=new double[c.n]; double sw=0; int q=qProfile.getSelectedItemPosition(); for(int i=0;i<c.n;i++){double u=(i+.5)/c.n; c.x[i]=u*c.L; if(q==0)w[i]=Math.sqrt(Math.max(0,1-Math.pow(2*u-1,2)))+.05; else if(q==1)w[i]=1; else if(q==2)w[i]=1.15-u; else if(q==3)w[i]=.15+u; else w[i]=.25+4*u*(1-u); sw+=w[i];} for(int i=0;i<c.n;i++)c.fi[i]=c.targetF*w[i]/sw;
      double desired=Math.abs(c.targetM), base=0; for(int i=0;i<c.n;i++)base+=c.fi[i]*c.x[i]; double delta=desired-base; double mean=0; for(double xx:c.x)mean+=xx; mean/=c.n; double den=0; for(double xx:c.x)den+=(xx-mean)*(xx-mean); if(Math.abs(delta)>1e-9&&den>1e-9){for(int i=0;i<c.n;i++)c.fi[i]+=delta*(c.x[i]-mean)/den;}
      boolean neg=false; for(double v:c.fi)if(v<0)neg=true; if(neg){for(int i=0;i<c.n;i++)c.fi[i]=Math.max(.001,c.fi[i]); double sum=0;for(double v:c.fi)sum+=v;for(int i=0;i<c.n;i++)c.fi[i]*=c.targetF/sum;}
      c.sumF=0;c.calcM=0;for(int i=0;i<c.n;i++){c.sumF+=c.fi[i];c.calcM+=c.fi[i]*c.x[i];} if(c.targetM<0)c.calcM=-c.calcM; c.mErr=Math.abs(c.targetM)>1e-6?100*(c.calcM-c.targetM)/Math.abs(c.targetM):0; double area=Math.max(1,d(padW)*d(padL)); double max=0;for(double v:c.fi)max=Math.max(max,v); c.padP=max*1000/(area/1e6)/1e6; c.tree=synth(c); return c; }
    String synth(Calc c){StringBuilder s=new StringBuilder(); ArrayList<Double> vals=new ArrayList<>(); for(double v:c.fi)vals.add(v*c.sf); int lvl=1; while(vals.size()>1&&lvl<=c.layers){ArrayList<Double> nx=new ArrayList<>(); s.append("Layer "+lvl+":\n"); for(int i=0;i<vals.size();i+=2){if(i+1<vals.size()){double a=vals.get(i),b=vals.get(i+1),tot=a+b; double left=b/tot,right=a/tot; s.append(String.format(Locale.US,"  B%d  %.1f + %.1f = %.1f kN | pivot %.0f/%.0f %%\n",i/2+1,a,b,tot,left*100,right*100)); nx.add(tot);}else{nx.add(vals.get(i)); s.append(String.format(Locale.US,"  B%d  single %.1f kN\n",i/2+1,vals.get(i)));}} vals=nx;lvl++;} s.append("Top branches after selected layers: "+vals.size()+"\nSelected actuators: "+c.nAct+"\n"); return s.toString();}

    class TankView extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),t=new Paint(Paint.ANTI_ALIAS_FLAG); Calc c; TankView(){super(MainActivity.this);setBackgroundColor(Color.rgb(5,17,29));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));} void set(Calc x){c=x;invalidate();} protected void onDraw(Canvas cn){super.onDraw(cn); int w=getWidth(),h=getHeight(); if(c==null)return; float y=h*.42f,left=w*.08f,right=w*.94f,len=right-left; p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(44,55,70)); RectF tank=new RectF(left,y-h*.07f,right,y+h*.07f); cn.drawRoundRect(tank,h*.07f,h*.07f,p); p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.rgb(170,190,210));cn.drawRoundRect(tank,h*.07f,h*.07f,p); t.setTextSize(dp(10));t.setColor(Color.WHITE); for(int i=0;i<c.n;i++){float x=left+(float)(c.x[i]/c.L)*len; p.setColor(CYAN);p.setStrokeWidth(2);cn.drawLine(x,y-h*.07f,x,y+h*.07f,p); float ah=(float)Math.min(h*.24,dp(30)+c.fi[i]*.65); p.setColor(BLUE);p.setStrokeWidth(4);cn.drawLine(x,y-h*.09f,x,y-h*.09f-ah,p);cn.drawLine(x,y-h*.09f,x-dp(5),y-h*.09f-dp(8),p);cn.drawLine(x,y-h*.09f,x+dp(5),y-h*.09f-dp(8),p); cn.drawText("S"+(i+1),x-dp(7),y+h*.12f,t); cn.drawText(String.format(Locale.US,"%.0f",c.fi[i]),x-dp(8),y-h*.12f-ah,t);} float base=h*.82f; p.setColor(Color.rgb(60,75,90));p.setStrokeWidth(7);cn.drawLine(w*.08f,base,w*.94f,base,p); for(int a=0;a<c.nAct;a++){float ax=w*(.15f+.7f*(a+.5f)/c.nAct);p.setColor(GREEN);p.setStyle(Paint.Style.FILL);cn.drawRect(ax-dp(12),base-dp(55),ax+dp(12),base,p);p.setStyle(Paint.Style.STROKE);p.setColor(Color.WHITE);p.setStrokeWidth(2);cn.drawLine(ax,base-dp(55),ax,y+h*.1f,p);t.setTextSize(dp(9));cn.drawText("A"+(a+1),ax-dp(7),base+dp(14),t);} p.setColor(ORANGE);p.setStrokeWidth(5); for(int i=0;i<c.n-1;i+=2){float x1=left+(float)(c.x[i]/c.L)*len,x2=left+(float)(c.x[Math.min(i+1,c.n-1)]/c.L)*len;float by=y+h*.18f;cn.drawLine(x1,by,x2,by,p);cn.drawLine(x1,y+h*.08f,x1,by,p);cn.drawLine(x2,y+h*.08f,x2,by,p);} t.setTextSize(dp(12));t.setColor(Color.rgb(200,220,235));cn.drawText("EFT + station loads + whiffletree + actuators",dp(10),dp(20),t);cn.drawText(String.format(Locale.US,"ΣF %.1f kN   M %.1f kN·m",c.sumF,c.calcM),dp(10),dp(38),t);}}
    static class Calc{double L,D,targetF,targetM,pbar,sf,designF,actLoad,bore,lc,sumF,calcM,mErr,padP;int n,layers,nAct;double[]x,fi;String tree;}
    double stdClass(double v){double[] a={10,20,25,50,75,100,150,200,250,300,500,750,1000};for(double x:a)if(x>=v)return x;return Math.ceil(v/100)*100;}
    double d(EditText e){return Double.parseDouble(e.getText().toString().trim().replace(',','.'));} int clamp(int v,int a,int b){return Math.max(a,Math.min(b,v));} String fmt(double v){return String.format(Locale.US,"%.1f",v);} int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(4));return p;} TextView tx(String s,int z,boolean b,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,b?Typeface.BOLD:Typeface.NORMAL);return v;} TextView card(String s,int c){TextView v=tx(s,13,false,Color.WHITE);v.setPadding(dp(10),dp(10),dp(10),dp(10));v.setBackground(bg(c,10));return v;} Button small(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setAllCaps(false);return b;} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
}
