package com.mg.whiffletreeaero;
import android.os.Bundle;import android.graphics.*;import android.view.*;import android.widget.*;import java.util.*;
public class V48Activity extends V47Activity{
 TextView bomInfo; BomView bomView;
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(8),dp(8),dp(8),dp(8));p.setBackground(bg(Color.rgb(12,31,47),12));p.addView(tx("PROFESSIONAL AUTO BOM / COMPONENT SELECTION",16,true,Color.WHITE));bomInfo=card("BOM hesaplanıyor...",Color.rgb(20,48,68));p.addView(bomInfo,lp());bomView=new BomView();p.addView(bomView,new LinearLayout.LayoutParams(-1,dp(980)));root.addView(p,28,lp());refreshBom();}
 void refreshBom(){try{Calc c=compute(false);int a=Math.max(1,(int)Math.round(d(actCount))),n=c.n,l=Math.max(1,(int)Math.round(d(layers))),beams=Math.max(1,n-a)+Math.max(0,(l-1)*a),joints=n+beams+a,pins=joints,lc=a,sv=a,hoses=2*a,pressCount=a,lvdt=a,strain=4*n,daq=lc+lvdt+pressCount+strain+n;double sum=0;for(double v:c.fi)sum+=v;double actDesign=sum/a*c.sf;double lcCap=std(actDesign,new double[]{25,50,75,100,150,200,250,300,500,750,1000});double bore=Math.sqrt(4*(actDesign*1000)/(Math.PI*Math.max(1,d(pressure)*1e5)))*1000;double boreSel=std(bore,new double[]{32,40,50,63,80,100,125,160,200});bomInfo.setText(String.format(Locale.US,"AUTO BOM SUMMARY\n%d stations • %d actuators • %d layers • ~%d beams\nDesign actuator load %.1f kN • suggested bore %.0f mm • load cell %.0f kN\n%d pins/joints • %d servo valves • %d hydraulic hoses • ~%d DAQ channels\nSelection is concept-level: replace generic classes with approved supplier part numbers after detailed qualification.",n,a,l,beams,actDesign,boreSel,lcCap,pins,sv,hoses,daq));bomView.data=new int[]{n,a,l,beams,joints,pins,lc,sv,hoses,pressCount,lvdt,strain,daq};bomView.invalidate();}catch(Exception e){}}
 double std(double x,double[] s){for(double v:s)if(v>=x)return v;return s[s.length-1];}
 class BomView extends View{
  Paint p=new Paint(1),t=new Paint(1);int[] data=new int[13];String[] names={"LOAD PADS / SADDLES","ACTUATORS","WHIFFLETREE LAYERS","BEAMS","SPHERICAL JOINTS","PINS / CLEVISES","LOAD CELLS","SERVO VALVES","HP/RETURN HOSES","PRESSURE SENSORS","LVDT","STRAIN CHANNELS","TOTAL DAQ CH."};
  BomView(){super(V48Activity.this);setBackgroundColor(Color.rgb(5,17,29));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));}
  @Override protected void onDraw(Canvas c){super.onDraw(c);int W=getWidth();t.setColor(Color.WHITE);t.setTextSize(dp(13));c.drawText("EFT RIG BILL OF MATERIALS",dp(14),dp(30),t);float y=dp(70);for(int i=0;i<names.length;i++){p.setColor(i%2==0?Color.rgb(16,43,62):Color.rgb(20,51,72));c.drawRoundRect(new RectF(dp(14),y,W-dp(14),y+dp(48)),dp(6),dp(6),p);t.setTextSize(dp(7));t.setColor(Color.rgb(190,215,232));c.drawText(names[i],dp(26),y+dp(20),t);t.setTextSize(dp(10));t.setColor(i==12?Color.rgb(247,207,77):Color.WHITE);c.drawText(String.valueOf(data[i]),W-dp(62),y+dp(30),t);y+=dp(55);}float sy=y+dp(15);p.setColor(Color.rgb(16,43,62));c.drawRoundRect(new RectF(dp(14),sy,W-dp(14),sy+dp(170)),dp(8),dp(8),p);t.setColor(Color.rgb(247,207,77));t.setTextSize(dp(8));c.drawText("PURCHASE / DESIGN PACKAGE",dp(26),sy+dp(28),t);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText("Actuator + servo valve + manifold + hose/fittings",dp(26),sy+dp(55),t);c.drawText("Load cell + LVDT + pressure + strain instrumentation",dp(26),sy+dp(80),t);c.drawText("Beam + pivot + pin + clevis + spherical bearing + tie rod",dp(26),sy+dp(105),t);c.drawText("Pad/liner + strongback + anchors + guards + cable/hose routing",dp(26),sy+dp(130),t);t.setColor(Color.rgb(185,210,230));c.drawText("Final P/N requires supplier datasheet and independent engineering approval.",dp(26),sy+dp(155),t);}
 }
}
