package com.mg.whiffletreeaero;
import android.os.Bundle;import android.graphics.*;import android.view.*;import android.widget.*;import java.util.*;
public class V50Activity extends V49Activity{
 TextView verifyInfo; VerifyView verifyView;
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(8),dp(8),dp(8),dp(8));p.setBackground(bg(Color.rgb(12,31,47),12));p.addView(tx("INDEPENDENT CALCULATION VERIFICATION",16,true,Color.WHITE));verifyInfo=card("Verification running...",Color.rgb(20,48,68));p.addView(verifyInfo,lp());verifyView=new VerifyView();p.addView(verifyView,new LinearLayout.LayoutParams(-1,dp(780)));root.addView(p,30,lp());refreshVerify();}
 double pct(double a,double b){return 100*Math.abs(a-b)/Math.max(1,Math.abs(b));}
 void refreshVerify(){try{Calc c=compute(false);double sf=0,m=0,act=0;for(int i=0;i<c.n;i++){sf+=c.fi[i];m+=c.fi[i]*c.x[i];}for(double v:c.actLoads)act+=v;double eF=pct(sf,c.targetF),eM=pct(m,c.targetM),eA=pct(act,sf),beamEq=Math.abs(c.sumF-sf)/Math.max(1,sf)*100;boolean ok=eF<=1&&eM<=2&&eA<=2&&beamEq<=1;verifyInfo.setText(String.format(Locale.US,"%s\nIndependent path A: Σstation = %.2f kN vs target %.2f kN | error %.3f%%\nIndependent path B: Σ(Fi·xi) = %.2f kN·m vs target %.2f | error %.3f%%\nActuator closure: Σactuator = %.2f kN vs station %.2f | error %.3f%%\nBeam/reaction closure error %.3f%%\n%s",ok?"CALCULATION VERIFIED":"CALCULATION NOT VERIFIED",sf,c.targetF,m,c.targetM,eM,act,sf,eA,beamEq,ok?"All concept-level equilibrium gates passed.":"Review load distribution/topology before using sizing outputs."));verifyView.vals=new double[]{eF,eM,eA,beamEq};verifyView.invalidate();}catch(Exception e){verifyInfo.setText("CALCULATION NOT VERIFIED — inputs could not be independently evaluated.");}}
 class VerifyView extends View{
  Paint p=new Paint(1),t=new Paint(1);double[] vals={0,0,0,0};String[] n={"ΣF CLOSURE","ΣM CLOSURE","ACTUATOR CLOSURE","REACTION / BEAM"};double[] lim={1,2,2,1};
  VerifyView(){super(V50Activity.this);setBackgroundColor(Color.rgb(5,17,29));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));}
  @Override protected void onDraw(Canvas c){super.onDraw(c);int W=getWidth();t.setColor(Color.WHITE);t.setTextSize(dp(13));c.drawText("TWO-PATH EQUILIBRIUM AUDIT",dp(16),dp(32),t);float y=dp(80);for(int i=0;i<4;i++){boolean ok=vals[i]<=lim[i];p.setColor(Color.rgb(16,43,62));c.drawRoundRect(new RectF(dp(16),y,W-dp(16),y+dp(105)),dp(8),dp(8),p);t.setColor(Color.WHITE);t.setTextSize(dp(8));c.drawText(n[i],dp(28),y+dp(28),t);t.setColor(ok?Color.rgb(75,210,130):Color.rgb(235,85,75));t.setTextSize(dp(12));c.drawText(String.format(Locale.US,"%.3f%%  %s",vals[i],ok?"PASS":"FAIL"),dp(28),y+dp(60),t);t.setTextSize(dp(7));t.setColor(Color.rgb(185,210,230));c.drawText(String.format(Locale.US,"verification gate ≤ %.1f%%",lim[i]),dp(28),y+dp(86),t);y+=dp(120);}p.setColor(Color.rgb(20,51,72));c.drawRoundRect(new RectF(dp(16),y+dp(10),W-dp(16),y+dp(155)),dp(8),dp(8),p);t.setColor(Color.rgb(247,207,77));t.setTextSize(dp(8));c.drawText("VERIFICATION PHILOSOPHY",dp(28),y+dp(40),t);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText("Primary sizing results are not accepted solely because the UI produced them.",dp(28),y+dp(70),t);c.drawText("Force, moment, actuator and reaction closures are recomputed independently.",dp(28),y+dp(95),t);c.drawText("Final rig release still requires detailed structural/FEM and test-safety review.",dp(28),y+dp(120),t);}
 }
}