package com.mg.whiffletreeaero;
import android.os.Bundle;import android.graphics.*;import android.view.*;import android.widget.*;import java.util.*;
public class V52Activity extends V51Activity{
 TextView nodeInfo; NodeView nodeView;
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(8),dp(8),dp(8),dp(8));p.setBackground(bg(Color.rgb(12,31,47),12));p.addView(tx("NODE EQUILIBRIUM SOLVER",16,true,Color.WHITE));nodeInfo=card("Node equilibrium solving...",Color.rgb(20,48,68));p.addView(nodeInfo,lp());nodeView=new NodeView();p.addView(nodeView,new LinearLayout.LayoutParams(-1,dp(980)));root.addView(p,32,lp());refreshNodes();}
 static class NR{int id,layer;double fl,fr,reaction,mErr;String status;}
 ArrayList<NR> solveNodes(){Calc c=compute(false);ArrayList<NR> out=new ArrayList<>();for(BeamData b:c.beamData){NR n=new NR();n.id=b.id+1;n.layer=b.layer;n.fl=b.fLeft;n.fr=b.fRight;n.reaction=b.fLeft+b.fRight;double ml=b.fLeft*b.leftArm,mr=b.fRight*b.rightArm;n.mErr=100*Math.abs(ml-mr)/Math.max(1e-9,Math.max(Math.abs(ml),Math.abs(mr)));n.status=n.mErr<=0.5?"PASS":(n.mErr<=2?"WARN":"FAIL");out.add(n);}return out;}
 void refreshNodes(){try{ArrayList<NR> a=solveNodes();double worst=0,totalR=0;for(NR n:a){worst=Math.max(worst,n.mErr);totalR+=n.reaction;}nodeInfo.setText(String.format(Locale.US,"%s\nSolved %d whiffletree beam/pivot nodes bottom-up.\nWorst node moment-balance error %.4f%% | summed node reactions %.1f kN\nEach node uses ΣF=0 and ΣM=0 in the local beam plane. Fx/Fy/Fz components from the 6-DOF screen remain concept-level until full 3D attachment geometry is defined.",worst<=0.5?"NODE NETWORK VERIFIED":(worst<=2?"NODE NETWORK REVIEW":"NODE NETWORK FAIL"),a.size(),worst,totalR));nodeView.nodes=a;nodeView.invalidate();}catch(Exception e){nodeInfo.setText("NODE NETWORK NOT VERIFIED — inputs could not be solved.");}}
 class NodeView extends View{Paint p=new Paint(1),t=new Paint(1);ArrayList<NR> nodes=new ArrayList<>();NodeView(){super(V52Activity.this);setBackgroundColor(Color.rgb(5,17,29));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));}
 @Override protected void onDraw(Canvas c){super.onDraw(c);int W=getWidth();t.setColor(Color.WHITE);t.setTextSize(dp(13));c.drawText("WHIFFLETREE NODE FREE-BODY AUDIT",dp(16),dp(30),t);float y=dp(70);int shown=Math.min(nodes.size(),10);for(int i=0;i<shown;i++){NR n=nodes.get(i);int col=n.status.equals("PASS")?Color.rgb(67,190,113):(n.status.equals("WARN")?Color.rgb(247,207,77):Color.rgb(229,82,74));p.setColor(Color.rgb(16,43,62));c.drawRoundRect(new RectF(dp(16),y,W-dp(16),y+dp(78)),dp(7),dp(7),p);t.setColor(Color.WHITE);t.setTextSize(dp(8));c.drawText(String.format(Locale.US,"B%d  L%d",n.id,n.layer),dp(28),y+dp(24),t);t.setTextSize(dp(7));c.drawText(String.format(Locale.US,"Fleft %.1f  Fright %.1f  R %.1f kN",n.fl,n.fr,n.reaction),dp(28),y+dp(48),t);t.setColor(col);c.drawText(String.format(Locale.US,"ΣM err %.4f%%  %s",n.mErr,n.status),W-dp(150),y+dp(48),t);y+=dp(88);}p.setColor(Color.rgb(20,51,72));c.drawRoundRect(new RectF(dp(16),y+dp(10),W-dp(16),y+dp(165)),dp(8),dp(8),p);t.setColor(Color.rgb(247,207,77));t.setTextSize(dp(8));c.drawText("LOCAL NODE EQUILIBRIUM",dp(28),y+dp(40),t);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText("Reaction = Fleft + Fright",dp(28),y+dp(68),t);c.drawText("Moment check: Fleft·Lleft ≈ Fright·Lright",dp(28),y+dp(94),t);c.drawText("Node results propagate upward through the whiffletree tree.",dp(28),y+dp(120),t);c.drawText("Full 3D vector closure will require actual joint coordinates and axis directions.",dp(28),y+dp(146),t);}
 }
}