package com.mg.whiffletreeaero;
import android.os.Bundle;import android.graphics.*;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;
public class V53Activity extends V52Activity{
 EditText yOff,zOff,actDrop; TextView jointInfo; Joint3DView jointView;
 @Override public void onCreate(Bundle b){super.onCreate(b);yOff=field("Pad lateral Y offset [mm]","180");zOff=field("Beam/pivot Z offset [mm]","220");actDrop=field("Actuator base drop [mm]","700");LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(8),dp(8),dp(8),dp(8));p.setBackground(bg(Color.rgb(12,31,47),12));p.addView(tx("3D JOINT COORDINATE / LINK VECTOR SOLVER",16,true,Color.WHITE));jointInfo=card("3D joint geometry solving...",Color.rgb(20,48,68));p.addView(jointInfo,lp());jointView=new Joint3DView();p.addView(jointView,new LinearLayout.LayoutParams(-1,dp(980)));root.addView(p,33,lp());TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){refreshJoints();}public void afterTextChanged(Editable e){}};for(EditText e:new EditText[]{yOff,zOff,actDrop,F,M,L,D,stations,actCount,actCapacity,sf})e.addTextChangedListener(w);refreshJoints();}
 static class JR{int id;double x1,y1,z1,x2,y2,z2,len,ux,uy,uz,axial,lateral,angle;String status;}
 ArrayList<JR> solveJoints(){Calc c=compute(false);ArrayList<JR> a=new ArrayList<>();double yo=d(yOff)/1000.0,zo=d(zOff)/1000.0,drop=d(actDrop)/1000.0;for(int i=0;i<c.n;i++){JR r=new JR();r.id=i+1;r.x1=c.x[i];r.y1=(i%2==0?yo:-yo);r.z1=c.D/2.0;r.x2=c.x[i];r.y2=0;r.z2=c.D/2.0-zo;double dx=r.x2-r.x1,dy=r.y2-r.y1,dz=r.z2-r.z1;r.len=Math.sqrt(dx*dx+dy*dy+dz*dz);r.ux=dx/r.len;r.uy=dy/r.len;r.uz=dz/r.len;double f=c.fi[i]*c.sf;r.axial=f/Math.max(.15,Math.abs(r.uz));r.lateral=Math.abs(r.axial)*Math.sqrt(r.ux*r.ux+r.uy*r.uy);r.angle=Math.toDegrees(Math.acos(Math.min(1,Math.max(-1,Math.abs(r.uz)))));r.status=r.angle<=8?"PASS":(r.angle<=12?"WARN":"FAIL");a.add(r);}return a;}
 void refreshJoints(){try{ArrayList<JR>a=solveJoints();double peak=0,ang=0,lat=0;for(JR r:a){peak=Math.max(peak,r.axial);ang=Math.max(ang,r.angle);lat=Math.max(lat,r.lateral);}jointInfo.setText(String.format(Locale.US,"3D JOINT SOLVER\nSolved %d pad→pivot links from explicit X/Y/Z coordinates.\nPeak axial %.1f kN | peak lateral %.1f kN | max misalignment %.2f°\nCoordinates are generated from tank stations + editable Y/Z offsets.\nActuator base drop %.0f mm is reserved for next full actuator-axis closure stage.",a.size(),peak,lat,ang,d(actDrop)));jointView.j=a;jointView.invalidate();}catch(Exception e){jointInfo.setText("3D JOINT SOLVER NOT VERIFIED — geometry/input error.");}}
 class Joint3DView extends View{Paint p=new Paint(1),t=new Paint(1);ArrayList<JR> j=new ArrayList<>();Joint3DView(){super(V53Activity.this);setBackgroundColor(Color.rgb(5,17,29));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));}
 @Override protected void onDraw(Canvas c){super.onDraw(c);int W=getWidth();t.setColor(Color.WHITE);t.setTextSize(dp(13));c.drawText("PAD → PIVOT 3D VECTOR MAP",dp(16),dp(30),t);float y=dp(70);int shown=Math.min(j.size(),10);for(int i=0;i<shown;i++){JR r=j.get(i);int col=r.status.equals("PASS")?Color.rgb(67,190,113):(r.status.equals("WARN")?Color.rgb(247,207,77):Color.rgb(229,82,74));p.setColor(Color.rgb(16,43,62));c.drawRoundRect(new RectF(dp(16),y,W-dp(16),y+dp(78)),dp(7),dp(7),p);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText(String.format(Locale.US,"S%d  L %.0f mm  u=[%.2f, %.2f, %.2f]",r.id,r.len*1000,r.ux,r.uy,r.uz),dp(28),y+dp(24),t);c.drawText(String.format(Locale.US,"Axial %.1f kN  Lateral %.1f kN",r.axial,r.lateral),dp(28),y+dp(49),t);t.setColor(col);c.drawText(String.format(Locale.US,"θ %.2f°  %s",r.angle,r.status),W-dp(118),y+dp(49),t);y+=dp(88);}p.setColor(Color.rgb(20,51,72));c.drawRoundRect(new RectF(dp(16),y+dp(10),W-dp(16),y+dp(180)),dp(8),dp(8),p);t.setColor(Color.rgb(247,207,77));t.setTextSize(dp(8));c.drawText("3D LINK PHYSICS",dp(28),y+dp(40),t);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText("u = (P2-P1)/|P2-P1|",dp(28),y+dp(68),t);c.drawText("Axial demand follows station load projected onto the link axis.",dp(28),y+dp(94),t);c.drawText("Lateral component exposes misalignment / side-load sensitivity.",dp(28),y+dp(120),t);c.drawText("Next stage will close pivot→actuator coordinates and 3D reactions.",dp(28),y+dp(146),t);}
 }
}