package com.mg.whiffletreeaero;
import android.os.Bundle;import android.graphics.*;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;
public class V54Activity extends V53Activity{
 EditText baseY,baseX;TextView closureInfo;ClosureView closureView;
 @Override public void onCreate(Bundle b){super.onCreate(b);baseY=field("Actuator base Y offset [mm]","0");baseX=field("Actuator base X offset [mm]","0");LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(8),dp(8),dp(8),dp(8));p.setBackground(bg(Color.rgb(12,31,47),12));p.addView(tx("PIVOT → ACTUATOR 3D CLOSURE / AXIS REACTION",16,true,Color.WHITE));closureInfo=card("3D actuator closure solving...",Color.rgb(20,48,68));p.addView(closureInfo,lp());closureView=new ClosureView();p.addView(closureView,new LinearLayout.LayoutParams(-1,dp(980)));root.addView(p,34,lp());TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){refreshClosure();}public void afterTextChanged(Editable e){}};for(EditText e:new EditText[]{baseY,baseX,yOff,zOff,actDrop,F,M,L,D,stations,actCount,actCapacity,sf})e.addTextChangedListener(w);refreshClosure();}
 static class AR{int id,count;double px,py,pz,bx,by,bz,ux,uy,uz,total,axis,side,angle,closure;String status;}
 ArrayList<AR> solveClosure(){Calc c=compute(false);ArrayList<JR> links=solveJoints();int na=Math.max(1,c.nAct);double[] fx=new double[na],fy=new double[na],fz=new double[na],sx=new double[na],sy=new double[na],sz=new double[na];int[] cnt=new int[na];for(int i=0;i<links.size();i++){JR r=links.get(i);int a=c.stationAct[i];if(a<0||a>=na)continue;double f=r.axial;fx[a]+=f*r.ux;fy[a]+=f*r.uy;fz[a]+=f*r.uz;sx[a]+=r.x2;sy[a]+=r.y2;sz[a]+=r.z2;cnt[a]++;}ArrayList<AR> out=new ArrayList<>();double by=d(baseY)/1000.0,bxOff=d(baseX)/1000.0,drop=d(actDrop)/1000.0;for(int a=0;a<na;a++){AR r=new AR();r.id=a+1;r.count=Math.max(1,cnt[a]);r.px=sx[a]/r.count;r.py=sy[a]/r.count;r.pz=sz[a]/r.count;r.bx=r.px+bxOff;r.by=by;r.bz=r.pz-drop;double dx=r.bx-r.px,dy=r.by-r.py,dz=r.bz-r.pz,len=Math.sqrt(dx*dx+dy*dy+dz*dz);if(len<1e-6)len=1e-6;r.ux=dx/len;r.uy=dy/len;r.uz=dz/len;r.total=Math.sqrt(fx[a]*fx[a]+fy[a]*fy[a]+fz[a]*fz[a]);double dot=fx[a]*r.ux+fy[a]*r.uy+fz[a]*r.uz;r.axis=Math.abs(dot);r.side=Math.sqrt(Math.max(0,r.total*r.total-r.axis*r.axis));r.angle=Math.toDegrees(Math.atan2(r.side,Math.max(1e-9,r.axis)));r.closure=100*r.side/Math.max(1e-9,r.total);r.status=r.closure<=5?"PASS":(r.closure<=10?"WARN":"FAIL");out.add(r);}return out;}
 void refreshClosure(){try{ArrayList<AR>a=solveClosure();double peakAxis=0,peakSide=0,worst=0,ang=0;int fail=0;for(AR r:a){peakAxis=Math.max(peakAxis,r.axis);peakSide=Math.max(peakSide,r.side);worst=Math.max(worst,r.closure);ang=Math.max(ang,r.angle);if(r.status.equals("FAIL"))fail++;}String st=fail>0?"3D ACTUATOR CLOSURE: FAIL":(worst>5?"3D ACTUATOR CLOSURE: WARN":"3D ACTUATOR CLOSURE: PASS");closureInfo.setText(String.format(Locale.US,"%s\nActuators %d | peak axis %.1f kN | peak side-load %.1f kN\nMax axis misalignment %.2f° | worst single-axis residual %.2f%%\nBase offsets X %.0f mm | Y %.0f mm | drop %.0f mm\nThe side component is the force that a purely axial actuator cannot carry without joint/fixture reaction. Final acceptance requires supplier side-load limits and detailed 3D fixture analysis.",st,a.size(),peakAxis,peakSide,ang,worst,d(baseX),d(baseY),d(actDrop)));closureView.a=a;closureView.invalidate();}catch(Exception e){closureInfo.setText("3D ACTUATOR CLOSURE NOT VERIFIED — geometry/input error.");}}
 class ClosureView extends View{Paint p=new Paint(1),t=new Paint(1);ArrayList<AR>a=new ArrayList<>();ClosureView(){super(V54Activity.this);setBackgroundColor(Color.rgb(5,17,29));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));}
 @Override protected void onDraw(Canvas c){super.onDraw(c);int W=getWidth();t.setColor(Color.WHITE);t.setTextSize(dp(13));c.drawText("ACTUATOR AXIS REACTION / 3D LOAD PATH",dp(16),dp(30),t);float y=dp(70);int shown=Math.min(a.size(),8);for(int i=0;i<shown;i++){AR r=a.get(i);int col=r.status.equals("PASS")?Color.rgb(67,190,113):(r.status.equals("WARN")?Color.rgb(247,207,77):Color.rgb(229,82,74));p.setColor(Color.rgb(16,43,62));c.drawRoundRect(new RectF(dp(16),y,W-dp(16),y+dp(96)),dp(7),dp(7),p);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText(String.format(Locale.US,"A%d  axis u=[%.2f, %.2f, %.2f]  %d stations",r.id,r.ux,r.uy,r.uz,r.count),dp(28),y+dp(23),t);c.drawText(String.format(Locale.US,"Resultant %.1f | Axis %.1f | Side %.1f kN",r.total,r.axis,r.side),dp(28),y+dp(48),t);t.setColor(col);c.drawText(String.format(Locale.US,"θ %.2f°  residual %.2f%%  %s",r.angle,r.closure,r.status),dp(28),y+dp(74),t);y+=dp(106);}p.setColor(Color.rgb(20,51,72));c.drawRoundRect(new RectF(dp(16),y+dp(10),W-dp(16),y+dp(185)),dp(8),dp(8),p);t.setColor(Color.rgb(247,207,77));t.setTextSize(dp(8));c.drawText("3D CLOSURE PHYSICS",dp(28),y+dp(40),t);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText("Incoming pivot load vector = Σ(link axial force × link unit vector).",dp(28),y+dp(68),t);c.drawText("Actuator axis force = |F · u_actuator|.",dp(28),y+dp(94),t);c.drawText("Side-load = |F - (F·u)u|; this must be reacted by joints/fixture.",dp(28),y+dp(120),t);c.drawText("Residual % indicates how poorly a single axial actuator aligns with the incoming load.",dp(28),y+dp(146),t);c.drawText("Use spherical joints and geometry optimization to drive this value down.",dp(28),y+dp(172),t);}
 }
}