package com.mg.whiffletreeaero;
import android.os.Bundle;import android.graphics.*;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;
public class V55Activity extends V54Activity{
 TextView optInfo;OptView optView;Button applyBest;ArrayList<Opt> best=new ArrayList<>();
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(8),dp(8),dp(8),dp(8));p.setBackground(bg(Color.rgb(12,31,47),12));p.addView(tx("ACTUATOR GEOMETRY OPTIMIZER",16,true,Color.WHITE));optInfo=card("Geometry optimization running...",Color.rgb(20,48,68));p.addView(optInfo,lp());applyBest=new Button(this);applyBest.setText("APPLY BEST GEOMETRY");applyBest.setOnClickListener(v->{if(best.size()>0){Opt o=best.get(0);baseX.setText(String.format(Locale.US,"%.0f",o.x));baseY.setText(String.format(Locale.US,"%.0f",o.y));actDrop.setText(String.format(Locale.US,"%.0f",o.drop));refreshClosure();}});p.addView(applyBest,lp());optView=new OptView();p.addView(optView,new LinearLayout.LayoutParams(-1,dp(950)));root.addView(p,35,lp());TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){refreshOpt();}public void afterTextChanged(Editable e){}};for(EditText e:new EditText[]{baseX,baseY,actDrop,yOff,zOff,F,M,L,D,stations,actCount,actCapacity,sf})e.addTextChangedListener(w);refreshOpt();}
 static class Opt{double x,y,drop,peakSide,peakAngle,peakAxis,score,strokePenalty;}
 Opt eval(double bxOffMm,double byMm,double dropMm,double refDrop){Calc c=compute(false);ArrayList<JR> links=solveJoints();int na=Math.max(1,c.nAct);double[] fx=new double[na],fy=new double[na],fz=new double[na],sx=new double[na],sy=new double[na],sz=new double[na];int[] cnt=new int[na];for(int i=0;i<links.size();i++){JR r=links.get(i);int a=c.stationAct[i];if(a<0||a>=na)continue;fx[a]+=r.axial*r.ux;fy[a]+=r.axial*r.uy;fz[a]+=r.axial*r.uz;sx[a]+=r.x2;sy[a]+=r.y2;sz[a]+=r.z2;cnt[a]++;}Opt o=new Opt();o.x=bxOffMm;o.y=byMm;o.drop=dropMm;double bxOff=bxOffMm/1000.0,by=byMm/1000.0,drop=dropMm/1000.0;for(int a=0;a<na;a++){int n=Math.max(1,cnt[a]);double px=sx[a]/n,py=sy[a]/n,pz=sz[a]/n;double dx=bxOff,dy=by-py,dz=-drop;double len=Math.sqrt(dx*dx+dy*dy+dz*dz);if(len<1e-6)len=1e-6;double ux=dx/len,uy=dy/len,uz=dz/len;double total=Math.sqrt(fx[a]*fx[a]+fy[a]*fy[a]+fz[a]*fz[a]);double axis=Math.abs(fx[a]*ux+fy[a]*uy+fz[a]*uz);double side=Math.sqrt(Math.max(0,total*total-axis*axis));double ang=Math.toDegrees(Math.atan2(side,Math.max(1e-9,axis)));o.peakAxis=Math.max(o.peakAxis,axis);o.peakSide=Math.max(o.peakSide,side);o.peakAngle=Math.max(o.peakAngle,ang);}double cap=Math.max(1,d(actCapacity)),util=100*o.peakAxis/cap;double strokeUse=Math.abs(dropMm-refDrop)/Math.max(1,refDrop)*100;o.strokePenalty=Math.max(0,strokeUse-35);o.score=100-(o.peakSide/Math.max(1,o.peakAxis))*55-o.peakAngle*2.5-Math.max(0,util-85)*0.8-o.strokePenalty*0.5;return o;}
 ArrayList<Opt> optimize(){double ox=d(baseX),oy=d(baseY),od=Math.max(300,d(actDrop));ArrayList<Opt> c=new ArrayList<>();for(double x=ox-300;x<=ox+300;x+=100)for(double y=oy-300;y<=oy+300;y+=100)for(double dr=Math.max(300,od-300);dr<=od+300;dr+=100)c.add(eval(x,y,dr,od));Collections.sort(c,(a,b)->Double.compare(b.score,a.score));return new ArrayList<>(c.subList(0,Math.min(3,c.size())));}
 void refreshOpt(){try{best=optimize();Opt o=best.get(0);optInfo.setText(String.format(Locale.US,"BEST GEOMETRY\nBase X %.0f mm | Y %.0f mm | drop %.0f mm\nPeak side-load %.1f kN | max misalignment %.2f° | peak axis %.1f kN\nOptimization score %.1f/100\nSearch balances side-load, angular alignment, actuator utilization and stroke-placement penalty.",o.x,o.y,o.drop,o.peakSide,o.peakAngle,o.peakAxis,o.score));optView.items=best;optView.invalidate();}catch(Exception e){optInfo.setText("Geometry optimizer could not evaluate current inputs.");}}
 class OptView extends View{Paint p=new Paint(1),t=new Paint(1);ArrayList<Opt>items=new ArrayList<>();OptView(){super(V55Activity.this);setBackgroundColor(Color.rgb(5,17,29));t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));}
 @Override protected void onDraw(Canvas c){super.onDraw(c);int W=getWidth();t.setColor(Color.WHITE);t.setTextSize(dp(13));c.drawText("TOP 3 ACTUATOR BASE GEOMETRIES",dp(16),dp(30),t);float y=dp(75);for(int i=0;i<items.size();i++){Opt o=items.get(i);p.setColor(i==0?Color.rgb(24,74,67):Color.rgb(16,43,62));c.drawRoundRect(new RectF(dp(16),y,W-dp(16),y+dp(150)),dp(8),dp(8),p);t.setColor(i==0?Color.rgb(247,207,77):Color.WHITE);t.setTextSize(dp(10));c.drawText("#"+(i+1)+"  SCORE "+String.format(Locale.US,"%.1f",o.score),dp(28),y+dp(30),t);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText(String.format(Locale.US,"Base X %.0f  Y %.0f  Drop %.0f mm",o.x,o.y,o.drop),dp(28),y+dp(58),t);c.drawText(String.format(Locale.US,"Peak axis %.1f kN | side %.1f kN",o.peakAxis,o.peakSide),dp(28),y+dp(84),t);c.drawText(String.format(Locale.US,"Max angle %.2f° | stroke penalty %.1f",o.peakAngle,o.strokePenalty),dp(28),y+dp(110),t);c.drawText(i==0?"Recommended: minimum combined geometry penalty":"Alternative geometry",dp(28),y+dp(136),t);y+=dp(165);}p.setColor(Color.rgb(20,51,72));c.drawRoundRect(new RectF(dp(16),y+dp(10),W-dp(16),y+dp(195)),dp(8),dp(8),p);t.setColor(Color.rgb(247,207,77));t.setTextSize(dp(8));c.drawText("OPTIMIZATION LOGIC",dp(28),y+dp(40),t);t.setColor(Color.WHITE);t.setTextSize(dp(7));c.drawText("1. Scan actuator base X/Y/drop around the current design.",dp(28),y+dp(70),t);c.drawText("2. Recompute 3D pivot→actuator axis reaction for every candidate.",dp(28),y+dp(96),t);c.drawText("3. Penalize side-load, misalignment and overload risk.",dp(28),y+dp(122),t);c.drawText("4. Penalize excessive base movement as a stroke-placement proxy.",dp(28),y+dp(148),t);c.drawText("Final geometry still needs real hardpoints, stroke envelopes and CAD interference checks.",dp(28),y+dp(174),t);}}
 }
}
