plugins { id 'com.android.application' }

android {
    namespace 'com.mg.stonefluorescence'
    compileSdk 35

    signingConfigs {
        debug {
            storeFile rootProject.file('dev-update.jks')
            storePassword 'stoneglow123'
            keyAlias 'stoneglow'
            keyPassword 'stoneglow123'
        }
    }

    defaultConfig {
        applicationId 'com.mg.stonefluorescence'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '1.4'
    }

    buildTypes {
        debug { signingConfig signingConfigs.debug }
    }
}
