package com.muhammetgecgil.turkradyo;

import android.content.Context;
import android.content.SharedPreferences;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Learned per-station stream resolver: remember healthy URLs, quarantine failures,
 * rank candidates by observed startup/success history, then rediscover the SAME station. */
public final class StreamFallbackManager {
    private static final String PREFS="stream_health_v4";
    private static final String[] MIRRORS={"https://de1.api.radio-browser.info","https://fi1.api.radio-browser.info","https://nl1.api.radio-browser.info"};
    private StreamFallbackManager(){}
    public interface Callback{void onResult(String url);}

    private static String sid(String name){String s=name==null?"turk_radyo":name.toLowerCase(new Locale("tr","TR"));s=s.replaceAll("[^a-z0-9çğıöşü]+","_");return s.length()>80?s.substring(0,80):s;}
    private static String preferredKey(String n){return"preferred_"+sid(n);} private static String goodKey(String n){return"good_"+sid(n);} private static String statKey(String n){return"stats_"+sid(n);} private static String badKey(String n,String u){return"bad_"+sid(n)+"_"+Integer.toHexString(u.hashCode());}
    private static SharedPreferences p(Context c){return c.getSharedPreferences(PREFS,Context.MODE_PRIVATE);}

    public static String getPreferred(Context c,String name,String primary){SharedPreferences p=p(c);String pref=p.getString(preferredKey(name),"");if(isHealthy(p,name,pref))return pref;List<String> ranked=cachedCandidates(c,name,primary);return ranked.isEmpty()?primary:ranked.get(0);}

    public static void markGood(Context c,String name,String url,long startupMs){if(url==null||url.isEmpty())return;SharedPreferences p=p(c);long now=System.currentTimeMillis();try{JSONObject db=stats(p,name),x=db.optJSONObject(url);if(x==null)x=new JSONObject();int ok=x.optInt("ok",0)+1,fail=x.optInt("fail",0);long old=x.optLong("avgStartup",0),avg=startupMs>0?(old<=0?startupMs:Math.round(old*.72+startupMs*.28)):old;x.put("ok",ok).put("fail",fail).put("avgStartup",avg).put("lastOk",now).put("lastResult","ok");db.put(url,x);JSONArray a;try{a=new JSONArray(p.getString(goodKey(name),"[]"));}catch(Exception e){a=new JSONArray();}JSONArray out=new JSONArray();JSONObject n=new JSONObject();n.put("url",url).put("startupMs",avg).put("lastOk",now).put("score",score(x));out.put(n);for(int i=0;i<a.length()&&out.length()<12;i++){JSONObject q=a.optJSONObject(i);if(q!=null&&!url.equals(q.optString("url")))out.put(q);}p.edit().putString(preferredKey(name),url).putString(goodKey(name),out.toString()).putString(statKey(name),db.toString()).remove(badKey(name,url)).apply();}catch(Exception ignored){}}

    public static void markBad(Context c,String name,String url,long quarantineMs){if(url==null||url.isEmpty())return;SharedPreferences p=p(c);long now=System.currentTimeMillis(),until=now+Math.max(60_000L,quarantineMs);try{JSONObject db=stats(p,name),x=db.optJSONObject(url);if(x==null)x=new JSONObject();x.put("ok",x.optInt("ok",0)).put("fail",x.optInt("fail",0)+1).put("lastFail",now).put("lastResult","fail");db.put(url,x);SharedPreferences.Editor e=p.edit().putLong(badKey(name,url),until).putString(statKey(name),db.toString());if(url.equals(p.getString(preferredKey(name),"")))e.remove(preferredKey(name));e.apply();}catch(Exception ignored){}}

    private static JSONObject stats(SharedPreferences p,String name){try{return new JSONObject(p.getString(statKey(name),"{}"));}catch(Exception e){return new JSONObject();}}
    private static int score(JSONObject x){int ok=x.optInt("ok",0),fail=x.optInt("fail",0);long ms=x.optLong("avgStartup",2500),last=x.optLong("lastOk",0);int s=50+Math.min(25,ok*3)-Math.min(40,fail*9);if(ms>0)s+=ms<800?24:ms<1500?15:ms<2500?7:-8;if(last>System.currentTimeMillis()-7L*86400000L)s+=8;return Math.max(0,Math.min(100,s));}
    private static boolean isHealthy(SharedPreferences p,String n,String u){return u!=null&&!u.isEmpty()&&p.getLong(badKey(n,u),0)<System.currentTimeMillis();}

    public static List<String> cachedCandidates(Context c,String name,String primary){SharedPreferences p=p(c);JSONObject db=stats(p,name);Set<String> all=new LinkedHashSet<>();String pref=p.getString(preferredKey(name),"");if(isHealthy(p,name,pref))all.add(pref);try{JSONArray a=new JSONArray(p.getString(goodKey(name),"[]"));for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null&&isHealthy(p,name,x.optString("url")))all.add(x.optString("url"));}}catch(Exception ignored){}if(isHealthy(p,name,primary))all.add(primary);List<String> out=new ArrayList<>(all);out.sort((a,b)->Integer.compare(score(db.optJSONObject(b)==null?new JSONObject():db.optJSONObject(b)),score(db.optJSONObject(a)==null?new JSONObject():db.optJSONObject(a))));return out;}

    public static String getHealthJson(Context c,String name){SharedPreferences p=p(c);try{JSONObject out=new JSONObject();out.put("station",name);out.put("preferred",p.getString(preferredKey(name),""));out.put("streams",stats(p,name));return out.toString();}catch(Exception e){return"{}";}}

    public static void discoverBestAsync(Context c,String name,String primary,Callback cb){new Thread(()->{String best=null;long bestMs=Long.MAX_VALUE;int bestLearned=-1;JSONObject db=stats(p(c),name);for(String u:cachedCandidates(c,name,primary)){long ms=probe(u);if(ms>=0){JSONObject x=db.optJSONObject(u);int learned=score(x==null?new JSONObject():x);if(best==null||learned>bestLearned+8||(Math.abs(learned-bestLearned)<=8&&ms<bestMs)){best=u;bestMs=ms;bestLearned=learned;}}else markBad(c,name,u,5*60_000L);}if(best==null){for(Candidate x:searchDirectory(name)){if(sameUrl(primary,x.url))continue;long ms=probe(x.url);if(ms>=0){best=x.url;bestMs=ms;break;}markBad(c,name,x.url,2*60_000L);}}final String result=best;final long latency=bestMs;if(result!=null)markGood(c,name,result,latency);new android.os.Handler(android.os.Looper.getMainLooper()).post(()->cb.onResult(result));},"stream-repair").start();}

    private static boolean sameUrl(String a,String b){return a!=null&&a.equals(b);} private static final class Candidate{String url;int score;Candidate(String u,int s){url=u;score=s;}}
    private static List<Candidate> searchDirectory(String name){ArrayList<Candidate> out=new ArrayList<>();String enc;try{enc=URLEncoder.encode(name==null?"":name,"UTF-8");}catch(Exception e){return out;}for(String base:MIRRORS){HttpURLConnection h=null;try{URL u=new URL(base+"/json/stations/search?countrycode=TR&hidebroken=true&limit=80&order=clickcount&reverse=true&name="+enc);h=(HttpURLConnection)u.openConnection();h.setConnectTimeout(3500);h.setReadTimeout(5000);h.setRequestProperty("User-Agent","TurkRadyo/2.1");if(h.getResponseCode()/100!=2)continue;StringBuilder sb=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(h.getInputStream(),StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null&&sb.length()<1_500_000)sb.append(line);}JSONArray a=new JSONArray(sb.toString());String target=norm(name);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String n=o.optString("name"),url=o.optString("url_resolved",o.optString("url"));if(url.isEmpty())continue;int sim=similarity(target,norm(n));if(sim<65)continue;int sc=sim*2+(o.optInt("lastcheckok")==1?50:0)+Math.min(30,o.optInt("bitrate")/8)+Math.min(20,o.optInt("votes")/10);out.add(new Candidate(url,sc));}if(!out.isEmpty())break;}catch(Exception ignored){}finally{if(h!=null)h.disconnect();}}out.sort((a,b)->Integer.compare(b.score,a.score));return out.size()>16?new ArrayList<>(out.subList(0,16)):out;}
    private static String norm(String s){if(s==null)return"";return s.toLowerCase(new Locale("tr","TR")).replace(" radyo "," ").replace(" radio "," ").replace(" fm "," ").replaceAll("[^a-z0-9çğıöşü]+"," ").trim();}
    private static int similarity(String a,String b){if(a.equals(b))return 100;if(a.isEmpty()||b.isEmpty())return 0;if(a.contains(b)||b.contains(a))return 88;Set<String>A=new HashSet<>(),B=new HashSet<>();for(String x:a.split(" "))if(x.length()>2)A.add(x);for(String x:b.split(" "))if(x.length()>2)B.add(x);int hit=0;for(String x:A)if(B.contains(x))hit++;return(int)(70.0*hit/Math.max(1,Math.max(A.size(),B.size())));}
    private static long probe(String raw){HttpURLConnection h=null;InputStream in=null;try{long t0=System.currentTimeMillis();h=(HttpURLConnection)new URL(raw).openConnection();h.setInstanceFollowRedirects(true);h.setConnectTimeout(2800);h.setReadTimeout(3800);h.setRequestProperty("User-Agent","TurkRadyo/2.1");h.setRequestProperty("Icy-MetaData","0");int code=h.getResponseCode();if(code<200||code>=400)return-1;String ct=String.valueOf(h.getContentType()).toLowerCase(Locale.ROOT);in=new BufferedInputStream(h.getInputStream(),8192);byte[] buf=new byte[8192];int total=0,n;while(total<8192&&(n=in.read(buf,0,Math.min(buf.length,8192-total)))>0)total+=n;long ms=System.currentTimeMillis()-t0;if(total<64)return-1;if(raw.toLowerCase(Locale.ROOT).contains(".m3u8")||ct.contains("mpegurl"))return total>=128?ms:-1;return total>=2048?ms:-1;}catch(Exception e){return-1;}finally{try{if(in!=null)in.close();}catch(Exception ignored){}if(h!=null)h.disconnect();}}
}
