plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mg.hafizadostum.v4'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mg.hafizadostum.v42'
        minSdk 23
        targetSdk 35
        versionCode 42
        versionName '4.2'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
