plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mg.battleship'
    compileSdk 35

    signingConfigs {
        persistentDev {
            storeFile file('../signing/amiral-dev.jks')
            storePassword 'AmiralDev2026!'
            keyAlias 'amiral'
            keyPassword 'AmiralDev2026!'
        }
    }

    defaultConfig {
        applicationId 'com.mg.battleship'
        minSdk 26
        targetSdk 35
        versionCode 16
        versionName '16.0'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.persistentDev
        }
        release {
            signingConfig signingConfigs.persistentDev
            minifyEnabled false
        }
    }

    sourceSets {
        main.java.srcDirs = ['src/v7/java', 'src/v4/java']
    }
}