plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mg.battleship'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mg.battleship'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '4.0'
    }

    sourceSets {
        main.java.srcDirs = ['src/v4/java']
    }
}
