name: Export APKSigner Temporary
on:
  push:
    paths:
      - '.github/workflows/export-apksigner-temp.yml'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: android-actions/setup-android@v3
      - name: Install build tools
        run: sdkmanager 'build-tools;35.0.0'
      - name: Collect APKSigner
        run: |
          mkdir -p out
          cp "$ANDROID_SDK_ROOT/build-tools/35.0.0/lib/apksigner.jar" out/apksigner.jar
      - uses: actions/upload-artifact@v4
        with:
          name: apksigner-temp
          path: out/apksigner.jar
          retention-days: 1
